## On the negative NPMI for Top2Vec (-0.17)

Top2Vec produced topics whose top-word NPMI score on this corpus is **negative**
(roughly -0.17 in our run), meaning the top words selected for each topic **co-occur
less often than chance** in the document collection. This is an **anti-coherence**
signal, not just "weak" coherence, and we therefore **exclude Top2Vec from the
recommended unsupervised configuration** for this dataset.

Why this happens here:

- Top2Vec relies on `doc2vec` (or, optionally, a sentence-transformer) embeddings of
  full documents, then clusters with HDBSCAN. With ~3.9k short, often near-duplicate
  patient-provider exchanges, doc2vec embeddings are underdetermined and HDBSCAN tends
  to produce one large noise cluster plus a few small topics whose representative
  words generalize poorly across documents.
- BERTopic, by contrast, uses pretrained sentence-transformer embeddings + UMAP +
  HDBSCAN + class-based TF-IDF, which is far more robust at this corpus size and
  produces positive NPMI on the same data.

**Reported in the paper:** Top2Vec is included in Table X for completeness, but
flagged with the negative-NPMI caveat and not carried into the recommendations.

## Input corpus: shared training split

To keep the unsupervised topic models (BERTopic, Top2Vec, LDA) directly comparable
with the supervised pipeline, we fit them on the **training portion of the shared
split** produced by `create_shared_split.py` (dedup'd, restricted to labels with
>= 100 occurrences in the pooled corpus). The next cell reconstructs that input.
Replace the loose `df_diabetes` / `df_covid` reads further down with `train_docs`.

In [ ]:
# SHARED_SPLIT_TOPIC_INPUT_v1
# Build the training-split corpus that the supervised models see, for fair comparison.
import random, numpy as np, pandas as pd

SEED = 42
random.seed(SEED); np.random.seed(SEED)

dfCovid    = pd.read_csv("data/dataRwaCovid.csv", on_bad_lines="skip", low_memory=False)
dfDiabetes = pd.read_csv("data/dataIHADiabetes.csv", on_bad_lines="skip", low_memory=False)

DiabetesTopics = ["Physical","Psychological","No Symptoms","Prognosis","Laboratory/Testing","Imaging","Clinical","Testing/Monitoring Devices","Health Data","Diagnostic Methods - Other","Medications","Procedures","Alternative","Physical Therapy","Counseling","Adverse Events","Therapeutic Devices","Treatment(Rx) - Other","Outpatient Logistics/Scheduling","Hospitalizations","Insurance/Billing","Medical Records","Referrals","Transportation","Primary (Pharmaceutical Prevention)","Primary (Non-Pharmaceutical Prevention)","Secondary (Pharmaceutical Prevention)","Secondary (Non-Pharmaceutical Prevention)","Diet/Nutrition","Exercise","Substance Use","Entertainment","Lifestyle - Other","Housing","Work/School","Social Services","Friends & Family","Cultural/Religion","Travel","Physical Environment/Climate","Financial","Social - Other","Technical/IT","Safety Concerns","Health Education","Sexual & Reproductive Health","Child & Family Health","Problems Solved","Grateful Patient","Service Complaint","Request to Stop","Emergent","Urgent","Non-urgent","Stigma Present","Rapport","Transition to Adult Clinic"]
CovidTopics = ["Physical","Mental/Emotional","No Symptoms","Laboratory/Testing","Imaging","Clinical","Diagnostic Methods - Other","Medications","Procedures","Alternative","Physical Therapy","Counseling","Treatment(Rx) - Other","Outpatient Logistics/Scheduling","Hospitalizations","Pharmaceutical Prevention","Non-Pharmaceutical Prevention","Diet/Nutrition","Exercise","Substance Use","Lifestyle - Other","Housing","Work/School","Social Services","Friends & Family","Cultural/Religion","Travel","Physical Environment/Climate","Financial","Social - Other","Technical/IT","Safety concern","Health Education","Maternal & Child Health","Problems Solved","Grateful Patient","Service Complaint","Request to Stop","Emergent","Urgent","Non-urgent","Stigma Present","wave","batch"]
common = sorted(set(DiabetesTopics) & set(CovidTopics))

dfD = dfDiabetes[["conversation"] + common].copy(); dfD["source"] = "Canada"
dfC = dfCovid[["conversation(english_only)"] + common].rename(
    columns={"conversation(english_only)": "conversation"}).copy(); dfC["source"] = "Rwanda"

dfCombined = pd.concat([dfC, dfD]).reset_index(drop=True)
label_keep = dfCombined[common].sum()[lambda s: s >= 100].index.tolist()
dfFilt = (dfCombined[["conversation", "source"] + label_keep]
          .drop_duplicates(subset="conversation")
          .reset_index(drop=True))

_split = np.load("data/shared_split_indices.npz")
train_idx = _split["train_idx"]

train_docs    = dfFilt.iloc[train_idx]["conversation"].tolist()
train_sources = dfFilt.iloc[train_idx]["source"].tolist()
print(f"Training docs for unsupervised models: {len(train_docs)} "
      f"(Rwanda {sum(s=='Rwanda' for s in train_sources)}, "
      f"Canada {sum(s=='Canada' for s in train_sources)})")
print(f"Labels kept (only used for downstream comparison): {len(label_keep)}")

In [ ]:
!pip install bertopic

Requirement already satisfied: bertopic in /usr/local/lib/python3.11/dist-packages (0.17.3)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (5.1.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.13.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (25.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.55.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.6.0+cu124)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.34.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.14.1)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.1.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.8.3)

In [ ]:
import pandas as pd
from bertopic import BERTopic

In [ ]:
df_diabetes = pd.read_csv("dataIHADiabetes.csv")
df_covid    = pd.read_csv("cleaned_and_extracted_dataset-2.csv")

In [ ]:
df_diabetes = df_diabetes["conversation"]

In [ ]:
df_diabetes.head()

0    (S) : Hi! Welcome to WelTel's Interior Health ...
1    (S) : If you're finding lumps, try to find alt...
2    (S) : DATA REVIEW followed by a text response ...
3    (S) : "I may have diabetes BUT diabetes does n...
4    (S) : Time spent amongst treesðŸŒ³ðŸŒ³ is neve...
Name: conversation, dtype: object

In [ ]:

df_covid= df_covid.rename(columns={'conversation(english_only)': 'conversation'})

In [ ]:
df_covid = df_covid["conversation"]

In [ ]:
df_covid.head()

0    (S): Hello, how are you today? Do you have any...
1    (S): Welcome to Rwanda Ministry of Health plat...
2    (S): Welcome to Rwanda Ministry of Health plat...
3    (S): Hello, how are you today? Do you have any...
4    (S): Welcome to Rwanda Ministry of Health plat...
Name: conversation, dtype: object

In [ ]:
df = pd.concat([df_diabetes, df_covid])

In [ ]:
df.head()

0    (S) : Hi! Welcome to WelTel's Interior Health ...
1    (S) : If you're finding lumps, try to find alt...
2    (S) : DATA REVIEW followed by a text response ...
3    (S) : "I may have diabetes BUT diabetes does n...
4    (S) : Time spent amongst treesðŸŒ³ðŸŒ³ is neve...
Name: conversation, dtype: object

In [ ]:
import pandas as pd
import numpy as np
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, PartOfSpeech
from sklearn.feature_extraction.text import CountVectorizer
from hdbscan import HDBSCAN

docs = df
hdbscan_model = HDBSCAN(min_cluster_size=30, metric='euclidean', cluster_selection_method='eom', prediction_data=True)

keybert_model = KeyBERTInspired(top_n_words=6)
mmr_model = MaximalMarginalRelevance(diversity=0.5,top_n_words=6)
pos_model = PartOfSpeech("en_core_web_sm",top_n_words=6)

representation_model = {
    "Main": keybert_model,
    "Diverse_Keywords": mmr_model,
    "Nouns_and_Adjectives": pos_model
}

vectorizer_model = CountVectorizer(stop_words="english")

topic_model = BERTopic(
    language="english",
    hdbscan_model=hdbscan_model,
    representation_model=representation_model,
    vectorizer_model=vectorizer_model,
    top_n_words=6,
    verbose=True
)
topics, _ = topic_model.fit_transform(docs)
print("ITS WORKING:",topic_model.get_topic_info(),"YES IT DOES")
topic_info = topic_model.get_topic_info()
topic_info = topic_info.set_index('Topic')

if 'Main' in topic_info.columns:
    name_column = 'Main'
else:
    name_column = 'Name'

topic_distr, _ = topic_model.approximate_distribution(docs)

probability_threshold = 0.05
multi_label_topics_ids = []
multi_label_topics_names = []
for doc_distr in topic_distr:
    relevant_topic_ids_array = np.where(doc_distr > probability_threshold)[0]

    multi_label_topics_ids.append(relevant_topic_ids_array)

    if relevant_topic_ids_array.size > 0:
        doc_topic_names = topic_info.loc[relevant_topic_ids_array][name_column].tolist()
    else:
        doc_topic_names =[]
    multi_label_topics_names.append(doc_topic_names)

results_df = pd.DataFrame({
    'Document': docs,
    'Dominant_Topic': topics,
    'Multi_Label_Topic_IDs': multi_label_topics_ids,
    'Multi_Label_Topic_Names': multi_label_topics_names
})
print(results_df)

2025-08-17 06:05:25,504 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/123 [00:00<?, ?it/s]

2025-08-17 06:05:39,078 - BERTopic - Embedding - Completed ✓
2025-08-17 06:05:39,081 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-08-17 06:06:31,554 - BERTopic - Dimensionality - Completed ✓
2025-08-17 06:06:31,555 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-08-17 06:06:31,683 - BERTopic - Cluster - Completed ✓
2025-08-17 06:06:31,688 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-08-17 06:06:38,419 - BERTopic - Representation - Completed ✓

ITS WORKING:     Topic  Count                                            Name  \
0      -1    611          -1_coronavirus_rwanda_symptom_symptoms
1       0   1173                   0_hello_covid19_covid_texting
2       1    731               1_covid_covid19_illness_telephone
3       2    248                 2_diabetes_holidays_26th_clinic
4       3    174              3_mwaramutse_covid_covid19_illness
5       4    173              4_coronavirus_symptom_fever_rwanda
6       5    138               5_holidays_happy_emergency_spring
7       6    110        6_inactivated_patient_reactivated_health
8       7     72         7_coronavirus_greetings_covid19_symptom
9       8     70               8_coronavirus_hello_symptom_today
10      9     56              9_coronavirus_rwanda_fever_symptom
11     10     52       10_diabetes_confident_questions_answering
12     11     45        11_inactivated_reactivated_weltel_active
13     12     42  12_hypoglycemia_hyperglycemia_aerobic_diabetes
14     13     42                13_monday_weekend_beautiful_text
15     14     41        14_coronavirus_covid19_greetings_symptom
16     15     33          15_coronavirus_rwanda_covid19_symptoms
17     16     32         16_novorapid_novopen_pharmacare_humalog
18     17     32                17_glycemic_glucose_sugar_sugars
19     18     32         18_diabetes_diabetic_clinic_appointment

                                       Representation  \
0   [coronavirus, rwanda, symptom, symptoms, greet...
1    [hello, covid19, covid, texting, morning, today]
2   [covid, covid19, illness, telephone, quarantin...
3   [diabetes, holidays, 26th, clinic, insulin, 27th]
4   [mwaramutse, covid, covid19, illness, health, ...
5   [coronavirus, symptom, fever, rwanda, quaranti...
6   [holidays, happy, emergency, spring, weather, pm]
7   [inactivated, patient, reactivated, health, ho...
8   [coronavirus, greetings, covid19, symptom, hel...
9   [coronavirus, hello, symptom, today, symptoms,...
10  [coronavirus, rwanda, fever, symptom, flu, sym...
11  [diabetes, confident, questions, answering, 10...
12  [inactivated, reactivated, weltel, active, con...
13  [hypoglycemia, hyperglycemia, aerobic, diabete...
14  [monday, weekend, beautiful, text, checking, w...
15  [coronavirus, covid19, greetings, symptom, rwa...
16  [coronavirus, rwanda, covid19, symptoms, sympt...
17  [novorapid, novopen, pharmacare, humalog, bios...
18  [glycemic, glucose, sugar, sugars, insulin, ke...
19  [diabetes, diabetic, clinic, appointment, swit...

                                     Diverse_Keywords  \
0   [eiko, coronavirus, symptoms, diabetes, sites,...
1   [line, message, texting, concerns, covid19, te...
2   [covid, sms, inactivated, facility, didnt, pro...
3   [insulin, eiko, 21062021, clinic, dietitian, s...
4   [covid, mwaramutse, care, hotline, patients, p...
5   [symptom, yesno, rwanda, informing, coronaviru...
6         [week, dr, eiko, 10012022, warmer, weather]
7   [inactivated, advised, shes, testing, hospital...
8   [coronavirus, greetings, negative, covid19, er...
9   [symptoms, coronavirus, administrator, current...
10  [ministry, rwanda, symptom, automated, coronav...
11  [monthly, answering, scale, eiko, diabetes, 21...
12  [testing, didnt, facility, reactivated, messag...
13  [21032022, aerobic, dyk, weightssprinting, cau...
14  [23052022, monday, screenshot, month, number, ...
15  [coronavirus, symptoms, negative, plateforme, ...
16  [contacts, symptom, ministry, rwanda, coronavi...
17  [pharmacare, substituted, biosimilar, fyipharm...
18  [ketones, oatmeal, urine, glycemic, grams, 050...
19  [pediatrician, switchboard, diabetes, weekends...

                                 Nouns_and_Adjectives  \
0    [coronavirus, ok, symptoms, diabetes, good, new]
1   [line, reaction, basis, message, concerns, daily]
2   [covid, health, morning, situation, telephone,...
3    [insulin, diabetes, text, project, clinic, week]
4          [covid, uyu, barwaye, care, home, hotline]
5     [symptom, ok, new, platform, contacts, welcome]
6          [great, week, good, hear, warmer, weather]
7   [facility, patient, testing, tomorrow, contact...
8   [symptoms, coronavirus, today, cooperation, ne...
9   [symptoms, coronavirus, today, symptom, ok, pr...
10  [platform, symptom, new, ok, checkin, coronavi...
11  [confident, monthly, question, scale, thanks, ...
12  [contact, administrator, active, testing, faci...
13  [exercise, month, aerobic, hypoglycemia, scree...
14  [beautiful, different, weeks, screenshot, past...
15  [coronavirus, symptoms, cooperation, negative,...
16   [ok, contacts, symptom, new, platform, patients]
17  [novorapid, trurapi, products, reminder, weeks...
18  [ketones, urine, oatmeal, sugars, index, glyce...
19  [pediatrician, weekends, diabetes, diabetic, o...

                                  Representative_Docs
0   [(S): Are you OK (Yes/No)? Or tell us if you h...
1   [(P): Good morning! We are well.! || (S): Hell...
2   [(C): Good morning! We want to know your situa...
3   [(S) : Bolusing even 5 minutes before eating c...
4   [(C): Good morning! We want to know your illne...
5   [(S): Welcome to Rwanda Ministry of Health pla...
6   [(S) : It's finally starting to feel like spri...
7   [(S): haven't heard from you yet. how are you?...
8   [(S): Hello, how are you today? Do you have an...
9   [(S): Hello, how are you today? Do you have an...
10  [(S): Welcome to Rwanda Ministry of Health pla...
11  [(S) : Anything you need from us this week?   ...
12  [(S): The contact didn't go to any health faci...
13  [(S) : DYK. Aerobic (running) exercise general...
14  [(S) : We will be checking in once every two w...
15  [(S): Welcome to the platform of the Ministry ...
16  [(S): Welcome to Rwanda Ministry of Health pla...
17  [(S) : Just a reminder that in 3 weeks (May 29...
18  [(S) : DYK: For the same # grams of carbs, oat...
19  [(S) : Reminder that if you need help with you...   YES IT DOES

100%|██████████| 4/4 [00:02<00:00,  1.34it/s]

                                               Document  Dominant_Topic  \
0     (S) : Hi! Welcome to WelTel's Interior Health ...              -1
1     (S) : If you're finding lumps, try to find alt...              10
2     (S) : DATA REVIEW followed by a text response ...               2
3     (S) : "I may have diabetes BUT diabetes does n...              -1
4     (S) : Time spent amongst treesðŸŒ³ðŸŒ³ is neve...              -1
...                                                 ...             ...
2786  (S): haven't heard from you yet. how are you? ...              -1
2787  (C): Hello #Perpetue#! How are you? Were you t...               1
2788  (S): Hello, this is the texting line used for ...               0
2789  (C): Good morning! This is Babyl Health Rwanda...               1
2790  (S): Hello, do you have any health or COVID re...               1

        Multi_Label_Topic_IDs  \
0        [0, 1, 2, 5, 13, 15]
1              [2, 5, 10, 18]
2             [2, 10, 12, 18]
3                 [2, 10, 18]
4              [2, 5, 10, 18]
...                       ...
2786            [1, 6, 9, 11]
2787     [1, 3, 6, 7, 11, 14]
2788         [0, 1, 7, 8, 14]
2789  [1, 3, 4, 6, 9, 11, 15]
2790          [0, 1, 3, 7, 8]

                                Multi_Label_Topic_Names
0     [0_hello_covid19_covid_texting, 1_covid_covid1...
1     [2_diabetes_holidays_26th_clinic, 5_holidays_h...
2     [2_diabetes_holidays_26th_clinic, 10_diabetes_...
3     [2_diabetes_holidays_26th_clinic, 10_diabetes_...
4     [2_diabetes_holidays_26th_clinic, 5_holidays_h...
...                                                 ...
2786  [1_covid_covid19_illness_telephone, 6_inactiva...
2787  [1_covid_covid19_illness_telephone, 3_mwaramut...
2788  [0_hello_covid19_covid_texting, 1_covid_covid1...
2789  [1_covid_covid19_illness_telephone, 3_mwaramut...
2790  [0_hello_covid19_covid_texting, 1_covid_covid1...

[3907 rows x 4 columns]

In [ ]:
probability_threshold = 0.09
multi_label_topics_ids = []
multi_label_topics_names = []
for doc_distr in topic_distr:
    relevant_topic_ids_array = np.where(doc_distr > probability_threshold)[0]

    multi_label_topics_ids.append(relevant_topic_ids_array)

    if relevant_topic_ids_array.size > 0:
        doc_topic_names = topic_info.loc[relevant_topic_ids_array][name_column].tolist()
    else:
        doc_topic_names =[]
    multi_label_topics_names.append(doc_topic_names)

results_df = pd.DataFrame({
    'Topic_IDs': multi_label_topics_ids,
    'Topic_Names': multi_label_topics_names
})
print(results_df)

              Topic_IDs                                        Topic_Names
0            [2, 5, 13]  [2_diabetes_holidays_26th_clinic, 5_holidays_h...
1        [2, 5, 10, 18]  [2_diabetes_holidays_26th_clinic, 5_holidays_h...
2       [2, 10, 12, 18]  [2_diabetes_holidays_26th_clinic, 10_diabetes_...
3           [2, 10, 18]  [2_diabetes_holidays_26th_clinic, 10_diabetes_...
4            [2, 5, 10]  [2_diabetes_holidays_26th_clinic, 5_holidays_h...
...                 ...                                                ...
3902      [1, 6, 9, 11]  [1_covid_covid19_illness_telephone, 6_inactiva...
3903  [1, 3, 6, 11, 14]  [1_covid_covid19_illness_telephone, 3_mwaramut...
3904       [0, 1, 7, 8]  [0_hello_covid19_covid_texting, 1_covid_covid1...
3905      [1, 3, 6, 11]  [1_covid_covid19_illness_telephone, 3_mwaramut...
3906          [0, 1, 3]  [0_hello_covid19_covid_texting, 1_covid_covid1...

[3907 rows x 2 columns]

In [ ]:
!pip install top2vec
from top2vec import Top2Vec

if isinstance(docs, (pd.Series, pd.DataFrame)):
    docs_list = docs.tolist()
else:
    docs_list = list(docs)

top2vec_model = Top2Vec(documents=docs_list, embedding_model='universal-sentence-encoder')

num_topics = top2vec_model.get_num_topics()

topic_words, word_scores, topic_nums = top2vec_model.get_topics(num_topics)

num_words_to_display = 6

print(f"Top 6 Words for Each Topic")

for i in range(17):
  topic_num = topic_nums[i]
  top_words_for_topic = topic_words[i][:num_words_to_display]
  word_scores_for_topic = word_scores[i][:num_words_to_display]
  print(word_scores_for_topic)

  print(f"\nTopic {topic_num}:")
  print(' '.join(top_words_for_topic))

Requirement already satisfied: top2vec in /usr/local/lib/python3.11/dist-packages (1.0.36)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from top2vec) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from top2vec) (2.2.2)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from top2vec) (1.6.1)
Requirement already satisfied: gensim>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from top2vec) (4.3.3)
Requirement already satisfied: umap-learn>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from top2vec) (0.5.9.post2)
Requirement already satisfied: hdbscan>=0.8.27 in /usr/local/lib/python3.11/dist-packages (from top2vec) (0.8.40)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.11/dist-packages (from top2vec) (1.9.4)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (from top2vec) (4.55.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from top2vec) (4.67.1)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim>=4.0.0->top2vec) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim>=4.0.0->top2vec) (7.3.0.post1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.27->top2vec) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2.0->top2vec) (3.6.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.1->top2vec) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.1->top2vec) (0.5.13)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->top2vec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->top2vec) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->top2vec) (2025.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (0.34.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (0.6.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from wordcloud->top2vec) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from wordcloud->top2vec) (3.10.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers->top2vec) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers->top2vec) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers->top2vec) (1.1.7)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51.2->umap-learn>=0.5.1->top2vec) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->top2vec) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim>=4.0.0->top2vec) (1.17.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (3.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (2025.8.3)

2025-08-17 06:06:53,179 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
2025-08-17 06:06:54,795 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
2025-08-17 06:07:44,905 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
2025-08-17 06:07:50,496 - top2vec - INFO - Creating lower dimension embedding of documents
INFO:top2vec:Creating lower dimension embedding of documents
2025-08-17 06:08:12,516 - top2vec - INFO - Finding dense areas of documents
INFO:top2vec:Finding dense areas of documents
2025-08-17 06:08:12,601 - top2vec - INFO - Finding topics
INFO:top2vec:Finding topics

Top 6 Words for Each Topic
[0.28693154 0.27057695 0.25272065 0.25185287 0.24175093 0.22627215]

Topic 0:
messages greetings texting hi hello reply
[0.21896195 0.21772696 0.21056734 0.20288265 0.19306508 0.19180605]

Topic 1:
hotline illness health patient tested re
[0.3427351  0.34238896 0.2562301  0.24375933 0.20574446 0.19535023]

Topic 2:
symptom symptoms illness flu re health
[0.3014471  0.24877934 0.2376104  0.2293275  0.21377304 0.20875686]

Topic 3:
hotline telephone phone sms texting messages
[0.31775886 0.28874552 0.27649024 0.26873857 0.24307445 0.21598089]

Topic 4:
symptoms hi greetings hello symptom morning
[0.32092032 0.29953766 0.2789727  0.2656779  0.22606246 0.20958272]

Topic 5:
hi greetings hello merry fine welcome
[0.21683423 0.20692323 0.1954192  0.18838958 0.18616742 0.18570375]

Topic 6:
dexcom appointment sugars insulin diabetes healthy
[0.3045201  0.23311168 0.22014213 0.21730745 0.20936038 0.20750786]

Topic 7:
confident hi greetings survey diabetes hello
[0.3479679  0.269724   0.2403442  0.2282825  0.22620292 0.21878654]

Topic 8:
merry xmas greetings hi happy fine
[0.27979335 0.27231276 0.27082884 0.26704997 0.2405582  0.20630914]

Topic 9:
texting sugars diabetes text insulin hotline
[0.23601773 0.22708951 0.21851711 0.21446928 0.2069343  0.20427287]

Topic 10:
hi fine hello greetings evening healthy
[0.37692738 0.3473464  0.3059428  0.2836119  0.2718245  0.22698504]

Topic 11:
insulin diabetes sugars exercise dexcom bolus
[0.23391566 0.21173394 0.20033354 0.19057839 0.18989348 0.18206894]

Topic 12:
diabetes dexcom insulin care greetings healthy
[0.21401328 0.21281059 0.21124095 0.20213789 0.19577941 0.19474465]

Topic 13:
dexcom fine greetings bolus appointment working
[0.39619792 0.32271028 0.30951196 0.26333833 0.22874409 0.22822899]

Topic 14:
diabetes insulin sugars dexcom pediatrician appointment
[0.48019826 0.31469846 0.30932462 0.3089197  0.26344875 0.20729673]

Topic 15:
insulin diabetes sugars dexcom bolus temperature
[0.24032493 0.18655741 0.17481247 0.16990009 0.16748753 0.16712299]

Topic 16:
survey hi evening sure hello sugars

In [ ]:
results_df.to_csv('BerTopic_results.csv', index=False)

In [ ]:
!pip install top2vec
!pip install gensim
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import pandas as pd

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = re.sub(r'[^a-zA-Z\s]', '', text, re.I|re.A)
    text = text.lower()
    text = text.strip()

    tokens = []
    for token in text.split():
        if token not in stop_words:
            tokens.append(lemmatizer.lemmatize(token))

    return " ".join(tokens)


preprocessed_docs = [preprocess_text(doc) for doc in docs]

Requirement already satisfied: top2vec in /usr/local/lib/python3.11/dist-packages (1.0.36)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from top2vec) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from top2vec) (2.2.2)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from top2vec) (1.6.1)
Requirement already satisfied: gensim>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from top2vec) (4.3.3)
Requirement already satisfied: umap-learn>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from top2vec) (0.5.9.post2)
Requirement already satisfied: hdbscan>=0.8.27 in /usr/local/lib/python3.11/dist-packages (from top2vec) (0.8.40)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.11/dist-packages (from top2vec) (1.9.4)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (from top2vec) (4.55.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from top2vec) (4.67.1)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim>=4.0.0->top2vec) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim>=4.0.0->top2vec) (7.3.0.post1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.27->top2vec) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2.0->top2vec) (3.6.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.1->top2vec) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.1->top2vec) (0.5.13)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->top2vec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->top2vec) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->top2vec) (2025.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (0.34.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers->top2vec) (0.6.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from wordcloud->top2vec) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from wordcloud->top2vec) (3.10.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers->top2vec) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers->top2vec) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers->top2vec) (1.1.7)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51.2->umap-learn>=0.5.1->top2vec) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->top2vec) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim>=4.0.0->top2vec) (1.17.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud->top2vec) (3.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers->top2vec) (2025.8.3)
Requirement already satisfied: gensim in /usr/local/lib/python3.11/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.11/dist-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim) (7.3.0.post1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation


vectorizer_lda = CountVectorizer(max_df=0.9, min_df=5, ngram_range=(1,2))
X_lda = vectorizer_lda.fit_transform(preprocessed_docs)


lda_model = LatentDirichletAllocation(n_components=17, random_state=42)
lda_model.fit(X_lda)

def display_topics(model, feature_names, num_top_words):
    topics = []
    for topic_idx, topic in enumerate(model.components_):
        topic_words = [feature_names[i] for i in topic.argsort()[:-num_top_words - 1:-1]]
        print(f"Topic {topic_idx}: {' '.join(topic_words)}")
        topics.append(topic_words)
    return topics

print("LDA Topics")
feature_names_lda = vectorizer_lda.get_feature_names_out()
lda_topics = display_topics(lda_model, feature_names_lda, 10)

LDA Topics
Topic 0: dr dr eiko eiko good im week great work know happy
Topic 1: thank good covid morning call situation telephone good morning know know situation
Topic 2: share share today health covid health like would would like today concern would like share
Topic 3: covid hello good patient care home based care patient home hotline following following
Topic 4: survey dr eiko dr eiko get good short would thank reminder
Topic 5: go contact patient patient inactivated inactivated tomorrow testing go health didnt facility
Topic 6: every please checking would two dr good like two week week
Topic 7: diabetes text texting month tir helping good screenshot project question
Topic 8: test tested negative tested negative get day result negative covid ok want
Topic 9: confident dr eiko dr eiko diabetes thanks good scale diabetes confident question
Topic 10: great week much good thank pumpkin helpful response texting im
Topic 11: dr good dr eiko eiko im insulin hear ok im good get
Topic 12: coronavirus thank hello symptom symptom coronavirus tested message today symptom hello today today
Topic 13: covid hello today concern covid related related concern related used line sent
Topic 14: symptom hello today hello today symptom coronavirus today symptom coronavirus coronavirus hello thank good
Topic 15: symptom ok tell new new symptom tell new yesno tell ok yesno yesno symptom ok
Topic 16: good madi dietitian dietitian madi around eat finger td great blood sugar

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF


vectorizer_nmf = TfidfVectorizer(max_df=0.9, min_df=5, ngram_range=(1,2))
X_nmf = vectorizer_nmf.fit_transform(preprocessed_docs)

nmf_model = NMF(n_components=17, random_state=42)
nmf_model.fit(X_nmf)

print("\nNMF Topics")
feature_names_nmf = vectorizer_nmf.get_feature_names_out()
nmf_topics = display_topics(nmf_model, feature_names_nmf, 10)

NMF Topics
Topic 0: reaction line used used covid hello texting texting line sent daily reaction today concern message basis reaction daily basis
Topic 1: new symptom yesno yesno tell ok yesno tell new symptom ok new tell symptom ok
Topic 2: go patient inactivated inactivated health facility facility contact didnt shes advised testing shes didnt go facility testing
Topic 3: symptom coronavirus today symptom hello today coronavirus symptom coronavirus hello hello today cooperation thank cooperation
Topic 4: call telephone phone situation know situation want know patient covid based patient know want
Topic 5: patient home following patient care covid mwaramutse hotline following uyu based care rugo hello uyu ni mugukurikirana
Topic 6: dr eiko dr eiko im great good week im good hear ok
Topic 7: share today health covid share concern would like share hello health would like like would health
Topic 8: administrator active weltel please active weltel longer active please contact contact administrator weltel contact longer
Topic 9: morning good morning nice good day nice day day hello thank well morning well
Topic 10: confident scale helping diabetes diabetes confident confident super super confident super question answering monthly
Topic 11: receive automated automated checkin message thank part automated checkin longer receive receive part checkin longer
Topic 12: medical test medical test test checking control medical control checking get go medical centre
Topic 13: negative tested negative tested negative covid code inform tested inform covid ag note tested
Topic 14: havent heard heard heard yet havent yet yet good yet well yet hello yet im week havent
Topic 15: every every two two different please beautiful monday know beautiful like something something different week would checking every
Topic 16: month text tir project screenshot screenshot tir past past month exercise free

In [ ]:
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary
from gensim.utils import simple_preprocess

tokenized_docs = [doc.split() for doc in preprocessed_docs]

gensim_dictionary = Dictionary(tokenized_docs)

def calculate_coherence(topics, tokenized_docs, dictionary):

    coherence_model = CoherenceModel(
        topics=topics,
        texts=tokenized_docs,
        dictionary=dictionary,
        coherence='c_v'
    )
    return coherence_model.get_coherence()
def calculate_coherence_npmi(topics, tokenized_docs, dictionary):

    coherence_model = CoherenceModel(
        topics=topics,
        texts=tokenized_docs,
        dictionary=dictionary,
        coherence='c_npmi'
    )
    return coherence_model.get_coherence()

analyzer_lda = vectorizer_lda.build_analyzer()
tokenized_docs_lda = [analyzer_lda(doc) for doc in preprocessed_docs]
gensim_dictionary_lda = Dictionary(tokenized_docs_lda)
lda_topics = [t for t in lda_topics if t]
coherence_lda = calculate_coherence(lda_topics, tokenized_docs_lda, gensim_dictionary_lda)
coherence_lda_npmi = calculate_coherence_npmi(lda_topics, tokenized_docs_lda, gensim_dictionary_lda)
print(f"LDA Coherence CV Score: {coherence_lda:.4f}")
print(f"LDA coherence NPMI Score:{coherence_lda_npmi:.4f}")


analyzer_nmf = vectorizer_nmf.build_analyzer()
tokenized_docs_nmf = [analyzer_nmf(doc) for doc in preprocessed_docs]
gensim_dictionary_nmf = Dictionary(tokenized_docs_nmf)
nmf_topics = [t for t in nmf_topics if t]
coherence_nmf = calculate_coherence(nmf_topics, tokenized_docs_nmf, gensim_dictionary_nmf)
coherence_nmf_npmi = calculate_coherence_npmi(nmf_topics, tokenized_docs_nmf, gensim_dictionary_nmf)
print(f"NMF Coherence CV Score: {coherence_nmf:.4f}")
print(f"NMF Coherence NPMI Score: {coherence_nmf_npmi:.4f}")



bertopic_info = topic_model.get_topic_info()
bertopic_topics = []
for topic_num in bertopic_info.Topic:
    if topic_num != -1:
        # print(f"Topic {topic_num}:")

        words = [word for word, _ in topic_model.get_topic(topic_num)[:10]]
        # print(len(topic_model.get_topic(topic_num)))
        # print(' '.join(words))
        bertopic_topics.append(words)
bertopic_topics = [t for t in bertopic_topics if t]
coherence_bertopic = calculate_coherence(bertopic_topics, tokenized_docs_lda, gensim_dictionary_lda)
coherence_bertopic_npmi = calculate_coherence_npmi(bertopic_topics, tokenized_docs_lda, gensim_dictionary_lda)
print(f"BERTopic Coherence Score: {coherence_bertopic:.4f}")
print(f"BERTopic Coherence NPMI Score: {coherence_bertopic_npmi:.4f}")

top2vec_topics = [list(words)[:10] for words in top2vec_model.topic_words]
top2vec_topics = [[word for word in t] for t in top2vec_topics]
top2vec_topics = [t for t in top2vec_topics if t]
coherence_top2vec = calculate_coherence(top2vec_topics, tokenized_docs_lda, gensim_dictionary_lda)
coherence_top2vec_npmi = calculate_coherence_npmi(top2vec_topics, tokenized_docs_lda, gensim_dictionary_lda)
print(f"Top2Vec Coherence Score: {coherence_top2vec:.4f}")
print(f"Top2Vec Coherence NPMI Score: {coherence_top2vec_npmi:.4f}")






def calculate_topic_diversity(topics):

    num_top_words = len(topics[0])

    all_words = [word for topic in topics for word in topic]

    unique_words = set(all_words)

    diversity = len(unique_words) / len(all_words)
    return diversity

diversity_lda = calculate_topic_diversity(lda_topics)
diversity_nmf = calculate_topic_diversity(nmf_topics)
diversity_bertopic = calculate_topic_diversity(bertopic_topics)
diversity_top2vec = calculate_topic_diversity(top2vec_topics)


print("2. Topic Diversity Scores")
print(f"   LDA Diversity Score:      {diversity_lda:.4f}")
print(f"   NMF Diversity Score:      {diversity_nmf:.4f}")
print(f"   BERTopic Diversity Score: {diversity_bertopic:.4f}")
print(f"   Top2Vec Diversity Score:  {diversity_top2vec:.4f}")

LDA Coherence CV Score: 0.7117
LDA coherence NPMI Score:0.0847
NMF Coherence CV Score: 0.8423
NMF Coherence NPMI Score: 0.0833
BERTopic Coherence Score: 0.7253
BERTopic Coherence NPMI Score: 0.1382
Top2Vec Coherence Score: 0.3414
Top2Vec Coherence NPMI Score: -0.1722
2. Topic Diversity Scores
   LDA Diversity Score:      0.6647
   NMF Diversity Score:      0.9765
   BERTopic Diversity Score: 0.6140
   Top2Vec Diversity Score:  0.2741