In [1]:
import pandas as pd
import random
import numpy as np
import torch
def set_seed(seed):
    """Set seed for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)

In [2]:
dfCovid = pd.read_csv('data/dataRwaCovid.csv')

In [3]:
dfDiabetes = pd.read_csv('data/dataIHADiabetes.csv')

In [4]:
DiabetesTopics = [
    "Physical",
    "Psychological",
    "No Symptoms",
    "Prognosis",
    "Laboratory/Testing",
    "Imaging",
    "Clinical",
    "Testing/Monitoring Devices",
    "Health Data",
    "Diagnostic Methods - Other",
    "Medications",
    "Procedures",
    "Alternative",
    "Physical Therapy",
    "Counseling",
    "Adverse Events",
    "Therapeutic Devices",
    "Treatment(Rx) - Other",
    "Outpatient Logistics/Scheduling",
    "Hospitalizations",
    "Insurance/Billing",
    "Medical Records",
    "Referrals",
    "Transportation",
    "Primary (Pharmaceutical Prevention)",
    "Primary (Non-Pharmaceutical Prevention)",
    "Secondary (Pharmaceutical Prevention)",
    "Secondary (Non-Pharmaceutical Prevention)",
    "Diet/Nutrition",
    "Exercise",
    "Substance Use",
    "Entertainment",
    "Lifestyle - Other",
    "Housing",
    "Work/School",
    "Social Services",
    "Friends & Family",
    "Cultural/Religion",
    "Travel",
    "Physical Environment/Climate",
    "Financial",
    "Social - Other",
    "Technical/IT",
    "Safety Concerns",
    "Health Education",
    "Sexual & Reproductive Health",
    "Child & Family Health",
    "Problems Solved",
    "Grateful Patient",
    "Service Complaint",
    "Request to Stop",
    "Emergent",
    "Urgent",
    "Non-urgent",
    "Stigma Present",
    "Rapport",
    "Transition to Adult Clinic"
]

In [5]:
CovidTopics = [
    "Physical",
    "Mental/Emotional",
    "No Symptoms",
    "Laboratory/Testing",
    "Imaging",
    "Clinical",
    "Diagnostic Methods - Other",
    "Medications",
    "Procedures",
    "Alternative",
    "Physical Therapy",
    "Counseling",
    "Treatment(Rx) - Other",
    "Outpatient Logistics/Scheduling",
    "Hospitalizations",
    "Pharmaceutical Prevention",
    "Non-Pharmaceutical Prevention",
    "Diet/Nutrition",
    "Exercise",
    "Substance Use",
    "Lifestyle - Other",
    "Housing",
    "Work/School",
    "Social Services",
    "Friends & Family",
    "Cultural/Religion",
    "Travel",
    "Physical Environment/Climate",
    "Financial",
    "Social - Other",
    "Technical/IT",
    "Safety concern",
    "Health Education",
    "Maternal & Child Health",
    "Problems Solved",
    "Grateful Patient",
    "Service Complaint",
    "Request to Stop",
    "Emergent",
    "Urgent",
    "Non-urgent",
    "Stigma Present",
    "wave",
    "batch"
]

In [6]:
commonSubtopics = sorted(list(set(DiabetesTopics) & set(CovidTopics)))

In [7]:
dfCovid[commonSubtopics].sum()

Alternative                          35
Clinical                              5
Counseling                            0
Cultural/Religion                   154
Diagnostic Methods - Other            5
Diet/Nutrition                      102
Emergent                            138
Exercise                             25
Financial                            53
Friends & Family                    138
Grateful Patient                    244
Health Education                     45
Hospitalizations                     15
Housing                              32
Imaging                               7
Laboratory/Testing                 1018
Lifestyle - Other                    52
Medications                         152
No Symptoms                        1657
Non-urgent                         2383
Outpatient Logistics/Scheduling     268
Physical                            406
Physical Environment/Climate          6
Physical Therapy                      1
Problems Solved                      45
Procedures                            0
Request to Stop                      50
Service Complaint                   106
Social - Other                        7
Social Services                      30
Stigma Present                       15
Substance Use                         0
Technical/IT                        185
Travel                               12
Treatment(Rx) - Other                 0
Urgent                              270
Work/School                          46
dtype: int64

In [8]:
diabetesColumns = commonSubtopics[:]
diabetesColumns.insert(0,"conversation")
dfDiabetesNew = dfDiabetes[diabetesColumns]

In [9]:
covidColumns = commonSubtopics[:]
covidColumns.insert(0,"conversation(english_only)")
dfCovidNew = dfCovid[covidColumns]

In [10]:
dfCovidNew = dfCovidNew.rename(columns={"conversation(english_only)":"conversation"})

df

In [11]:
dfCombined = pd.concat([dfCovidNew, dfDiabetesNew])

In [12]:
dfCombined.sum()

conversation                       (S): Hello, how are you today? Do you have any...
Alternative                                                                       35
Clinical                                                                           6
Counseling                                                                         0
Cultural/Religion                                                                343
Diagnostic Methods - Other                                                         8
Diet/Nutrition                                                                   340
Emergent                                                                         140
Exercise                                                                         131
Financial                                                                         53
Friends & Family                                                                 291
Grateful Patient                                                                 291
Health Education                                                                 322
Hospitalizations                                                                  15
Housing                                                                           41
Imaging                                                                            8
Laboratory/Testing                                                              1078
Lifestyle - Other                                                                 73
Medications                                                                      418
No Symptoms                                                                     1658
Non-urgent                                                                      3483
Outpatient Logistics/Scheduling                                                  448
Physical                                                                         628
Physical Environment/Climate                                                     203
Physical Therapy                                                                   1
Problems Solved                                                                   57
Procedures                                                                         7
Request to Stop                                                                   56
Service Complaint                                                                116
Social - Other                                                                    10
Social Services                                                                  100
Stigma Present                                                                    15
Substance Use                                                                      0
Technical/IT                                                                     238
Travel                                                                            38
Treatment(Rx) - Other                                                              1
Urgent                                                                           284
Work/School                                                                      143
dtype: object

In [13]:
n = 100
label_sum = dfCombined[commonSubtopics].sum()
label_keep = label_sum[label_sum >= n].index.tolist()
label_keep_original = label_keep[:]
label_keep.insert(0,"conversation")

dfCombined_filtered = dfCombined[label_keep]
dfCombined_filtered.shape

(3907, 20)

In [14]:
dfCombined_filtered.sum()

conversation                       (S): Hello, how are you today? Do you have any...
Cultural/Religion                                                                343
Diet/Nutrition                                                                   340
Emergent                                                                         140
Exercise                                                                         131
Friends & Family                                                                 291
Grateful Patient                                                                 291
Health Education                                                                 322
Laboratory/Testing                                                              1078
Medications                                                                      418
No Symptoms                                                                     1658
Non-urgent                                                                      3483
Outpatient Logistics/Scheduling                                                  448
Physical                                                                         628
Physical Environment/Climate                                                     203
Service Complaint                                                                116
Social Services                                                                  100
Technical/IT                                                                     238
Urgent                                                                           284
Work/School                                                                      143
dtype: object

In [15]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].str.lower()

/tmp/ipykernel_1133/1116881674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].str.lower()

In [16]:
import nltk
import re
import string

In [17]:
!pip install contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 15.4 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 13.6 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.1 textsearch-0.0.24

In [18]:
import contractions

In [19]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([contractions.fix(word) for word in x.split()]))

/tmp/ipykernel_1133/2646981620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([contractions.fix(word) for word in x.split()]))

In [20]:
dfCombined_filtered.shape

(3907, 20)

In [21]:
dfCombined_filtered.head()

,conversation,Cultural/Religion,Diet/Nutrition,Emergent,Exercise,Friends & Family,Grateful Patient,Health Education,Laboratory/Testing,Medications,No Symptoms,Non-urgent,Outpatient Logistics/Scheduling,Physical,Physical Environment/Climate,Service Complaint,Social Services,Technical/IT,Urgent,Work/School
0,"(s): hello, how are you today? do you have any...",1,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0
1,(s): welcome to rwanda ministry of health plat...,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
2,(s): welcome to rwanda ministry of health plat...,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
3,"(s): hello, how are you today? do you have any...",0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0
4,(s): welcome to rwanda ministry of health plat...,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0

In [22]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'\d+','',x))

/tmp/ipykernel_1133/3892837535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'\d+','',x))

In [23]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'[.]',' ',x))

/tmp/ipykernel_1133/1879545715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'[.]',' ',x))

In [24]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: "".join([char for char in x if char not in string.punctuation]))

/tmp/ipykernel_1133/2885321218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: "".join([char for char in x if char not in string.punctuation]))

In [25]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [26]:
from nltk.corpus import stopwords

In [27]:
sw = stopwords.words('english')

In [28]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([word for word in x.split() if word not in sw]))

/tmp/ipykernel_1133/280526503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([word for word in x.split() if word not in sw]))

In [29]:
import nltk
nltk.download("punkt_tab")
nltk.download('punkt')
nltk.download("wordnet")
nltk.download("averaged_perceptron_tagger_eng")
nltk.download('averaged_perceptron_tagger')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

from nltk.corpus import wordnet

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def lemmatize_with_pos(text):
    tokens = nltk.word_tokenize(text)
    tagged_tokens = nltk.pos_tag(tokens)
    return " ".join([lemmatizer.lemmatize(token, get_wordnet_pos(pos)) for token, pos in tagged_tokens])

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

In [30]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lemmatize_with_pos)

/tmp/ipykernel_1133/306948834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lemmatize_with_pos)

In [31]:
dfCombined_filtered.head()
dfCombined_filtered.shape

(3907, 20)

In [32]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

dfCombined_filtered['conversation_tokens'] = dfCombined_filtered['conversation'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/tmp/ipykernel_1133/4092647881.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered['conversation_tokens'] = dfCombined_filtered['conversation'].apply(word_tokenize)

In [33]:
!pip install scikit-multilearn

Collecting scikit-multilearn
  Downloading scikit_multilearn-0.2.0-py3-none-any.whl.metadata (6.0 kB)
Downloading scikit_multilearn-0.2.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 4.7 MB/s eta 0:00:00
Installing collected packages: scikit-multilearn
Successfully installed scikit-multilearn-0.2.0

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import pandas as pd
from skmultilearn.model_selection import iterative_train_test_split
from sklearn.model_selection import train_test_split

In [35]:
tf = TfidfVectorizer(max_features=5000,ngram_range=(1,2),min_df=3,max_df=0.6 )
x =dfCombined_filtered["conversation"]

In [36]:
import torch
# from sklearn.multi
# torch.cuda.get_device_name()

In [37]:
len(label_keep_original)

y = dfCombined_filtered[label_keep_original].to_numpy()
print(y.shape)

(3907, 19)

In [38]:

import numpy as np

split = np.load("data/shared_split_indices.npz")
train_idx = split["train_idx"]
val_idx   = split["val_idx"]
test_idx  = split["test_idx"]

x_raw = dfCombined_filtered["conversation"].to_numpy()
y     = dfCombined_filtered[label_keep_original].to_numpy()

x_train_raw = x_raw[train_idx]
x_val_raw   = x_raw[val_idx]
x_test_raw  = x_raw[test_idx]

y_train = y[train_idx]
y_val   = y[val_idx]
y_test  = y[test_idx]

df_aug_train = pd.read_csv("data/backtranslated_train.csv")

import pandas as pd
import numpy as np
import re
import string
import contractions
import nltk
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

df_aug_train = pd.read_csv('data/backtranslated_train.csv')

y_train = df_aug_train[label_keep_original].to_numpy()

sw = stopwords.words('english')
lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'): return wordnet.ADJ
    elif treebank_tag.startswith('V'): return wordnet.VERB
    elif treebank_tag.startswith('N'): return wordnet.NOUN
    elif treebank_tag.startswith('R'): return wordnet.ADV
    else: return wordnet.NOUN

def lemmatize_with_pos(text):
    tokens = word_tokenize(text)
    tagged = nltk.pos_tag(tokens)
    return " ".join([lemmatizer.lemmatize(tok, get_wordnet_pos(pos)) for tok, pos in tagged])

def preprocess(text):
    text = text.lower()
    text = " ".join([contractions.fix(word) for word in text.split()])
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[.]', ' ', text)
    text = "".join([c for c in text if c not in string.punctuation])
    text = " ".join([w for w in text.split() if w not in sw])
    text = lemmatize_with_pos(text)
    return text

df_aug_train['conversation'] = df_aug_train['conversation'].apply(preprocess)
x_train = df_aug_train["conversation"].to_numpy()

y_train = df_aug_train[label_keep_original].to_numpy()

x_train = tf.fit_transform(pd.Series(x_train.flatten()))
x_val   = tf.transform(pd.Series(x_val_raw.flatten()))
x_test  = tf.transform(pd.Series(x_test_raw.flatten()))

In [39]:
x_train.shape
type(x_train)

scipy.sparse._csr.csr_matrix

In [40]:
y_train.shape
type(y_train)

numpy.ndarray

In [41]:
from xgboost import XGBClassifier
from sklearn.multiclass import OneVsRestClassifier

In [42]:
# x_val,  y_val,  x_test,y_test = iterative_train_test_split(x_, y_, test_size=0.5)

In [43]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)

In [44]:
!pip install --upgrade scikit-multilearn

Requirement already satisfied: scikit-multilearn in /usr/local/lib/python3.12/dist-packages (0.2.0)

In [45]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 18.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [46]:
import optuna

In [47]:
from sklearn.multiclass import OneVsRestClassifier
import numpy as np
from sklearn.metrics import f1_score

In [48]:
from cuml.ensemble import RandomForestClassifier

In [49]:
x_train = x_train.toarray()
x_val = x_val.toarray()
x_test = x_test.toarray()

In [50]:
from enum import auto
models = {}
list_params = {}
for i,label_name in enumerate(label_keep_original):
    print(label_name)
    def objective(trial):
      params = {
       'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
       'max_depth': trial.suggest_int('max_depth', 1, 10),
       'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
       'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 6),
       'n_bins': trial.suggest_int('n_bins', 10, 256),
      'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
      'split_criterion': trial.suggest_categorical('criterion', ['gini', 'entropy']),
      'random_state': 42,

      }
      model = RandomForestClassifier(**params)
      print(type(x_train))
      print(type(y_train[:,i]))
      model.fit(x_train, y_train[:,i])
      x_val_predic = model.predict_proba(x_val)[:, 1]


      best_f1 = 0
      best_thresh = 0.5
      for threshold_val in np.arange(0.05, 0.96, 0.05):
          preds = (x_val_predic > threshold_val).astype(int)
          current_f1 = f1_score(y_val[:, i], preds)
          if current_f1 > best_f1:
              best_f1 = current_f1
              best_thresh = threshold_val
      return best_f1
    study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
    study.optimize(objective, n_trials=50)
    print(f"Best trial for {label_name}: F1 score= {study.best_value:.4f}")
    print(f"Best hyperparameters: {study.best_params}")
    list_params[label_name] = study.best_params

[I 2026-05-25 15:22:57,020] A new study created in memory with name: no-name-80467046-eeaf-4b40-a935-086d74ea3040

Cultural/Religion
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:03,296] Trial 0 finished with value: 0.912621359223301 and parameters: {'n_estimators': 674, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 126, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.912621359223301.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:07,240] Trial 1 finished with value: 0.9038461538461539 and parameters: {'n_estimators': 377, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 250, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.912621359223301.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:10,177] Trial 2 finished with value: 0.9215686274509803 and parameters: {'n_estimators': 735, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 69, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.9215686274509803.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:12,028] Trial 3 finished with value: 0.8080808080808081 and parameters: {'n_estimators': 327, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 102, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.9215686274509803.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:14,634] Trial 4 finished with value: 0.9357798165137615 and parameters: {'n_estimators': 116, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 214, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:20,627] Trial 5 finished with value: 0.9292929292929293 and parameters: {'n_estimators': 649, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 217, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:22,386] Trial 6 finished with value: 0.7764705882352941 and parameters: {'n_estimators': 254, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 182, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:24,257] Trial 7 finished with value: 0.8073394495412844 and parameters: {'n_estimators': 396, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 181, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:28,608] Trial 8 finished with value: 0.8256880733944955 and parameters: {'n_estimators': 905, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_bins': 209, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:33,886] Trial 9 finished with value: 0.8035714285714286 and parameters: {'n_estimators': 972, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 197, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:34,717] Trial 10 finished with value: 0.9357798165137615 and parameters: {'n_estimators': 108, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 27, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:35,562] Trial 11 finished with value: 0.9259259259259259 and parameters: {'n_estimators': 119, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:36,405] Trial 12 finished with value: 0.9259259259259259 and parameters: {'n_estimators': 111, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:37,227] Trial 13 finished with value: 0.8172043010752689 and parameters: {'n_estimators': 235, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 57, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:39,857] Trial 14 finished with value: 0.9090909090909091 and parameters: {'n_estimators': 498, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 156, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:41,000] Trial 15 finished with value: 0.8842105263157894 and parameters: {'n_estimators': 226, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 96, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:42,930] Trial 16 finished with value: 0.9 and parameters: {'n_estimators': 496, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 254, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:44,013] Trial 17 finished with value: 0.9272727272727272 and parameters: {'n_estimators': 119, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 144, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:45,388] Trial 18 finished with value: 0.92 and parameters: {'n_estimators': 233, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 46, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:47,694] Trial 19 finished with value: 0.9038461538461539 and parameters: {'n_estimators': 797, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 114, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:49,050] Trial 20 finished with value: 0.9158878504672897 and parameters: {'n_estimators': 323, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 81, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:51,935] Trial 21 finished with value: 0.9292929292929293 and parameters: {'n_estimators': 615, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 226, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:54,517] Trial 22 finished with value: 0.9357798165137615 and parameters: {'n_estimators': 528, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 224, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:56,773] Trial 23 finished with value: 0.9074074074074074 and parameters: {'n_estimators': 466, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 162, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:23:58,128] Trial 24 finished with value: 0.9259259259259259 and parameters: {'n_estimators': 176, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 236, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:00,560] Trial 25 finished with value: 0.9183673469387755 and parameters: {'n_estimators': 575, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 190, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:02,949] Trial 26 finished with value: 0.819047619047619 and parameters: {'n_estimators': 844, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 166, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:03,893] Trial 27 finished with value: 0.9183673469387755 and parameters: {'n_estimators': 176, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 39, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:05,968] Trial 28 finished with value: 0.9090909090909091 and parameters: {'n_estimators': 310, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 232, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:07,599] Trial 29 finished with value: 0.9038461538461539 and parameters: {'n_estimators': 426, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 136, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:09,832] Trial 30 finished with value: 0.9215686274509803 and parameters: {'n_estimators': 699, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 208, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:12,784] Trial 31 finished with value: 0.9292929292929293 and parameters: {'n_estimators': 637, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 223, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:15,387] Trial 32 finished with value: 0.9357798165137615 and parameters: {'n_estimators': 560, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 212, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:17,957] Trial 33 finished with value: 0.9183673469387755 and parameters: {'n_estimators': 549, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 238, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:19,213] Trial 34 finished with value: 0.9183673469387755 and parameters: {'n_estimators': 163, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 203, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:22,779] Trial 35 finished with value: 0.9292929292929293 and parameters: {'n_estimators': 720, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 244, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:25,801] Trial 36 finished with value: 0.9183673469387755 and parameters: {'n_estimators': 789, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 177, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:27,486] Trial 37 finished with value: 0.803921568627451 and parameters: {'n_estimators': 366, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 256, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:28,844] Trial 38 finished with value: 0.9038461538461539 and parameters: {'n_estimators': 281, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 209, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:30,872] Trial 39 finished with value: 0.8245614035087719 and parameters: {'n_estimators': 559, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 190, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:32,449] Trial 40 finished with value: 0.9038461538461539 and parameters: {'n_estimators': 366, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 148, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:35,505] Trial 41 finished with value: 0.9292929292929293 and parameters: {'n_estimators': 652, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 220, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:38,311] Trial 42 finished with value: 0.9357798165137615 and parameters: {'n_estimators': 608, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 216, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:40,258] Trial 43 finished with value: 0.9183673469387755 and parameters: {'n_estimators': 436, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 174, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:42,640] Trial 44 finished with value: 0.9272727272727272 and parameters: {'n_estimators': 586, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 122, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:44,765] Trial 45 finished with value: 0.8695652173913043 and parameters: {'n_estimators': 511, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 195, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:48,796] Trial 46 finished with value: 0.9259259259259259 and parameters: {'n_estimators': 998, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 213, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.9357798165137615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:52,809] Trial 47 finished with value: 0.94 and parameters: {'n_estimators': 771, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 245, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 47 with value: 0.94.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:55,969] Trial 48 finished with value: 0.9038461538461539 and parameters: {'n_estimators': 931, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 245, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 47 with value: 0.94.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:24:58,685] Trial 49 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 767, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 229, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 47 with value: 0.94.
[I 2026-05-25 15:24:58,687] A new study created in memory with name: no-name-ee7df54b-1f92-4d40-8fa0-822fca5d3127

Best trial for Cultural/Religion: F1 score= 0.9400
Best hyperparameters: {'n_estimators': 771, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 245, 'max_features': 'sqrt', 'criterion': 'entropy'}
Diet/Nutrition
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:00,407] Trial 0 finished with value: 0.7692307692307693 and parameters: {'n_estimators': 644, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 166, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7692307692307693.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:01,292] Trial 1 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 331, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 12, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.7692307692307693.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:03,394] Trial 2 finished with value: 0.8440366972477065 and parameters: {'n_estimators': 632, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 224, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:04,296] Trial 3 finished with value: 0.7209302325581395 and parameters: {'n_estimators': 248, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 13, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:05,801] Trial 4 finished with value: 0.7608695652173914 and parameters: {'n_estimators': 478, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 93, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:07,210] Trial 5 finished with value: 0.7 and parameters: {'n_estimators': 462, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 116, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:09,183] Trial 6 finished with value: 0.7872340425531915 and parameters: {'n_estimators': 370, 'max_depth': 1, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 82, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:13,645] Trial 7 finished with value: 0.7619047619047619 and parameters: {'n_estimators': 994, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 207, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:15,719] Trial 8 finished with value: 0.7209302325581395 and parameters: {'n_estimators': 852, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 77, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:17,188] Trial 9 finished with value: 0.8172043010752689 and parameters: {'n_estimators': 269, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 222, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:19,140] Trial 10 finished with value: 0.75 and parameters: {'n_estimators': 642, 'max_depth': 1, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 247, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:20,345] Trial 11 finished with value: 0.8 and parameters: {'n_estimators': 186, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 238, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:22,619] Trial 12 finished with value: 0.6829268292682927 and parameters: {'n_estimators': 730, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 166, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:23,684] Trial 13 finished with value: 0.8043478260869565 and parameters: {'n_estimators': 129, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 197, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8440366972477065.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:25,480] Trial 14 finished with value: 0.8490566037735849 and parameters: {'n_estimators': 567, 'max_depth': 2, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 211, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 14 with value: 0.8490566037735849.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:27,094] Trial 15 finished with value: 0.8301886792452831 and parameters: {'n_estimators': 579, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 164, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 14 with value: 0.8490566037735849.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:29,636] Trial 16 finished with value: 0.8490566037735849 and parameters: {'n_estimators': 805, 'max_depth': 2, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 254, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 14 with value: 0.8490566037735849.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:31,523] Trial 17 finished with value: 0.7865168539325843 and parameters: {'n_estimators': 795, 'max_depth': 1, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 193, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 14 with value: 0.8490566037735849.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:34,378] Trial 18 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 941, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 250, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:36,568] Trial 19 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 902, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 144, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:39,044] Trial 20 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 953, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 40, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:41,180] Trial 21 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 914, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 139, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:43,700] Trial 22 finished with value: 0.831858407079646 and parameters: {'n_estimators': 910, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 139, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:45,834] Trial 23 finished with value: 0.8490566037735849 and parameters: {'n_estimators': 899, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 133, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:47,820] Trial 24 finished with value: 0.8440366972477065 and parameters: {'n_estimators': 758, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 107, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:49,710] Trial 25 finished with value: 0.7586206896551724 and parameters: {'n_estimators': 869, 'max_depth': 1, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 149, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:52,101] Trial 26 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 997, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 179, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:53,798] Trial 27 finished with value: 0.8347826086956521 and parameters: {'n_estimators': 742, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 53, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:56,074] Trial 28 finished with value: 0.8411214953271028 and parameters: {'n_estimators': 941, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 119, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:25:57,760] Trial 29 finished with value: 0.8 and parameters: {'n_estimators': 706, 'max_depth': 1, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 161, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:00,194] Trial 30 finished with value: 0.8411214953271028 and parameters: {'n_estimators': 827, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 184, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:02,596] Trial 31 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 996, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 180, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:04,775] Trial 32 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 941, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 137, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:07,060] Trial 33 finished with value: 0.8440366972477065 and parameters: {'n_estimators': 886, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 148, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:09,290] Trial 34 finished with value: 0.7692307692307693 and parameters: {'n_estimators': 993, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 177, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 18 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:12,746] Trial 35 finished with value: 0.8737864077669902 and parameters: {'n_estimators': 695, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 235, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 35 with value: 0.8737864077669902.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:15,350] Trial 36 finished with value: 0.7912087912087912 and parameters: {'n_estimators': 684, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 231, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 35 with value: 0.8737864077669902.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:18,841] Trial 37 finished with value: 0.8712871287128713 and parameters: {'n_estimators': 781, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 256, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 35 with value: 0.8737864077669902.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:21,613] Trial 38 finished with value: 0.8712871287128713 and parameters: {'n_estimators': 477, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 255, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.8737864077669902.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:23,678] Trial 39 finished with value: 0.7640449438202247 and parameters: {'n_estimators': 440, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 243, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 35 with value: 0.8737864077669902.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:26,477] Trial 40 finished with value: 0.8712871287128713 and parameters: {'n_estimators': 498, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 219, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.8737864077669902.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:29,284] Trial 41 finished with value: 0.8712871287128713 and parameters: {'n_estimators': 521, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 218, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.8737864077669902.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:32,052] Trial 42 finished with value: 0.88 and parameters: {'n_estimators': 507, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 221, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 42 with value: 0.88.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:34,490] Trial 43 finished with value: 0.8823529411764706 and parameters: {'n_estimators': 420, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 231, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 43 with value: 0.8823529411764706.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:36,850] Trial 44 finished with value: 0.8712871287128713 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 232, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 43 with value: 0.8823529411764706.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:38,447] Trial 45 finished with value: 0.7777777777777778 and parameters: {'n_estimators': 299, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 234, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 43 with value: 0.8823529411764706.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:41,700] Trial 46 finished with value: 0.8712871287128713 and parameters: {'n_estimators': 622, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 255, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 43 with value: 0.8823529411764706.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:43,863] Trial 47 finished with value: 0.8627450980392157 and parameters: {'n_estimators': 383, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 202, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 43 with value: 0.8823529411764706.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:46,019] Trial 48 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 431, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 211, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 43 with value: 0.8823529411764706.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:47,799] Trial 49 finished with value: 0.7777777777777778 and parameters: {'n_estimators': 340, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 242, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 43 with value: 0.8823529411764706.
[I 2026-05-25 15:26:47,801] A new study created in memory with name: no-name-a67943d9-da9d-4a64-9198-ee6af16703b7

Best trial for Diet/Nutrition: F1 score= 0.8824
Best hyperparameters: {'n_estimators': 420, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 231, 'max_features': 'sqrt', 'criterion': 'entropy'}
Emergent
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:50,624] Trial 0 finished with value: 0.38095238095238093 and parameters: {'n_estimators': 713, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 254, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.38095238095238093.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:51,654] Trial 1 finished with value: 0.4375 and parameters: {'n_estimators': 117, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 139, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.4375.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:52,667] Trial 2 finished with value: 0.35294117647058826 and parameters: {'n_estimators': 214, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 136, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.4375.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:53,799] Trial 3 finished with value: 0.07142857142857142 and parameters: {'n_estimators': 390, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 123, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.4375.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:55,057] Trial 4 finished with value: 0.34146341463414637 and parameters: {'n_estimators': 327, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 91, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.4375.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:56,459] Trial 5 finished with value: 0.32 and parameters: {'n_estimators': 902, 'max_depth': 1, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 55, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.4375.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:57,144] Trial 6 finished with value: 0.4489795918367347 and parameters: {'n_estimators': 148, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 31, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 6 with value: 0.4489795918367347.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:26:59,060] Trial 7 finished with value: 0.28125 and parameters: {'n_estimators': 545, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 135, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 6 with value: 0.4489795918367347.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:00,107] Trial 8 finished with value: 0.3177570093457944 and parameters: {'n_estimators': 316, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 31, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 6 with value: 0.4489795918367347.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:04,377] Trial 9 finished with value: 0.41935483870967744 and parameters: {'n_estimators': 904, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 240, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 6 with value: 0.4489795918367347.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:05,364] Trial 10 finished with value: 0.3783783783783784 and parameters: {'n_estimators': 533, 'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 6 with value: 0.4489795918367347.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:06,326] Trial 11 finished with value: 0.41025641025641024 and parameters: {'n_estimators': 105, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 190, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 6 with value: 0.4489795918367347.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:07,353] Trial 12 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 112, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 167, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:08,894] Trial 13 finished with value: 0.4262295081967213 and parameters: {'n_estimators': 245, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 200, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:10,432] Trial 14 finished with value: 0.37362637362637363 and parameters: {'n_estimators': 437, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 186, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:12,558] Trial 15 finished with value: 0.3559322033898305 and parameters: {'n_estimators': 723, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 74, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:13,468] Trial 16 finished with value: 0.3333333333333333 and parameters: {'n_estimators': 182, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 99, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:15,873] Trial 17 finished with value: 0.43478260869565216 and parameters: {'n_estimators': 688, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 160, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:17,105] Trial 18 finished with value: 0.3392857142857143 and parameters: {'n_estimators': 264, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 163, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:18,891] Trial 19 finished with value: 0.3902439024390244 and parameters: {'n_estimators': 413, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 219, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:19,701] Trial 20 finished with value: 0.37209302325581395 and parameters: {'n_estimators': 164, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 47, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:20,724] Trial 21 finished with value: 0.417910447761194 and parameters: {'n_estimators': 111, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 114, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:21,754] Trial 22 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 111, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 160, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 12 with value: 0.45454545454545453.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:23,468] Trial 23 finished with value: 0.46153846153846156 and parameters: {'n_estimators': 286, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 163, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 23 with value: 0.46153846153846156.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:25,446] Trial 24 finished with value: 0.45 and parameters: {'n_estimators': 335, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 162, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 23 with value: 0.46153846153846156.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:27,186] Trial 25 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 256, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 23 with value: 0.46153846153846156.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:28,358] Trial 26 finished with value: 0.3225806451612903 and parameters: {'n_estimators': 202, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 212, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 23 with value: 0.46153846153846156.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:30,724] Trial 27 finished with value: 0.43902439024390244 and parameters: {'n_estimators': 469, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 152, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 23 with value: 0.46153846153846156.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:32,252] Trial 28 finished with value: 0.4666666666666667 and parameters: {'n_estimators': 268, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 181, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:35,430] Trial 29 finished with value: 0.4666666666666667 and parameters: {'n_estimators': 665, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 250, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:38,605] Trial 30 finished with value: 0.41935483870967744 and parameters: {'n_estimators': 622, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 1, 'n_bins': 251, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:42,272] Trial 31 finished with value: 0.36666666666666664 and parameters: {'n_estimators': 813, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 234, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:45,417] Trial 32 finished with value: 0.4 and parameters: {'n_estimators': 766, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 213, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:48,314] Trial 33 finished with value: 0.42424242424242425 and parameters: {'n_estimators': 639, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 182, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:50,436] Trial 34 finished with value: 0.4057971014492754 and parameters: {'n_estimators': 345, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 144, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:52,479] Trial 35 finished with value: 0.2975206611570248 and parameters: {'n_estimators': 508, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 200, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:53,835] Trial 36 finished with value: 0.4166666666666667 and parameters: {'n_estimators': 290, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'n_bins': 117, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:56,434] Trial 37 finished with value: 0.4642857142857143 and parameters: {'n_estimators': 606, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 174, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:27:58,572] Trial 38 finished with value: 0.3434343434343434 and parameters: {'n_estimators': 613, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 200, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:02,152] Trial 39 finished with value: 0.43137254901960786 and parameters: {'n_estimators': 844, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 233, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:04,865] Trial 40 finished with value: 0.4126984126984127 and parameters: {'n_estimators': 587, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:07,857] Trial 41 finished with value: 0.4444444444444444 and parameters: {'n_estimators': 681, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 171, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:09,360] Trial 42 finished with value: 0.38095238095238093 and parameters: {'n_estimators': 371, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 145, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:10,915] Trial 43 finished with value: 0.4507042253521127 and parameters: {'n_estimators': 221, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 175, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:13,206] Trial 44 finished with value: 0.4 and parameters: {'n_estimators': 499, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 191, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:16,494] Trial 45 finished with value: 0.43902439024390244 and parameters: {'n_estimators': 577, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 254, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:19,437] Trial 46 finished with value: 0.40540540540540543 and parameters: {'n_estimators': 981, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 221, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:20,497] Trial 47 finished with value: 0.39285714285714285 and parameters: {'n_estimators': 164, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 98, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:23,285] Trial 48 finished with value: 0.43137254901960786 and parameters: {'n_estimators': 748, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 138, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 28 with value: 0.4666666666666667.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:25,417] Trial 49 finished with value: 0.43902439024390244 and parameters: {'n_estimators': 446, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 149, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 28 with value: 0.4666666666666667.
[I 2026-05-25 15:28:25,419] A new study created in memory with name: no-name-e0e4999b-7b39-446f-ba9a-2a6ccf9d609c

Best trial for Emergent: F1 score= 0.4667
Best hyperparameters: {'n_estimators': 268, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 181, 'max_features': 'sqrt', 'criterion': 'entropy'}
Exercise
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:27,457] Trial 0 finished with value: 0.75 and parameters: {'n_estimators': 441, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 196, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:29,886] Trial 1 finished with value: 0.7317073170731707 and parameters: {'n_estimators': 756, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 113, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:32,690] Trial 2 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 892, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 27, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:34,220] Trial 3 finished with value: 0.6428571428571429 and parameters: {'n_estimators': 387, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 205, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:36,892] Trial 4 finished with value: 0.6428571428571429 and parameters: {'n_estimators': 901, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 124, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:38,146] Trial 5 finished with value: 0.6285714285714286 and parameters: {'n_estimators': 717, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 52, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:39,905] Trial 6 finished with value: 0.48 and parameters: {'n_estimators': 910, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 88, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:41,490] Trial 7 finished with value: 0.6 and parameters: {'n_estimators': 876, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_bins': 84, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:42,510] Trial 8 finished with value: 0.6206896551724138 and parameters: {'n_estimators': 180, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 140, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:45,489] Trial 9 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 868, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:46,826] Trial 10 finished with value: 0.7441860465116279 and parameters: {'n_estimators': 642, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 17, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:49,815] Trial 11 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 988, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 21, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:52,870] Trial 12 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 981, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 13, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:54,872] Trial 13 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 559, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 54, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:28:58,054] Trial 14 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 762, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 162, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:00,803] Trial 15 finished with value: 0.8 and parameters: {'n_estimators': 987, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 46, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:02,172] Trial 16 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 231, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 252, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:04,673] Trial 17 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 797, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:07,367] Trial 18 finished with value: 0.7777777777777778 and parameters: {'n_estimators': 650, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 73, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:08,814] Trial 19 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 439, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 35, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:11,251] Trial 20 finished with value: 0.8 and parameters: {'n_estimators': 835, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 67, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:14,065] Trial 21 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 958, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 12, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:17,194] Trial 22 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 1000, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 16, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:20,053] Trial 23 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 935, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 45, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:22,720] Trial 24 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 831, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 32, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:25,125] Trial 25 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 687, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 93, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:27,051] Trial 26 finished with value: 0.6428571428571429 and parameters: {'n_estimators': 817, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 35, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:29,899] Trial 27 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 821, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 64, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:31,995] Trial 28 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 569, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 67, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:33,452] Trial 29 finished with value: 0.75 and parameters: {'n_estimators': 277, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 188, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:35,306] Trial 30 finished with value: 0.7441860465116279 and parameters: {'n_estimators': 606, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 103, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:38,083] Trial 31 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 832, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 33, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:40,648] Trial 32 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 742, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 62, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:43,078] Trial 33 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 799, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 36, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:45,075] Trial 34 finished with value: 0.7272727272727273 and parameters: {'n_estimators': 860, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:47,111] Trial 35 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 482, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 81, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:49,194] Trial 36 finished with value: 0.6428571428571429 and parameters: {'n_estimators': 933, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 50, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:55,029] Trial 37 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 770, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 143, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:29:57,958] Trial 38 finished with value: 0.6428571428571429 and parameters: {'n_estimators': 704, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 35, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:02,489] Trial 39 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 898, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 58, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:04,667] Trial 40 finished with value: 0.6428571428571429 and parameters: {'n_estimators': 858, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 75, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:07,253] Trial 41 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 722, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 61, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:10,147] Trial 42 finished with value: 0.8108108108108109 and parameters: {'n_estimators': 746, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 97, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:13,285] Trial 43 finished with value: 0.8571428571428571 and parameters: {'n_estimators': 902, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 121, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:14,733] Trial 44 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 834, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 24, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:16,894] Trial 45 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 655, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 43, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:19,453] Trial 46 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 769, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:22,455] Trial 47 finished with value: 0.8235294117647058 and parameters: {'n_estimators': 946, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 58, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:23,211] Trial 48 finished with value: 0.48 and parameters: {'n_estimators': 120, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 82, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 11 with value: 0.8571428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:24,816] Trial 49 finished with value: 0.6206896551724138 and parameters: {'n_estimators': 887, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 23, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 11 with value: 0.8571428571428571.
[I 2026-05-25 15:30:24,818] A new study created in memory with name: no-name-23125e11-1ae1-4918-a4ed-b734e4e1644a

Best trial for Exercise: F1 score= 0.8571
Best hyperparameters: {'n_estimators': 988, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 21, 'max_features': 'sqrt', 'criterion': 'gini'}
Friends & Family
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:26,706] Trial 0 finished with value: 0.27692307692307694 and parameters: {'n_estimators': 978, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 84, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.27692307692307694.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:27,610] Trial 1 finished with value: 0.2988505747126437 and parameters: {'n_estimators': 316, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 13, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.2988505747126437.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:29,769] Trial 2 finished with value: 0.275 and parameters: {'n_estimators': 568, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 245, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.2988505747126437.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:31,092] Trial 3 finished with value: 0.4888888888888889 and parameters: {'n_estimators': 205, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 231, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.4888888888888889.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:32,664] Trial 4 finished with value: 0.5486725663716814 and parameters: {'n_estimators': 264, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 184, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.5486725663716814.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:34,021] Trial 5 finished with value: 0.379746835443038 and parameters: {'n_estimators': 287, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 219, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.5486725663716814.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:35,520] Trial 6 finished with value: 0.1568627450980392 and parameters: {'n_estimators': 447, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 227, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.5486725663716814.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:37,199] Trial 7 finished with value: 0.5585585585585585 and parameters: {'n_estimators': 350, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 119, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 7 with value: 0.5585585585585585.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:39,145] Trial 8 finished with value: 0.2702702702702703 and parameters: {'n_estimators': 693, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 158, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 7 with value: 0.5585585585585585.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:40,415] Trial 9 finished with value: 0.5102040816326531 and parameters: {'n_estimators': 168, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 214, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 7 with value: 0.5585585585585585.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:43,406] Trial 10 finished with value: 0.5739130434782609 and parameters: {'n_estimators': 751, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 100, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.5739130434782609.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:46,565] Trial 11 finished with value: 0.5689655172413793 and parameters: {'n_estimators': 795, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 104, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.5739130434782609.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:49,558] Trial 12 finished with value: 0.6017699115044248 and parameters: {'n_estimators': 833, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 75, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:52,562] Trial 13 finished with value: 0.5569620253164557 and parameters: {'n_estimators': 872, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 59, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:54,808] Trial 14 finished with value: 0.584070796460177 and parameters: {'n_estimators': 658, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_bins': 47, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:57,060] Trial 15 finished with value: 0.591304347826087 and parameters: {'n_estimators': 636, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 34, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:30:58,695] Trial 16 finished with value: 0.5636363636363636 and parameters: {'n_estimators': 532, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:01,551] Trial 17 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 898, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 58, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:03,491] Trial 18 finished with value: 0.29213483146067415 and parameters: {'n_estimators': 625, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 145, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:06,017] Trial 19 finished with value: 0.584070796460177 and parameters: {'n_estimators': 819, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 37, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:09,184] Trial 20 finished with value: 0.6 and parameters: {'n_estimators': 989, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 77, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:12,212] Trial 21 finished with value: 0.6 and parameters: {'n_estimators': 985, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 73, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:15,306] Trial 22 finished with value: 0.5892857142857143 and parameters: {'n_estimators': 996, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 82, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:17,763] Trial 23 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 916, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 74, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:21,340] Trial 24 finished with value: 0.5892857142857143 and parameters: {'n_estimators': 1000, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 128, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.6017699115044248.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:24,811] Trial 25 finished with value: 0.6024096385542169 and parameters: {'n_estimators': 918, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 103, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 25 with value: 0.6024096385542169.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:27,120] Trial 26 finished with value: 0.36893203883495146 and parameters: {'n_estimators': 855, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 105, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 25 with value: 0.6024096385542169.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:30,276] Trial 27 finished with value: 0.6071428571428571 and parameters: {'n_estimators': 754, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 159, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:33,568] Trial 28 finished with value: 0.5663716814159292 and parameters: {'n_estimators': 741, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 179, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:35,262] Trial 29 finished with value: 0.14779874213836477 and parameters: {'n_estimators': 753, 'max_depth': 1, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 157, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:38,934] Trial 30 finished with value: 0.5688073394495413 and parameters: {'n_estimators': 908, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 188, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:42,002] Trial 31 finished with value: 0.5862068965517241 and parameters: {'n_estimators': 815, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 97, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:45,543] Trial 32 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 928, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 123, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:48,362] Trial 33 finished with value: 0.5740740740740741 and parameters: {'n_estimators': 932, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 84, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:50,920] Trial 34 finished with value: 0.3469387755102041 and parameters: {'n_estimators': 859, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 139, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:54,344] Trial 35 finished with value: 0.5892857142857143 and parameters: {'n_estimators': 952, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 114, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:56,963] Trial 36 finished with value: 0.5964912280701754 and parameters: {'n_estimators': 704, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 64, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:31:59,037] Trial 37 finished with value: 0.28125 and parameters: {'n_estimators': 795, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 156, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:00,247] Trial 38 finished with value: 0.2619047619047619 and parameters: {'n_estimators': 551, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 26, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:02,835] Trial 39 finished with value: 0.5660377358490566 and parameters: {'n_estimators': 839, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 89, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:04,599] Trial 40 finished with value: 0.4842105263157895 and parameters: {'n_estimators': 439, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 195, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:07,594] Trial 41 finished with value: 0.5945945945945946 and parameters: {'n_estimators': 972, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 72, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:10,294] Trial 42 finished with value: 0.5945945945945946 and parameters: {'n_estimators': 888, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 50, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:13,528] Trial 43 finished with value: 0.5789473684210527 and parameters: {'n_estimators': 956, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 73, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:16,141] Trial 44 finished with value: 0.5871559633027523 and parameters: {'n_estimators': 783, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:20,233] Trial 45 finished with value: 0.5137614678899083 and parameters: {'n_estimators': 964, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 254, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:22,702] Trial 46 finished with value: 0.56 and parameters: {'n_estimators': 882, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 93, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:26,014] Trial 47 finished with value: 0.5811965811965812 and parameters: {'n_estimators': 996, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 47, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:28,881] Trial 48 finished with value: 0.5892857142857143 and parameters: {'n_estimators': 710, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 166, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 27 with value: 0.6071428571428571.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:31,549] Trial 49 finished with value: 0.42718446601941745 and parameters: {'n_estimators': 844, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 135, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 27 with value: 0.6071428571428571.
[I 2026-05-25 15:32:31,551] A new study created in memory with name: no-name-0d501cef-575e-4706-b681-d53280bf07b0

Best trial for Friends & Family: F1 score= 0.6071
Best hyperparameters: {'n_estimators': 754, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 159, 'max_features': 'sqrt', 'criterion': 'gini'}
Grateful Patient
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:33,591] Trial 0 finished with value: 0.13312202852614896 and parameters: {'n_estimators': 881, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 190, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.13312202852614896.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:35,287] Trial 1 finished with value: 0.5588235294117647 and parameters: {'n_estimators': 499, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 206, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.5588235294117647.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:37,285] Trial 2 finished with value: 0.5783132530120482 and parameters: {'n_estimators': 705, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 164, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.5783132530120482.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:38,399] Trial 3 finished with value: 0.5892857142857143 and parameters: {'n_estimators': 218, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 60, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.5892857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:40,852] Trial 4 finished with value: 0.55 and parameters: {'n_estimators': 446, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 249, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.5892857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:42,866] Trial 5 finished with value: 0.4666666666666667 and parameters: {'n_estimators': 521, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 238, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 3 with value: 0.5892857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:44,475] Trial 6 finished with value: 0.40404040404040403 and parameters: {'n_estimators': 480, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 107, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.5892857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:47,700] Trial 7 finished with value: 0.3870967741935484 and parameters: {'n_estimators': 915, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 135, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 3 with value: 0.5892857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:50,984] Trial 8 finished with value: 0.6078431372549019 and parameters: {'n_estimators': 445, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 169, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:53,303] Trial 9 finished with value: 0.5531914893617021 and parameters: {'n_estimators': 496, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 48, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:55,653] Trial 10 finished with value: 0.5555555555555556 and parameters: {'n_estimators': 131, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 1, 'n_bins': 102, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:57,213] Trial 11 finished with value: 0.5546218487394958 and parameters: {'n_estimators': 225, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:32:59,170] Trial 12 finished with value: 0.5517241379310345 and parameters: {'n_estimators': 281, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 61, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:01,367] Trial 13 finished with value: 0.5739130434782609 and parameters: {'n_estimators': 310, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 142, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:03,274] Trial 14 finished with value: 0.6078431372549019 and parameters: {'n_estimators': 673, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 85, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:05,139] Trial 15 finished with value: 0.5957446808510638 and parameters: {'n_estimators': 690, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 101, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 8 with value: 0.6078431372549019.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:07,391] Trial 16 finished with value: 0.6122448979591837 and parameters: {'n_estimators': 687, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 172, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:10,445] Trial 17 finished with value: 0.5970149253731343 and parameters: {'n_estimators': 797, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 178, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:11,962] Trial 18 finished with value: 0.3870967741935484 and parameters: {'n_estimators': 372, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 218, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:14,415] Trial 19 finished with value: 0.5757575757575758 and parameters: {'n_estimators': 628, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 160, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:16,112] Trial 20 finished with value: 0.42105263157894735 and parameters: {'n_estimators': 591, 'max_depth': 1, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 213, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:18,370] Trial 21 finished with value: 0.5918367346938775 and parameters: {'n_estimators': 757, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 120, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:20,440] Trial 22 finished with value: 0.5961538461538461 and parameters: {'n_estimators': 622, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 156, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:22,292] Trial 23 finished with value: 0.5185185185185185 and parameters: {'n_estimators': 821, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 89, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:24,161] Trial 24 finished with value: 0.584070796460177 and parameters: {'n_estimators': 413, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 185, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:26,560] Trial 25 finished with value: 0.5869565217391305 and parameters: {'n_estimators': 973, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 85, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:28,387] Trial 26 finished with value: 0.4722222222222222 and parameters: {'n_estimators': 690, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 138, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:30,380] Trial 27 finished with value: 0.6095238095238096 and parameters: {'n_estimators': 576, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 119, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:32,544] Trial 28 finished with value: 0.5915492957746479 and parameters: {'n_estimators': 552, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 122, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:33,956] Trial 29 finished with value: 0.5316455696202531 and parameters: {'n_estimators': 377, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 172, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:36,382] Trial 30 finished with value: 0.6037735849056604 and parameters: {'n_estimators': 575, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 200, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:38,642] Trial 31 finished with value: 0.6122448979591837 and parameters: {'n_estimators': 650, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 148, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.6122448979591837.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:41,577] Trial 32 finished with value: 0.6336633663366337 and parameters: {'n_estimators': 830, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 197, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:44,337] Trial 33 finished with value: 0.6019417475728155 and parameters: {'n_estimators': 849, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 152, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:46,397] Trial 34 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 760, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 189, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:49,812] Trial 35 finished with value: 0.6019417475728155 and parameters: {'n_estimators': 895, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 229, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:52,255] Trial 36 finished with value: 0.5393258426966292 and parameters: {'n_estimators': 747, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 199, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:54,531] Trial 37 finished with value: 0.5765765765765766 and parameters: {'n_estimators': 634, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 122, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:33:58,168] Trial 38 finished with value: 0.41904761904761906 and parameters: {'n_estimators': 985, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 251, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:01,807] Trial 39 finished with value: 0.6 and parameters: {'n_estimators': 926, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 147, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:03,928] Trial 40 finished with value: 0.5185185185185185 and parameters: {'n_estimators': 737, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 167, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:05,833] Trial 41 finished with value: 0.5882352941176471 and parameters: {'n_estimators': 525, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 180, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:07,538] Trial 42 finished with value: 0.6078431372549019 and parameters: {'n_estimators': 443, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 168, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:09,539] Trial 43 finished with value: 0.5538461538461539 and parameters: {'n_estimators': 473, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 130, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:11,705] Trial 44 finished with value: 0.5617977528089888 and parameters: {'n_estimators': 645, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 196, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:16,047] Trial 45 finished with value: 0.5892857142857143 and parameters: {'n_estimators': 589, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 226, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:17,604] Trial 46 finished with value: 0.45652173913043476 and parameters: {'n_estimators': 529, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 113, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:20,083] Trial 47 finished with value: 0.5979381443298969 and parameters: {'n_estimators': 802, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 149, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:22,488] Trial 48 finished with value: 0.58 and parameters: {'n_estimators': 662, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 210, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 32 with value: 0.6336633663366337.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:25,360] Trial 49 finished with value: 0.6138613861386139 and parameters: {'n_estimators': 856, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 32 with value: 0.6336633663366337.
[I 2026-05-25 15:34:25,361] A new study created in memory with name: no-name-2ededfc5-9050-4bb4-a8d5-5a9491d3e13a

Best trial for Grateful Patient: F1 score= 0.6337
Best hyperparameters: {'n_estimators': 830, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 197, 'max_features': 'sqrt', 'criterion': 'gini'}
Health Education
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:26,154] Trial 0 finished with value: 0.6506024096385542 and parameters: {'n_estimators': 212, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 30, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.6506024096385542.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:28,159] Trial 1 finished with value: 0.75 and parameters: {'n_estimators': 880, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:29,328] Trial 2 finished with value: 0.6111111111111112 and parameters: {'n_estimators': 928, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_bins': 39, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:30,508] Trial 3 finished with value: 0.6534653465346535 and parameters: {'n_estimators': 206, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 224, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:33,475] Trial 4 finished with value: 0.7333333333333333 and parameters: {'n_estimators': 862, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 191, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:34,684] Trial 5 finished with value: 0.6829268292682927 and parameters: {'n_estimators': 357, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 72, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:35,694] Trial 6 finished with value: 0.6585365853658537 and parameters: {'n_estimators': 518, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:37,060] Trial 7 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 408, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 124, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:38,092] Trial 8 finished with value: 0.6265060240963856 and parameters: {'n_estimators': 266, 'max_depth': 1, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 144, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:41,307] Trial 9 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 887, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 194, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:43,994] Trial 10 finished with value: 0.7333333333333333 and parameters: {'n_estimators': 700, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 90, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:46,716] Trial 11 finished with value: 0.7272727272727273 and parameters: {'n_estimators': 742, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 255, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:50,279] Trial 12 finished with value: 0.7111111111111111 and parameters: {'n_estimators': 992, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 164, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:52,737] Trial 13 finished with value: 0.7272727272727273 and parameters: {'n_estimators': 763, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 186, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:55,091] Trial 14 finished with value: 0.7191011235955056 and parameters: {'n_estimators': 617, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 113, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:34:56,867] Trial 15 finished with value: 0.6746987951807228 and parameters: {'n_estimators': 855, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 71, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:00,067] Trial 16 finished with value: 0.7191011235955056 and parameters: {'n_estimators': 821, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 213, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:02,037] Trial 17 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 576, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 161, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:03,396] Trial 18 finished with value: 0.6590909090909091 and parameters: {'n_estimators': 520, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 100, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:04,375] Trial 19 finished with value: 0.7032967032967034 and parameters: {'n_estimators': 110, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 153, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:05,888] Trial 20 finished with value: 0.6904761904761905 and parameters: {'n_estimators': 618, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 54, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:09,337] Trial 21 finished with value: 0.7191011235955056 and parameters: {'n_estimators': 1000, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:11,866] Trial 22 finished with value: 0.7333333333333333 and parameters: {'n_estimators': 642, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 216, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:14,292] Trial 23 finished with value: 0.735632183908046 and parameters: {'n_estimators': 781, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 139, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:16,779] Trial 24 finished with value: 0.7272727272727273 and parameters: {'n_estimators': 787, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 133, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:18,794] Trial 25 finished with value: 0.6746987951807228 and parameters: {'n_estimators': 685, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 155, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:20,091] Trial 26 finished with value: 0.6590909090909091 and parameters: {'n_estimators': 442, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 114, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:22,050] Trial 27 finished with value: 0.7333333333333333 and parameters: {'n_estimators': 573, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 87, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:24,840] Trial 28 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 913, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 169, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:27,692] Trial 29 finished with value: 0.7111111111111111 and parameters: {'n_estimators': 931, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 18, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:30,017] Trial 30 finished with value: 0.6585365853658537 and parameters: {'n_estimators': 921, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 164, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:32,525] Trial 31 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 813, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 135, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:35,410] Trial 32 finished with value: 0.75 and parameters: {'n_estimators': 952, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 173, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:38,246] Trial 33 finished with value: 0.7272727272727273 and parameters: {'n_estimators': 922, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 205, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:41,460] Trial 34 finished with value: 0.6470588235294118 and parameters: {'n_estimators': 959, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 1, 'n_bins': 240, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:44,612] Trial 35 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 867, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:46,769] Trial 36 finished with value: 0.65 and parameters: {'n_estimators': 716, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 174, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:47,897] Trial 37 finished with value: 0.7272727272727273 and parameters: {'n_estimators': 329, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 43, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:50,658] Trial 38 finished with value: 0.6746987951807228 and parameters: {'n_estimators': 888, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 230, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:53,013] Trial 39 finished with value: 0.7096774193548387 and parameters: {'n_estimators': 829, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 195, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:54,885] Trial 40 finished with value: 0.7555555555555555 and parameters: {'n_estimators': 455, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 120, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:56,692] Trial 41 finished with value: 0.7333333333333333 and parameters: {'n_estimators': 447, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 154, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:58,069] Trial 42 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 342, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 119, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:35:59,190] Trial 43 finished with value: 0.7191011235955056 and parameters: {'n_estimators': 252, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 70, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:01,263] Trial 44 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 488, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 188, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:03,430] Trial 45 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 948, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'n_bins': 13, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:05,157] Trial 46 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 414, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 169, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:07,501] Trial 47 finished with value: 0.7333333333333333 and parameters: {'n_estimators': 546, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 102, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:10,184] Trial 48 finished with value: 0.7415730337078652 and parameters: {'n_estimators': 969, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 144, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 40 with value: 0.7555555555555555.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:12,017] Trial 49 finished with value: 0.6585365853658537 and parameters: {'n_estimators': 378, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 203, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 40 with value: 0.7555555555555555.
[I 2026-05-25 15:36:12,019] A new study created in memory with name: no-name-5c9dad08-fadf-4aed-b39a-af92bdaf467b

Best trial for Health Education: F1 score= 0.7556
Best hyperparameters: {'n_estimators': 455, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 120, 'max_features': 'sqrt', 'criterion': 'gini'}
Laboratory/Testing
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:14,337] Trial 0 finished with value: 0.8192771084337349 and parameters: {'n_estimators': 630, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 215, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8192771084337349.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:15,053] Trial 1 finished with value: 0.6782006920415224 and parameters: {'n_estimators': 151, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 49, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.8192771084337349.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:16,870] Trial 2 finished with value: 0.8680351906158358 and parameters: {'n_estimators': 404, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 74, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8680351906158358.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:17,976] Trial 3 finished with value: 0.88125 and parameters: {'n_estimators': 156, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 77, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:21,678] Trial 4 finished with value: 0.8795180722891566 and parameters: {'n_estimators': 715, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 185, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:24,716] Trial 5 finished with value: 0.8106508875739645 and parameters: {'n_estimators': 990, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 176, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:26,158] Trial 6 finished with value: 0.5725806451612904 and parameters: {'n_estimators': 564, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 174, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:27,391] Trial 7 finished with value: 0.742671009771987 and parameters: {'n_estimators': 747, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 29, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:29,105] Trial 8 finished with value: 0.7756410256410257 and parameters: {'n_estimators': 721, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 143, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:31,117] Trial 9 finished with value: 0.8764705882352941 and parameters: {'n_estimators': 385, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 98, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:32,098] Trial 10 finished with value: 0.8670520231213873 and parameters: {'n_estimators': 107, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 121, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:36,523] Trial 11 finished with value: 0.8768768768768769 and parameters: {'n_estimators': 921, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 239, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:38,088] Trial 12 finished with value: 0.8650137741046832 and parameters: {'n_estimators': 331, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 180, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:41,260] Trial 13 finished with value: 0.8771929824561403 and parameters: {'n_estimators': 858, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 83, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:42,329] Trial 14 finished with value: 0.8681318681318682 and parameters: {'n_estimators': 268, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:44,055] Trial 15 finished with value: 0.861878453038674 and parameters: {'n_estimators': 487, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 132, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:48,326] Trial 16 finished with value: 0.8802395209580839 and parameters: {'n_estimators': 751, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 256, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:49,762] Trial 17 finished with value: 0.8713450292397661 and parameters: {'n_estimators': 207, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 252, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:51,789] Trial 18 finished with value: 0.8613569321533924 and parameters: {'n_estimators': 823, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 54, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:54,292] Trial 19 finished with value: 0.873900293255132 and parameters: {'n_estimators': 516, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 215, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:36:56,572] Trial 20 finished with value: 0.867816091954023 and parameters: {'n_estimators': 625, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 107, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:00,418] Trial 21 finished with value: 0.8805031446540881 and parameters: {'n_estimators': 717, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 205, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:04,005] Trial 22 finished with value: 0.8795180722891566 and parameters: {'n_estimators': 636, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 222, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:08,352] Trial 23 finished with value: 0.8727272727272727 and parameters: {'n_estimators': 801, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 255, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.88125.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:12,847] Trial 24 finished with value: 0.8828828828828829 and parameters: {'n_estimators': 888, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 198, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:16,412] Trial 25 finished with value: 0.867816091954023 and parameters: {'n_estimators': 906, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 157, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:19,569] Trial 26 finished with value: 0.8203592814371258 and parameters: {'n_estimators': 937, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 199, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:21,947] Trial 27 finished with value: 0.8664688427299704 and parameters: {'n_estimators': 462, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 152, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:26,260] Trial 28 finished with value: 0.8797653958944281 and parameters: {'n_estimators': 987, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 200, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:28,836] Trial 29 finished with value: 0.8217522658610272 and parameters: {'n_estimators': 679, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 231, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:31,200] Trial 30 finished with value: 0.8713450292397661 and parameters: {'n_estimators': 596, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 202, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:35,530] Trial 31 finished with value: 0.8802395209580839 and parameters: {'n_estimators': 785, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 236, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:38,862] Trial 32 finished with value: 0.8771929824561403 and parameters: {'n_estimators': 669, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 212, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:43,029] Trial 33 finished with value: 0.8771929824561403 and parameters: {'n_estimators': 880, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 163, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:46,008] Trial 34 finished with value: 0.867816091954023 and parameters: {'n_estimators': 758, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 75, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:48,833] Trial 35 finished with value: 0.8154761904761905 and parameters: {'n_estimators': 808, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 190, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:53,400] Trial 36 finished with value: 0.8828828828828829 and parameters: {'n_estimators': 853, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 242, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:54,666] Trial 37 finished with value: 0.6597222222222222 and parameters: {'n_estimators': 850, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 46, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:37:59,166] Trial 38 finished with value: 0.880466472303207 and parameters: {'n_estimators': 963, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 226, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:02,239] Trial 39 finished with value: 0.8771929824561403 and parameters: {'n_estimators': 547, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 242, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:04,084] Trial 40 finished with value: 0.7218543046357616 and parameters: {'n_estimators': 704, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 168, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:08,523] Trial 41 finished with value: 0.8823529411764706 and parameters: {'n_estimators': 975, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 227, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:12,572] Trial 42 finished with value: 0.8746355685131195 and parameters: {'n_estimators': 903, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 208, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:16,541] Trial 43 finished with value: 0.8693009118541033 and parameters: {'n_estimators': 994, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 189, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:20,779] Trial 44 finished with value: 0.8797653958944281 and parameters: {'n_estimators': 950, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 218, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:22,120] Trial 45 finished with value: 0.8797653958944281 and parameters: {'n_estimators': 168, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 242, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.8828828828828829.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:25,571] Trial 46 finished with value: 0.8830409356725146 and parameters: {'n_estimators': 840, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 46 with value: 0.8830409356725146.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:28,414] Trial 47 finished with value: 0.8731563421828908 and parameters: {'n_estimators': 846, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 93, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 46 with value: 0.8830409356725146.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:30,144] Trial 48 finished with value: 0.8764705882352941 and parameters: {'n_estimators': 376, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 110, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 46 with value: 0.8830409356725146.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:31,792] Trial 49 finished with value: 0.8802395209580839 and parameters: {'n_estimators': 303, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 130, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 46 with value: 0.8830409356725146.
[I 2026-05-25 15:38:31,794] A new study created in memory with name: no-name-6318a2b2-f0de-4705-9e77-686e8dcfc992

Best trial for Laboratory/Testing: F1 score= 0.8830
Best hyperparameters: {'n_estimators': 840, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'gini'}
Medications
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:33,161] Trial 0 finished with value: 0.7090909090909091 and parameters: {'n_estimators': 270, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 224, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.7090909090909091.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:35,423] Trial 1 finished with value: 0.6601941747572816 and parameters: {'n_estimators': 873, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 157, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.7090909090909091.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:39,068] Trial 2 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 743, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 230, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8484848484848485.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:40,341] Trial 3 finished with value: 0.22553897180762852 and parameters: {'n_estimators': 857, 'max_depth': 1, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 66, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8484848484848485.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:42,020] Trial 4 finished with value: 0.49070631970260226 and parameters: {'n_estimators': 809, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 120, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.8484848484848485.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:42,885] Trial 5 finished with value: 0.7107438016528925 and parameters: {'n_estimators': 208, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 14, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.8484848484848485.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:46,649] Trial 6 finished with value: 0.8888888888888888 and parameters: {'n_estimators': 783, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 241, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 6 with value: 0.8888888888888888.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:47,765] Trial 7 finished with value: 0.8661417322834646 and parameters: {'n_estimators': 142, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 6 with value: 0.8888888888888888.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:49,766] Trial 8 finished with value: 0.8872180451127819 and parameters: {'n_estimators': 494, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 94, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 6 with value: 0.8888888888888888.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:51,338] Trial 9 finished with value: 0.8032786885245902 and parameters: {'n_estimators': 403, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 145, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 6 with value: 0.8888888888888888.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:54,774] Trial 10 finished with value: 0.9051094890510949 and parameters: {'n_estimators': 681, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 256, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:38:58,107] Trial 11 finished with value: 0.8970588235294118 and parameters: {'n_estimators': 652, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 251, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:01,054] Trial 12 finished with value: 0.9051094890510949 and parameters: {'n_estimators': 621, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 189, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:04,453] Trial 13 finished with value: 0.832 and parameters: {'n_estimators': 992, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 190, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:06,735] Trial 14 finished with value: 0.8661417322834646 and parameters: {'n_estimators': 600, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 193, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:08,932] Trial 15 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 436, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 192, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:11,065] Trial 16 finished with value: 0.7454545454545455 and parameters: {'n_estimators': 666, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 207, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:13,367] Trial 17 finished with value: 0.8837209302325582 and parameters: {'n_estimators': 560, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 171, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:15,198] Trial 18 finished with value: 0.7008547008547008 and parameters: {'n_estimators': 353, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 256, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:18,368] Trial 19 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 707, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 213, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:21,687] Trial 20 finished with value: 0.8702290076335878 and parameters: {'n_estimators': 971, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 171, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:24,957] Trial 21 finished with value: 0.9051094890510949 and parameters: {'n_estimators': 626, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 256, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:27,676] Trial 22 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 509, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 231, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:30,690] Trial 23 finished with value: 0.8721804511278195 and parameters: {'n_estimators': 608, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 253, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9051094890510949.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:33,942] Trial 24 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 704, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 210, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:36,838] Trial 25 finished with value: 0.8837209302325582 and parameters: {'n_estimators': 737, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 206, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:39,777] Trial 26 finished with value: 0.7017543859649122 and parameters: {'n_estimators': 897, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 170, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:41,594] Trial 27 finished with value: 0.7678571428571429 and parameters: {'n_estimators': 513, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 218, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:45,093] Trial 28 finished with value: 0.9037037037037037 and parameters: {'n_estimators': 807, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 188, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:47,606] Trial 29 finished with value: 0.7192982456140351 and parameters: {'n_estimators': 694, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 230, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:49,173] Trial 30 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 314, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 96, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:52,327] Trial 31 finished with value: 0.8970588235294118 and parameters: {'n_estimators': 611, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 232, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:55,221] Trial 32 finished with value: 0.8970588235294118 and parameters: {'n_estimators': 558, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 241, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:39:58,214] Trial 33 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 648, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 220, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:00,580] Trial 34 finished with value: 0.7394957983193278 and parameters: {'n_estimators': 760, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 155, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:03,160] Trial 35 finished with value: 0.8444444444444444 and parameters: {'n_estimators': 452, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 242, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:06,808] Trial 36 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 858, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 205, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:08,031] Trial 37 finished with value: 0.6857142857142857 and parameters: {'n_estimators': 728, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 22, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:12,353] Trial 38 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 903, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 241, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:15,917] Trial 39 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 813, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 180, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:17,971] Trial 40 finished with value: 0.6321243523316062 and parameters: {'n_estimators': 833, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 138, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:21,245] Trial 41 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 761, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 178, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:24,592] Trial 42 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 787, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 179, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:27,852] Trial 43 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 794, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 153, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:31,444] Trial 44 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 905, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 120, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:34,806] Trial 45 finished with value: 0.8955223880597015 and parameters: {'n_estimators': 953, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 102, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:38,940] Trial 46 finished with value: 0.8548387096774194 and parameters: {'n_estimators': 886, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 128, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:42,495] Trial 47 finished with value: 0.8872180451127819 and parameters: {'n_estimators': 947, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:45,369] Trial 48 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 771, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 79, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:47,874] Trial 49 finished with value: 0.7192982456140351 and parameters: {'n_estimators': 833, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 174, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 24 with value: 0.9117647058823529.
[I 2026-05-25 15:40:47,876] A new study created in memory with name: no-name-248d3df2-4581-4896-af29-5f616c18f59e

Best trial for Medications: F1 score= 0.9118
Best hyperparameters: {'n_estimators': 704, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 210, 'max_features': 'sqrt', 'criterion': 'gini'}
No Symptoms
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:49,674] Trial 0 finished with value: 0.7787934186471663 and parameters: {'n_estimators': 629, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 82, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7787934186471663.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:50,997] Trial 1 finished with value: 0.763302752293578 and parameters: {'n_estimators': 619, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 16, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7787934186471663.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:52,514] Trial 2 finished with value: 0.6776470588235294 and parameters: {'n_estimators': 795, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 76, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.7787934186471663.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:53,540] Trial 3 finished with value: 0.7865168539325843 and parameters: {'n_estimators': 174, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 81, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:55,219] Trial 4 finished with value: 0.7474747474747475 and parameters: {'n_estimators': 623, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 154, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:56,550] Trial 5 finished with value: 0.7717996289424861 and parameters: {'n_estimators': 351, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 101, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:40:58,790] Trial 6 finished with value: 0.7596899224806202 and parameters: {'n_estimators': 653, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 212, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:00,766] Trial 7 finished with value: 0.7775768535262206 and parameters: {'n_estimators': 506, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 149, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:01,915] Trial 8 finished with value: 0.6915351506456241 and parameters: {'n_estimators': 866, 'max_depth': 1, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 30, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:03,022] Trial 9 finished with value: 0.7383966244725738 and parameters: {'n_estimators': 329, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 122, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:04,230] Trial 10 finished with value: 0.7703984819734345 and parameters: {'n_estimators': 162, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 240, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:05,270] Trial 11 finished with value: 0.7823008849557522 and parameters: {'n_estimators': 133, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 64, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 3 with value: 0.7865168539325843.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:06,281] Trial 12 finished with value: 0.7945205479452054 and parameters: {'n_estimators': 133, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 53, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 12 with value: 0.7945205479452054.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:07,660] Trial 13 finished with value: 0.7884615384615384 and parameters: {'n_estimators': 273, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 48, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 12 with value: 0.7945205479452054.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:09,132] Trial 14 finished with value: 0.7816901408450704 and parameters: {'n_estimators': 341, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 44, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 12 with value: 0.7945205479452054.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:10,522] Trial 15 finished with value: 0.8133086876155268 and parameters: {'n_estimators': 265, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:12,522] Trial 16 finished with value: 0.8068181818181818 and parameters: {'n_estimators': 456, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:14,534] Trial 17 finished with value: 0.8045540796963947 and parameters: {'n_estimators': 461, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:16,871] Trial 18 finished with value: 0.8088531187122736 and parameters: {'n_estimators': 458, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 181, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:21,148] Trial 19 finished with value: 0.8075471698113208 and parameters: {'n_estimators': 992, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 193, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:22,626] Trial 20 finished with value: 0.7846153846153846 and parameters: {'n_estimators': 262, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 185, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:26,862] Trial 21 finished with value: 0.8052930056710775 and parameters: {'n_estimators': 995, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 193, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:30,249] Trial 22 finished with value: 0.804040404040404 and parameters: {'n_estimators': 762, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 171, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:34,401] Trial 23 finished with value: 0.784452296819788 and parameters: {'n_estimators': 993, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 228, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:36,660] Trial 24 finished with value: 0.790224032586558 and parameters: {'n_estimators': 455, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 209, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:39,061] Trial 25 finished with value: 0.8015122873345936 and parameters: {'n_estimators': 532, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:40,439] Trial 26 finished with value: 0.7884615384615384 and parameters: {'n_estimators': 234, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:42,641] Trial 27 finished with value: 0.7977099236641222 and parameters: {'n_estimators': 371, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 249, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:45,147] Trial 28 finished with value: 0.7876588021778584 and parameters: {'n_estimators': 713, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 156, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:48,503] Trial 29 finished with value: 0.8022598870056498 and parameters: {'n_estimators': 849, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 113, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:50,541] Trial 30 finished with value: 0.7869481765834933 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 206, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:52,539] Trial 31 finished with value: 0.8060263653483992 and parameters: {'n_estimators': 436, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 34, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:55,040] Trial 32 finished with value: 0.8022388059701493 and parameters: {'n_estimators': 598, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:41:57,300] Trial 33 finished with value: 0.7946257197696737 and parameters: {'n_estimators': 557, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:00,695] Trial 34 finished with value: 0.7849686847599165 and parameters: {'n_estimators': 692, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 226, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:03,142] Trial 35 finished with value: 0.8060836501901141 and parameters: {'n_estimators': 497, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 92, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:04,461] Trial 36 finished with value: 0.795959595959596 and parameters: {'n_estimators': 214, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 144, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:06,227] Trial 37 finished with value: 0.7479674796747967 and parameters: {'n_estimators': 591, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 167, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:08,073] Trial 38 finished with value: 0.7907869481765835 and parameters: {'n_estimators': 310, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 200, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:09,605] Trial 39 finished with value: 0.7700729927007299 and parameters: {'n_estimators': 420, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 78, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:12,351] Trial 40 finished with value: 0.7739602169981917 and parameters: {'n_estimators': 893, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 104, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:14,648] Trial 41 finished with value: 0.8128544423440454 and parameters: {'n_estimators': 491, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 61, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:16,816] Trial 42 finished with value: 0.7954110898661568 and parameters: {'n_estimators': 484, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 67, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:19,213] Trial 43 finished with value: 0.8040816326530612 and parameters: {'n_estimators': 547, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 23, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:20,256] Trial 44 finished with value: 0.5902439024390244 and parameters: {'n_estimators': 393, 'max_depth': 1, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 62, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:21,801] Trial 45 finished with value: 0.7669172932330827 and parameters: {'n_estimators': 653, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 38, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:23,202] Trial 46 finished with value: 0.8038095238095239 and parameters: {'n_estimators': 319, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:24,256] Trial 47 finished with value: 0.7923211169284468 and parameters: {'n_estimators': 193, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 23, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:25,779] Trial 48 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 283, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 222, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:27,724] Trial 49 finished with value: 0.7829181494661922 and parameters: {'n_estimators': 521, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 58, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 15 with value: 0.8133086876155268.
[I 2026-05-25 15:42:27,726] A new study created in memory with name: no-name-e77fb319-ec8f-4999-958e-ac1cf67214f2

Best trial for No Symptoms: F1 score= 0.8133
Best hyperparameters: {'n_estimators': 265, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'entropy'}
Non-urgent
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:29,044] Trial 0 finished with value: 0.9470802919708029 and parameters: {'n_estimators': 470, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 143, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.9470802919708029.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:31,258] Trial 1 finished with value: 0.9504761904761905 and parameters: {'n_estimators': 635, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 211, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.9504761904761905.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:34,701] Trial 2 finished with value: 0.9534246575342465 and parameters: {'n_estimators': 672, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 206, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:36,165] Trial 3 finished with value: 0.9475620975160993 and parameters: {'n_estimators': 418, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:37,040] Trial 4 finished with value: 0.9422382671480144 and parameters: {'n_estimators': 214, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 95, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:39,970] Trial 5 finished with value: 0.9499545040946314 and parameters: {'n_estimators': 785, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 170, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:41,439] Trial 6 finished with value: 0.9456521739130435 and parameters: {'n_estimators': 433, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 190, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:43,389] Trial 7 finished with value: 0.9466063348416289 and parameters: {'n_estimators': 645, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 118, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:44,382] Trial 8 finished with value: 0.9410698096101541 and parameters: {'n_estimators': 104, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 236, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:47,052] Trial 9 finished with value: 0.9500454132606722 and parameters: {'n_estimators': 843, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 146, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9534246575342465.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:50,054] Trial 10 finished with value: 0.9543336439888164 and parameters: {'n_estimators': 964, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 23, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9543336439888164.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:53,041] Trial 11 finished with value: 0.954248366013072 and parameters: {'n_estimators': 984, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 19, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 10 with value: 0.9543336439888164.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:56,024] Trial 12 finished with value: 0.9551401869158879 and parameters: {'n_estimators': 962, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 19, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 12 with value: 0.9551401869158879.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:42:59,136] Trial 13 finished with value: 0.9561157796451915 and parameters: {'n_estimators': 943, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:01,235] Trial 14 finished with value: 0.9518413597733711 and parameters: {'n_estimators': 842, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 63, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:04,329] Trial 15 finished with value: 0.9550045913682277 and parameters: {'n_estimators': 900, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 57, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:06,179] Trial 16 finished with value: 0.9522058823529411 and parameters: {'n_estimators': 739, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 50, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:09,156] Trial 17 finished with value: 0.9521178637200737 and parameters: {'n_estimators': 915, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 86, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:12,281] Trial 18 finished with value: 0.9528301886792453 and parameters: {'n_estimators': 999, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 1, 'n_bins': 19, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:14,540] Trial 19 finished with value: 0.9535315985130112 and parameters: {'n_estimators': 735, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 93, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:16,423] Trial 20 finished with value: 0.9537037037037037 and parameters: {'n_estimators': 524, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 41, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:19,522] Trial 21 finished with value: 0.9533582089552238 and parameters: {'n_estimators': 879, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 62, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:22,536] Trial 22 finished with value: 0.9522058823529411 and parameters: {'n_estimators': 895, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 39, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:25,465] Trial 23 finished with value: 0.9533394327538883 and parameters: {'n_estimators': 803, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 74, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:27,683] Trial 24 finished with value: 0.953168044077135 and parameters: {'n_estimators': 913, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:29,059] Trial 25 finished with value: 0.9543336439888164 and parameters: {'n_estimators': 289, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 39, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:32,287] Trial 26 finished with value: 0.9538745387453874 and parameters: {'n_estimators': 948, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 106, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:34,765] Trial 27 finished with value: 0.9532538955087076 and parameters: {'n_estimators': 735, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 57, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:36,683] Trial 28 finished with value: 0.953168044077135 and parameters: {'n_estimators': 587, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 33, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:38,176] Trial 29 finished with value: 0.9491833030852994 and parameters: {'n_estimators': 816, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 76, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:40,840] Trial 30 finished with value: 0.9541284403669725 and parameters: {'n_estimators': 874, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:43,874] Trial 31 finished with value: 0.9560336763330215 and parameters: {'n_estimators': 957, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 27, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:46,678] Trial 32 finished with value: 0.9544186046511628 and parameters: {'n_estimators': 940, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 31, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:50,135] Trial 33 finished with value: 0.9543336439888164 and parameters: {'n_estimators': 993, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 50, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:52,342] Trial 34 finished with value: 0.9532538955087076 and parameters: {'n_estimators': 688, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 28, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:54,178] Trial 35 finished with value: 0.9490909090909091 and parameters: {'n_estimators': 783, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 69, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:56,671] Trial 36 finished with value: 0.9523809523809523 and parameters: {'n_estimators': 863, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:43:59,237] Trial 37 finished with value: 0.9512195121951219 and parameters: {'n_estimators': 922, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 143, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:01,622] Trial 38 finished with value: 0.953168044077135 and parameters: {'n_estimators': 953, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 45, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:03,231] Trial 39 finished with value: 0.9541284403669725 and parameters: {'n_estimators': 311, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:05,500] Trial 40 finished with value: 0.9508196721311475 and parameters: {'n_estimators': 777, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 110, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:08,452] Trial 41 finished with value: 0.9561157796451915 and parameters: {'n_estimators': 926, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 29, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:11,296] Trial 42 finished with value: 0.9561157796451915 and parameters: {'n_estimators': 899, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:14,095] Trial 43 finished with value: 0.9561157796451915 and parameters: {'n_estimators': 828, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:16,602] Trial 44 finished with value: 0.9529190207156308 and parameters: {'n_estimators': 838, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 29, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:20,215] Trial 45 finished with value: 0.9544186046511628 and parameters: {'n_estimators': 600, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 251, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:23,371] Trial 46 finished with value: 0.9546716003700277 and parameters: {'n_estimators': 701, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 214, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:25,088] Trial 47 finished with value: 0.9532538955087076 and parameters: {'n_estimators': 835, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 23, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:28,355] Trial 48 finished with value: 0.9529085872576177 and parameters: {'n_estimators': 999, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 82, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 13 with value: 0.9561157796451915.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:31,699] Trial 49 finished with value: 0.9524697110904008 and parameters: {'n_estimators': 881, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 50, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 13 with value: 0.9561157796451915.
[I 2026-05-25 15:44:31,700] A new study created in memory with name: no-name-0cce3896-091f-4bf2-a9d6-abb99600568a

Best trial for Non-urgent: F1 score= 0.9561
Best hyperparameters: {'n_estimators': 943, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'gini'}
Outpatient Logistics/Scheduling
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:32,753] Trial 0 finished with value: 0.7034482758620689 and parameters: {'n_estimators': 175, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 16, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:34,609] Trial 1 finished with value: 0.41304347826086957 and parameters: {'n_estimators': 827, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 116, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:36,175] Trial 2 finished with value: 0.4791666666666667 and parameters: {'n_estimators': 570, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 122, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:37,563] Trial 3 finished with value: 0.5544554455445545 and parameters: {'n_estimators': 492, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 100, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:38,620] Trial 4 finished with value: 0.6194690265486725 and parameters: {'n_estimators': 221, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 114, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:39,573] Trial 5 finished with value: 0.6324786324786325 and parameters: {'n_estimators': 137, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 88, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:42,029] Trial 6 finished with value: 0.656934306569343 and parameters: {'n_estimators': 551, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 214, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:44,857] Trial 7 finished with value: 0.6774193548387096 and parameters: {'n_estimators': 843, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 174, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:47,558] Trial 8 finished with value: 0.6890756302521008 and parameters: {'n_estimators': 556, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 163, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:48,392] Trial 9 finished with value: 0.5904761904761905 and parameters: {'n_estimators': 166, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 67, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:49,775] Trial 10 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 310, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:52,077] Trial 11 finished with value: 0.68 and parameters: {'n_estimators': 394, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:55,750] Trial 12 finished with value: 0.6805555555555556 and parameters: {'n_estimators': 711, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 253, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:44:58,262] Trial 13 finished with value: 0.6942148760330579 and parameters: {'n_estimators': 646, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 38, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:01,031] Trial 14 finished with value: 0.6573426573426573 and parameters: {'n_estimators': 978, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:03,899] Trial 15 finished with value: 0.6942148760330579 and parameters: {'n_estimators': 719, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 49, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:05,708] Trial 16 finished with value: 0.6618705035971223 and parameters: {'n_estimators': 434, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 40, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:06,956] Trial 17 finished with value: 0.38202247191011235 and parameters: {'n_estimators': 705, 'max_depth': 1, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 40, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:08,236] Trial 18 finished with value: 0.6611570247933884 and parameters: {'n_estimators': 346, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 78, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:10,117] Trial 19 finished with value: 0.6616541353383458 and parameters: {'n_estimators': 606, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 30, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:11,486] Trial 20 finished with value: 0.6571428571428571 and parameters: {'n_estimators': 264, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 57, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:14,201] Trial 21 finished with value: 0.7 and parameters: {'n_estimators': 677, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 54, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7034482758620689.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:16,914] Trial 22 finished with value: 0.7096774193548387 and parameters: {'n_estimators': 655, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 24, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:20,215] Trial 23 finished with value: 0.7066666666666667 and parameters: {'n_estimators': 830, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 20, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:23,386] Trial 24 finished with value: 0.7019867549668874 and parameters: {'n_estimators': 825, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 20, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:27,370] Trial 25 finished with value: 0.6991869918699187 and parameters: {'n_estimators': 939, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 74, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:29,157] Trial 26 finished with value: 0.5871559633027523 and parameters: {'n_estimators': 785, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 27, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:33,624] Trial 27 finished with value: 0.688 and parameters: {'n_estimators': 932, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 151, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:35,884] Trial 28 finished with value: 0.6891891891891891 and parameters: {'n_estimators': 471, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 94, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:37,479] Trial 29 finished with value: 0.4791666666666667 and parameters: {'n_estimators': 776, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 65, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:40,451] Trial 30 finished with value: 0.6938775510204082 and parameters: {'n_estimators': 914, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:44,030] Trial 31 finished with value: 0.6845637583892618 and parameters: {'n_estimators': 858, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 35, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:47,157] Trial 32 finished with value: 0.7096774193548387 and parameters: {'n_estimators': 788, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 24, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 22 with value: 0.7096774193548387.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:49,747] Trial 33 finished with value: 0.7154471544715447 and parameters: {'n_estimators': 624, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 24, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:52,786] Trial 34 finished with value: 0.7154471544715447 and parameters: {'n_estimators': 765, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 24, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:55,721] Trial 35 finished with value: 0.7049180327868853 and parameters: {'n_estimators': 621, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 107, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:45:58,497] Trial 36 finished with value: 0.7027027027027027 and parameters: {'n_estimators': 753, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 51, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:00,979] Trial 37 finished with value: 0.7096774193548387 and parameters: {'n_estimators': 494, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 132, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:02,373] Trial 38 finished with value: 0.4175824175824176 and parameters: {'n_estimators': 659, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 82, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:04,864] Trial 39 finished with value: 0.6991869918699187 and parameters: {'n_estimators': 589, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:07,445] Trial 40 finished with value: 0.6956521739130435 and parameters: {'n_estimators': 879, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 63, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:10,086] Trial 41 finished with value: 0.697986577181208 and parameters: {'n_estimators': 497, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 149, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:12,854] Trial 42 finished with value: 0.6802721088435374 and parameters: {'n_estimators': 524, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 202, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:16,554] Trial 43 finished with value: 0.704 and parameters: {'n_estimators': 755, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 135, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:19,962] Trial 44 finished with value: 0.6891891891891891 and parameters: {'n_estimators': 560, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 251, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:23,025] Trial 45 finished with value: 0.7096774193548387 and parameters: {'n_estimators': 628, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 123, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:24,848] Trial 46 finished with value: 0.6055045871559633 and parameters: {'n_estimators': 427, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 211, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:27,791] Trial 47 finished with value: 0.6942148760330579 and parameters: {'n_estimators': 684, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 45, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:30,604] Trial 48 finished with value: 0.6756756756756757 and parameters: {'n_estimators': 731, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 34, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.7154471544715447.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:33,284] Trial 49 finished with value: 0.6891891891891891 and parameters: {'n_estimators': 792, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 21, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 33 with value: 0.7154471544715447.
[I 2026-05-25 15:46:33,286] A new study created in memory with name: no-name-9533d04f-dbf7-4951-9b6c-c7346d42ba18

Best trial for Outpatient Logistics/Scheduling: F1 score= 0.7154
Best hyperparameters: {'n_estimators': 624, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 24, 'max_features': 'sqrt', 'criterion': 'entropy'}
Physical
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:34,436] Trial 0 finished with value: 0.30254777070063693 and parameters: {'n_estimators': 533, 'max_depth': 1, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 38, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.30254777070063693.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:35,477] Trial 1 finished with value: 0.28029197080291973 and parameters: {'n_estimators': 924, 'max_depth': 1, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 21, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.30254777070063693.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:36,326] Trial 2 finished with value: 0.5037037037037037 and parameters: {'n_estimators': 112, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 166, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.5037037037037037.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:37,804] Trial 3 finished with value: 0.609271523178808 and parameters: {'n_estimators': 370, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 172, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 3 with value: 0.609271523178808.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:38,763] Trial 4 finished with value: 0.654320987654321 and parameters: {'n_estimators': 151, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 98, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 4 with value: 0.654320987654321.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:40,169] Trial 5 finished with value: 0.6419753086419753 and parameters: {'n_estimators': 307, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 177, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.654320987654321.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:41,292] Trial 6 finished with value: 0.6136363636363636 and parameters: {'n_estimators': 213, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 206, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 4 with value: 0.654320987654321.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:44,365] Trial 7 finished with value: 0.7368421052631579 and parameters: {'n_estimators': 595, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 183, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 7 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:47,297] Trial 8 finished with value: 0.7444444444444445 and parameters: {'n_estimators': 741, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 103, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 8 with value: 0.7444444444444445.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:49,101] Trial 9 finished with value: 0.7419354838709677 and parameters: {'n_estimators': 429, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 88, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 8 with value: 0.7444444444444445.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:52,064] Trial 10 finished with value: 0.5255474452554745 and parameters: {'n_estimators': 830, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 254, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 8 with value: 0.7444444444444445.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:54,314] Trial 11 finished with value: 0.75 and parameters: {'n_estimators': 669, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 94, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:56,779] Trial 12 finished with value: 0.7472527472527473 and parameters: {'n_estimators': 743, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 100, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:46:58,756] Trial 13 finished with value: 0.7134502923976608 and parameters: {'n_estimators': 685, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 66, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:02,007] Trial 14 finished with value: 0.7403314917127072 and parameters: {'n_estimators': 951, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:04,558] Trial 15 finished with value: 0.7362637362637363 and parameters: {'n_estimators': 766, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 133, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:06,701] Trial 16 finished with value: 0.73224043715847 and parameters: {'n_estimators': 630, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 69, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:08,422] Trial 17 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 482, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:10,343] Trial 18 finished with value: 0.5906040268456376 and parameters: {'n_estimators': 837, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 57, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:12,880] Trial 19 finished with value: 0.7444444444444445 and parameters: {'n_estimators': 703, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:14,865] Trial 20 finished with value: 0.6871165644171779 and parameters: {'n_estimators': 995, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 44, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:17,731] Trial 21 finished with value: 0.7292817679558011 and parameters: {'n_estimators': 770, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 91, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:20,926] Trial 22 finished with value: 0.7340425531914894 and parameters: {'n_estimators': 672, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 143, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:23,909] Trial 23 finished with value: 0.7344632768361582 and parameters: {'n_estimators': 835, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 110, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:25,882] Trial 24 finished with value: 0.73224043715847 and parameters: {'n_estimators': 561, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 78, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 11 with value: 0.75.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:28,837] Trial 25 finished with value: 0.7608695652173914 and parameters: {'n_estimators': 729, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 150, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 25 with value: 0.7608695652173914.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:31,431] Trial 26 finished with value: 0.632258064516129 and parameters: {'n_estimators': 888, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 151, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 25 with value: 0.7608695652173914.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:34,107] Trial 27 finished with value: 0.7362637362637363 and parameters: {'n_estimators': 617, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 202, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 25 with value: 0.7608695652173914.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:36,426] Trial 28 finished with value: 0.745945945945946 and parameters: {'n_estimators': 521, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 117, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 25 with value: 0.7608695652173914.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:39,163] Trial 29 finished with value: 0.7684210526315789 and parameters: {'n_estimators': 803, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:41,753] Trial 30 finished with value: 0.7593582887700535 and parameters: {'n_estimators': 805, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 17, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:44,356] Trial 31 finished with value: 0.7486631016042781 and parameters: {'n_estimators': 818, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:47,186] Trial 32 finished with value: 0.7486631016042781 and parameters: {'n_estimators': 891, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 24, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:49,854] Trial 33 finished with value: 0.7486631016042781 and parameters: {'n_estimators': 792, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 42, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:51,370] Trial 34 finished with value: 0.6375 and parameters: {'n_estimators': 658, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 10, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:53,939] Trial 35 finished with value: 0.75 and parameters: {'n_estimators': 902, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 35, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:56,229] Trial 36 finished with value: 0.7526881720430108 and parameters: {'n_estimators': 724, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 28, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:47:58,173] Trial 37 finished with value: 0.6496815286624203 and parameters: {'n_estimators': 952, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 24, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:00,491] Trial 38 finished with value: 0.7593582887700535 and parameters: {'n_estimators': 715, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 33, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:01,955] Trial 39 finished with value: 0.28029197080291973 and parameters: {'n_estimators': 866, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 54, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:04,597] Trial 40 finished with value: 0.7634408602150538 and parameters: {'n_estimators': 556, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 163, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:06,516] Trial 41 finished with value: 0.7419354838709677 and parameters: {'n_estimators': 350, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 193, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:08,985] Trial 42 finished with value: 0.7403314917127072 and parameters: {'n_estimators': 575, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 166, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:11,670] Trial 43 finished with value: 0.7431693989071039 and parameters: {'n_estimators': 524, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 225, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:13,888] Trial 44 finished with value: 0.7486631016042781 and parameters: {'n_estimators': 444, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 6, 'n_bins': 156, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:15,189] Trial 45 finished with value: 0.7446808510638298 and parameters: {'n_estimators': 257, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:17,524] Trial 46 finished with value: 0.609271523178808 and parameters: {'n_estimators': 714, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 180, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:20,735] Trial 47 finished with value: 0.7553191489361702 and parameters: {'n_estimators': 782, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 49, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:23,074] Trial 48 finished with value: 0.7526881720430108 and parameters: {'n_estimators': 746, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 32, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:25,641] Trial 49 finished with value: 0.7472527472527473 and parameters: {'n_estimators': 640, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 157, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 29 with value: 0.7684210526315789.
[I 2026-05-25 15:48:25,643] A new study created in memory with name: no-name-e9c3d8d6-c689-4051-916f-93d843739204

Best trial for Physical: F1 score= 0.7684
Best hyperparameters: {'n_estimators': 803, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'gini'}
Physical Environment/Climate
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:26,793] Trial 0 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 145, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 187, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8421052631578947.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:27,920] Trial 1 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 251, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 126, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:29,298] Trial 2 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 249, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 220, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:30,374] Trial 3 finished with value: 0.8292682926829268 and parameters: {'n_estimators': 244, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 131, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:31,406] Trial 4 finished with value: 0.8292682926829268 and parameters: {'n_estimators': 534, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 17, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:32,430] Trial 5 finished with value: 0.8108108108108109 and parameters: {'n_estimators': 380, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 27, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:34,504] Trial 6 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 640, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 176, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:36,766] Trial 7 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 652, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 248, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:37,763] Trial 8 finished with value: 0.5333333333333333 and parameters: {'n_estimators': 217, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 186, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:38,944] Trial 9 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 245, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 28, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:41,095] Trial 10 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 999, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 102, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:43,557] Trial 11 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 748, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 256, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:44,801] Trial 12 finished with value: 0.8108108108108109 and parameters: {'n_estimators': 491, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 90, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:47,011] Trial 13 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 803, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 78, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:48,562] Trial 14 finished with value: 0.85 and parameters: {'n_estimators': 428, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 145, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:50,558] Trial 15 finished with value: 0.17391304347826086 and parameters: {'n_estimators': 657, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 251, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:52,847] Trial 16 finished with value: 0.8108108108108109 and parameters: {'n_estimators': 944, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 150, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:54,031] Trial 17 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 370, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 66, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:55,638] Trial 18 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 622, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 119, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:58,023] Trial 19 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 798, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 215, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:58,861] Trial 20 finished with value: 0.5333333333333333 and parameters: {'n_estimators': 114, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 161, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:48:59,900] Trial 21 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 356, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 66, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:00,907] Trial 22 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 350, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 52, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:02,034] Trial 23 finished with value: 0.8095238095238095 and parameters: {'n_estimators': 438, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 47, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:03,111] Trial 24 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 297, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 116, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:04,778] Trial 25 finished with value: 0.8108108108108109 and parameters: {'n_estimators': 545, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 2, 'n_bins': 101, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:06,614] Trial 26 finished with value: 0.85 and parameters: {'n_estimators': 434, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 222, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:07,985] Trial 27 finished with value: 0.5333333333333333 and parameters: {'n_estimators': 725, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 77, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:09,322] Trial 28 finished with value: 0.8095238095238095 and parameters: {'n_estimators': 305, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 201, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:10,283] Trial 29 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 137, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 160, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:11,925] Trial 30 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 595, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 46, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:12,780] Trial 31 finished with value: 0.85 and parameters: {'n_estimators': 185, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 62, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:13,792] Trial 32 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 338, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 71, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:14,946] Trial 33 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 291, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 132, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:16,344] Trial 34 finished with value: 0.8095238095238095 and parameters: {'n_estimators': 478, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 95, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:17,342] Trial 35 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 179, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 119, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:19,189] Trial 36 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 398, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 233, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:20,208] Trial 37 finished with value: 0.8108108108108109 and parameters: {'n_estimators': 503, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 16, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:21,316] Trial 38 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 352, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 32, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:22,715] Trial 39 finished with value: 0.85 and parameters: {'n_estimators': 255, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 177, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:23,760] Trial 40 finished with value: 0.17391304347826086 and parameters: {'n_estimators': 572, 'max_depth': 1, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 61, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:24,755] Trial 41 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 360, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 48, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:25,588] Trial 42 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 208, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 39, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:26,900] Trial 43 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 682, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 57, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:27,921] Trial 44 finished with value: 0.8095238095238095 and parameters: {'n_estimators': 261, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 86, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:28,807] Trial 45 finished with value: 0.8717948717948718 and parameters: {'n_estimators': 301, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 24, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:30,186] Trial 46 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 391, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 112, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:31,447] Trial 47 finished with value: 0.8421052631578947 and parameters: {'n_estimators': 476, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 67, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:32,556] Trial 48 finished with value: 0.8095238095238095 and parameters: {'n_estimators': 334, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 87, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.8717948717948718.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:33,776] Trial 49 finished with value: 0.8108108108108109 and parameters: {'n_estimators': 230, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 194, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.8717948717948718.
[I 2026-05-25 15:49:33,778] A new study created in memory with name: no-name-2426d2fd-b21e-45e6-9a68-ab669e7dda2e

Best trial for Physical Environment/Climate: F1 score= 0.8718
Best hyperparameters: {'n_estimators': 251, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 126, 'max_features': 'log2', 'criterion': 'entropy'}
Service Complaint
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:38,879] Trial 0 finished with value: 0.3076923076923077 and parameters: {'n_estimators': 946, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 1, 'n_bins': 247, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.3076923076923077.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:41,760] Trial 1 finished with value: 0.23529411764705882 and parameters: {'n_estimators': 619, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 214, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.3076923076923077.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:44,051] Trial 2 finished with value: 0.35294117647058826 and parameters: {'n_estimators': 613, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 186, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:45,658] Trial 3 finished with value: 0.3404255319148936 and parameters: {'n_estimators': 447, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 44, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:47,838] Trial 4 finished with value: 0.26666666666666666 and parameters: {'n_estimators': 699, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 179, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:48,811] Trial 5 finished with value: 0.32142857142857145 and parameters: {'n_estimators': 182, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 23, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:49,943] Trial 6 finished with value: 0.11764705882352941 and parameters: {'n_estimators': 163, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_bins': 230, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:50,739] Trial 7 finished with value: 0.0 and parameters: {'n_estimators': 219, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 67, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:51,713] Trial 8 finished with value: 0.0 and parameters: {'n_estimators': 126, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 254, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:52,633] Trial 9 finished with value: 0.2 and parameters: {'n_estimators': 244, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 32, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:54,852] Trial 10 finished with value: 0.0 and parameters: {'n_estimators': 817, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 125, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:56,904] Trial 11 finished with value: 0.2916666666666667 and parameters: {'n_estimators': 439, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 130, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:49:58,911] Trial 12 finished with value: 0.26666666666666666 and parameters: {'n_estimators': 474, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 173, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:00,432] Trial 13 finished with value: 0.25806451612903225 and parameters: {'n_estimators': 445, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 96, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:01,916] Trial 14 finished with value: 0.2608695652173913 and parameters: {'n_estimators': 342, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 181, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:04,269] Trial 15 finished with value: 0.2222222222222222 and parameters: {'n_estimators': 608, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 71, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:06,908] Trial 16 finished with value: 0.23809523809523808 and parameters: {'n_estimators': 727, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 150, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.35294117647058826.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:08,417] Trial 17 finished with value: 0.3684210526315789 and parameters: {'n_estimators': 319, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 97, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:09,630] Trial 18 finished with value: 0.0 and parameters: {'n_estimators': 329, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 96, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:12,034] Trial 19 finished with value: 0.0 and parameters: {'n_estimators': 856, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 205, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:13,604] Trial 20 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 339, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 156, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:15,180] Trial 21 finished with value: 0.35 and parameters: {'n_estimators': 343, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 149, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:16,872] Trial 22 finished with value: 0.15384615384615385 and parameters: {'n_estimators': 533, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 120, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:18,369] Trial 23 finished with value: 0.35 and parameters: {'n_estimators': 312, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 162, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:20,394] Trial 24 finished with value: 0.17391304347826086 and parameters: {'n_estimators': 558, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 202, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:21,842] Trial 25 finished with value: 0.35555555555555557 and parameters: {'n_estimators': 270, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 96, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:22,976] Trial 26 finished with value: 0.0 and parameters: {'n_estimators': 253, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 103, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 17 with value: 0.3684210526315789.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:23,884] Trial 27 finished with value: 0.3793103448275862 and parameters: {'n_estimators': 104, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 64, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.3793103448275862.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:25,585] Trial 28 finished with value: 0.3333333333333333 and parameters: {'n_estimators': 396, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 68, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.3793103448275862.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:26,657] Trial 29 finished with value: 0.27848101265822783 and parameters: {'n_estimators': 140, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 60, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.3793103448275862.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:29,395] Trial 30 finished with value: 0.3018867924528302 and parameters: {'n_estimators': 969, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 11, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.3793103448275862.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:30,301] Trial 31 finished with value: 0.2857142857142857 and parameters: {'n_estimators': 101, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 85, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.3793103448275862.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:31,649] Trial 32 finished with value: 0.3783783783783784 and parameters: {'n_estimators': 286, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 27 with value: 0.3793103448275862.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:33,295] Trial 33 finished with value: 0.3902439024390244 and parameters: {'n_estimators': 379, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 115, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.3902439024390244.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:34,864] Trial 34 finished with value: 0.25806451612903225 and parameters: {'n_estimators': 394, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 109, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 33 with value: 0.3902439024390244.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:35,944] Trial 35 finished with value: 0.4 and parameters: {'n_estimators': 194, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 84, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:37,111] Trial 36 finished with value: 0.3125 and parameters: {'n_estimators': 194, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 49, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:38,394] Trial 37 finished with value: 0.3508771929824561 and parameters: {'n_estimators': 179, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 116, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:39,559] Trial 38 finished with value: 0.25806451612903225 and parameters: {'n_estimators': 273, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 81, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:40,441] Trial 39 finished with value: 0.24 and parameters: {'n_estimators': 104, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 135, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:41,501] Trial 40 finished with value: 0.2857142857142857 and parameters: {'n_estimators': 217, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 48, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:42,821] Trial 41 finished with value: 0.38095238095238093 and parameters: {'n_estimators': 296, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 86, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:43,868] Trial 42 finished with value: 0.375 and parameters: {'n_estimators': 160, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 82, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:45,142] Trial 43 finished with value: 0.2702702702702703 and parameters: {'n_estimators': 391, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 31, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:46,339] Trial 44 finished with value: 0.3 and parameters: {'n_estimators': 229, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 58, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:47,892] Trial 45 finished with value: 0.32558139534883723 and parameters: {'n_estimators': 281, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 135, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:49,486] Trial 46 finished with value: 0.16 and parameters: {'n_estimators': 493, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 111, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:50,392] Trial 47 finished with value: 0.0 and parameters: {'n_estimators': 214, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 85, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:51,339] Trial 48 finished with value: 0.36 and parameters: {'n_estimators': 143, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 78, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 35 with value: 0.4.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:52,458] Trial 49 finished with value: 0.21052631578947367 and parameters: {'n_estimators': 285, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 37, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 35 with value: 0.4.
[I 2026-05-25 15:50:52,460] A new study created in memory with name: no-name-4e8379e8-6123-4a11-9677-3586d9a50357

Best trial for Service Complaint: F1 score= 0.4000
Best hyperparameters: {'n_estimators': 194, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 84, 'max_features': 'sqrt', 'criterion': 'entropy'}
Social Services
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:54,612] Trial 0 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 497, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:55,973] Trial 1 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 275, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 134, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:56,721] Trial 2 finished with value: 0.782608695652174 and parameters: {'n_estimators': 276, 'max_depth': 1, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 28, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:50:59,505] Trial 3 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 669, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 88, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:02,116] Trial 4 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 506, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 176, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:03,278] Trial 5 finished with value: 0.782608695652174 and parameters: {'n_estimators': 813, 'max_depth': 1, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 38, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:04,369] Trial 6 finished with value: 0.782608695652174 and parameters: {'n_estimators': 669, 'max_depth': 1, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 60, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:05,846] Trial 7 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 394, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 150, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:07,152] Trial 8 finished with value: 0.782608695652174 and parameters: {'n_estimators': 322, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 212, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:09,396] Trial 9 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 698, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 100, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:10,467] Trial 10 finished with value: 0.782608695652174 and parameters: {'n_estimators': 109, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 256, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:13,718] Trial 11 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 990, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 134, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:14,821] Trial 12 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 147, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 174, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:16,336] Trial 13 finished with value: 0.782608695652174 and parameters: {'n_estimators': 466, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 110, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:17,537] Trial 14 finished with value: 0.782608695652174 and parameters: {'n_estimators': 241, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 165, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:19,530] Trial 15 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 401, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 209, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:21,292] Trial 16 finished with value: 0.782608695652174 and parameters: {'n_estimators': 585, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 79, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:22,637] Trial 17 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 216, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 121, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:24,269] Trial 18 finished with value: 0.782608695652174 and parameters: {'n_estimators': 375, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 201, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:26,516] Trial 19 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 576, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 147, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:29,047] Trial 20 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 823, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 55, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:31,898] Trial 21 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 671, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 87, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:35,169] Trial 22 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 783, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 124, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:37,265] Trial 23 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 485, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 83, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:40,129] Trial 24 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 620, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 103, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:42,115] Trial 25 finished with value: 0.782608695652174 and parameters: {'n_estimators': 967, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 14, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:43,790] Trial 26 finished with value: 0.8 and parameters: {'n_estimators': 748, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 62, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:47,877] Trial 27 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 880, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_bins': 136, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:50,358] Trial 28 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 532, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 190, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:51,706] Trial 29 finished with value: 0.782608695652174 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 154, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:54,294] Trial 30 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 452, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 232, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:56,949] Trial 31 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 528, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 182, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:51:59,939] Trial 32 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 636, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 163, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:03,417] Trial 33 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 722, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_bins': 116, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:05,353] Trial 34 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 365, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 139, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:06,287] Trial 35 finished with value: 0.782608695652174 and parameters: {'n_estimators': 199, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 38, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:07,599] Trial 36 finished with value: 0.782608695652174 and parameters: {'n_estimators': 451, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 93, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:09,399] Trial 37 finished with value: 0.782608695652174 and parameters: {'n_estimators': 508, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 158, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:11,333] Trial 38 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 324, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 124, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:12,827] Trial 39 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 631, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 4, 'n_bins': 62, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:15,212] Trial 40 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 570, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 175, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:16,520] Trial 41 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 272, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 150, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:17,886] Trial 42 finished with value: 0.782608695652174 and parameters: {'n_estimators': 427, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 194, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:19,322] Trial 43 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 377, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 140, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:20,483] Trial 44 finished with value: 0.782608695652174 and parameters: {'n_estimators': 338, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 103, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:22,100] Trial 45 finished with value: 0.8 and parameters: {'n_estimators': 415, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 222, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:23,475] Trial 46 finished with value: 0.782608695652174 and parameters: {'n_estimators': 268, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 171, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:24,466] Trial 47 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 159, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 75, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:27,109] Trial 48 finished with value: 0.8333333333333334 and parameters: {'n_estimators': 592, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 112, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.8333333333333334.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:28,810] Trial 49 finished with value: 0.8 and parameters: {'n_estimators': 483, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 130, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.8333333333333334.
[I 2026-05-25 15:52:28,812] A new study created in memory with name: no-name-12c88082-07b1-4d98-8985-8f9b17a47184

Best trial for Social Services: F1 score= 0.8333
Best hyperparameters: {'n_estimators': 497, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 129, 'max_features': 'sqrt', 'criterion': 'gini'}
Technical/IT
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:31,786] Trial 0 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 907, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 224, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.6909090909090909.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:33,318] Trial 1 finished with value: 0.6785714285714286 and parameters: {'n_estimators': 533, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 146, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.6909090909090909.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:34,004] Trial 2 finished with value: 0.6415094339622641 and parameters: {'n_estimators': 125, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 30, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.6909090909090909.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:35,961] Trial 3 finished with value: 0.6415094339622641 and parameters: {'n_estimators': 899, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 155, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 0 with value: 0.6909090909090909.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:37,022] Trial 4 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 111, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 190, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 4 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:39,458] Trial 5 finished with value: 0.7368421052631579 and parameters: {'n_estimators': 979, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 128, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:43,980] Trial 6 finished with value: 0.7017543859649122 and parameters: {'n_estimators': 884, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 206, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:45,891] Trial 7 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 914, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 19, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:46,989] Trial 8 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 207, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 160, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:49,753] Trial 9 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 807, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 196, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:51,515] Trial 10 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 538, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 84, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:53,289] Trial 11 finished with value: 0.7017543859649122 and parameters: {'n_estimators': 355, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 100, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:55,260] Trial 12 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 640, 'max_depth': 1, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 247, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:56,908] Trial 13 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 371, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 105, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:52:59,629] Trial 14 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 676, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 177, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:01,061] Trial 15 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 373, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 66, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:04,161] Trial 16 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 732, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 137, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:05,389] Trial 17 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 253, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 119, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:07,050] Trial 18 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 435, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 58, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:10,420] Trial 19 finished with value: 0.7017543859649122 and parameters: {'n_estimators': 993, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 185, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:11,575] Trial 20 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 116, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 236, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:14,241] Trial 21 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 665, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 174, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:17,700] Trial 22 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 768, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 216, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:20,406] Trial 23 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 685, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 171, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:23,541] Trial 24 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 809, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 127, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:26,906] Trial 25 finished with value: 0.7368421052631579 and parameters: {'n_estimators': 998, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 191, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:29,737] Trial 26 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 997, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 196, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:32,047] Trial 27 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 579, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 254, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:34,827] Trial 28 finished with value: 0.7017543859649122 and parameters: {'n_estimators': 835, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 118, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:37,691] Trial 29 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 944, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 219, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:39,324] Trial 30 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 455, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 158, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:42,464] Trial 31 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 862, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 182, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:46,527] Trial 32 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 938, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'n_bins': 229, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:48,059] Trial 33 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 599, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 145, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:49,915] Trial 34 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 474, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 1, 'n_bins': 196, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:51,118] Trial 35 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 210, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'n_bins': 165, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:52,850] Trial 36 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 742, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 148, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:54,292] Trial 37 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 317, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 204, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:53:57,619] Trial 38 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 960, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3, 'n_bins': 181, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:01,363] Trial 39 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 903, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 213, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:03,558] Trial 40 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 496, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 135, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:04,524] Trial 41 finished with value: 0.7241379310344828 and parameters: {'n_estimators': 158, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 60, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:05,389] Trial 42 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 140, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 45, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:06,344] Trial 43 finished with value: 0.7241379310344828 and parameters: {'n_estimators': 191, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 26, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:07,246] Trial 44 finished with value: 0.7241379310344828 and parameters: {'n_estimators': 172, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 12, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:08,235] Trial 45 finished with value: 0.7017543859649122 and parameters: {'n_estimators': 191, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 10, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:09,457] Trial 46 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 269, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 5, 'n_bins': 33, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:10,377] Trial 47 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 158, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 28, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:11,559] Trial 48 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 261, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 79, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:12,442] Trial 49 finished with value: 0.7 and parameters: {'n_estimators': 179, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 1, 'n_bins': 45, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 5 with value: 0.7368421052631579.
[I 2026-05-25 15:54:12,444] A new study created in memory with name: no-name-3c6ab3b3-300c-4aa6-8ac6-f1e4ba26b060

Best trial for Technical/IT: F1 score= 0.7368
Best hyperparameters: {'n_estimators': 979, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 1, 'n_bins': 128, 'max_features': 'sqrt', 'criterion': 'gini'}
Urgent
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:14,550] Trial 0 finished with value: 0.3283582089552239 and parameters: {'n_estimators': 829, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 29, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.3283582089552239.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:16,504] Trial 1 finished with value: 0.33707865168539325 and parameters: {'n_estimators': 538, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 106, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.33707865168539325.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:17,752] Trial 2 finished with value: 0.34615384615384615 and parameters: {'n_estimators': 145, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 201, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.34615384615384615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:19,206] Trial 3 finished with value: 0.16 and parameters: {'n_estimators': 554, 'max_depth': 1, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 150, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.34615384615384615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:20,038] Trial 4 finished with value: 0.30337078651685395 and parameters: {'n_estimators': 117, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 68, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.34615384615384615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:22,242] Trial 5 finished with value: 0.3409090909090909 and parameters: {'n_estimators': 506, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 194, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.34615384615384615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:23,062] Trial 6 finished with value: 0.1360759493670886 and parameters: {'n_estimators': 223, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 6, 'n_bins': 11, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.34615384615384615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:25,489] Trial 7 finished with value: 0.3409090909090909 and parameters: {'n_estimators': 937, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 29, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.34615384615384615.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:26,538] Trial 8 finished with value: 0.3728813559322034 and parameters: {'n_estimators': 370, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4, 'n_bins': 26, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:27,976] Trial 9 finished with value: 0.3611111111111111 and parameters: {'n_estimators': 660, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_bins': 73, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:29,498] Trial 10 finished with value: 0.35714285714285715 and parameters: {'n_estimators': 360, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_bins': 146, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:30,992] Trial 11 finished with value: 0.2692307692307692 and parameters: {'n_estimators': 687, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 83, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:32,129] Trial 12 finished with value: 0.3333333333333333 and parameters: {'n_estimators': 355, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'n_bins': 60, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:34,707] Trial 13 finished with value: 0.36619718309859156 and parameters: {'n_estimators': 716, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 251, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:37,184] Trial 14 finished with value: 0.1702127659574468 and parameters: {'n_estimators': 776, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 246, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:38,805] Trial 15 finished with value: 0.37209302325581395 and parameters: {'n_estimators': 372, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 238, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:40,343] Trial 16 finished with value: 0.31746031746031744 and parameters: {'n_estimators': 372, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 180, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 8 with value: 0.3728813559322034.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:41,426] Trial 17 finished with value: 0.37777777777777777 and parameters: {'n_estimators': 258, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 116, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:42,574] Trial 18 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 246, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 115, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:43,774] Trial 19 finished with value: 0.3310344827586207 and parameters: {'n_estimators': 257, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 120, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:44,762] Trial 20 finished with value: 0.3333333333333333 and parameters: {'n_estimators': 290, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 50, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:46,357] Trial 21 finished with value: 0.3333333333333333 and parameters: {'n_estimators': 446, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 177, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:48,163] Trial 22 finished with value: 0.3486238532110092 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 213, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:49,555] Trial 23 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 454, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 5, 'n_bins': 92, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:50,698] Trial 24 finished with value: 0.32075471698113206 and parameters: {'n_estimators': 180, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 225, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:52,390] Trial 25 finished with value: 0.2857142857142857 and parameters: {'n_estimators': 598, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_bins': 158, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:53,778] Trial 26 finished with value: 0.3230769230769231 and parameters: {'n_estimators': 324, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 126, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:55,109] Trial 27 finished with value: 0.32967032967032966 and parameters: {'n_estimators': 446, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 100, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:55,981] Trial 28 finished with value: 0.34146341463414637 and parameters: {'n_estimators': 180, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 45, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:56,869] Trial 29 finished with value: 0.2972972972972973 and parameters: {'n_estimators': 296, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3, 'n_bins': 14, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:54:57,976] Trial 30 finished with value: 0.35294117647058826 and parameters: {'n_estimators': 422, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 3, 'n_bins': 34, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:00,779] Trial 31 finished with value: 0.37142857142857144 and parameters: {'n_estimators': 794, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 254, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:03,656] Trial 32 finished with value: 0.1360759493670886 and parameters: {'n_estimators': 977, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 233, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:06,267] Trial 33 finished with value: 0.3582089552238806 and parameters: {'n_estimators': 804, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 5, 'n_bins': 235, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:09,740] Trial 34 finished with value: 0.32432432432432434 and parameters: {'n_estimators': 876, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 4, 'n_bins': 255, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:11,714] Trial 35 finished with value: 0.3333333333333333 and parameters: {'n_estimators': 525, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 1, 'n_bins': 210, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:13,644] Trial 36 finished with value: 0.1360759493670886 and parameters: {'n_estimators': 611, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 182, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:14,625] Trial 37 finished with value: 0.2962962962962963 and parameters: {'n_estimators': 101, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 165, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:15,662] Trial 38 finished with value: 0.34285714285714286 and parameters: {'n_estimators': 187, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 137, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:18,930] Trial 39 finished with value: 0.3287671232876712 and parameters: {'n_estimators': 881, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 219, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:20,400] Trial 40 finished with value: 0.1360759493670886 and parameters: {'n_estimators': 494, 'max_depth': 1, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 202, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:22,925] Trial 41 finished with value: 0.3380281690140845 and parameters: {'n_estimators': 734, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 252, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 17 with value: 0.37777777777777777.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:25,508] Trial 42 finished with value: 0.4057971014492754 and parameters: {'n_estimators': 740, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 242, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:27,914] Trial 43 finished with value: 0.27450980392156865 and parameters: {'n_estimators': 837, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 193, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:30,129] Trial 44 finished with value: 0.34615384615384615 and parameters: {'n_estimators': 573, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_bins': 242, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:32,286] Trial 45 finished with value: 0.35294117647058826 and parameters: {'n_estimators': 626, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2, 'n_bins': 230, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:34,953] Trial 46 finished with value: 0.3619047619047619 and parameters: {'n_estimators': 758, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 238, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:36,405] Trial 47 finished with value: 0.35555555555555557 and parameters: {'n_estimators': 338, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 203, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:38,052] Trial 48 finished with value: 0.34234234234234234 and parameters: {'n_estimators': 654, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 76, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:39,432] Trial 49 finished with value: 0.36666666666666664 and parameters: {'n_estimators': 384, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 58, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 42 with value: 0.4057971014492754.
[I 2026-05-25 15:55:39,434] A new study created in memory with name: no-name-84b70863-5c17-4da5-b6e9-6b5c8f415ef4

Best trial for Urgent: F1 score= 0.4058
Best hyperparameters: {'n_estimators': 740, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2, 'n_bins': 242, 'max_features': 'log2', 'criterion': 'gini'}
Work/School
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:40,805] Trial 0 finished with value: 0.6153846153846154 and parameters: {'n_estimators': 610, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 105, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 0 with value: 0.6153846153846154.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:43,809] Trial 1 finished with value: 0.6976744186046512 and parameters: {'n_estimators': 945, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 161, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:45,467] Trial 2 finished with value: 0.5588235294117647 and parameters: {'n_estimators': 690, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_bins': 89, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:47,302] Trial 3 finished with value: 0.48 and parameters: {'n_estimators': 787, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'n_bins': 87, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:49,640] Trial 4 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 550, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 230, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:51,535] Trial 5 finished with value: 0.5161290322580645 and parameters: {'n_estimators': 719, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'n_bins': 61, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:53,763] Trial 6 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 491, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 249, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:54,908] Trial 7 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 888, 'max_depth': 1, 'min_samples_split': 2, 'min_samples_leaf': 6, 'n_bins': 42, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:55,991] Trial 8 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 333, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'n_bins': 15, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:55:57,200] Trial 9 finished with value: 0.6122448979591837 and parameters: {'n_estimators': 149, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 6, 'n_bins': 216, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:00,219] Trial 10 finished with value: 0.5555555555555556 and parameters: {'n_estimators': 1000, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 171, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:02,288] Trial 11 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 506, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 167, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:04,232] Trial 12 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 396, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_bins': 188, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:05,775] Trial 13 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 253, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5, 'n_bins': 238, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:08,187] Trial 14 finished with value: 0.5205479452054794 and parameters: {'n_estimators': 843, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 3, 'n_bins': 149, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:10,352] Trial 15 finished with value: 0.65 and parameters: {'n_estimators': 592, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_bins': 197, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 1 with value: 0.6976744186046512.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:13,452] Trial 16 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 979, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 136, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:17,074] Trial 17 finished with value: 0.6976744186046512 and parameters: {'n_estimators': 994, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 125, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:19,904] Trial 18 finished with value: 0.45714285714285713 and parameters: {'n_estimators': 905, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 126, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 16 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:22,171] Trial 19 finished with value: 0.5555555555555556 and parameters: {'n_estimators': 768, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 142, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:24,811] Trial 20 finished with value: 0.5277777777777778 and parameters: {'n_estimators': 947, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 4, 'n_bins': 163, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:28,251] Trial 21 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 984, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 119, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:31,322] Trial 22 finished with value: 0.6976744186046512 and parameters: {'n_estimators': 855, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 106, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 16 with value: 0.7142857142857143.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:34,310] Trial 23 finished with value: 0.7317073170731707 and parameters: {'n_estimators': 926, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 142, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:37,221] Trial 24 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 813, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 194, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:39,986] Trial 25 finished with value: 0.7317073170731707 and parameters: {'n_estimators': 811, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 206, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:42,405] Trial 26 finished with value: 0.5483870967741935 and parameters: {'n_estimators': 698, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'n_bins': 211, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:44,900] Trial 27 finished with value: 0.5757575757575758 and parameters: {'n_estimators': 904, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 1, 'n_bins': 179, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:46,803] Trial 28 finished with value: 0.5818181818181818 and parameters: {'n_estimators': 741, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 2, 'n_bins': 142, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:48,659] Trial 29 finished with value: 0.6153846153846154 and parameters: {'n_estimators': 628, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 87, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:50,904] Trial 30 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 643, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 107, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:53,881] Trial 31 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 802, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 203, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:57,136] Trial 32 finished with value: 0.6976744186046512 and parameters: {'n_estimators': 833, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 228, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:56:59,877] Trial 33 finished with value: 0.5277777777777778 and parameters: {'n_estimators': 929, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_bins': 186, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:02,901] Trial 34 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 861, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 155, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:05,788] Trial 35 finished with value: 0.6153846153846154 and parameters: {'n_estimators': 798, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 219, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:09,593] Trial 36 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 937, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'n_bins': 255, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:11,795] Trial 37 finished with value: 0.47368421052631576 and parameters: {'n_estimators': 663, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 199, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:13,762] Trial 38 finished with value: 0.631578947368421 and parameters: {'n_estimators': 739, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'n_bins': 71, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:16,029] Trial 39 finished with value: 0.5070422535211268 and parameters: {'n_estimators': 808, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_bins': 139, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:18,715] Trial 40 finished with value: 0.5277777777777778 and parameters: {'n_estimators': 873, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 181, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:22,087] Trial 41 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 952, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 205, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:25,057] Trial 42 finished with value: 0.6976744186046512 and parameters: {'n_estimators': 754, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 228, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:28,126] Trial 43 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 802, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'n_bins': 198, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:30,445] Trial 44 finished with value: 0.65 and parameters: {'n_estimators': 700, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 5, 'n_bins': 173, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:33,804] Trial 45 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 878, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 217, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:36,154] Trial 46 finished with value: 0.6976744186046512 and parameters: {'n_estimators': 563, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 157, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:39,413] Trial 47 finished with value: 0.5 and parameters: {'n_estimators': 964, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5, 'n_bins': 242, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:42,170] Trial 48 finished with value: 0.7 and parameters: {'n_estimators': 830, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_bins': 189, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[I 2026-05-25 15:57:45,258] Trial 49 finished with value: 0.6818181818181818 and parameters: {'n_estimators': 909, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'n_bins': 118, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 23 with value: 0.7317073170731707.

Best trial for Work/School: F1 score= 0.7317
Best hyperparameters: {'n_estimators': 926, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 3, 'n_bins': 142, 'max_features': 'sqrt', 'criterion': 'gini'}

In [51]:
import numpy as np
from sklearn.metrics import f1_score

In [52]:
models = {}
for i,label_name in enumerate(label_keep_original):


  model = RandomForestClassifier(**list_params[label_name])

  model.fit(x_train, y_train[:,i])
  models[label_name] = model

In [53]:
optimal_thresholds = {}
import numpy as np
for i, label_name in enumerate(label_keep_original):

    x_val_predic = models[label_name].predict_proba(x_val)[:, 1]
    best_f1 = 0
    best_thresh = 0.5 # Default
    for threshold_val in np.arange(0.05, 0.96, 0.05):
        preds = (x_val_predic > threshold_val).astype(int)
        current_f1 = f1_score(y_val[:, i], preds)
        if current_f1 > best_f1:
            best_f1 = current_f1
            best_thresh = threshold_val
    optimal_thresholds[label_name] = best_thresh
    print(f"Optimal threshold for {label_name}: {best_thresh:.2f} (F1: {best_f1:.4f})")

Optimal threshold for Cultural/Religion: 0.15 (F1: 0.9293)
Optimal threshold for Diet/Nutrition: 0.15 (F1: 0.8627)
Optimal threshold for Emergent: 0.10 (F1: 0.4706)
Optimal threshold for Exercise: 0.10 (F1: 0.8571)
Optimal threshold for Friends & Family: 0.10 (F1: 0.5763)
Optimal threshold for Grateful Patient: 0.10 (F1: 0.5769)
Optimal threshold for Health Education: 0.10 (F1: 0.7500)
Optimal threshold for Laboratory/Testing: 0.35 (F1: 0.8824)
Optimal threshold for Medications: 0.15 (F1: 0.9037)
Optimal threshold for No Symptoms: 0.50 (F1: 0.8030)
Optimal threshold for Non-urgent: 0.70 (F1: 0.9552)
Optimal threshold for Outpatient Logistics/Scheduling: 0.15 (F1: 0.6806)
Optimal threshold for Physical: 0.20 (F1: 0.7513)
Optimal threshold for Physical Environment/Climate: 0.10 (F1: 0.8421)
Optimal threshold for Service Complaint: 0.05 (F1: 0.3030)
Optimal threshold for Social Services: 0.15 (F1: 0.8333)
Optimal threshold for Technical/IT: 0.10 (F1: 0.7368)
Optimal threshold for Urgent: 0.10 (F1: 0.2951)
Optimal threshold for Work/School: 0.10 (F1: 0.7317)

In [54]:
import numpy as np
from sklearn.metrics import f1_score, classification_report

Y_pred_all = np.zeros(y_test.shape)

print("--- Individual Class F1 Scores ---")

for i, label_name in enumerate(label_keep_original):

    x_test_predic = models[label_name].predict_proba(x_test)[:, 1]

    y_test_final = (x_test_predic > optimal_thresholds[label_name]).astype(int)

    Y_pred_all[:, i] = y_test_final

    f1 = f1_score(y_test[:, i], y_test_final)
    count = dfCombined_filtered[label_name].sum()
    print(f"  {label_name:<40} F1: {f1:.4f}   Count: {count}")

print("\n" + "="*50 + "\n")

macro_f1    = f1_score(y_test, Y_pred_all, average='macro',    zero_division=0)
micro_f1    = f1_score(y_test, Y_pred_all, average='micro',    zero_division=0)
weighted_f1 = f1_score(y_test, Y_pred_all, average='weighted', zero_division=0)

print("--- Overall Test Set Metrics ---")
print(f"  Macro F1 Score:    {macro_f1:.4f}")
print(f"  Micro F1 Score:    {micro_f1:.4f}")
print(f"  Weighted F1 Score: {weighted_f1:.4f}")

print("--- Full Classification Report ---")
print(classification_report(
    y_test,
    Y_pred_all,
    target_names=label_keep_original,
    zero_division=0
))

--- Individual Class F1 Scores ---
  Cultural/Religion                        F1: 0.9159   Count: 343
  Diet/Nutrition                           F1: 0.8511   Count: 340
  Emergent                                 F1: 0.4286   Count: 140
  Exercise                                 F1: 0.7368   Count: 131
  Friends & Family                         F1: 0.6000   Count: 291
  Grateful Patient                         F1: 0.5593   Count: 291
  Health Education                         F1: 0.7312   Count: 322
  Laboratory/Testing                       F1: 0.9213   Count: 1078
  Medications                              F1: 0.8718   Count: 418
  No Symptoms                              F1: 0.8000   Count: 1658
  Non-urgent                               F1: 0.9526   Count: 3483
  Outpatient Logistics/Scheduling          F1: 0.7516   Count: 448
  Physical                                 F1: 0.7735   Count: 628
  Physical Environment/Climate             F1: 0.8649   Count: 203
  Service Complaint                        F1: 0.2162   Count: 116
  Social Services                          F1: 0.6400   Count: 100
  Technical/IT                             F1: 0.6071   Count: 238
  Urgent                                   F1: 0.3077   Count: 284
  Work/School                              F1: 0.6667   Count: 143

==================================================

--- Overall Test Set Metrics ---
  Macro F1 Score:    0.6945
  Micro F1 Score:    0.8227
  Weighted F1 Score: 0.8203
--- Full Classification Report ---
                                 precision    recall  f1-score   support

              Cultural/Religion       0.91      0.92      0.92        53
                 Diet/Nutrition       0.91      0.80      0.85        50
                       Emergent       0.41      0.45      0.43        20
                       Exercise       0.82      0.67      0.74        21
               Friends & Family       0.50      0.75      0.60        40
               Grateful Patient       0.46      0.70      0.56        47
               Health Education       0.72      0.74      0.73        46
             Laboratory/Testing       0.89      0.95      0.92       166
                    Medications       0.93      0.82      0.87        62
                    No Symptoms       0.72      0.90      0.80       255
                     Non-urgent       0.93      0.98      0.95       522
Outpatient Logistics/Scheduling       0.71      0.80      0.75        74
                       Physical       0.80      0.74      0.77        94
   Physical Environment/Climate       0.94      0.80      0.86        20
              Service Complaint       0.21      0.22      0.22        18
                Social Services       1.00      0.47      0.64        17
                   Technical/IT       0.94      0.45      0.61        38
                         Urgent       0.43      0.24      0.31        42
                    Work/School       0.81      0.57      0.67        23

                      micro avg       0.80      0.84      0.82      1608
                      macro avg       0.74      0.68      0.69      1608
                   weighted avg       0.81      0.84      0.82      1608
                    samples avg       0.83      0.87      0.83      1608

In [55]:

import numpy as np
from sklearn.metrics import f1_score

N_BOOTSTRAP = 1000
rng = np.random.default_rng(42)
n = len(y_test)

boot_scores = []
for _ in range(N_BOOTSTRAP):
    idx = rng.integers(0, n, size=n)
    score = f1_score(y_test[idx], Y_pred_all[idx], average='macro', zero_division=0)
    boot_scores.append(score)

boot_scores = np.array(boot_scores)
lo = np.percentile(boot_scores, 2.5)
hi = np.percentile(boot_scores, 97.5)
print(f"Macro F1: {macro_f1:.4f}  95% CI [{lo:.4f}, {hi:.4f}]")

Macro F1: 0.6945  95% CI [0.6623, 0.7201]

In [57]:

import numpy as np, os
os.makedirs("predictions", exist_ok=True)



np.savez_compressed(
    "predictions/RandomForest_preds.npz",
    y_true = y_test,
    y_pred = Y_pred_all,
)
print("Saved predictions/RandomForest_preds.npz")

Saved predictions/RandomForest_preds.npz

## Per-corpus + per-label evaluation (RandomForest)

Loads saved `RandomForest_preds.npz` and reports Macro F1 (+ 95% bootstrap CI) and per-label F1 separately for the pooled corpus and for the Rwanda and Canada halves. Source labels come from `Ensemble_test_predictions.json`, which carries the per-row `source_corpus` field for the same 584-doc test set.

In [ ]:
# PERCORPUSCELL_v1
# Per-corpus + per-label evaluation against the shared test split, with 1,000-resample bootstrap CIs.
import json, numpy as np
from sklearn.metrics import f1_score, classification_report

with open("predictions/Ensemble_test_predictions.json") as f:
    _ens = json.load(f)
_src    = np.array([r["source_corpus"] for r in _ens])
_labels = list(_ens[0]["true_labels"].keys())

_d = np.load("predictions/RandomForest_preds.npz")
_yt, _yp = _d["y_true"].astype(int), _d["y_pred"]
if _yp.dtype != int:
    _yp = (_yp > 0.5).astype(int) if _yp.max() <= 1 else _yp.astype(int)

for _corpus in ["Combined", "Rwanda", "Canada"]:
    _mask = np.ones(len(_src), bool) if _corpus == "Combined" else (_src == _corpus)
    _yti, _ypi = _yt[_mask], _yp[_mask]
    _macro = f1_score(_yti, _ypi, average="macro", zero_division=0)

    _rng = np.random.default_rng(42)
    _n = len(_yti)
    _boot = np.empty(1000)
    for _i in range(1000):
        _idx = _rng.integers(0, _n, _n)
        _boot[_i] = f1_score(_yti[_idx], _ypi[_idx], average="macro", zero_division=0)
    _lo, _hi = np.percentile(_boot, [2.5, 97.5])

    print(f"\n=== {{_corpus}} (n={{_n}})  Macro F1 {{_macro:.4f}}  95% CI [{{_lo:.4f}}, {{_hi:.4f}}] ===")
    print(classification_report(_yti, _ypi, target_names=_labels, zero_division=0))