In [ ]:
import pandas as pd
import pandas as pd
import random
import numpy as np
import torch
def set_seed(seed):
    """Set seed for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)

In [ ]:
dfCovid = pd.read_csv('data/dataRwaCovid.csv')

In [ ]:
dfDiabetes = pd.read_csv('data/dataIHADiabetes.csv')

In [ ]:
DiabetesTopics = [
    "Physical",
    "Psychological",
    "No Symptoms",
    "Prognosis",
    "Laboratory/Testing",
    "Imaging",
    "Clinical",
    "Testing/Monitoring Devices",
    "Health Data",
    "Diagnostic Methods - Other",
    "Medications",
    "Procedures",
    "Alternative",
    "Physical Therapy",
    "Counseling",
    "Adverse Events",
    "Therapeutic Devices",
    "Treatment(Rx) - Other",
    "Outpatient Logistics/Scheduling",
    "Hospitalizations",
    "Insurance/Billing",
    "Medical Records",
    "Referrals",
    "Transportation",
    "Primary (Pharmaceutical Prevention)",
    "Primary (Non-Pharmaceutical Prevention)",
    "Secondary (Pharmaceutical Prevention)",
    "Secondary (Non-Pharmaceutical Prevention)",
    "Diet/Nutrition",
    "Exercise",
    "Substance Use",
    "Entertainment",
    "Lifestyle - Other",
    "Housing",
    "Work/School",
    "Social Services",
    "Friends & Family",
    "Cultural/Religion",
    "Travel",
    "Physical Environment/Climate",
    "Financial",
    "Social - Other",
    "Technical/IT",
    "Safety Concerns",
    "Health Education",
    "Sexual & Reproductive Health",
    "Child & Family Health",
    "Problems Solved",
    "Grateful Patient",
    "Service Complaint",
    "Request to Stop",
    "Emergent",
    "Urgent",
    "Non-urgent",
    "Stigma Present",
    "Rapport",
    "Transition to Adult Clinic"
]

In [ ]:
CovidTopics = [
    "Physical",
    "Mental/Emotional",
    "No Symptoms",
    "Laboratory/Testing",
    "Imaging",
    "Clinical",
    "Diagnostic Methods - Other",
    "Medications",
    "Procedures",
    "Alternative",
    "Physical Therapy",
    "Counseling",
    "Treatment(Rx) - Other",
    "Outpatient Logistics/Scheduling",
    "Hospitalizations",
    "Pharmaceutical Prevention",
    "Non-Pharmaceutical Prevention",
    "Diet/Nutrition",
    "Exercise",
    "Substance Use",
    "Lifestyle - Other",
    "Housing",
    "Work/School",
    "Social Services",
    "Friends & Family",
    "Cultural/Religion",
    "Travel",
    "Physical Environment/Climate",
    "Financial",
    "Social - Other",
    "Technical/IT",
    "Safety concern",
    "Health Education",
    "Maternal & Child Health",
    "Problems Solved",
    "Grateful Patient",
    "Service Complaint",
    "Request to Stop",
    "Emergent",
    "Urgent",
    "Non-urgent",
    "Stigma Present",
    "wave",
    "batch"
]

In [ ]:
commonSubtopics = sorted(list(set(DiabetesTopics) & set(CovidTopics)))

In [ ]:
len(commonSubtopics)

37

In [ ]:
dfCovid[commonSubtopics].sum()

Alternative                          35
Clinical                              5
Counseling                            0
Cultural/Religion                   154
Diagnostic Methods - Other            5
Diet/Nutrition                      102
Emergent                            138
Exercise                             25
Financial                            53
Friends & Family                    138
Grateful Patient                    244
Health Education                     45
Hospitalizations                     15
Housing                              32
Imaging                               7
Laboratory/Testing                 1018
Lifestyle - Other                    52
Medications                         152
No Symptoms                        1657
Non-urgent                         2383
Outpatient Logistics/Scheduling     268
Physical                            406
Physical Environment/Climate          6
Physical Therapy                      1
Problems Solved                      45
Procedures                            0
Request to Stop                      50
Service Complaint                   106
Social - Other                        7
Social Services                      30
Stigma Present                       15
Substance Use                         0
Technical/IT                        185
Travel                               12
Treatment(Rx) - Other                 0
Urgent                              270
Work/School                          46
dtype: int64

In [ ]:
diabetesColumns = commonSubtopics[:]
diabetesColumns.insert(0,"conversation")
dfDiabetesNew = dfDiabetes[diabetesColumns]

In [ ]:
covidColumns = commonSubtopics[:]
covidColumns.insert(0,"conversation(english_only)")
dfCovidNew = dfCovid[covidColumns]

In [ ]:
dfCovidNew = dfCovidNew.rename(columns={"conversation(english_only)":"conversation"})

In [ ]:
dfCombined = pd.concat([dfCovidNew, dfDiabetesNew])

In [ ]:
n = 100
label_sum = dfCombined[commonSubtopics].sum()
label_keep = label_sum[label_sum >= n].index.tolist()
label_keep_original = label_keep[:]
label_keep.insert(0,"conversation")

dfCombined_filtered = dfCombined[label_keep]
dfCombined_filtered.shape

(3907, 20)

In [ ]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].str.lower()

/tmp/ipykernel_3595/1116881674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].str.lower()

In [ ]:
import nltk
import re
import string

In [ ]:
!pip install contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 15.3 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 11.5 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.1 textsearch-0.0.24

In [ ]:
import contractions

In [ ]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([contractions.fix(word) for word in x.split()]))

/tmp/ipykernel_3595/2646981620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([contractions.fix(word) for word in x.split()]))

In [ ]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'\d+','',x))

/tmp/ipykernel_3595/3892837535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'\d+','',x))

In [ ]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'[.]',' ',x))

/tmp/ipykernel_3595/1879545715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'[.]',' ',x))

In [ ]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: "".join([char for char in x if char not in string.punctuation]))

/tmp/ipykernel_3595/2885321218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: "".join([char for char in x if char not in string.punctuation]))

In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
sw = stopwords.words('english')

In [ ]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([word for word in x.split() if word not in sw]))

/tmp/ipykernel_3595/280526503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([word for word in x.split() if word not in sw]))

In [ ]:
import nltk
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("averaged_perceptron_tagger_eng")
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

from nltk.corpus import wordnet

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def lemmatize_with_pos(text):
    tokens = nltk.word_tokenize(text)
    tagged_tokens = nltk.pos_tag(tokens)
    return " ".join([lemmatizer.lemmatize(token, get_wordnet_pos(pos)) for token, pos in tagged_tokens])

# Apply it (after stopword removal and before TF-IDF)
# dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lemmatize_with_pos)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

In [ ]:
# dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([lemmatizer.lemmatize(word) for word in x.split()]))
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lemmatize_with_pos)

/tmp/ipykernel_3595/1177021903.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lemmatize_with_pos)

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

dfCombined_filtered['conversation_tokens'] = dfCombined_filtered['conversation'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/tmp/ipykernel_3595/4092647881.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered['conversation_tokens'] = dfCombined_filtered['conversation'].apply(word_tokenize)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [ ]:
# tf = TfidfVectorizer(max_features=7000,min_df = 3,max_df = 0.8, ngram_range=(1,2))
# x = tf.fit_transform(dfCombined_filtered["conversation"])
tf = TfidfVectorizer(max_features=7000, min_df=3, max_df=0.8, ngram_range=(1,2))
x = dfCombined_filtered["conversation"]  # keep as raw text for now

In [ ]:
x

0       hello today symptom coronavirus p well thank h...
1       welcome rwanda ministry health platform daily ...
2       welcome rwanda ministry health platform daily ...
3       hello today symptom coronavirus p hello get sy...
4       welcome rwanda ministry health platform daily ...
                              ...
1111    remembermy worth dictate number youðÿœ· p than...
1112    sugar consistently trend check ketone urine bl...
1113    hour weekendsholidays speak pediatrician call ...
1114    feel free text questionsconcerns successes u e...
1115    life give lemon bite make funny face ðÿ‹ inte...
Name: conversation, Length: 3907, dtype: object

In [ ]:
!pip install scikit-multilearn

Collecting scikit-multilearn
  Downloading scikit_multilearn-0.2.0-py3-none-any.whl.metadata (6.0 kB)
Downloading scikit_multilearn-0.2.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 6.5 MB/s eta 0:00:00
Installing collected packages: scikit-multilearn
Successfully installed scikit-multilearn-0.2.0

In [ ]:
y = dfCombined_filtered[label_keep_original].to_numpy()

In [ ]:
from skmultilearn.model_selection import iterative_train_test_split
import numpy as np

In [ ]:
np.random.seed(42)

In [ ]:

import numpy as np

split = np.load("data/shared_split_indices.npz")
train_idx = split["train_idx"]
val_idx   = split["val_idx"]
test_idx  = split["test_idx"]

x_raw = dfCombined_filtered["conversation"].to_numpy()
y     = dfCombined_filtered[label_keep_original].to_numpy()

x_train_raw = x_raw[train_idx]
x_val_raw   = x_raw[val_idx]
x_test_raw  = x_raw[test_idx]

y_train = y[train_idx]
y_val   = y[val_idx]
y_test  = y[test_idx]

df_aug_train = pd.read_csv("data/backtranslated_train.csv")

import pandas as pd
import numpy as np
import re
import string
import contractions
import nltk
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

df_aug_train = pd.read_csv('data/backtranslated_train.csv')

y_train = df_aug_train[label_keep_original].to_numpy()

sw = stopwords.words('english')
lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'): return wordnet.ADJ
    elif treebank_tag.startswith('V'): return wordnet.VERB
    elif treebank_tag.startswith('N'): return wordnet.NOUN
    elif treebank_tag.startswith('R'): return wordnet.ADV
    else: return wordnet.NOUN

def lemmatize_with_pos(text):
    tokens = word_tokenize(text)
    tagged = nltk.pos_tag(tokens)
    return " ".join([lemmatizer.lemmatize(tok, get_wordnet_pos(pos)) for tok, pos in tagged])

def preprocess(text):
    text = text.lower()
    text = " ".join([contractions.fix(word) for word in text.split()])
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[.]', ' ', text)
    text = "".join([c for c in text if c not in string.punctuation])
    text = " ".join([w for w in text.split() if w not in sw])
    text = lemmatize_with_pos(text)
    return text

df_aug_train['conversation'] = df_aug_train['conversation'].apply(preprocess)
x_train = df_aug_train["conversation"].to_numpy()

y_train = df_aug_train[label_keep_original].to_numpy()

x_train = tf.fit_transform(pd.Series(x_train.flatten()))
x_val   = tf.transform(pd.Series(x_val_raw.flatten()))
x_test  = tf.transform(pd.Series(x_test_raw.flatten()))

In [ ]:
x_train.shape

(5468, 7000)

In [ ]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.multioutput import MultiOutputClassifier

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 15.4 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [ ]:
import optuna

In [ ]:
import numpy as np
from sklearn.metrics import f1_score

In [ ]:
models = {}
list_params = {}
for i,label_name in enumerate(label_keep_original):

    y_train_curr = y_train[:,i]

    def objective(trial):

      params = {
        'C': trial.suggest_float('C',.01,50),
    'gamma': trial.suggest_float('gamma', 0.01,50),
    'kernel': trial.suggest_categorical('kernel',['rbf','linear','poly','sigmoid']),
      }

      model = SVC(**params,class_weight='balanced',random_state=42, probability=True, cache_size=2000)
      model.fit(x_train,y_train_curr)


      x_val_predic = model.predict_proba(x_val)[:,1]

      best_f1 = 0
      best_thresh = 0.5
      for threshold_val in np.arange(0.05, 0.96, 0.05):
          preds = (x_val_predic > threshold_val).astype(int)
          current_f1 = f1_score(y_val[:, i], preds)
          if current_f1 > best_f1:
              best_f1 = current_f1
              best_thresh = threshold_val
      return best_f1
    study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
    study.optimize(objective, n_trials=50, n_jobs=-1)
    print(f"Best trial for {label_name}: F1 score= {study.best_value:.4f}")
    print(f"Best hyperparameters: {study.best_params}")
    list_params[label_name] = study.best_params

[I 2026-05-20 16:42:27,445] A new study created in memory with name: no-name-62ff6757-2b7c-49c0-9898-c6a2bc752b2d
[I 2026-05-20 16:43:05,912] Trial 0 finished with value: 0.9484536082474226 and parameters: {'C': 17.566356148415796, 'gamma': 0.3846720812006211, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:43:17,601] Trial 1 finished with value: 0.4861878453038674 and parameters: {'C': 3.807427136875315, 'gamma': 3.396322798230847, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:43:25,497] Trial 2 finished with value: 0.9387755102040817 and parameters: {'C': 46.00250747794792, 'gamma': 23.477840579880507, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:43:45,906] Trial 4 finished with value: 0.9278350515463918 and parameters: {'C': 5.602598723708729, 'gamma': 16.23626630874636, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:44:17,441] Trial 3 finished with value: 0.2843601895734597 and parameters: {'C': 21.659859299038065, 'gamma': 45.35481587468235, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:44:47,946] Trial 5 finished with value: 0.3033175355450237 and parameters: {'C': 10.527332367635506, 'gamma': 25.8251528999592, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:45:49,930] Trial 6 finished with value: 0.8686868686868687 and parameters: {'C': 47.94208442751416, 'gamma': 1.1346596297507265, 'kernel': 'poly'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:46:11,754] Trial 8 finished with value: 0.9484536082474226 and parameters: {'C': 31.984925230010624, 'gamma': 33.49166473231902, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:46:17,630] Trial 7 finished with value: 0.6829268292682927 and parameters: {'C': 3.4443017048622497, 'gamma': 36.78685762092023, 'kernel': 'poly'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:46:30,340] Trial 9 finished with value: 0.9387755102040817 and parameters: {'C': 44.43146591402942, 'gamma': 38.978077679454714, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:48:03,497] Trial 10 finished with value: 0.1724137931034483 and parameters: {'C': 33.83650228460989, 'gamma': 40.36919804780098, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:48:14,555] Trial 11 finished with value: 0.3835616438356164 and parameters: {'C': 18.97553599286446, 'gamma': 11.183413302197597, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:48:22,075] Trial 12 finished with value: 0.9484536082474226 and parameters: {'C': 26.226561235446955, 'gamma': 13.557737549842235, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:48:32,880] Trial 13 finished with value: 0.9484536082474226 and parameters: {'C': 31.369405406299364, 'gamma': 28.636040911049935, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:48:41,790] Trial 14 finished with value: 0.9387755102040817 and parameters: {'C': 33.99964849417195, 'gamma': 26.22285103189876, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:48:53,059] Trial 15 finished with value: 0.9484536082474226 and parameters: {'C': 15.443730078761384, 'gamma': 32.94181874583058, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:49:00,372] Trial 16 finished with value: 0.9484536082474226 and parameters: {'C': 16.894971649547717, 'gamma': 49.66856061884966, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:49:11,883] Trial 17 finished with value: 0.9387755102040817 and parameters: {'C': 40.36728083852141, 'gamma': 19.940743926070635, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:50:29,878] Trial 18 finished with value: 0.6829268292682927 and parameters: {'C': 39.740583413806654, 'gamma': 19.162181856664915, 'kernel': 'poly'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:50:56,312] Trial 19 finished with value: 0.4810126582278481 and parameters: {'C': 25.66617370128208, 'gamma': 9.550987108960646, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:51:14,970] Trial 21 finished with value: 0.9484536082474226 and parameters: {'C': 12.207351724612877, 'gamma': 32.01319326534347, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:51:34,083] Trial 22 finished with value: 0.9484536082474226 and parameters: {'C': 24.142110381709365, 'gamma': 7.5505524086133144, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:51:54,043] Trial 23 finished with value: 0.9484536082474226 and parameters: {'C': 28.56916127796092, 'gamma': 14.168327109117442, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:52:14,775] Trial 24 finished with value: 0.9484536082474226 and parameters: {'C': 26.415476865323377, 'gamma': 2.711038949476266, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:52:15,935] Trial 20 finished with value: 0.5411764705882353 and parameters: {'C': 26.711049043884724, 'gamma': 7.972798488918748, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:52:34,727] Trial 25 finished with value: 0.9387755102040817 and parameters: {'C': 38.152221929696864, 'gamma': 6.266693216460813, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:52:35,955] Trial 26 finished with value: 0.9387755102040817 and parameters: {'C': 37.639545159549215, 'gamma': 0.04943578818339489, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:52:53,371] Trial 27 finished with value: 0.9484536082474226 and parameters: {'C': 21.714147294503903, 'gamma': 12.876911955687323, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:53:28,840] Trial 28 finished with value: 0.3132530120481928 and parameters: {'C': 30.271313154352065, 'gamma': 14.015164541517168, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:54:26,544] Trial 29 finished with value: 0.6829268292682927 and parameters: {'C': 31.720582810456882, 'gamma': 21.162716804412206, 'kernel': 'poly'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:54:54,181] Trial 30 finished with value: 0.6829268292682927 and parameters: {'C': 9.559736984239194, 'gamma': 4.116298741809924, 'kernel': 'poly'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:54:57,916] Trial 31 finished with value: 0.4626865671641791 and parameters: {'C': 9.08914562942795, 'gamma': 4.937493370736366, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:55:12,836] Trial 32 finished with value: 0.9387755102040817 and parameters: {'C': 34.44100468018505, 'gamma': 31.18891416564336, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:55:17,504] Trial 33 finished with value: 0.9484536082474226 and parameters: {'C': 33.699957054431096, 'gamma': 31.809552725522156, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:55:33,536] Trial 34 finished with value: 0.9484536082474226 and parameters: {'C': 21.929069915051837, 'gamma': 29.183242111267965, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:55:37,201] Trial 35 finished with value: 0.9484536082474226 and parameters: {'C': 21.60476905499895, 'gamma': 28.927791312757112, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:55:52,208] Trial 36 finished with value: 0.9484536082474226 and parameters: {'C': 29.90583306457859, 'gamma': 23.717597371494374, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:56:38,380] Trial 37 finished with value: 0.3033175355450237 and parameters: {'C': 0.7653133016046105, 'gamma': 23.803524584204858, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:56:55,257] Trial 38 finished with value: 0.28054298642533937 and parameters: {'C': 13.628724184160905, 'gamma': 35.745952074565544, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:56:58,046] Trial 39 finished with value: 0.9387755102040817 and parameters: {'C': 43.60337094529627, 'gamma': 17.27403753970805, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:57:14,008] Trial 40 finished with value: 0.9387755102040817 and parameters: {'C': 44.725006663640336, 'gamma': 16.666125993339364, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:57:16,872] Trial 41 finished with value: 0.9484536082474226 and parameters: {'C': 23.209809946423935, 'gamma': 41.72035022446614, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:57:32,933] Trial 42 finished with value: 0.9484536082474226 and parameters: {'C': 16.354913291290146, 'gamma': 35.535972634707214, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:57:37,238] Trial 43 finished with value: 0.9484536082474226 and parameters: {'C': 18.0189222765809, 'gamma': 35.06941820809828, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:57:53,404] Trial 44 finished with value: 0.9484536082474226 and parameters: {'C': 19.102711582469798, 'gamma': 27.82219276119736, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:57:56,403] Trial 45 finished with value: 0.9484536082474226 and parameters: {'C': 15.150186186171684, 'gamma': 27.707188619360004, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:59:37,502] Trial 46 finished with value: 0.1724137931034483 and parameters: {'C': 28.04585295693521, 'gamma': 43.72118073173607, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:59:41,982] Trial 47 finished with value: 0.1724137931034483 and parameters: {'C': 27.85840392578462, 'gamma': 33.36822718568284, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 16:59:58,996] Trial 48 finished with value: 0.9387755102040817 and parameters: {'C': 6.937422345606869, 'gamma': 32.66999948794317, 'kernel': 'linear'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 17:00:40,924] Trial 49 finished with value: 0.6829268292682927 and parameters: {'C': 7.981652780193187, 'gamma': 37.85756467100019, 'kernel': 'poly'}. Best is trial 0 with value: 0.9484536082474226.
[I 2026-05-20 17:00:40,927] A new study created in memory with name: no-name-38e23101-c8c0-49bf-a1f4-1872842ceba4

Best trial for Cultural/Religion: F1 score= 0.9485
Best hyperparameters: {'C': 17.566356148415796, 'gamma': 0.3846720812006211, 'kernel': 'linear'}

[I 2026-05-20 17:02:05,564] Trial 0 finished with value: 0.74 and parameters: {'C': 15.85700511759008, 'gamma': 0.9268234020862953, 'kernel': 'poly'}. Best is trial 0 with value: 0.74.
[I 2026-05-20 17:02:27,150] Trial 1 finished with value: 0.1622464898595944 and parameters: {'C': 19.291983859093502, 'gamma': 29.335800021647735, 'kernel': 'rbf'}. Best is trial 0 with value: 0.74.
[I 2026-05-20 17:02:46,725] Trial 3 finished with value: 0.7735849056603774 and parameters: {'C': 34.368397774525725, 'gamma': 7.05204770952567, 'kernel': 'linear'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:02:59,207] Trial 2 finished with value: 0.38461538461538464 and parameters: {'C': 49.81187874226788, 'gamma': 17.069079746591083, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:03:50,497] Trial 5 finished with value: 0.391304347826087 and parameters: {'C': 44.06184137239519, 'gamma': 11.715492506492122, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:04:34,179] Trial 4 finished with value: 0.1622464898595944 and parameters: {'C': 28.174105512629446, 'gamma': 23.987819167857634, 'kernel': 'rbf'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:04:49,990] Trial 6 finished with value: 0.34951456310679613 and parameters: {'C': 7.6926941950132015, 'gamma': 48.05191061248201, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:06:23,901] Trial 7 finished with value: 0.1622464898595944 and parameters: {'C': 37.27726886625549, 'gamma': 45.17296665835718, 'kernel': 'rbf'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:06:36,808] Trial 8 finished with value: 0.1935483870967742 and parameters: {'C': 15.504625614415028, 'gamma': 20.38867996007264, 'kernel': 'rbf'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:07:22,408] Trial 9 finished with value: 0.3584905660377358 and parameters: {'C': 12.188234984224282, 'gamma': 25.624915394829028, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.7735849056603774.
[I 2026-05-20 17:07:43,866] Trial 11 finished with value: 0.7850467289719626 and parameters: {'C': 30.67606091479942, 'gamma': 0.12619048178470482, 'kernel': 'linear'}. Best is trial 11 with value: 0.7850467289719626.
[I 2026-05-20 17:08:03,016] Trial 10 finished with value: 0.6363636363636364 and parameters: {'C': 8.570424347107023, 'gamma': 16.700987448775948, 'kernel': 'poly'}. Best is trial 11 with value: 0.7850467289719626.
[I 2026-05-20 17:08:04,040] Trial 12 finished with value: 0.7850467289719626 and parameters: {'C': 30.903537806876532, 'gamma': 0.4985744687478473, 'kernel': 'linear'}. Best is trial 11 with value: 0.7850467289719626.
[I 2026-05-20 17:08:24,639] Trial 13 finished with value: 0.7850467289719626 and parameters: {'C': 30.38006604020362, 'gamma': 1.4885627852592913, 'kernel': 'linear'}. Best is trial 11 with value: 0.7850467289719626.
[I 2026-05-20 17:08:26,305] Trial 14 finished with value: 0.8 and parameters: {'C': 26.889246729734833, 'gamma': 1.7866025461979536, 'kernel': 'linear'}. Best is trial 14 with value: 0.8.
[I 2026-05-20 17:08:45,357] Trial 15 finished with value: 0.8 and parameters: {'C': 22.9725517930668, 'gamma': 33.1702017996446, 'kernel': 'linear'}. Best is trial 14 with value: 0.8.
[I 2026-05-20 17:08:47,763] Trial 16 finished with value: 0.8 and parameters: {'C': 23.1441042037979, 'gamma': 33.36756044388889, 'kernel': 'linear'}. Best is trial 14 with value: 0.8.
[I 2026-05-20 17:09:07,918] Trial 17 finished with value: 0.8 and parameters: {'C': 24.972335840720774, 'gamma': 36.271545413502224, 'kernel': 'linear'}. Best is trial 14 with value: 0.8.
[I 2026-05-20 17:09:09,493] Trial 18 finished with value: 0.8 and parameters: {'C': 23.334690712525322, 'gamma': 36.988566842950874, 'kernel': 'linear'}. Best is trial 14 with value: 0.8.
[I 2026-05-20 17:09:33,978] Trial 20 finished with value: 0.8627450980392157 and parameters: {'C': 3.9629563755723396, 'gamma': 44.19013269181864, 'kernel': 'linear'}. Best is trial 20 with value: 0.8627450980392157.
[I 2026-05-20 17:09:50,819] Trial 19 finished with value: 0.8686868686868687 and parameters: {'C': 0.3180140385241792, 'gamma': 41.06097563231474, 'kernel': 'linear'}. Best is trial 19 with value: 0.8686868686868687.
[I 2026-05-20 17:10:29,528] Trial 22 finished with value: 0.8712871287128713 and parameters: {'C': 0.4500017971387565, 'gamma': 42.04260046691817, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:10:56,957] Trial 21 finished with value: 0.6363636363636364 and parameters: {'C': 3.247524145059237, 'gamma': 40.77801306151326, 'kernel': 'poly'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:11:15,671] Trial 23 finished with value: 0.8686868686868687 and parameters: {'C': 0.2728986669142852, 'gamma': 43.25506680699544, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:12:15,185] Trial 24 finished with value: 0.735632183908046 and parameters: {'C': 0.04185514968847631, 'gamma': 42.795155737564876, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:12:19,252] Trial 25 finished with value: 0.8037383177570093 and parameters: {'C': 0.10740472330374834, 'gamma': 49.89608599223171, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:12:41,213] Trial 27 finished with value: 0.8380952380952381 and parameters: {'C': 7.66390975650507, 'gamma': 39.705953948289704, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:12:59,050] Trial 26 finished with value: 0.8686868686868687 and parameters: {'C': 0.30869986811739725, 'gamma': 49.591667688136866, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:13:04,148] Trial 28 finished with value: 0.8627450980392157 and parameters: {'C': 3.9322316182676396, 'gamma': 47.05881812238478, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:14:25,283] Trial 29 finished with value: 0.6363636363636364 and parameters: {'C': 5.055444862044056, 'gamma': 38.10034704315387, 'kernel': 'poly'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:14:27,720] Trial 30 finished with value: 0.6363636363636364 and parameters: {'C': 13.29425027491869, 'gamma': 38.77731181698747, 'kernel': 'poly'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:14:49,649] Trial 32 finished with value: 0.8247422680412371 and parameters: {'C': 9.90652454881017, 'gamma': 43.12982467919716, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:15:49,464] Trial 33 finished with value: 0.8043478260869565 and parameters: {'C': 0.12116324961942423, 'gamma': 49.49630718359978, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:15:52,909] Trial 31 finished with value: 0.6363636363636364 and parameters: {'C': 12.106928265716626, 'gamma': 32.69455629798847, 'kernel': 'poly'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:16:11,259] Trial 34 finished with value: 0.7961165048543689 and parameters: {'C': 19.3238281891893, 'gamma': 45.433620916624186, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:16:13,679] Trial 35 finished with value: 0.7961165048543689 and parameters: {'C': 17.69756704663613, 'gamma': 45.646226624429204, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:17:55,645] Trial 36 finished with value: 0.1622464898595944 and parameters: {'C': 3.2602032244984205, 'gamma': 30.02059883485862, 'kernel': 'rbf'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:17:59,502] Trial 37 finished with value: 0.1622464898595944 and parameters: {'C': 6.073731744132775, 'gamma': 29.15111302112727, 'kernel': 'rbf'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:18:53,015] Trial 38 finished with value: 0.3917525773195876 and parameters: {'C': 5.479346626163773, 'gamma': 41.658064705914974, 'kernel': 'sigmoid'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:18:56,931] Trial 39 finished with value: 0.3917525773195876 and parameters: {'C': 2.619659010505145, 'gamma': 42.26438400912306, 'kernel': 'sigmoid'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:19:17,696] Trial 41 finished with value: 0.7735849056603774 and parameters: {'C': 42.74904909363715, 'gamma': 35.00670185621946, 'kernel': 'linear'}. Best is trial 22 with value: 0.8712871287128713.
[I 2026-05-20 17:19:18,117] Trial 40 finished with value: 0.8932038834951457 and parameters: {'C': 2.3398040464251744, 'gamma': 47.61029763062439, 'kernel': 'linear'}. Best is trial 40 with value: 0.8932038834951457.
[I 2026-05-20 17:19:43,622] Trial 42 finished with value: 0.8952380952380953 and parameters: {'C': 1.984929951104605, 'gamma': 43.99426398408982, 'kernel': 'linear'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:19:44,722] Trial 43 finished with value: 0.8775510204081632 and parameters: {'C': 1.7983044187411572, 'gamma': 46.99880751721324, 'kernel': 'linear'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:20:05,356] Trial 44 finished with value: 0.8247422680412371 and parameters: {'C': 9.612927771077732, 'gamma': 47.10011064539066, 'kernel': 'linear'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:20:07,378] Trial 45 finished with value: 0.82 and parameters: {'C': 10.207768588838743, 'gamma': 46.44329974628019, 'kernel': 'linear'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:20:27,762] Trial 46 finished with value: 0.8411214953271028 and parameters: {'C': 6.951732471088198, 'gamma': 46.864088164779815, 'kernel': 'linear'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:21:50,425] Trial 47 finished with value: 0.1622464898595944 and parameters: {'C': 7.40661249875448, 'gamma': 39.73287936611346, 'kernel': 'rbf'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:22:12,362] Trial 48 finished with value: 0.1622464898595944 and parameters: {'C': 2.321367332041686, 'gamma': 40.00882599654243, 'kernel': 'rbf'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:22:35,346] Trial 49 finished with value: 0.35714285714285715 and parameters: {'C': 2.0170281369334955, 'gamma': 24.57015013412021, 'kernel': 'sigmoid'}. Best is trial 42 with value: 0.8952380952380953.
[I 2026-05-20 17:22:35,349] A new study created in memory with name: no-name-57a6a97d-49a9-459a-b5fb-bc5e0c5e13a0

Best trial for Diet/Nutrition: F1 score= 0.8952
Best hyperparameters: {'C': 1.984929951104605, 'gamma': 43.99426398408982, 'kernel': 'linear'}

[I 2026-05-20 17:23:20,839] Trial 1 finished with value: 0.4117647058823529 and parameters: {'C': 41.84327582989118, 'gamma': 27.356135831334544, 'kernel': 'poly'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:24:18,808] Trial 0 finished with value: 0.0 and parameters: {'C': 33.05828379931047, 'gamma': 29.29217438558429, 'kernel': 'rbf'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:25:04,853] Trial 2 finished with value: 0.0 and parameters: {'C': 14.120688526451673, 'gamma': 12.133209410758475, 'kernel': 'rbf'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:26:02,838] Trial 3 finished with value: 0.0 and parameters: {'C': 8.707294227031786, 'gamma': 37.732609351151936, 'kernel': 'rbf'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:26:05,763] Trial 4 finished with value: 0.0718562874251497 and parameters: {'C': 34.050644949561644, 'gamma': 21.30952285490974, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:26:51,886] Trial 6 finished with value: 0.4117647058823529 and parameters: {'C': 38.54778613303763, 'gamma': 6.203668422281221, 'kernel': 'poly'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:27:47,973] Trial 5 finished with value: 0.0 and parameters: {'C': 19.13241740027974, 'gamma': 24.141136549176327, 'kernel': 'rbf'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:28:37,479] Trial 7 finished with value: 0.0 and parameters: {'C': 4.595114094720507, 'gamma': 18.381837618785877, 'kernel': 'rbf'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:28:53,244] Trial 9 finished with value: 0.3684210526315789 and parameters: {'C': 23.88109219507468, 'gamma': 10.390861024915926, 'kernel': 'linear'}. Best is trial 1 with value: 0.4117647058823529.
[I 2026-05-20 17:29:15,270] Trial 8 finished with value: 0.42105263157894735 and parameters: {'C': 1.342185793621951, 'gamma': 0.9181931638773473, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:29:39,780] Trial 10 finished with value: 0.4117647058823529 and parameters: {'C': 9.478157395187006, 'gamma': 4.851824670060802, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:30:00,270] Trial 11 finished with value: 0.4117647058823529 and parameters: {'C': 3.4399722479562453, 'gamma': 47.61329180368831, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:30:24,989] Trial 12 finished with value: 0.4117647058823529 and parameters: {'C': 48.46570548864787, 'gamma': 47.2060085680677, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:30:46,709] Trial 13 finished with value: 0.4117647058823529 and parameters: {'C': 49.39829481927387, 'gamma': 32.27391652947857, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:31:02,965] Trial 15 finished with value: 0.3888888888888889 and parameters: {'C': 41.0656385335771, 'gamma': 0.12156118307126262, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:31:11,544] Trial 14 finished with value: 0.4117647058823529 and parameters: {'C': 46.024732060426366, 'gamma': 33.26554520288867, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:31:18,693] Trial 16 finished with value: 0.3684210526315789 and parameters: {'C': 27.848846715888886, 'gamma': 35.83939887729314, 'kernel': 'linear'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:31:27,210] Trial 17 finished with value: 0.3684210526315789 and parameters: {'C': 26.68592240198896, 'gamma': 16.284470656257916, 'kernel': 'linear'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:32:05,277] Trial 18 finished with value: 0.4117647058823529 and parameters: {'C': 19.933150792051887, 'gamma': 16.174986314933136, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:32:12,557] Trial 19 finished with value: 0.4117647058823529 and parameters: {'C': 17.696168595389125, 'gamma': 40.233831932828835, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:32:50,315] Trial 20 finished with value: 0.4117647058823529 and parameters: {'C': 41.332021371988716, 'gamma': 27.021789910910968, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:33:19,099] Trial 21 finished with value: 0.06666666666666667 and parameters: {'C': 41.98961506617962, 'gamma': 29.46190492068128, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:33:36,349] Trial 22 finished with value: 0.4117647058823529 and parameters: {'C': 36.94470344359788, 'gamma': 1.281774975853593, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:34:06,319] Trial 23 finished with value: 0.4117647058823529 and parameters: {'C': 35.1277787042047, 'gamma': 1.493139293746198, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:34:22,532] Trial 24 finished with value: 0.4117647058823529 and parameters: {'C': 30.43370826954269, 'gamma': 7.444463483619007, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:34:51,876] Trial 25 finished with value: 0.4117647058823529 and parameters: {'C': 30.31367313177085, 'gamma': 10.524356713330214, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:35:07,429] Trial 26 finished with value: 0.4117647058823529 and parameters: {'C': 0.1279689489193354, 'gamma': 7.132689713348144, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:35:39,657] Trial 27 finished with value: 0.4117647058823529 and parameters: {'C': 43.850025356948144, 'gamma': 5.657333422470241, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:35:54,294] Trial 28 finished with value: 0.4117647058823529 and parameters: {'C': 38.313085899495974, 'gamma': 5.084074824406677, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:35:55,080] Trial 29 finished with value: 0.3684210526315789 and parameters: {'C': 39.98173930828108, 'gamma': 22.316537743521458, 'kernel': 'linear'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:36:48,011] Trial 30 finished with value: 0.18791946308724833 and parameters: {'C': 23.272470541079343, 'gamma': 14.565416640560768, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:36:48,082] Trial 31 finished with value: 0.1891891891891892 and parameters: {'C': 22.28773350959854, 'gamma': 13.912075851548881, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:37:32,965] Trial 32 finished with value: 0.4117647058823529 and parameters: {'C': 12.25540309032639, 'gamma': 2.9971713027740328, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:37:33,038] Trial 33 finished with value: 0.4117647058823529 and parameters: {'C': 10.80371233828782, 'gamma': 3.5881408463648423, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:38:19,898] Trial 34 finished with value: 0.4117647058823529 and parameters: {'C': 9.197564164354393, 'gamma': 9.031068318121806, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:39:17,102] Trial 35 finished with value: 0.0 and parameters: {'C': 5.990294494339295, 'gamma': 8.453826048624963, 'kernel': 'rbf'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:40:03,139] Trial 36 finished with value: 0.0 and parameters: {'C': 5.529964796566123, 'gamma': 12.30482933533729, 'kernel': 'rbf'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:40:48,261] Trial 38 finished with value: 0.4117647058823529 and parameters: {'C': 1.4439180505992317, 'gamma': 19.028841479913844, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:41:01,187] Trial 37 finished with value: 0.0 and parameters: {'C': 0.2593963397311909, 'gamma': 27.136888402480086, 'kernel': 'rbf'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:41:33,620] Trial 39 finished with value: 0.4117647058823529 and parameters: {'C': 14.723992677958798, 'gamma': 27.438935509024514, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:41:47,806] Trial 40 finished with value: 0.4117647058823529 and parameters: {'C': 15.2086977204766, 'gamma': 42.07849230241428, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:42:20,164] Trial 41 finished with value: 0.4117647058823529 and parameters: {'C': 32.28426527102504, 'gamma': 4.892245152689605, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:42:34,826] Trial 42 finished with value: 0.4117647058823529 and parameters: {'C': 3.0040163685118095, 'gamma': 44.95979173706892, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:43:05,931] Trial 43 finished with value: 0.4117647058823529 and parameters: {'C': 5.316636245887647, 'gamma': 47.78712782539716, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:43:20,512] Trial 44 finished with value: 0.4117647058823529 and parameters: {'C': 6.957263591977602, 'gamma': 49.39648813683878, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:43:21,874] Trial 45 finished with value: 0.3888888888888889 and parameters: {'C': 7.966582506160961, 'gamma': 35.83243764062292, 'kernel': 'linear'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:43:37,505] Trial 46 finished with value: 0.3684210526315789 and parameters: {'C': 46.98589223129364, 'gamma': 35.51935864736639, 'kernel': 'linear'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:44:07,334] Trial 47 finished with value: 0.4117647058823529 and parameters: {'C': 46.07179575532987, 'gamma': 20.4935873014503, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:44:22,899] Trial 48 finished with value: 0.4117647058823529 and parameters: {'C': 4.31036280024416, 'gamma': 20.363417661397932, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:44:42,154] Trial 49 finished with value: 0.4117647058823529 and parameters: {'C': 2.381149530390691, 'gamma': 24.23954592075784, 'kernel': 'poly'}. Best is trial 8 with value: 0.42105263157894735.
[I 2026-05-20 17:44:42,157] A new study created in memory with name: no-name-b5d651f6-7ab5-44f5-8cdf-542a78a64f84

Best trial for Emergent: F1 score= 0.4211
Best hyperparameters: {'C': 1.342185793621951, 'gamma': 0.9181931638773473, 'kernel': 'poly'}

[I 2026-05-20 17:44:54,991] Trial 1 finished with value: 0.6285714285714286 and parameters: {'C': 16.408180646538067, 'gamma': 0.7522585684476415, 'kernel': 'linear'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:46:13,219] Trial 2 finished with value: 0.5384615384615384 and parameters: {'C': 19.87602287292973, 'gamma': 49.8063152794406, 'kernel': 'poly'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:46:24,245] Trial 0 finished with value: 0.1 and parameters: {'C': 1.7624252221781262, 'gamma': 40.02462517597632, 'kernel': 'rbf'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:46:37,631] Trial 4 finished with value: 0.6285714285714286 and parameters: {'C': 30.613418422874837, 'gamma': 19.2486994803045, 'kernel': 'linear'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:46:50,814] Trial 5 finished with value: 0.6285714285714286 and parameters: {'C': 15.493579374461499, 'gamma': 21.25642394200347, 'kernel': 'linear'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:47:03,809] Trial 6 finished with value: 0.6285714285714286 and parameters: {'C': 23.212001214237123, 'gamma': 3.6737110657858305, 'kernel': 'linear'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:47:32,095] Trial 3 finished with value: 0.5384615384615384 and parameters: {'C': 43.01183457148771, 'gamma': 14.084687331089327, 'kernel': 'poly'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:48:46,970] Trial 7 finished with value: 0.4 and parameters: {'C': 15.794354189970619, 'gamma': 21.468566513944893, 'kernel': 'rbf'}. Best is trial 1 with value: 0.6285714285714286.
[I 2026-05-20 17:49:00,460] Trial 9 finished with value: 0.6451612903225806 and parameters: {'C': 8.116374793788172, 'gamma': 36.688034191958344, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:49:16,412] Trial 8 finished with value: 0.1 and parameters: {'C': 14.087995917512648, 'gamma': 47.076593609913324, 'kernel': 'rbf'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:50:06,507] Trial 11 finished with value: 0.3333333333333333 and parameters: {'C': 0.6664250286673976, 'gamma': 33.75535995922195, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:50:20,137] Trial 12 finished with value: 0.6451612903225806 and parameters: {'C': 7.049512950485852, 'gamma': 2.4261969303988202, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:50:33,887] Trial 13 finished with value: 0.6451612903225806 and parameters: {'C': 6.94338432610463, 'gamma': 31.37549717020863, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:50:40,667] Trial 10 finished with value: 0.5185185185185185 and parameters: {'C': 37.06488353460208, 'gamma': 5.116131431898676, 'kernel': 'rbf'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:51:04,064] Trial 14 finished with value: 0.5 and parameters: {'C': 30.624694972237286, 'gamma': 10.048326296090663, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:51:13,386] Trial 15 finished with value: 0.4827586206896552 and parameters: {'C': 8.305112262126714, 'gamma': 11.056911873850767, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:51:17,555] Trial 16 finished with value: 0.6451612903225806 and parameters: {'C': 9.33508026760473, 'gamma': 35.41608355007039, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:51:26,885] Trial 17 finished with value: 0.6451612903225806 and parameters: {'C': 8.567740207953921, 'gamma': 29.095588996402054, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:51:30,971] Trial 18 finished with value: 0.6285714285714286 and parameters: {'C': 49.760290234256836, 'gamma': 27.244589833443335, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:51:39,946] Trial 19 finished with value: 0.6285714285714286 and parameters: {'C': 27.248362525474114, 'gamma': 42.226217167975804, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:52:51,614] Trial 20 finished with value: 0.5384615384615384 and parameters: {'C': 27.64604726460904, 'gamma': 42.54297339232002, 'kernel': 'poly'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:52:59,165] Trial 21 finished with value: 0.5384615384615384 and parameters: {'C': 4.282011470960223, 'gamma': 39.30236602261803, 'kernel': 'poly'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:53:07,248] Trial 22 finished with value: 0.6451612903225806 and parameters: {'C': 3.4342747991195104, 'gamma': 31.8855806494631, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:53:13,737] Trial 23 finished with value: 0.6451612903225806 and parameters: {'C': 5.323594481914452, 'gamma': 32.2782954362725, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:53:20,795] Trial 24 finished with value: 0.6285714285714286 and parameters: {'C': 11.732218303515292, 'gamma': 25.53775459257365, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:53:26,989] Trial 25 finished with value: 0.6285714285714286 and parameters: {'C': 11.47226857662741, 'gamma': 26.715575142384427, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:53:33,893] Trial 26 finished with value: 0.6285714285714286 and parameters: {'C': 19.410854129267925, 'gamma': 36.83010419745659, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:53:40,162] Trial 27 finished with value: 0.6285714285714286 and parameters: {'C': 20.615000324963784, 'gamma': 37.041481231037935, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:53:47,701] Trial 28 finished with value: 0.6451612903225806 and parameters: {'C': 6.705339232513801, 'gamma': 18.432942840426115, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:54:19,497] Trial 29 finished with value: 0.37037037037037035 and parameters: {'C': 7.464906500652838, 'gamma': 16.63651047029455, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:54:42,606] Trial 30 finished with value: 0.20833333333333334 and parameters: {'C': 0.10591976411312842, 'gamma': 45.41567552505646, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:54:56,009] Trial 32 finished with value: 0.6285714285714286 and parameters: {'C': 11.467056494381005, 'gamma': 34.708450609159804, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:55:09,457] Trial 33 finished with value: 0.6451612903225806 and parameters: {'C': 10.4009886783129, 'gamma': 30.975408992921736, 'kernel': 'linear'}. Best is trial 9 with value: 0.6451612903225806.
[I 2026-05-20 17:55:24,618] Trial 34 finished with value: 0.6666666666666666 and parameters: {'C': 3.8267966505709383, 'gamma': 39.29416172150034, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:55:39,169] Trial 35 finished with value: 0.6451612903225806 and parameters: {'C': 2.9856149680587354, 'gamma': 39.71777947341046, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:56:02,477] Trial 31 finished with value: 0.4 and parameters: {'C': 0.7996362639816157, 'gamma': 23.356057136531305, 'kernel': 'rbf'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:57:21,266] Trial 37 finished with value: 0.5384615384615384 and parameters: {'C': 13.753351080238616, 'gamma': 44.27179879604752, 'kernel': 'poly'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:57:22,193] Trial 36 finished with value: 0.4 and parameters: {'C': 5.086449848179263, 'gamma': 23.192032476808926, 'kernel': 'rbf'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:57:35,583] Trial 38 finished with value: 0.6451612903225806 and parameters: {'C': 5.219075850999638, 'gamma': 29.610871920527245, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:57:35,713] Trial 39 finished with value: 0.6285714285714286 and parameters: {'C': 17.685275340955087, 'gamma': 49.176211486891496, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:57:48,931] Trial 40 finished with value: 0.6285714285714286 and parameters: {'C': 18.197248583411767, 'gamma': 38.42031532776592, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:57:48,977] Trial 41 finished with value: 0.6285714285714286 and parameters: {'C': 13.475830458441909, 'gamma': 0.3155096406410429, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:58:02,254] Trial 42 finished with value: 0.6451612903225806 and parameters: {'C': 9.243215422158514, 'gamma': 34.579875439899034, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:58:02,744] Trial 43 finished with value: 0.6451612903225806 and parameters: {'C': 8.980450380418556, 'gamma': 35.73750543736301, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:58:17,154] Trial 44 finished with value: 0.6451612903225806 and parameters: {'C': 2.5451204908688805, 'gamma': 41.710744203987915, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:58:17,797] Trial 45 finished with value: 0.6428571428571429 and parameters: {'C': 2.999108926862404, 'gamma': 41.698562624765515, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:58:31,032] Trial 46 finished with value: 0.6451612903225806 and parameters: {'C': 6.784687693053442, 'gamma': 3.2896096077044645, 'kernel': 'linear'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:59:37,209] Trial 47 finished with value: 0.5384615384615384 and parameters: {'C': 35.321874706172096, 'gamma': 28.585167957034187, 'kernel': 'poly'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 17:59:52,084] Trial 48 finished with value: 0.5384615384615384 and parameters: {'C': 35.24574182922794, 'gamma': 8.317311344979917, 'kernel': 'poly'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 18:00:48,821] Trial 49 finished with value: 0.2608695652173913 and parameters: {'C': 21.219048720272518, 'gamma': 33.097037280065436, 'kernel': 'rbf'}. Best is trial 34 with value: 0.6666666666666666.
[I 2026-05-20 18:00:48,825] A new study created in memory with name: no-name-b975ff1e-5419-44ce-af6c-3eb9aaac64ba

Best trial for Exercise: F1 score= 0.6667
Best hyperparameters: {'C': 3.8267966505709383, 'gamma': 39.29416172150034, 'kernel': 'linear'}

[I 2026-05-20 18:01:24,671] Trial 0 finished with value: 0.23140495867768596 and parameters: {'C': 10.678700528366159, 'gamma': 2.8465454939584145, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.23140495867768596.
[I 2026-05-20 18:02:32,477] Trial 1 finished with value: 0.14779874213836477 and parameters: {'C': 45.10218582447375, 'gamma': 29.04342286033237, 'kernel': 'rbf'}. Best is trial 0 with value: 0.23140495867768596.
[I 2026-05-20 18:03:01,243] Trial 3 finished with value: 0.45977011494252873 and parameters: {'C': 45.14020596084483, 'gamma': 15.826120004040797, 'kernel': 'linear'}. Best is trial 3 with value: 0.45977011494252873.
[I 2026-05-20 18:03:09,027] Trial 2 finished with value: 0.14779874213836477 and parameters: {'C': 16.357514382436477, 'gamma': 49.081831556467144, 'kernel': 'rbf'}. Best is trial 3 with value: 0.45977011494252873.
[I 2026-05-20 18:04:29,367] Trial 4 finished with value: 0.36363636363636365 and parameters: {'C': 37.37115110850755, 'gamma': 12.574726505682852, 'kernel': 'poly'}. Best is trial 3 with value: 0.45977011494252873.
[I 2026-05-20 18:04:40,405] Trial 5 finished with value: 0.36363636363636365 and parameters: {'C': 9.671022250304132, 'gamma': 44.34023495443163, 'kernel': 'poly'}. Best is trial 3 with value: 0.45977011494252873.
[I 2026-05-20 18:04:56,915] Trial 6 finished with value: 0.45977011494252873 and parameters: {'C': 48.19785359356027, 'gamma': 35.30316683099838, 'kernel': 'linear'}. Best is trial 3 with value: 0.45977011494252873.
[I 2026-05-20 18:06:23,419] Trial 7 finished with value: 0.14826498422712933 and parameters: {'C': 39.07552239153314, 'gamma': 16.997464162350713, 'kernel': 'rbf'}. Best is trial 3 with value: 0.45977011494252873.
[I 2026-05-20 18:06:30,116] Trial 8 finished with value: 0.36363636363636365 and parameters: {'C': 23.967910646351182, 'gamma': 25.673490403588918, 'kernel': 'poly'}. Best is trial 3 with value: 0.45977011494252873.
[I 2026-05-20 18:06:58,020] Trial 10 finished with value: 0.5168539325842697 and parameters: {'C': 12.120745775881534, 'gamma': 47.44468494338829, 'kernel': 'linear'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:08:07,675] Trial 9 finished with value: 0.14779874213836477 and parameters: {'C': 16.684919494319175, 'gamma': 34.246220493257155, 'kernel': 'rbf'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:08:13,583] Trial 11 finished with value: 0.4444444444444444 and parameters: {'C': 0.11819602362847803, 'gamma': 39.5826117381059, 'kernel': 'linear'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:08:35,628] Trial 12 finished with value: 0.4691358024691358 and parameters: {'C': 29.286008339842155, 'gamma': 15.472556525519206, 'kernel': 'linear'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:08:41,656] Trial 13 finished with value: 0.4691358024691358 and parameters: {'C': 29.95643077692014, 'gamma': 16.209054948373947, 'kernel': 'linear'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:09:03,267] Trial 14 finished with value: 0.4691358024691358 and parameters: {'C': 29.349929516273036, 'gamma': 5.492293003203514, 'kernel': 'linear'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:09:08,987] Trial 15 finished with value: 0.4731182795698925 and parameters: {'C': 26.37127567150064, 'gamma': 3.19075418000004, 'kernel': 'linear'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:10:12,320] Trial 16 finished with value: 0.18181818181818182 and parameters: {'C': 22.970815766920172, 'gamma': 23.00417583748479, 'kernel': 'sigmoid'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:10:21,121] Trial 17 finished with value: 0.18633540372670807 and parameters: {'C': 20.370061766442824, 'gamma': 22.7939087530495, 'kernel': 'sigmoid'}. Best is trial 10 with value: 0.5168539325842697.
[I 2026-05-20 18:10:48,594] Trial 18 finished with value: 0.5714285714285714 and parameters: {'C': 1.3307262150153605, 'gamma': 8.351221221861977, 'kernel': 'linear'}. Best is trial 18 with value: 0.5714285714285714.
[I 2026-05-20 18:10:50,970] Trial 19 finished with value: 0.5679012345679012 and parameters: {'C': 3.4897177215518695, 'gamma': 8.649826355657627, 'kernel': 'linear'}. Best is trial 18 with value: 0.5714285714285714.
[I 2026-05-20 18:11:24,783] Trial 21 finished with value: 0.5882352941176471 and parameters: {'C': 1.6472188192783586, 'gamma': 9.144468342222407, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:11:40,546] Trial 20 finished with value: 0.5 and parameters: {'C': 0.4177387637915807, 'gamma': 7.890503180798467, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:11:57,678] Trial 22 finished with value: 0.5783132530120482 and parameters: {'C': 1.8831461855826233, 'gamma': 10.207971787656888, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:12:09,071] Trial 23 finished with value: 0.5542168674698795 and parameters: {'C': 4.161473487255184, 'gamma': 8.924854225401814, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:12:26,047] Trial 24 finished with value: 0.5416666666666666 and parameters: {'C': 5.817367528903263, 'gamma': 0.22294839708463243, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:12:36,709] Trial 25 finished with value: 0.5416666666666666 and parameters: {'C': 7.175686295108838, 'gamma': 0.4762350340114363, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:12:54,163] Trial 26 finished with value: 0.5416666666666666 and parameters: {'C': 7.113750683033494, 'gamma': 12.200674384028137, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:13:04,366] Trial 27 finished with value: 0.525 and parameters: {'C': 15.933598288131616, 'gamma': 12.146541336478634, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:14:04,061] Trial 28 finished with value: 0.19767441860465115 and parameters: {'C': 13.670588428407978, 'gamma': 20.624794450613265, 'kernel': 'sigmoid'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:14:30,079] Trial 29 finished with value: 0.36363636363636365 and parameters: {'C': 2.188571915800676, 'gamma': 19.969830903899776, 'kernel': 'poly'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:15:12,081] Trial 31 finished with value: 0.2786885245901639 and parameters: {'C': 8.75596258544288, 'gamma': 4.593788533390415, 'kernel': 'sigmoid'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:15:34,519] Trial 30 finished with value: 0.36363636363636365 and parameters: {'C': 2.703213809180217, 'gamma': 5.095716368212889, 'kernel': 'poly'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:15:43,219] Trial 32 finished with value: 0.5542168674698795 and parameters: {'C': 3.696599262268849, 'gamma': 8.200565958508145, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:16:05,863] Trial 33 finished with value: 0.5301204819277109 and parameters: {'C': 4.987030848864528, 'gamma': 8.979554045762438, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:16:12,602] Trial 34 finished with value: 0.5121951219512195 and parameters: {'C': 10.653731927048444, 'gamma': 10.094011133799528, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:17:56,355] Trial 35 finished with value: 0.15284552845528454 and parameters: {'C': 11.2229585067284, 'gamma': 11.07747487878623, 'kernel': 'rbf'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:18:01,232] Trial 36 finished with value: 0.14779874213836477 and parameters: {'C': 0.10947099848300001, 'gamma': 13.201832049941835, 'kernel': 'rbf'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:18:29,778] Trial 38 finished with value: 0.5263157894736842 and parameters: {'C': 7.54478156874037, 'gamma': 5.974622875146537, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:18:32,843] Trial 37 finished with value: 0.5714285714285714 and parameters: {'C': 1.2763674142086643, 'gamma': 6.51957630941267, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:19:01,177] Trial 40 finished with value: 0.5054945054945055 and parameters: {'C': 14.71818954312012, 'gamma': 1.6207646219503857, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:19:01,278] Trial 39 finished with value: 0.5679012345679012 and parameters: {'C': 2.6783863904859535, 'gamma': 18.36178910269821, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:19:29,067] Trial 41 finished with value: 0.525 and parameters: {'C': 17.649028240569486, 'gamma': 30.827004842232302, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:19:30,317] Trial 42 finished with value: 0.5416666666666666 and parameters: {'C': 5.39458010035486, 'gamma': 14.894684166100049, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:19:57,805] Trial 43 finished with value: 0.5416666666666666 and parameters: {'C': 5.593921537006759, 'gamma': 14.630509380304812, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:20:04,024] Trial 44 finished with value: 0.5783132530120482 and parameters: {'C': 1.9252488959879215, 'gamma': 6.475127587682845, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:21:28,120] Trial 45 finished with value: 0.36363636363636365 and parameters: {'C': 9.180577603454957, 'gamma': 7.368376170514743, 'kernel': 'poly'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:21:31,863] Trial 46 finished with value: 0.36363636363636365 and parameters: {'C': 37.93206951977919, 'gamma': 3.220954316974585, 'kernel': 'poly'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:23:06,575] Trial 47 finished with value: 0.4642857142857143 and parameters: {'C': 34.19065757869215, 'gamma': 2.722196701859466, 'kernel': 'rbf'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:23:15,658] Trial 48 finished with value: 0.22950819672131148 and parameters: {'C': 34.78151046161057, 'gamma': 5.952960283822975, 'kernel': 'rbf'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:23:31,531] Trial 49 finished with value: 0.5783132530120482 and parameters: {'C': 1.9186613906166732, 'gamma': 5.8724981477730696, 'kernel': 'linear'}. Best is trial 21 with value: 0.5882352941176471.
[I 2026-05-20 18:23:31,533] A new study created in memory with name: no-name-fcd17179-d47b-4d5e-a355-b0463689d0aa

Best trial for Friends & Family: F1 score= 0.5882
Best hyperparameters: {'C': 1.6472188192783586, 'gamma': 9.144468342222407, 'kernel': 'linear'}

[I 2026-05-20 18:23:56,702] Trial 1 finished with value: 0.449438202247191 and parameters: {'C': 45.10083899349538, 'gamma': 48.54515206022255, 'kernel': 'linear'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:24:38,662] Trial 0 finished with value: 0.19161676646706588 and parameters: {'C': 44.466219246994314, 'gamma': 25.292843804257085, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:25:07,445] Trial 2 finished with value: 0.16901408450704225 and parameters: {'C': 18.181108036149393, 'gamma': 37.60843624144799, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:25:32,148] Trial 4 finished with value: 0.449438202247191 and parameters: {'C': 28.077278736666454, 'gamma': 45.481703512867966, 'kernel': 'linear'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:25:39,813] Trial 3 finished with value: 0.2185792349726776 and parameters: {'C': 28.406734011215505, 'gamma': 18.503914971795528, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:26:04,595] Trial 6 finished with value: 0.449438202247191 and parameters: {'C': 48.919125561627496, 'gamma': 47.3616288977685, 'kernel': 'linear'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:27:16,080] Trial 5 finished with value: 0.13312202852614896 and parameters: {'C': 41.59409668641092, 'gamma': 33.68888658655353, 'kernel': 'rbf'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:27:34,088] Trial 7 finished with value: 0.24161073825503357 and parameters: {'C': 34.08837886219003, 'gamma': 31.542666419740655, 'kernel': 'poly'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:28:22,603] Trial 8 finished with value: 0.27586206896551724 and parameters: {'C': 18.20135600216847, 'gamma': 21.064667466741057, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.449438202247191.
[I 2026-05-20 18:28:48,210] Trial 10 finished with value: 0.45714285714285713 and parameters: {'C': 20.672021106000905, 'gamma': 49.31669852602672, 'kernel': 'linear'}. Best is trial 10 with value: 0.45714285714285713.
[I 2026-05-20 18:29:05,059] Trial 9 finished with value: 0.24161073825503357 and parameters: {'C': 34.21990144117685, 'gamma': 26.512828417172717, 'kernel': 'poly'}. Best is trial 10 with value: 0.45714285714285713.
[I 2026-05-20 18:29:36,235] Trial 12 finished with value: 0.48717948717948717 and parameters: {'C': 3.110470159885196, 'gamma': 1.9670512387849186, 'kernel': 'linear'}. Best is trial 12 with value: 0.48717948717948717.
[I 2026-05-20 18:30:29,522] Trial 13 finished with value: 0.5135135135135135 and parameters: {'C': 0.4510703890035517, 'gamma': 7.492399038561845, 'kernel': 'linear'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:30:30,610] Trial 11 finished with value: 0.3225806451612903 and parameters: {'C': 2.558358349823095, 'gamma': 3.7210346377433865, 'kernel': 'rbf'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:31:04,131] Trial 14 finished with value: 0.5066666666666667 and parameters: {'C': 1.5348337243329806, 'gamma': 0.9926738554401039, 'kernel': 'linear'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:31:30,311] Trial 16 finished with value: 0.4657534246575342 and parameters: {'C': 9.633212155874386, 'gamma': 11.566980864411958, 'kernel': 'linear'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:31:31,767] Trial 15 finished with value: 0.5066666666666667 and parameters: {'C': 0.2906224523314128, 'gamma': 1.4651281543303618, 'kernel': 'linear'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:31:56,244] Trial 17 finished with value: 0.4657534246575342 and parameters: {'C': 8.937024073336591, 'gamma': 8.606125929457857, 'kernel': 'linear'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:31:57,419] Trial 18 finished with value: 0.4675324675324675 and parameters: {'C': 10.229574070939288, 'gamma': 9.923560791574415, 'kernel': 'linear'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:33:27,275] Trial 20 finished with value: 0.24161073825503357 and parameters: {'C': 14.04262944847157, 'gamma': 15.809018953793, 'kernel': 'poly'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:33:39,918] Trial 19 finished with value: 0.13333333333333333 and parameters: {'C': 10.332269642107143, 'gamma': 11.764643857802945, 'kernel': 'rbf'}. Best is trial 13 with value: 0.5135135135135135.
[I 2026-05-20 18:34:20,121] Trial 22 finished with value: 0.5185185185185185 and parameters: {'C': 1.0151909360416704, 'gamma': 0.7802566317899068, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:34:48,128] Trial 23 finished with value: 0.463768115942029 and parameters: {'C': 5.069089063702716, 'gamma': 6.6031308531360615, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:35:10,938] Trial 21 finished with value: 0.14457831325301204 and parameters: {'C': 5.6776595543531165, 'gamma': 7.872368662188738, 'kernel': 'rbf'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:35:15,638] Trial 24 finished with value: 0.463768115942029 and parameters: {'C': 6.081480390708414, 'gamma': 0.552664535791461, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:35:50,954] Trial 25 finished with value: 0.5185185185185185 and parameters: {'C': 1.034962989526497, 'gamma': 0.675628582988424, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:35:53,646] Trial 26 finished with value: 0.4943820224719101 and parameters: {'C': 1.3149834057968235, 'gamma': 4.828812393892106, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:36:16,156] Trial 27 finished with value: 0.4675324675324675 and parameters: {'C': 13.956708235399223, 'gamma': 5.120825265818238, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:36:19,462] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 14.662124084511401, 'gamma': 14.371788536140876, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:37:47,884] Trial 29 finished with value: 0.24161073825503357 and parameters: {'C': 13.728446587084626, 'gamma': 15.099435400538166, 'kernel': 'poly'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:37:53,653] Trial 30 finished with value: 0.24161073825503357 and parameters: {'C': 7.33126547191431, 'gamma': 22.749096648931936, 'kernel': 'poly'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:38:22,970] Trial 32 finished with value: 0.48717948717948717 and parameters: {'C': 3.327421133065224, 'gamma': 0.3824509804032542, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:38:50,358] Trial 31 finished with value: 0.23255813953488372 and parameters: {'C': 6.057981486813066, 'gamma': 23.53149371107627, 'kernel': 'sigmoid'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:39:31,710] Trial 33 finished with value: 0.5 and parameters: {'C': 0.20906933559685628, 'gamma': 4.2820272402671575, 'kernel': 'linear'}. Best is trial 22 with value: 0.5185185185185185.
[I 2026-05-20 18:39:42,980] Trial 34 finished with value: 0.5205479452054794 and parameters: {'C': 0.4885828531785191, 'gamma': 3.9762555202634675, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:40:01,576] Trial 35 finished with value: 0.4810126582278481 and parameters: {'C': 3.4313901951735892, 'gamma': 0.16639166340819156, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:40:53,921] Trial 37 finished with value: 0.25 and parameters: {'C': 24.401090007411323, 'gamma': 6.7779009432808675, 'kernel': 'sigmoid'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:41:20,092] Trial 36 finished with value: 0.4444444444444444 and parameters: {'C': 0.037079037548046756, 'gamma': 8.225876585410028, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:41:20,453] Trial 38 finished with value: 0.47368421052631576 and parameters: {'C': 11.79991750724017, 'gamma': 10.785217373225121, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:41:45,323] Trial 39 finished with value: 0.47368421052631576 and parameters: {'C': 11.340707463903954, 'gamma': 41.5666152212068, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:41:47,287] Trial 40 finished with value: 0.463768115942029 and parameters: {'C': 8.092138687966964, 'gamma': 3.7922229130507334, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:42:15,915] Trial 42 finished with value: 0.45454545454545453 and parameters: {'C': 4.28719772486669, 'gamma': 2.8822411934222636, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:42:43,425] Trial 41 finished with value: 0.23333333333333334 and parameters: {'C': 39.26214336695233, 'gamma': 17.83737121278784, 'kernel': 'sigmoid'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:42:47,886] Trial 43 finished with value: 0.49382716049382713 and parameters: {'C': 2.264089705809356, 'gamma': 6.564116669702221, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:43:14,913] Trial 44 finished with value: 0.4883720930232558 and parameters: {'C': 2.3410883357787053, 'gamma': 28.272877688668448, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:44:32,749] Trial 45 finished with value: 0.13312202852614896 and parameters: {'C': 7.693417627849361, 'gamma': 31.84202142713493, 'kernel': 'rbf'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:44:56,110] Trial 46 finished with value: 0.35 and parameters: {'C': 7.100435948957996, 'gamma': 3.364938194953403, 'kernel': 'rbf'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:44:58,067] Trial 47 finished with value: 0.4657534246575342 and parameters: {'C': 18.190055938670135, 'gamma': 2.421143196836046, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:45:21,676] Trial 48 finished with value: 0.4657534246575342 and parameters: {'C': 17.044864203860296, 'gamma': 2.132940333985239, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:45:24,797] Trial 49 finished with value: 0.45454545454545453 and parameters: {'C': 4.530292787482776, 'gamma': 13.531503222534594, 'kernel': 'linear'}. Best is trial 34 with value: 0.5205479452054794.
[I 2026-05-20 18:45:24,799] A new study created in memory with name: no-name-6342d2d7-ce08-4bb4-8d92-799723236da0

Best trial for Grateful Patient: F1 score= 0.5205
Best hyperparameters: {'C': 0.4885828531785191, 'gamma': 3.9762555202634675, 'kernel': 'linear'}

[I 2026-05-20 18:46:07,759] Trial 1 finished with value: 0.36065573770491804 and parameters: {'C': 17.996623902027814, 'gamma': 36.33182722712128, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.36065573770491804.
[I 2026-05-20 18:46:37,306] Trial 2 finished with value: 0.512 and parameters: {'C': 39.90003725272141, 'gamma': 8.32846969297971, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.512.
[I 2026-05-20 18:46:55,449] Trial 3 finished with value: 0.7191011235955056 and parameters: {'C': 31.899857800404376, 'gamma': 47.78065378538933, 'kernel': 'linear'}. Best is trial 3 with value: 0.7191011235955056.
[I 2026-05-20 18:47:08,078] Trial 0 finished with value: 0.3050847457627119 and parameters: {'C': 48.59284328294508, 'gamma': 27.071135828597072, 'kernel': 'rbf'}. Best is trial 3 with value: 0.7191011235955056.
[I 2026-05-20 18:47:39,140] Trial 4 finished with value: 0.368 and parameters: {'C': 5.285032055870299, 'gamma': 29.24464802080543, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.7191011235955056.
[I 2026-05-20 18:48:52,157] Trial 5 finished with value: 0.3050847457627119 and parameters: {'C': 9.36654320010691, 'gamma': 26.435638791818263, 'kernel': 'rbf'}. Best is trial 3 with value: 0.7191011235955056.
[I 2026-05-20 18:48:57,283] Trial 6 finished with value: 0.6190476190476191 and parameters: {'C': 14.864142254304022, 'gamma': 7.490637107175098, 'kernel': 'poly'}. Best is trial 3 with value: 0.7191011235955056.
[I 2026-05-20 18:49:10,186] Trial 7 finished with value: 0.7160493827160493 and parameters: {'C': 20.258323343512174, 'gamma': 5.493348731808079, 'kernel': 'linear'}. Best is trial 3 with value: 0.7191011235955056.
[I 2026-05-20 18:49:32,941] Trial 9 finished with value: 0.7912087912087912 and parameters: {'C': 1.1336503430326776, 'gamma': 31.516857373252712, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:49:43,406] Trial 8 finished with value: 0.375 and parameters: {'C': 39.390562656633946, 'gamma': 28.108799838005393, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:49:51,246] Trial 10 finished with value: 0.7252747252747253 and parameters: {'C': 18.822096307170654, 'gamma': 17.56005655473334, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:50:02,990] Trial 11 finished with value: 0.7674418604651163 and parameters: {'C': 2.291809448708462, 'gamma': 16.581635220650448, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:50:24,896] Trial 12 finished with value: 0.75 and parameters: {'C': 0.31023012926597815, 'gamma': 15.970852888605272, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:50:28,848] Trial 13 finished with value: 0.7912087912087912 and parameters: {'C': 0.7036983057417283, 'gamma': 15.964377142422602, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:50:52,597] Trial 14 finished with value: 0.7777777777777778 and parameters: {'C': 0.5254685164605466, 'gamma': 39.663747491484315, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:51:52,526] Trial 15 finished with value: 0.6190476190476191 and parameters: {'C': 9.501002043854514, 'gamma': 38.71372588342017, 'kernel': 'poly'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:52:11,313] Trial 16 finished with value: 0.6190476190476191 and parameters: {'C': 10.630763198522954, 'gamma': 35.29198287944082, 'kernel': 'poly'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:52:11,836] Trial 17 finished with value: 0.7142857142857143 and parameters: {'C': 27.856253476474052, 'gamma': 22.20156477343294, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:52:29,530] Trial 18 finished with value: 0.7142857142857143 and parameters: {'C': 26.16137170921011, 'gamma': 19.612438116884377, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:52:30,064] Trial 19 finished with value: 0.7441860465116279 and parameters: {'C': 7.5242444471830705, 'gamma': 12.082591563037695, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:54:14,115] Trial 21 finished with value: 0.18181818181818182 and parameters: {'C': 12.846016734880324, 'gamma': 45.44209494931701, 'kernel': 'rbf'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:54:14,571] Trial 20 finished with value: 0.48484848484848486 and parameters: {'C': 5.310297043443466, 'gamma': 11.77599870586304, 'kernel': 'rbf'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:54:32,937] Trial 22 finished with value: 0.7586206896551724 and parameters: {'C': 3.7432338333821615, 'gamma': 43.13069062398005, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:54:41,628] Trial 23 finished with value: 0.7912087912087912 and parameters: {'C': 0.5772592994900787, 'gamma': 41.31589052603976, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:54:53,288] Trial 24 finished with value: 0.7674418604651163 and parameters: {'C': 2.866938418507061, 'gamma': 32.26595693558667, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:55:11,790] Trial 26 finished with value: 0.7333333333333333 and parameters: {'C': 13.855971099280318, 'gamma': 49.8095697995841, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:55:15,693] Trial 25 finished with value: 0.75 and parameters: {'C': 0.294111392657733, 'gamma': 1.3587716634169436, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:55:31,702] Trial 27 finished with value: 0.7529411764705882 and parameters: {'C': 6.4629770378009015, 'gamma': 32.582368210681004, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:55:34,773] Trial 28 finished with value: 0.7529411764705882 and parameters: {'C': 6.255007088978874, 'gamma': 32.3745047353313, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:56:49,173] Trial 29 finished with value: 0.6190476190476191 and parameters: {'C': 21.886766473904384, 'gamma': 22.9349502946701, 'kernel': 'poly'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:56:53,158] Trial 30 finished with value: 0.6190476190476191 and parameters: {'C': 43.33073157543142, 'gamma': 23.14079821732188, 'kernel': 'poly'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:57:15,469] Trial 32 finished with value: 0.7912087912087912 and parameters: {'C': 1.1484971352123088, 'gamma': 40.95219655074501, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:57:34,595] Trial 33 finished with value: 0.7586206896551724 and parameters: {'C': 3.408186160729135, 'gamma': 43.038447922945004, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:57:53,178] Trial 34 finished with value: 0.7333333333333333 and parameters: {'C': 11.52569001757444, 'gamma': 40.59088791875231, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:58:32,276] Trial 31 finished with value: 0.18181818181818182 and parameters: {'C': 33.3202509303765, 'gamma': 42.281067991352835, 'kernel': 'rbf'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:58:38,124] Trial 35 finished with value: 0.37209302325581395 and parameters: {'C': 8.086445000881476, 'gamma': 38.21663117208424, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:59:15,755] Trial 37 finished with value: 0.7469879518072289 and parameters: {'C': 0.21007633791375674, 'gamma': 35.1064528611886, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:59:17,765] Trial 36 finished with value: 0.37398373983739835 and parameters: {'C': 7.750759887098745, 'gamma': 36.43338122704055, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:59:36,283] Trial 39 finished with value: 0.7252747252747253 and parameters: {'C': 16.10744284789066, 'gamma': 45.973554853706936, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 18:59:56,332] Trial 40 finished with value: 0.7586206896551724 and parameters: {'C': 3.5321256859698336, 'gamma': 24.975243695060694, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:00:01,051] Trial 38 finished with value: 0.35294117647058826 and parameters: {'C': 17.028237692957397, 'gamma': 45.87963021910227, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:00:55,341] Trial 42 finished with value: 0.7764705882352941 and parameters: {'C': 0.053755104531033604, 'gamma': 30.025064792553863, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:01:14,312] Trial 43 finished with value: 0.7529411764705882 and parameters: {'C': 4.96250214304872, 'gamma': 39.22765066774349, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:01:35,527] Trial 44 finished with value: 0.7674418604651163 and parameters: {'C': 1.9155727533634996, 'gamma': 41.17877639857316, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:01:39,410] Trial 41 finished with value: 0.3050847457627119 and parameters: {'C': 5.144163381315022, 'gamma': 31.225739123449316, 'kernel': 'rbf'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:01:54,607] Trial 45 finished with value: 0.7529411764705882 and parameters: {'C': 5.051152802463118, 'gamma': 37.16359170736095, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:01:58,638] Trial 46 finished with value: 0.7252747252747253 and parameters: {'C': 47.83342935688103, 'gamma': 27.15415836159695, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:02:13,647] Trial 47 finished with value: 0.7441860465116279 and parameters: {'C': 9.74385111679927, 'gamma': 34.67868924729199, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:02:16,919] Trial 48 finished with value: 0.7441860465116279 and parameters: {'C': 9.775269036702763, 'gamma': 49.25817313168428, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:02:27,811] Trial 49 finished with value: 0.7674418604651163 and parameters: {'C': 1.896450283103606, 'gamma': 48.44603688340632, 'kernel': 'linear'}. Best is trial 9 with value: 0.7912087912087912.
[I 2026-05-20 19:02:27,813] A new study created in memory with name: no-name-8199185f-4866-4e75-bf82-404a9474bb31

Best trial for Health Education: F1 score= 0.7912
Best hyperparameters: {'C': 1.1336503430326776, 'gamma': 31.516857373252712, 'kernel': 'linear'}

[I 2026-05-20 19:02:49,141] Trial 1 finished with value: 0.8597014925373134 and parameters: {'C': 14.828021308900382, 'gamma': 0.9048888062075903, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.8597014925373134.
[I 2026-05-20 19:03:25,939] Trial 0 finished with value: 0.47976011994003 and parameters: {'C': 17.62878630513766, 'gamma': 39.81872403115728, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.8597014925373134.
[I 2026-05-20 19:04:32,114] Trial 2 finished with value: 0.6123260437375746 and parameters: {'C': 48.834218598377376, 'gamma': 10.04362200080128, 'kernel': 'rbf'}. Best is trial 1 with value: 0.8597014925373134.
[I 2026-05-20 19:05:09,448] Trial 3 finished with value: 0.8225352112676056 and parameters: {'C': 17.747491886356187, 'gamma': 4.860923195984477, 'kernel': 'rbf'}. Best is trial 1 with value: 0.8597014925373134.
[I 2026-05-20 19:06:16,240] Trial 4 finished with value: 0.4791666666666667 and parameters: {'C': 36.66746453189213, 'gamma': 22.221945100553757, 'kernel': 'rbf'}. Best is trial 1 with value: 0.8597014925373134.
[I 2026-05-20 19:06:40,708] Trial 5 finished with value: 0.7761194029850746 and parameters: {'C': 33.43438189798042, 'gamma': 6.693964590235443, 'kernel': 'poly'}. Best is trial 1 with value: 0.8597014925373134.
[I 2026-05-20 19:06:42,746] Trial 6 finished with value: 0.9102167182662538 and parameters: {'C': 23.54458925811027, 'gamma': 30.045829481184267, 'kernel': 'linear'}. Best is trial 6 with value: 0.9102167182662538.
[I 2026-05-20 19:07:26,708] Trial 8 finished with value: 0.4718162839248434 and parameters: {'C': 8.257516121567319, 'gamma': 13.479454497083026, 'kernel': 'sigmoid'}. Best is trial 6 with value: 0.9102167182662538.
[I 2026-05-20 19:07:53,244] Trial 9 finished with value: 0.9107692307692308 and parameters: {'C': 21.9009426547011, 'gamma': 11.388946657443736, 'kernel': 'linear'}. Best is trial 9 with value: 0.9107692307692308.
[I 2026-05-20 19:08:13,546] Trial 10 finished with value: 0.8173374613003096 and parameters: {'C': 28.259247610422626, 'gamma': 1.156765807037378, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.9107692307692308.
[I 2026-05-20 19:08:23,324] Trial 7 finished with value: 0.4668587896253602 and parameters: {'C': 43.199048796373994, 'gamma': 29.234287061825412, 'kernel': 'rbf'}. Best is trial 9 with value: 0.9107692307692308.
[I 2026-05-20 19:08:47,081] Trial 11 finished with value: 0.9300911854103343 and parameters: {'C': 1.0679347051380255, 'gamma': 47.408809112408946, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:09:05,284] Trial 12 finished with value: 0.9235474006116208 and parameters: {'C': 0.47275592968658486, 'gamma': 28.424753039202894, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:09:17,442] Trial 13 finished with value: 0.916923076923077 and parameters: {'C': 3.6046640832240726, 'gamma': 19.932337519899484, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:09:33,270] Trial 14 finished with value: 0.9125 and parameters: {'C': 7.877047324660557, 'gamma': 47.79588338285815, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:09:48,941] Trial 15 finished with value: 0.9263803680981595 and parameters: {'C': 1.798606671947272, 'gamma': 49.665379378900866, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:10:03,061] Trial 16 finished with value: 0.916923076923077 and parameters: {'C': 2.8183611543139504, 'gamma': 49.855326872835306, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:11:26,712] Trial 17 finished with value: 0.7761194029850746 and parameters: {'C': 10.165651985751662, 'gamma': 49.24612934189338, 'kernel': 'poly'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:11:37,486] Trial 18 finished with value: 0.7761194029850746 and parameters: {'C': 12.056360910285395, 'gamma': 41.19203805627673, 'kernel': 'poly'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:11:54,459] Trial 19 finished with value: 0.9085365853658537 and parameters: {'C': 12.686492343830038, 'gamma': 38.898599763167546, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:12:05,332] Trial 20 finished with value: 0.916923076923077 and parameters: {'C': 5.89060185748487, 'gamma': 38.79532470877433, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:12:22,932] Trial 21 finished with value: 0.9174311926605505 and parameters: {'C': 5.31579189084837, 'gamma': 35.515939722749394, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:12:43,882] Trial 22 finished with value: 0.927710843373494 and parameters: {'C': 0.6817936771121867, 'gamma': 44.86702641385572, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:13:15,860] Trial 24 finished with value: 0.9235474006116208 and parameters: {'C': 1.829126593322869, 'gamma': 44.410140451995694, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:13:38,041] Trial 23 finished with value: 0.8222996515679443 and parameters: {'C': 0.04374357592546474, 'gamma': 45.853499805121054, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:13:49,045] Trial 25 finished with value: 0.9272727272727272 and parameters: {'C': 1.4919762961469836, 'gamma': 43.91610460229514, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:14:05,665] Trial 26 finished with value: 0.9125 and parameters: {'C': 8.12512721382494, 'gamma': 34.449627709288364, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:14:16,641] Trial 27 finished with value: 0.9164086687306502 and parameters: {'C': 7.523780018280064, 'gamma': 34.64652934513995, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:14:32,036] Trial 28 finished with value: 0.9118541033434651 and parameters: {'C': 17.06176599011758, 'gamma': 42.75979837604932, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:15:50,020] Trial 29 finished with value: 0.7761194029850746 and parameters: {'C': 18.87149963300093, 'gamma': 42.69960007763953, 'kernel': 'poly'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:16:04,061] Trial 30 finished with value: 0.7761194029850746 and parameters: {'C': 17.839609533001834, 'gamma': 44.44330083816256, 'kernel': 'poly'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:16:32,353] Trial 32 finished with value: 0.916923076923077 and parameters: {'C': 4.058154104933475, 'gamma': 46.444592068177684, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:16:51,358] Trial 31 finished with value: 0.4773413897280967 and parameters: {'C': 29.700756517084688, 'gamma': 38.086573327974705, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:17:31,218] Trial 34 finished with value: 0.9202453987730062 and parameters: {'C': 0.5389768299307638, 'gamma': 46.952796324123966, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:17:31,863] Trial 33 finished with value: 0.4773413897280967 and parameters: {'C': 0.8991335344741775, 'gamma': 38.665318488827154, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:17:57,847] Trial 35 finished with value: 0.9085365853658537 and parameters: {'C': 13.732844859481006, 'gamma': 41.16433232340988, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:19:13,952] Trial 36 finished with value: 0.44937586685159503 and parameters: {'C': 12.521065299649303, 'gamma': 49.92707234044653, 'kernel': 'rbf'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:19:40,974] Trial 37 finished with value: 0.44937586685159503 and parameters: {'C': 5.515955502359296, 'gamma': 49.90853064455853, 'kernel': 'rbf'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:19:42,947] Trial 38 finished with value: 0.9174311926605505 and parameters: {'C': 4.931834220925489, 'gamma': 32.062912671260875, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:20:08,113] Trial 40 finished with value: 0.9058823529411765 and parameters: {'C': 40.19974568174484, 'gamma': 25.747040608549494, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:20:08,666] Trial 39 finished with value: 0.9113149847094801 and parameters: {'C': 10.256207563224743, 'gamma': 44.69266133495265, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:20:35,143] Trial 41 finished with value: 0.9113149847094801 and parameters: {'C': 10.32278767882713, 'gamma': 18.46523584203257, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:20:38,169] Trial 42 finished with value: 0.9179331306990881 and parameters: {'C': 2.6298394336276854, 'gamma': 16.58095636971527, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:20:59,634] Trial 43 finished with value: 0.9079754601226994 and parameters: {'C': 49.08307154256355, 'gamma': 27.41687080697478, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:21:17,755] Trial 44 finished with value: 0.9212121212121213 and parameters: {'C': 0.5971758217522964, 'gamma': 27.50986930067511, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:22:41,746] Trial 45 finished with value: 0.47144948755490484 and parameters: {'C': 2.257468477330253, 'gamma': 24.079057039584647, 'kernel': 'rbf'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:23:01,536] Trial 46 finished with value: 0.45314685314685316 and parameters: {'C': 3.2862200276634974, 'gamma': 42.52267902756899, 'kernel': 'rbf'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:23:40,946] Trial 47 finished with value: 0.4723926380368098 and parameters: {'C': 6.603310256909065, 'gamma': 36.68946397620631, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:24:02,211] Trial 48 finished with value: 0.47007299270072994 and parameters: {'C': 6.855104748922321, 'gamma': 47.05555079992581, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:24:05,705] Trial 49 finished with value: 0.9125 and parameters: {'C': 8.912370292213001, 'gamma': 31.361509797164754, 'kernel': 'linear'}. Best is trial 11 with value: 0.9300911854103343.
[I 2026-05-20 19:24:05,709] A new study created in memory with name: no-name-2f235221-ad5e-4257-bd3c-64c016f07ff3

Best trial for Laboratory/Testing: F1 score= 0.9301
Best hyperparameters: {'C': 1.0679347051380255, 'gamma': 47.408809112408946, 'kernel': 'linear'}

[I 2026-05-20 19:25:28,285] Trial 0 finished with value: 0.7401574803149606 and parameters: {'C': 15.240328184968819, 'gamma': 41.87143644200601, 'kernel': 'poly'}. Best is trial 0 with value: 0.7401574803149606.
[I 2026-05-20 19:25:28,855] Trial 1 finished with value: 0.7401574803149606 and parameters: {'C': 46.36702929344883, 'gamma': 23.84384806768299, 'kernel': 'poly'}. Best is trial 0 with value: 0.7401574803149606.
[I 2026-05-20 19:26:50,308] Trial 2 finished with value: 0.7401574803149606 and parameters: {'C': 47.128055366761046, 'gamma': 2.612133756258451, 'kernel': 'poly'}. Best is trial 0 with value: 0.7401574803149606.
[I 2026-05-20 19:27:12,930] Trial 3 finished with value: 0.5631067961165048 and parameters: {'C': 48.95746105851475, 'gamma': 8.658629492326765, 'kernel': 'rbf'}. Best is trial 0 with value: 0.7401574803149606.
[I 2026-05-20 19:27:25,756] Trial 4 finished with value: 0.8740740740740741 and parameters: {'C': 0.5015837966102619, 'gamma': 36.98014795299567, 'kernel': 'linear'}. Best is trial 4 with value: 0.8740740740740741.
[I 2026-05-20 19:27:49,596] Trial 5 finished with value: 0.45714285714285713 and parameters: {'C': 7.224337745200466, 'gamma': 10.234029091803812, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8740740740740741.
[I 2026-05-20 19:28:49,778] Trial 6 finished with value: 0.7401574803149606 and parameters: {'C': 48.030494671515044, 'gamma': 6.207396595354143, 'kernel': 'poly'}. Best is trial 4 with value: 0.8740740740740741.
[I 2026-05-20 19:28:51,345] Trial 7 finished with value: 0.23974763406940064 and parameters: {'C': 34.56986557842031, 'gamma': 45.84530580022153, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8740740740740741.
[I 2026-05-20 19:29:12,913] Trial 9 finished with value: 0.8854961832061069 and parameters: {'C': 45.81380559345561, 'gamma': 24.57107174434264, 'kernel': 'linear'}. Best is trial 9 with value: 0.8854961832061069.
[I 2026-05-20 19:30:33,912] Trial 8 finished with value: 0.22370617696160267 and parameters: {'C': 40.98490171665178, 'gamma': 45.957302848944636, 'kernel': 'rbf'}. Best is trial 9 with value: 0.8854961832061069.
[I 2026-05-20 19:30:54,452] Trial 11 finished with value: 0.8939393939393939 and parameters: {'C': 27.22338780682579, 'gamma': 23.86483772225154, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:30:54,570] Trial 10 finished with value: 0.4742268041237113 and parameters: {'C': 31.336578129275505, 'gamma': 11.275161845817768, 'kernel': 'rbf'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:31:15,903] Trial 12 finished with value: 0.8939393939393939 and parameters: {'C': 26.21871583614711, 'gamma': 25.334809592677548, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:31:16,530] Trial 13 finished with value: 0.8939393939393939 and parameters: {'C': 22.87263112662155, 'gamma': 24.61062159452218, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:31:38,022] Trial 14 finished with value: 0.8939393939393939 and parameters: {'C': 21.289664613764387, 'gamma': 33.26828116527784, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:31:38,321] Trial 15 finished with value: 0.8939393939393939 and parameters: {'C': 22.014866609049268, 'gamma': 17.010973993802132, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:31:58,449] Trial 16 finished with value: 0.8939393939393939 and parameters: {'C': 29.673330633517356, 'gamma': 17.862683881398084, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:31:58,577] Trial 17 finished with value: 0.8939393939393939 and parameters: {'C': 31.40591324547242, 'gamma': 32.29432726271024, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:32:20,404] Trial 18 finished with value: 0.8939393939393939 and parameters: {'C': 16.088909144822168, 'gamma': 31.58114111393872, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:32:20,597] Trial 19 finished with value: 0.8939393939393939 and parameters: {'C': 15.519618702392899, 'gamma': 18.042979947808167, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:33:12,608] Trial 20 finished with value: 0.3076923076923077 and parameters: {'C': 38.89994646598935, 'gamma': 17.59946712187117, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:33:19,857] Trial 21 finished with value: 0.26440677966101694 and parameters: {'C': 37.93163234970052, 'gamma': 28.265203002624634, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:33:33,142] Trial 22 finished with value: 0.8939393939393939 and parameters: {'C': 24.894362518831766, 'gamma': 27.30466042723356, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:33:41,629] Trial 23 finished with value: 0.8939393939393939 and parameters: {'C': 25.58591389693262, 'gamma': 23.01460683090927, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:33:54,798] Trial 24 finished with value: 0.8939393939393939 and parameters: {'C': 25.410001070296815, 'gamma': 23.173363195790863, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:34:02,741] Trial 25 finished with value: 0.8939393939393939 and parameters: {'C': 18.986012921031623, 'gamma': 20.974348341979262, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:34:15,411] Trial 26 finished with value: 0.8939393939393939 and parameters: {'C': 19.505390440301355, 'gamma': 14.12854088734484, 'kernel': 'linear'}. Best is trial 11 with value: 0.8939393939393939.
[I 2026-05-20 19:34:24,540] Trial 27 finished with value: 0.9090909090909091 and parameters: {'C': 11.714186256948487, 'gamma': 14.034868755048876, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:34:37,316] Trial 28 finished with value: 0.9090909090909091 and parameters: {'C': 12.262248775524242, 'gamma': 38.28097759534986, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:36:08,467] Trial 29 finished with value: 0.23103448275862068 and parameters: {'C': 10.31789583082486, 'gamma': 36.81802337588687, 'kernel': 'rbf'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:36:21,644] Trial 30 finished with value: 0.22635135135135134 and parameters: {'C': 10.031139844566544, 'gamma': 42.019871489455745, 'kernel': 'rbf'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:36:44,833] Trial 32 finished with value: 0.9090909090909091 and parameters: {'C': 5.311784129670853, 'gamma': 28.5932919928795, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:37:33,546] Trial 31 finished with value: 0.7401574803149606 and parameters: {'C': 11.014621804699246, 'gamma': 40.98604695697722, 'kernel': 'poly'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:37:58,017] Trial 34 finished with value: 0.9007633587786259 and parameters: {'C': 2.878485967442396, 'gamma': 0.34062736794754045, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:38:07,313] Trial 33 finished with value: 0.7401574803149606 and parameters: {'C': 4.56157145199687, 'gamma': 37.55978297061222, 'kernel': 'poly'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:38:32,849] Trial 36 finished with value: 0.8872180451127819 and parameters: {'C': 1.723077748100167, 'gamma': 1.673448494071403, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:38:54,711] Trial 37 finished with value: 0.9090909090909091 and parameters: {'C': 4.750961621959266, 'gamma': 6.171096817127952, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:39:17,198] Trial 38 finished with value: 0.9090909090909091 and parameters: {'C': 6.398186278959044, 'gamma': 6.720023162952162, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:39:25,795] Trial 35 finished with value: 0.7761194029850746 and parameters: {'C': 1.5435275600014293, 'gamma': 0.6974275004675163, 'kernel': 'poly'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:39:48,962] Trial 40 finished with value: 0.6298342541436464 and parameters: {'C': 12.546363948743394, 'gamma': 4.432151821109091, 'kernel': 'sigmoid'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:40:10,973] Trial 41 finished with value: 0.9090909090909091 and parameters: {'C': 7.184028831846632, 'gamma': 49.01153393097825, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:40:33,531] Trial 42 finished with value: 0.9090909090909091 and parameters: {'C': 5.642456492791798, 'gamma': 7.349220531171823, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:40:39,594] Trial 39 finished with value: 0.7401574803149606 and parameters: {'C': 13.393235012977142, 'gamma': 5.215369218211383, 'kernel': 'poly'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:40:54,957] Trial 43 finished with value: 0.9090909090909091 and parameters: {'C': 6.702653512981751, 'gamma': 12.137671615283258, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:41:02,026] Trial 44 finished with value: 0.9090909090909091 and parameters: {'C': 8.257817417393952, 'gamma': 10.990900494386057, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:41:17,268] Trial 45 finished with value: 0.9090909090909091 and parameters: {'C': 8.250837412892295, 'gamma': 9.005114822982524, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:41:24,891] Trial 46 finished with value: 0.9090909090909091 and parameters: {'C': 4.71243255602508, 'gamma': 8.475984517265335, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:41:40,514] Trial 47 finished with value: 0.9090909090909091 and parameters: {'C': 4.446069831540034, 'gamma': 13.79807169083376, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:42:01,765] Trial 49 finished with value: 0.8939393939393939 and parameters: {'C': 17.52095106726074, 'gamma': 35.250186879422294, 'kernel': 'linear'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:42:43,402] Trial 48 finished with value: 0.391304347826087 and parameters: {'C': 13.16733669244545, 'gamma': 15.479862692627586, 'kernel': 'rbf'}. Best is trial 27 with value: 0.9090909090909091.
[I 2026-05-20 19:42:43,405] A new study created in memory with name: no-name-29302255-7189-443d-910d-15c12d00e56a

Best trial for Medications: F1 score= 0.9091
Best hyperparameters: {'C': 11.714186256948487, 'gamma': 14.034868755048876, 'kernel': 'linear'}

[I 2026-05-20 19:43:10,217] Trial 0 finished with value: 0.7181208053691275 and parameters: {'C': 22.624381233652933, 'gamma': 2.6096662066243734, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.7181208053691275.
[I 2026-05-20 19:43:17,963] Trial 1 finished with value: 0.8495934959349594 and parameters: {'C': 39.68390363500054, 'gamma': 22.868632993491644, 'kernel': 'linear'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:44:53,737] Trial 2 finished with value: 0.6122448979591837 and parameters: {'C': 13.20100897624779, 'gamma': 27.707324993688687, 'kernel': 'rbf'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:45:03,655] Trial 3 finished with value: 0.625 and parameters: {'C': 2.535873591765961, 'gamma': 18.7095915711974, 'kernel': 'rbf'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:46:05,336] Trial 5 finished with value: 0.6384976525821596 and parameters: {'C': 41.163732596580026, 'gamma': 18.84492455888749, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:46:36,386] Trial 4 finished with value: 0.6055276381909548 and parameters: {'C': 36.37933399959926, 'gamma': 34.51732847436936, 'kernel': 'rbf'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:47:33,696] Trial 7 finished with value: 0.6255144032921811 and parameters: {'C': 28.45972863425891, 'gamma': 25.747641007001757, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:47:38,961] Trial 6 finished with value: 0.8477366255144033 and parameters: {'C': 43.55314187928194, 'gamma': 41.49671021371235, 'kernel': 'poly'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:48:04,021] Trial 8 finished with value: 0.7058823529411765 and parameters: {'C': 35.02121163192067, 'gamma': 3.483680746263238, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.8495934959349594.
[I 2026-05-20 19:48:39,402] Trial 10 finished with value: 0.8536585365853658 and parameters: {'C': 37.25202492473023, 'gamma': 33.59529288024177, 'kernel': 'linear'}. Best is trial 10 with value: 0.8536585365853658.
[I 2026-05-20 19:49:13,797] Trial 11 finished with value: 0.8484848484848485 and parameters: {'C': 49.499852923132345, 'gamma': 49.95000036163208, 'kernel': 'linear'}. Best is trial 10 with value: 0.8536585365853658.
[I 2026-05-20 19:49:22,845] Trial 9 finished with value: 0.615979381443299 and parameters: {'C': 45.95246866278397, 'gamma': 23.871933578841624, 'kernel': 'rbf'}. Best is trial 10 with value: 0.8536585365853658.
[I 2026-05-20 19:49:50,126] Trial 12 finished with value: 0.8519269776876268 and parameters: {'C': 27.171812405250805, 'gamma': 14.390497914617862, 'kernel': 'linear'}. Best is trial 10 with value: 0.8536585365853658.
[I 2026-05-20 19:49:58,679] Trial 13 finished with value: 0.8536585365853658 and parameters: {'C': 28.754005583289306, 'gamma': 13.214222030965484, 'kernel': 'linear'}. Best is trial 10 with value: 0.8536585365853658.
[I 2026-05-20 19:50:27,107] Trial 14 finished with value: 0.8588957055214724 and parameters: {'C': 22.577732740121046, 'gamma': 10.806276922210875, 'kernel': 'linear'}. Best is trial 14 with value: 0.8588957055214724.
[I 2026-05-20 19:50:34,244] Trial 15 finished with value: 0.8624229979466119 and parameters: {'C': 19.896878982901445, 'gamma': 9.858528147668467, 'kernel': 'linear'}. Best is trial 15 with value: 0.8624229979466119.
[I 2026-05-20 19:51:01,816] Trial 16 finished with value: 0.86652977412731 and parameters: {'C': 18.240974915503816, 'gamma': 35.56617845141497, 'kernel': 'linear'}. Best is trial 16 with value: 0.86652977412731.
[I 2026-05-20 19:52:09,338] Trial 17 finished with value: 0.8477366255144033 and parameters: {'C': 17.199839936776897, 'gamma': 9.153555340069564, 'kernel': 'poly'}. Best is trial 16 with value: 0.86652977412731.
[I 2026-05-20 19:52:33,479] Trial 18 finished with value: 0.8477366255144033 and parameters: {'C': 15.334443296252783, 'gamma': 40.796504047434546, 'kernel': 'poly'}. Best is trial 16 with value: 0.86652977412731.
[I 2026-05-20 19:52:46,003] Trial 19 finished with value: 0.8636363636363636 and parameters: {'C': 8.508086637657327, 'gamma': 40.965001763206274, 'kernel': 'linear'}. Best is trial 16 with value: 0.86652977412731.
[I 2026-05-20 19:53:10,122] Trial 20 finished with value: 0.8649789029535865 and parameters: {'C': 7.639971457419302, 'gamma': 32.273440563282506, 'kernel': 'linear'}. Best is trial 16 with value: 0.86652977412731.
[I 2026-05-20 19:53:22,957] Trial 21 finished with value: 0.8632478632478633 and parameters: {'C': 8.260172397550638, 'gamma': 46.800151243615446, 'kernel': 'linear'}. Best is trial 16 with value: 0.86652977412731.
[I 2026-05-20 19:53:47,047] Trial 22 finished with value: 0.8649789029535865 and parameters: {'C': 7.75062898833141, 'gamma': 35.02444303765763, 'kernel': 'linear'}. Best is trial 16 with value: 0.86652977412731.
[I 2026-05-20 19:54:06,433] Trial 23 finished with value: 0.8764940239043825 and parameters: {'C': 0.7336963899581059, 'gamma': 32.77673336302734, 'kernel': 'linear'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:54:38,563] Trial 24 finished with value: 0.8627450980392157 and parameters: {'C': 0.24669710944994705, 'gamma': 33.08599998245653, 'kernel': 'linear'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:54:52,407] Trial 25 finished with value: 0.8747514910536779 and parameters: {'C': 0.6526498285253998, 'gamma': 31.142878052621786, 'kernel': 'linear'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:55:14,344] Trial 26 finished with value: 0.874251497005988 and parameters: {'C': 4.090260897162013, 'gamma': 29.565705301904906, 'kernel': 'linear'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:55:28,772] Trial 27 finished with value: 0.874251497005988 and parameters: {'C': 4.5064848901729615, 'gamma': 29.57562008451501, 'kernel': 'linear'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:55:52,694] Trial 28 finished with value: 0.8762677484787018 and parameters: {'C': 2.449595631789473, 'gamma': 28.3148908281093, 'kernel': 'linear'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:57:03,966] Trial 29 finished with value: 0.8477366255144033 and parameters: {'C': 11.794716105378818, 'gamma': 38.310152973013494, 'kernel': 'poly'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:57:26,335] Trial 30 finished with value: 0.8477366255144033 and parameters: {'C': 12.783252826521291, 'gamma': 38.05828296692078, 'kernel': 'poly'}. Best is trial 23 with value: 0.8764940239043825.
[I 2026-05-20 19:58:08,314] Trial 32 finished with value: 0.8796680497925311 and parameters: {'C': 0.9604188202134671, 'gamma': 29.30834983379026, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 19:58:11,149] Trial 31 finished with value: 0.6253443526170799 and parameters: {'C': 0.28387648634462476, 'gamma': 20.96680479048744, 'kernel': 'sigmoid'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 19:58:47,394] Trial 34 finished with value: 0.874251497005988 and parameters: {'C': 4.200038886328619, 'gamma': 27.714611602272967, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 19:58:54,298] Trial 33 finished with value: 0.8735177865612648 and parameters: {'C': 0.5560268059599323, 'gamma': 21.51360330103153, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 19:59:52,763] Trial 35 finished with value: 0.8392484342379958 and parameters: {'C': 0.05956753786295721, 'gamma': 26.23960618734177, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:00:36,051] Trial 36 finished with value: 0.6093552465233881 and parameters: {'C': 5.377004678288907, 'gamma': 30.720945329941575, 'kernel': 'rbf'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:01:12,149] Trial 38 finished with value: 0.865979381443299 and parameters: {'C': 9.301842105741008, 'gamma': 28.74029963806824, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:01:36,622] Trial 37 finished with value: 0.6078184110970997 and parameters: {'C': 4.1816096939933285, 'gamma': 31.57111218225406, 'kernel': 'rbf'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:02:29,214] Trial 40 finished with value: 0.6322378716744914 and parameters: {'C': 10.305431659354742, 'gamma': 18.661726246850122, 'kernel': 'sigmoid'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:02:54,299] Trial 39 finished with value: 0.6143958868894601 and parameters: {'C': 2.6818014522846356, 'gamma': 24.642328990660005, 'kernel': 'rbf'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:03:07,716] Trial 41 finished with value: 0.8744939271255061 and parameters: {'C': 2.3621360698695906, 'gamma': 25.395960497262898, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:03:31,478] Trial 42 finished with value: 0.8667992047713717 and parameters: {'C': 5.976224891840626, 'gamma': 36.8210986936797, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:03:45,276] Trial 43 finished with value: 0.8632478632478633 and parameters: {'C': 6.684024754969813, 'gamma': 26.477796548583573, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:04:07,257] Trial 44 finished with value: 0.8667992047713717 and parameters: {'C': 6.1697125725054995, 'gamma': 25.52387229401491, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:04:23,479] Trial 45 finished with value: 0.8762677484787018 and parameters: {'C': 2.480728273489442, 'gamma': 23.736788013484247, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:04:45,266] Trial 46 finished with value: 0.8744939271255061 and parameters: {'C': 2.8040605806212247, 'gamma': 22.475451881531306, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:05:00,649] Trial 47 finished with value: 0.8762677484787018 and parameters: {'C': 2.635592673178541, 'gamma': 22.3273685732835, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:05:34,527] Trial 48 finished with value: 0.6431852986217458 and parameters: {'C': 10.598118185938613, 'gamma': 15.608258218585972, 'kernel': 'sigmoid'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:05:36,335] Trial 49 finished with value: 0.8658536585365854 and parameters: {'C': 11.094828800838116, 'gamma': 17.201953789441607, 'kernel': 'linear'}. Best is trial 32 with value: 0.8796680497925311.
[I 2026-05-20 20:05:36,338] A new study created in memory with name: no-name-03073471-8cc9-49b1-bbe7-b1b28527cb7d

Best trial for No Symptoms: F1 score= 0.8797
Best hyperparameters: {'C': 0.9604188202134671, 'gamma': 29.30834983379026, 'kernel': 'linear'}

[I 2026-05-20 20:06:05,437] Trial 0 finished with value: 0.9516864175022789 and parameters: {'C': 49.878182116980696, 'gamma': 15.103662262110387, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:06:37,875] Trial 1 finished with value: 0.9413886384129847 and parameters: {'C': 41.94515921195743, 'gamma': 43.66299904462098, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:06:53,591] Trial 2 finished with value: 0.9406474820143885 and parameters: {'C': 30.138746721664656, 'gamma': 10.207217315736312, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:08:18,467] Trial 3 finished with value: 0.9387387387387387 and parameters: {'C': 27.64317317909785, 'gamma': 6.255476968041635, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:08:26,582] Trial 4 finished with value: 0.9408553230209281 and parameters: {'C': 15.649987431983023, 'gamma': 35.70304987457141, 'kernel': 'poly'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:09:50,629] Trial 5 finished with value: 0.9408553230209281 and parameters: {'C': 2.5765992470972012, 'gamma': 36.97146303441879, 'kernel': 'poly'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:09:54,591] Trial 6 finished with value: 0.9408553230209281 and parameters: {'C': 0.6965923784834009, 'gamma': 21.310622700681076, 'kernel': 'poly'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:11:23,419] Trial 8 finished with value: 0.9408553230209281 and parameters: {'C': 28.366140516484606, 'gamma': 44.20546589032054, 'kernel': 'poly'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:11:33,672] Trial 7 finished with value: 0.9406474820143885 and parameters: {'C': 15.513229355436431, 'gamma': 24.94415973633315, 'kernel': 'rbf'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:12:04,279] Trial 9 finished with value: 0.9279854147675478 and parameters: {'C': 48.538492645765196, 'gamma': 6.142924594817654, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:12:33,313] Trial 11 finished with value: 0.9516864175022789 and parameters: {'C': 38.59816978767484, 'gamma': 16.473029200017134, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:12:33,554] Trial 10 finished with value: 0.9423423423423424 and parameters: {'C': 19.75914744920436, 'gamma': 47.62830571697443, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:13:03,500] Trial 12 finished with value: 0.9516864175022789 and parameters: {'C': 39.98328525083941, 'gamma': 16.54476243832699, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:13:04,232] Trial 13 finished with value: 0.9516864175022789 and parameters: {'C': 41.17837218449504, 'gamma': 16.502299715480508, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:13:33,132] Trial 14 finished with value: 0.9516864175022789 and parameters: {'C': 49.26995037225807, 'gamma': 0.876045112946441, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:13:33,291] Trial 15 finished with value: 0.9516864175022789 and parameters: {'C': 48.37903919474007, 'gamma': 30.91018720455769, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:14:02,193] Trial 17 finished with value: 0.9516864175022789 and parameters: {'C': 33.98177089811404, 'gamma': 16.517130535225313, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:14:02,249] Trial 16 finished with value: 0.9516864175022789 and parameters: {'C': 34.76584956799761, 'gamma': 30.24571706277064, 'kernel': 'linear'}. Best is trial 0 with value: 0.9516864175022789.
[I 2026-05-20 20:14:31,544] Trial 19 finished with value: 0.9522935779816514 and parameters: {'C': 44.09847634743954, 'gamma': 12.600019349640355, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:14:31,608] Trial 18 finished with value: 0.9516864175022789 and parameters: {'C': 36.839827251092494, 'gamma': 12.251647446421988, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:15:00,702] Trial 20 finished with value: 0.9516864175022789 and parameters: {'C': 43.19120877796379, 'gamma': 9.912297883888865, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:15:31,578] Trial 22 finished with value: 0.9522935779816514 and parameters: {'C': 44.1139191996434, 'gamma': 22.35034399036584, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:16:00,631] Trial 23 finished with value: 0.9522935779816514 and parameters: {'C': 45.144382852479396, 'gamma': 22.495306255183337, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:16:16,110] Trial 21 finished with value: 0.9406474820143885 and parameters: {'C': 44.26125778311316, 'gamma': 22.50565456317094, 'kernel': 'rbf'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:16:45,357] Trial 25 finished with value: 0.9516864175022789 and parameters: {'C': 45.90716304480712, 'gamma': 27.34620385325629, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:17:14,531] Trial 26 finished with value: 0.9516864175022789 and parameters: {'C': 35.06206164638185, 'gamma': 21.16323199639738, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:17:44,377] Trial 27 finished with value: 0.9516864175022789 and parameters: {'C': 32.44738398376602, 'gamma': 25.52295934184005, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:17:45,296] Trial 24 finished with value: 0.9406474820143885 and parameters: {'C': 44.93923734155366, 'gamma': 22.222368515256314, 'kernel': 'rbf'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:18:13,686] Trial 28 finished with value: 0.9516864175022789 and parameters: {'C': 45.52578593379885, 'gamma': 20.094960116686615, 'kernel': 'linear'}. Best is trial 19 with value: 0.9522935779816514.
[I 2026-05-20 20:18:14,949] Trial 29 finished with value: 0.9525547445255474 and parameters: {'C': 20.89185152313134, 'gamma': 30.512573720171176, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:18:42,840] Trial 30 finished with value: 0.9525547445255474 and parameters: {'C': 23.870517498355618, 'gamma': 12.409172559611106, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:18:44,483] Trial 31 finished with value: 0.9525547445255474 and parameters: {'C': 22.29282885448747, 'gamma': 34.7564770187098, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:19:12,051] Trial 32 finished with value: 0.9525547445255474 and parameters: {'C': 21.2404536666166, 'gamma': 32.47894828289897, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:19:15,570] Trial 33 finished with value: 0.9525547445255474 and parameters: {'C': 21.49511181403348, 'gamma': 36.35397042371797, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:19:42,403] Trial 34 finished with value: 0.9525547445255474 and parameters: {'C': 22.665000614728783, 'gamma': 35.9172948760241, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:20:19,896] Trial 35 finished with value: 0.9406474820143885 and parameters: {'C': 22.815861467451025, 'gamma': 32.251907744242935, 'kernel': 'sigmoid'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:20:47,936] Trial 36 finished with value: 0.9406474820143885 and parameters: {'C': 16.79965828995195, 'gamma': 40.08810619097979, 'kernel': 'sigmoid'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:20:50,706] Trial 37 finished with value: 0.9525547445255474 and parameters: {'C': 16.304266556322954, 'gamma': 40.32445174561328, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:22:21,726] Trial 39 finished with value: 0.9408553230209281 and parameters: {'C': 11.778020619532697, 'gamma': 33.194733697567635, 'kernel': 'poly'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:22:22,273] Trial 38 finished with value: 0.9408553230209281 and parameters: {'C': 10.928079918363863, 'gamma': 40.16150805736553, 'kernel': 'poly'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:24:06,126] Trial 41 finished with value: 0.9406474820143885 and parameters: {'C': 24.895458928931028, 'gamma': 29.47459550004981, 'kernel': 'rbf'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:24:08,186] Trial 40 finished with value: 0.9406474820143885 and parameters: {'C': 25.88199476329284, 'gamma': 28.627454017391287, 'kernel': 'rbf'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:24:36,791] Trial 42 finished with value: 0.9525547445255474 and parameters: {'C': 19.33872215197377, 'gamma': 34.170293019784125, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:24:37,982] Trial 43 finished with value: 0.9525547445255474 and parameters: {'C': 18.790175664337898, 'gamma': 34.342688232188394, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:25:05,855] Trial 44 finished with value: 0.9516864175022789 and parameters: {'C': 29.435020222935947, 'gamma': 37.617181789465135, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:25:06,983] Trial 45 finished with value: 0.9516864175022789 and parameters: {'C': 30.61530314417224, 'gamma': 37.780397442035735, 'kernel': 'linear'}. Best is trial 29 with value: 0.9525547445255474.
[I 2026-05-20 20:25:35,778] Trial 46 finished with value: 0.9534246575342465 and parameters: {'C': 13.369337183869874, 'gamma': 43.12344757622313, 'kernel': 'linear'}. Best is trial 46 with value: 0.9534246575342465.
[I 2026-05-20 20:25:37,194] Trial 47 finished with value: 0.9534246575342465 and parameters: {'C': 12.577210072590297, 'gamma': 46.78538987845677, 'kernel': 'linear'}. Best is trial 46 with value: 0.9534246575342465.
[I 2026-05-20 20:26:40,377] Trial 48 finished with value: 0.9423423423423424 and parameters: {'C': 8.39792845369734, 'gamma': 48.47581797200215, 'kernel': 'sigmoid'}. Best is trial 46 with value: 0.9534246575342465.
[I 2026-05-20 20:26:41,315] Trial 49 finished with value: 0.9406474820143885 and parameters: {'C': 12.048242271570293, 'gamma': 49.41381892795085, 'kernel': 'sigmoid'}. Best is trial 46 with value: 0.9534246575342465.
[I 2026-05-20 20:26:41,317] A new study created in memory with name: no-name-029f8c68-9341-4860-8de8-c2fbd7557bd3

Best trial for Non-urgent: F1 score= 0.9534
Best hyperparameters: {'C': 13.369337183869874, 'gamma': 43.12344757622313, 'kernel': 'linear'}

[I 2026-05-20 20:27:12,065] Trial 1 finished with value: 0.6201550387596899 and parameters: {'C': 25.81957552860571, 'gamma': 44.78969981955124, 'kernel': 'linear'}. Best is trial 1 with value: 0.6201550387596899.
[I 2026-05-20 20:28:16,935] Trial 0 finished with value: 0.5076923076923077 and parameters: {'C': 2.069252625401716, 'gamma': 16.875094385890417, 'kernel': 'poly'}. Best is trial 1 with value: 0.6201550387596899.
[I 2026-05-20 20:28:19,822] Trial 2 finished with value: 0.20972644376899696 and parameters: {'C': 16.022677128577698, 'gamma': 17.013858954537575, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.6201550387596899.
[I 2026-05-20 20:29:51,265] Trial 3 finished with value: 0.5076923076923077 and parameters: {'C': 11.044476317452823, 'gamma': 34.72816381358986, 'kernel': 'poly'}. Best is trial 1 with value: 0.6201550387596899.
[I 2026-05-20 20:30:04,948] Trial 4 finished with value: 0.22330097087378642 and parameters: {'C': 6.5531115730867775, 'gamma': 37.201061337761274, 'kernel': 'rbf'}. Best is trial 1 with value: 0.6201550387596899.
[I 2026-05-20 20:30:23,676] Trial 5 finished with value: 0.625 and parameters: {'C': 38.37252642946203, 'gamma': 8.3672413423368, 'kernel': 'linear'}. Best is trial 5 with value: 0.625.
[I 2026-05-20 20:30:54,473] Trial 7 finished with value: 0.6299212598425197 and parameters: {'C': 42.96621844969805, 'gamma': 2.094375776696242, 'kernel': 'linear'}. Best is trial 7 with value: 0.6299212598425197.
[I 2026-05-20 20:31:08,550] Trial 6 finished with value: 0.20972644376899696 and parameters: {'C': 38.520108566400594, 'gamma': 14.387366555110907, 'kernel': 'sigmoid'}. Best is trial 7 with value: 0.6299212598425197.
[I 2026-05-20 20:32:05,618] Trial 8 finished with value: 0.2112 and parameters: {'C': 15.17539857546876, 'gamma': 39.23489843606146, 'kernel': 'sigmoid'}. Best is trial 7 with value: 0.6299212598425197.
[I 2026-05-20 20:32:51,057] Trial 9 finished with value: 0.24381625441696114 and parameters: {'C': 42.22180936080632, 'gamma': 18.534492334345604, 'kernel': 'rbf'}. Best is trial 7 with value: 0.6299212598425197.
[I 2026-05-20 20:33:21,393] Trial 10 finished with value: 0.2108626198083067 and parameters: {'C': 39.186480350314234, 'gamma': 38.24254932690358, 'kernel': 'sigmoid'}. Best is trial 7 with value: 0.6299212598425197.
[I 2026-05-20 20:33:21,472] Trial 11 finished with value: 0.640625 and parameters: {'C': 48.28857188119846, 'gamma': 1.006774671037327, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:33:52,384] Trial 13 finished with value: 0.6299212598425197 and parameters: {'C': 47.35909259065203, 'gamma': 1.8178086080702842, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:33:52,959] Trial 12 finished with value: 0.6201550387596899 and parameters: {'C': 30.240471312690268, 'gamma': 0.4027412022710388, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:34:24,108] Trial 14 finished with value: 0.640625 and parameters: {'C': 49.99550233407308, 'gamma': 1.2141781654733967, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:34:24,973] Trial 15 finished with value: 0.640625 and parameters: {'C': 48.494231918547094, 'gamma': 26.189756581724804, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:34:54,424] Trial 16 finished with value: 0.640625 and parameters: {'C': 48.19265744106096, 'gamma': 10.279000593655564, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:34:55,836] Trial 17 finished with value: 0.625 and parameters: {'C': 33.47339986167308, 'gamma': 8.704539452434716, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:35:25,379] Trial 18 finished with value: 0.6201550387596899 and parameters: {'C': 31.409881351412828, 'gamma': 7.395929216096377, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:36:23,607] Trial 19 finished with value: 0.5076923076923077 and parameters: {'C': 21.804721682162278, 'gamma': 25.8391295983891, 'kernel': 'poly'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:37:09,456] Trial 20 finished with value: 0.23389830508474577 and parameters: {'C': 21.91972317422229, 'gamma': 24.788587285153938, 'kernel': 'rbf'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:37:41,225] Trial 22 finished with value: 0.640625 and parameters: {'C': 49.611142348142685, 'gamma': 26.278424176233568, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:38:05,167] Trial 21 finished with value: 0.23875432525951557 and parameters: {'C': 49.943622163415135, 'gamma': 21.84776529217201, 'kernel': 'rbf'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:38:11,500] Trial 23 finished with value: 0.6299212598425197 and parameters: {'C': 45.429495100454034, 'gamma': 21.029399374840107, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:38:37,545] Trial 24 finished with value: 0.6299212598425197 and parameters: {'C': 44.21029140316497, 'gamma': 30.554172757232013, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:38:42,001] Trial 25 finished with value: 0.6299212598425197 and parameters: {'C': 43.05800747373273, 'gamma': 32.24695064207119, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:39:08,674] Trial 26 finished with value: 0.625 and parameters: {'C': 36.289809023942695, 'gamma': 5.167739680927963, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:39:12,981] Trial 27 finished with value: 0.625 and parameters: {'C': 35.535257687518126, 'gamma': 5.623148872496298, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:39:39,830] Trial 28 finished with value: 0.625 and parameters: {'C': 40.67087584219657, 'gamma': 12.355781245928778, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:40:42,097] Trial 29 finished with value: 0.5076923076923077 and parameters: {'C': 41.57721684395374, 'gamma': 12.669837355158357, 'kernel': 'poly'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:41:10,420] Trial 30 finished with value: 0.5076923076923077 and parameters: {'C': 0.4839844678143095, 'gamma': 48.82701242024057, 'kernel': 'poly'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:41:43,805] Trial 32 finished with value: 0.6299212598425197 and parameters: {'C': 46.936763583385094, 'gamma': 3.788994965425141, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:42:11,122] Trial 31 finished with value: 0.5076923076923077 and parameters: {'C': 45.97739313320173, 'gamma': 48.43535808557453, 'kernel': 'poly'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:42:15,301] Trial 33 finished with value: 0.6299212598425197 and parameters: {'C': 47.36644077372958, 'gamma': 8.769836196663805, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:42:42,460] Trial 34 finished with value: 0.640625 and parameters: {'C': 49.56930867744371, 'gamma': 10.474306913565206, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:42:48,299] Trial 35 finished with value: 0.640625 and parameters: {'C': 48.53524778936122, 'gamma': 0.019644127218529484, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:43:14,883] Trial 36 finished with value: 0.6299212598425197 and parameters: {'C': 45.07138082633656, 'gamma': 15.32983417483549, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:43:20,149] Trial 37 finished with value: 0.6201550387596899 and parameters: {'C': 27.44582651965336, 'gamma': 4.324013440025185, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:43:55,659] Trial 38 finished with value: 0.24858757062146894 and parameters: {'C': 26.958849982192024, 'gamma': 3.935251652514974, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:44:32,897] Trial 39 finished with value: 0.20972644376899696 and parameters: {'C': 4.701863898981799, 'gamma': 28.51678825223271, 'kernel': 'sigmoid'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:45:42,256] Trial 40 finished with value: 0.24338624338624337 and parameters: {'C': 4.280447113622802, 'gamma': 18.65927107105721, 'kernel': 'rbf'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:46:13,613] Trial 42 finished with value: 0.640625 and parameters: {'C': 49.73596631908436, 'gamma': 24.401969645717504, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:46:21,996] Trial 41 finished with value: 0.24253075571177504 and parameters: {'C': 37.12599207217969, 'gamma': 19.109995794311292, 'kernel': 'rbf'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:46:44,629] Trial 43 finished with value: 0.6299212598425197 and parameters: {'C': 44.689475967270994, 'gamma': 29.4577964079713, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:46:53,672] Trial 44 finished with value: 0.6299212598425197 and parameters: {'C': 44.34634512976158, 'gamma': 27.59000626357622, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:47:17,202] Trial 45 finished with value: 0.625 and parameters: {'C': 39.85720853756615, 'gamma': 34.282625680850416, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:47:25,342] Trial 46 finished with value: 0.625 and parameters: {'C': 40.24086679076804, 'gamma': 40.9433165873094, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:47:48,598] Trial 47 finished with value: 0.6299212598425197 and parameters: {'C': 47.151617180531055, 'gamma': 1.6509576627912743, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:47:58,462] Trial 48 finished with value: 0.640625 and parameters: {'C': 47.612213508796586, 'gamma': 16.41189543616968, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:48:12,803] Trial 49 finished with value: 0.6165413533834586 and parameters: {'C': 10.337641423938289, 'gamma': 22.567517049353118, 'kernel': 'linear'}. Best is trial 11 with value: 0.640625.
[I 2026-05-20 20:48:12,805] A new study created in memory with name: no-name-8c027851-dc96-43a0-a2c4-7cb5c7a6219c

Best trial for Outpatient Logistics/Scheduling: F1 score= 0.6406
Best hyperparameters: {'C': 48.28857188119846, 'gamma': 1.006774671037327, 'kernel': 'linear'}

[I 2026-05-20 20:49:51,955] Trial 1 finished with value: 0.6486486486486487 and parameters: {'C': 12.126135071739238, 'gamma': 17.30727496340851, 'kernel': 'poly'}. Best is trial 1 with value: 0.6486486486486487.
[I 2026-05-20 20:50:02,003] Trial 0 finished with value: 0.3071786310517529 and parameters: {'C': 1.6456852616307682, 'gamma': 33.75259095546099, 'kernel': 'rbf'}. Best is trial 1 with value: 0.6486486486486487.
[I 2026-05-20 20:51:32,464] Trial 2 finished with value: 0.6486486486486487 and parameters: {'C': 4.6269534381282345, 'gamma': 47.71155285988912, 'kernel': 'poly'}. Best is trial 1 with value: 0.6486486486486487.
[I 2026-05-20 20:51:50,642] Trial 3 finished with value: 0.34210526315789475 and parameters: {'C': 11.426604454294534, 'gamma': 18.275980051719177, 'kernel': 'rbf'}. Best is trial 1 with value: 0.6486486486486487.
[I 2026-05-20 20:53:08,736] Trial 4 finished with value: 0.6486486486486487 and parameters: {'C': 7.550096131093938, 'gamma': 34.498311726901306, 'kernel': 'poly'}. Best is trial 1 with value: 0.6486486486486487.
[I 2026-05-20 20:53:35,762] Trial 5 finished with value: 0.37815126050420167 and parameters: {'C': 48.7513368358959, 'gamma': 13.255371014556355, 'kernel': 'rbf'}. Best is trial 1 with value: 0.6486486486486487.
[I 2026-05-20 20:54:55,623] Trial 6 finished with value: 0.7111111111111111 and parameters: {'C': 33.685939421589104, 'gamma': 4.000640991122736, 'kernel': 'rbf'}. Best is trial 6 with value: 0.7111111111111111.
[I 2026-05-20 20:55:11,158] Trial 7 finished with value: 0.6486486486486487 and parameters: {'C': 40.92516331463434, 'gamma': 12.26315980345577, 'kernel': 'poly'}. Best is trial 6 with value: 0.7111111111111111.
[I 2026-05-20 20:55:44,924] Trial 9 finished with value: 0.7796610169491526 and parameters: {'C': 9.34434130656086, 'gamma': 18.56254675577701, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:56:02,768] Trial 8 finished with value: 0.2807017543859649 and parameters: {'C': 21.47815298172308, 'gamma': 39.28902311580964, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:56:16,297] Trial 10 finished with value: 0.7790697674418605 and parameters: {'C': 24.25479828232712, 'gamma': 48.73692938749421, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:56:35,438] Trial 11 finished with value: 0.7745664739884393 and parameters: {'C': 21.675180980104873, 'gamma': 26.41475768999672, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:56:48,987] Trial 12 finished with value: 0.7745664739884393 and parameters: {'C': 22.161291358899057, 'gamma': 26.3174123888822, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:57:06,683] Trial 13 finished with value: 0.776595744680851 and parameters: {'C': 29.293831324689684, 'gamma': 49.84343900622993, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:57:19,850] Trial 14 finished with value: 0.7771428571428571 and parameters: {'C': 30.054736050238105, 'gamma': 48.466300441661396, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:57:38,243] Trial 15 finished with value: 0.7771428571428571 and parameters: {'C': 16.91031733054463, 'gamma': 1.0259767030182303, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:57:51,555] Trial 16 finished with value: 0.7752808988764045 and parameters: {'C': 14.903740103142882, 'gamma': 1.4036405085049282, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:58:49,294] Trial 17 finished with value: 0.28029197080291973 and parameters: {'C': 37.73187003064063, 'gamma': 40.04500652122369, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:59:05,740] Trial 18 finished with value: 0.3231441048034934 and parameters: {'C': 38.21188094118049, 'gamma': 42.04699802587768, 'kernel': 'sigmoid'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:59:22,235] Trial 19 finished with value: 0.7796610169491526 and parameters: {'C': 8.031326047051444, 'gamma': 21.333569361086873, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:59:37,649] Trial 20 finished with value: 0.7790697674418605 and parameters: {'C': 26.072373965774087, 'gamma': 21.283406943846373, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 20:59:56,458] Trial 21 finished with value: 0.7796610169491526 and parameters: {'C': 8.059733430948231, 'gamma': 20.75100319602384, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 21:00:43,549] Trial 22 finished with value: 0.776595744680851 and parameters: {'C': 0.2528541592319282, 'gamma': 29.484678538230035, 'kernel': 'linear'}. Best is trial 9 with value: 0.7796610169491526.
[I 2026-05-20 21:00:45,250] Trial 23 finished with value: 0.7807486631016043 and parameters: {'C': 0.750689732754072, 'gamma': 11.163688030466785, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:01:18,018] Trial 24 finished with value: 0.7796610169491526 and parameters: {'C': 7.644911433039091, 'gamma': 9.654016320510785, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:01:19,888] Trial 25 finished with value: 0.7692307692307693 and parameters: {'C': 5.7796956354287, 'gamma': 7.6983623372580094, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:01:52,139] Trial 27 finished with value: 0.7771428571428571 and parameters: {'C': 16.82953141697423, 'gamma': 14.549139707919744, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:01:53,274] Trial 26 finished with value: 0.7708333333333334 and parameters: {'C': 3.148359424299071, 'gamma': 7.485404532864306, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:02:27,704] Trial 28 finished with value: 0.7734806629834254 and parameters: {'C': 3.9331914468267324, 'gamma': 22.532249735286698, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:03:00,107] Trial 29 finished with value: 0.294770206022187 and parameters: {'C': 11.413811727953307, 'gamma': 22.691024289560772, 'kernel': 'sigmoid'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:03:43,040] Trial 30 finished with value: 0.28029197080291973 and parameters: {'C': 0.24093574881040247, 'gamma': 30.131861924127243, 'kernel': 'sigmoid'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:04:15,389] Trial 32 finished with value: 0.7796610169491526 and parameters: {'C': 8.380980854291721, 'gamma': 18.08324958858453, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:04:48,715] Trial 31 finished with value: 0.3493282149712092 and parameters: {'C': 0.9898390872110205, 'gamma': 16.237477481221063, 'kernel': 'rbf'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:04:49,887] Trial 33 finished with value: 0.7796610169491526 and parameters: {'C': 10.867181919749115, 'gamma': 15.65391793216395, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:05:20,775] Trial 34 finished with value: 0.7796610169491526 and parameters: {'C': 13.154805699804264, 'gamma': 19.831923331730323, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:06:29,295] Trial 35 finished with value: 0.6486486486486487 and parameters: {'C': 14.870137347095753, 'gamma': 20.777298222921676, 'kernel': 'poly'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:06:58,026] Trial 36 finished with value: 0.6486486486486487 and parameters: {'C': 8.925100083364859, 'gamma': 10.598096793272198, 'kernel': 'poly'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:07:03,882] Trial 37 finished with value: 0.7692307692307693 and parameters: {'C': 5.601682199550723, 'gamma': 11.605051507880388, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:08:45,254] Trial 38 finished with value: 0.3192982456140351 and parameters: {'C': 4.646259647560711, 'gamma': 24.348565051806652, 'kernel': 'rbf'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:08:52,400] Trial 39 finished with value: 0.3194444444444444 and parameters: {'C': 3.312212367533693, 'gamma': 24.5973912038686, 'kernel': 'rbf'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:09:18,883] Trial 40 finished with value: 0.7727272727272727 and parameters: {'C': 18.382398170389678, 'gamma': 31.246166139246064, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:09:25,132] Trial 41 finished with value: 0.7796610169491526 and parameters: {'C': 10.454651823009769, 'gamma': 30.637972091668352, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:09:52,444] Trial 42 finished with value: 0.7796610169491526 and parameters: {'C': 8.207418141512848, 'gamma': 8.566473650094302, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:10:00,338] Trial 43 finished with value: 0.7796610169491526 and parameters: {'C': 7.516546828246104, 'gamma': 9.136508816629076, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:10:26,364] Trial 44 finished with value: 0.7752808988764045 and parameters: {'C': 6.717462271719926, 'gamma': 5.266516461647104, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:10:32,615] Trial 45 finished with value: 0.7727272727272727 and parameters: {'C': 6.50004433280232, 'gamma': 4.7543164821640325, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:12:02,226] Trial 46 finished with value: 0.6486486486486487 and parameters: {'C': 2.459306621485349, 'gamma': 13.587635138505103, 'kernel': 'poly'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:12:11,298] Trial 47 finished with value: 0.6486486486486487 and parameters: {'C': 13.314386732455514, 'gamma': 18.079406196731174, 'kernel': 'poly'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:12:34,128] Trial 48 finished with value: 0.7796610169491526 and parameters: {'C': 13.332338176665825, 'gamma': 17.998447263058708, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:12:39,632] Trial 49 finished with value: 0.7727272727272727 and parameters: {'C': 19.142899662972074, 'gamma': 26.58120284907182, 'kernel': 'linear'}. Best is trial 23 with value: 0.7807486631016043.
[I 2026-05-20 21:12:39,635] A new study created in memory with name: no-name-5b51d30d-bc4d-437d-9e47-eb3870e277cd

Best trial for Physical: F1 score= 0.7807
Best hyperparameters: {'C': 0.750689732754072, 'gamma': 11.163688030466785, 'kernel': 'linear'}

[I 2026-05-20 21:13:11,747] Trial 0 finished with value: 0.27450980392156865 and parameters: {'C': 43.692827665563186, 'gamma': 15.572280271397517, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.27450980392156865.
[I 2026-05-20 21:14:22,326] Trial 1 finished with value: 0.38461538461538464 and parameters: {'C': 40.810410426676846, 'gamma': 18.38001157335937, 'kernel': 'rbf'}. Best is trial 1 with value: 0.38461538461538464.
[I 2026-05-20 21:14:59,111] Trial 2 finished with value: 0.25 and parameters: {'C': 37.58983054925772, 'gamma': 38.11627158369731, 'kernel': 'rbf'}. Best is trial 1 with value: 0.38461538461538464.
[I 2026-05-20 21:15:13,935] Trial 4 finished with value: 0.8780487804878049 and parameters: {'C': 16.89935629449026, 'gamma': 30.510634280735612, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:15:44,123] Trial 3 finished with value: 0.8421052631578947 and parameters: {'C': 42.84366947492128, 'gamma': 1.0322910699899666, 'kernel': 'poly'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:15:49,044] Trial 5 finished with value: 0.2608695652173913 and parameters: {'C': 41.18334777467077, 'gamma': 16.387480155464655, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:16:33,683] Trial 7 finished with value: 0.1791044776119403 and parameters: {'C': 41.19806499180292, 'gamma': 49.81680113364935, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:17:27,229] Trial 6 finished with value: 0.25 and parameters: {'C': 14.368041574629796, 'gamma': 33.39772431706096, 'kernel': 'rbf'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:17:57,260] Trial 8 finished with value: 0.75 and parameters: {'C': 10.161224886200436, 'gamma': 24.07442550115623, 'kernel': 'poly'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:18:39,510] Trial 10 finished with value: 0.2 and parameters: {'C': 27.763654635138188, 'gamma': 42.750594136288136, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:18:45,206] Trial 9 finished with value: 0.75 and parameters: {'C': 29.98708275845629, 'gamma': 30.940412950366973, 'kernel': 'poly'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:00,057] Trial 12 finished with value: 0.8780487804878049 and parameters: {'C': 18.7285356909546, 'gamma': 3.3481501902222135, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:04,279] Trial 11 finished with value: 0.85 and parameters: {'C': 0.36993210588622816, 'gamma': 30.174980075312295, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:14,826] Trial 13 finished with value: 0.8780487804878049 and parameters: {'C': 18.14098142600392, 'gamma': 2.5038350521162576, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:18,640] Trial 14 finished with value: 0.8780487804878049 and parameters: {'C': 18.2631020377443, 'gamma': 0.7906928255003081, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:29,879] Trial 15 finished with value: 0.8571428571428571 and parameters: {'C': 21.320757951407842, 'gamma': 8.394594382084723, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:33,309] Trial 16 finished with value: 0.8780487804878049 and parameters: {'C': 9.015793365730529, 'gamma': 7.889351930164274, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:44,570] Trial 17 finished with value: 0.8717948717948718 and parameters: {'C': 6.621084485251831, 'gamma': 23.041793637854493, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:47,467] Trial 18 finished with value: 0.85 and parameters: {'C': 32.388442404989846, 'gamma': 22.302349657126673, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:19:58,866] Trial 19 finished with value: 0.8571428571428571 and parameters: {'C': 24.138405056080593, 'gamma': 42.17204391041464, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:02,144] Trial 20 finished with value: 0.85 and parameters: {'C': 49.6447477209714, 'gamma': 10.589562694201174, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:13,469] Trial 21 finished with value: 0.85 and parameters: {'C': 48.80384519934498, 'gamma': 12.455165512023381, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:16,715] Trial 22 finished with value: 0.8780487804878049 and parameters: {'C': 16.189992004320462, 'gamma': 4.809467522974175, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:27,781] Trial 23 finished with value: 0.8780487804878049 and parameters: {'C': 16.059051277098167, 'gamma': 5.141510747916632, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:31,441] Trial 24 finished with value: 0.8780487804878049 and parameters: {'C': 20.54902277724749, 'gamma': 4.7830531381354415, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:42,028] Trial 25 finished with value: 0.8571428571428571 and parameters: {'C': 21.50875097615299, 'gamma': 29.477077813670824, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:46,023] Trial 26 finished with value: 0.8780487804878049 and parameters: {'C': 12.092015955958065, 'gamma': 29.04366356081832, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:20:56,319] Trial 27 finished with value: 0.8780487804878049 and parameters: {'C': 11.773101128013206, 'gamma': 26.667885192347786, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:22:05,495] Trial 28 finished with value: 0.75 and parameters: {'C': 3.285102658627114, 'gamma': 19.34434471956307, 'kernel': 'poly'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:22:18,614] Trial 29 finished with value: 0.75 and parameters: {'C': 4.824809615456667, 'gamma': 36.12462209447265, 'kernel': 'poly'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:23:51,270] Trial 30 finished with value: 0.5517241379310345 and parameters: {'C': 26.943550351559054, 'gamma': 13.192564444596432, 'kernel': 'rbf'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:24:01,952] Trial 31 finished with value: 0.5 and parameters: {'C': 25.110963889848197, 'gamma': 13.569804958070637, 'kernel': 'rbf'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:24:05,741] Trial 32 finished with value: 0.8780487804878049 and parameters: {'C': 19.00543262696545, 'gamma': 0.6078161669284117, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:24:16,483] Trial 33 finished with value: 0.8780487804878049 and parameters: {'C': 17.483496333367746, 'gamma': 0.013730928865376413, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:24:20,212] Trial 34 finished with value: 0.8780487804878049 and parameters: {'C': 18.061646278724485, 'gamma': 1.2256216050845326, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:24:30,960] Trial 35 finished with value: 0.8780487804878049 and parameters: {'C': 13.33652943641579, 'gamma': 3.5371917938664232, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:24:41,670] Trial 36 finished with value: 0.5945945945945946 and parameters: {'C': 35.17056479761861, 'gamma': 4.082978557418418, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:24:57,876] Trial 37 finished with value: 0.27906976744186046 and parameters: {'C': 35.14785957678684, 'gamma': 8.045585937110253, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:26:28,317] Trial 38 finished with value: 0.6875 and parameters: {'C': 23.210085475745615, 'gamma': 9.300333970450698, 'kernel': 'rbf'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:26:43,053] Trial 40 finished with value: 0.8780487804878049 and parameters: {'C': 14.606585375681233, 'gamma': 17.194723290161093, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:26:44,061] Trial 39 finished with value: 0.38461538461538464 and parameters: {'C': 23.058772508747694, 'gamma': 17.073626687658756, 'kernel': 'rbf'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:26:57,567] Trial 41 finished with value: 0.8780487804878049 and parameters: {'C': 8.731996324481678, 'gamma': 34.30934236260001, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:26:58,523] Trial 42 finished with value: 0.8780487804878049 and parameters: {'C': 8.690717947363943, 'gamma': 6.520295970363794, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:27:11,802] Trial 43 finished with value: 0.8780487804878049 and parameters: {'C': 8.407195085225801, 'gamma': 6.727548571512079, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:27:12,999] Trial 44 finished with value: 0.8780487804878049 and parameters: {'C': 19.338054176146294, 'gamma': 2.571440894282831, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:27:26,885] Trial 45 finished with value: 0.8780487804878049 and parameters: {'C': 18.775305835087483, 'gamma': 1.9492502644272784, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:28:34,489] Trial 46 finished with value: 0.8108108108108109 and parameters: {'C': 14.119180471816652, 'gamma': 2.193492079731015, 'kernel': 'poly'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:28:51,719] Trial 47 finished with value: 0.75 and parameters: {'C': 10.922268695075507, 'gamma': 11.209086420959196, 'kernel': 'poly'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:29:06,300] Trial 49 finished with value: 0.8571428571428571 and parameters: {'C': 27.109727418600073, 'gamma': 20.157358411082157, 'kernel': 'linear'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:29:11,979] Trial 48 finished with value: 0.2777777777777778 and parameters: {'C': 10.372511680720478, 'gamma': 39.71514959556679, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.8780487804878049.
[I 2026-05-20 21:29:11,981] A new study created in memory with name: no-name-1d004877-edfb-4209-b3e4-3ca6cc86457e

Best trial for Physical Environment/Climate: F1 score= 0.8780
Best hyperparameters: {'C': 16.89935629449026, 'gamma': 30.510634280735612, 'kernel': 'linear'}

[I 2026-05-20 21:29:29,191] Trial 0 finished with value: 0.4583333333333333 and parameters: {'C': 39.42316791921491, 'gamma': 34.3947022107492, 'kernel': 'linear'}. Best is trial 0 with value: 0.4583333333333333.
[I 2026-05-20 21:30:01,654] Trial 1 finished with value: 0.21739130434782608 and parameters: {'C': 39.05924268939001, 'gamma': 34.47264457342017, 'kernel': 'poly'}. Best is trial 0 with value: 0.4583333333333333.
[I 2026-05-20 21:30:19,137] Trial 2 finished with value: 0.21739130434782608 and parameters: {'C': 17.38173418166387, 'gamma': 48.9768141112943, 'kernel': 'poly'}. Best is trial 0 with value: 0.4583333333333333.
[I 2026-05-20 21:30:50,654] Trial 3 finished with value: 0.21739130434782608 and parameters: {'C': 4.226435499277136, 'gamma': 8.348498902990116, 'kernel': 'poly'}. Best is trial 0 with value: 0.4583333333333333.
[I 2026-05-20 21:31:27,368] Trial 4 finished with value: 0.0 and parameters: {'C': 26.107296706241716, 'gamma': 28.936311090050577, 'kernel': 'sigmoid'}. Best is trial 0 with value: 0.4583333333333333.
[I 2026-05-20 21:32:16,746] Trial 6 finished with value: 0.21739130434782608 and parameters: {'C': 21.74429287024494, 'gamma': 42.49527643196996, 'kernel': 'poly'}. Best is trial 0 with value: 0.4583333333333333.
[I 2026-05-20 21:32:34,662] Trial 5 finished with value: 0.0 and parameters: {'C': 23.91000491267728, 'gamma': 36.28657985003353, 'kernel': 'rbf'}. Best is trial 0 with value: 0.4583333333333333.
[I 2026-05-20 21:32:52,733] Trial 8 finished with value: 0.46808510638297873 and parameters: {'C': 35.090090145618966, 'gamma': 27.94796889048917, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:33:06,505] Trial 7 finished with value: 0.21739130434782608 and parameters: {'C': 22.433351582937803, 'gamma': 6.254518661497969, 'kernel': 'poly'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:33:24,371] Trial 10 finished with value: 0.45454545454545453 and parameters: {'C': 4.80301487219111, 'gamma': 30.933214988488142, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:33:41,039] Trial 11 finished with value: 0.45454545454545453 and parameters: {'C': 47.33767634868014, 'gamma': 16.79185917709883, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:33:59,090] Trial 12 finished with value: 0.46808510638297873 and parameters: {'C': 36.68176562480424, 'gamma': 20.576138291173447, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:34:15,792] Trial 13 finished with value: 0.46808510638297873 and parameters: {'C': 33.878918705436774, 'gamma': 19.657799479424167, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:34:21,567] Trial 9 finished with value: 0.16 and parameters: {'C': 26.143914984724564, 'gamma': 0.34505892872862903, 'kernel': 'poly'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:34:32,425] Trial 14 finished with value: 0.4583333333333333 and parameters: {'C': 49.053198983300355, 'gamma': 20.501638427320984, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:34:39,460] Trial 15 finished with value: 0.46808510638297873 and parameters: {'C': 49.30488949847627, 'gamma': 22.099726246115814, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:35:44,164] Trial 17 finished with value: 0.08695652173913043 and parameters: {'C': 33.95131601563738, 'gamma': 13.487244380170186, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:36:17,167] Trial 16 finished with value: 0.0 and parameters: {'C': 34.13656982440816, 'gamma': 26.285419437297573, 'kernel': 'rbf'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:36:33,864] Trial 19 finished with value: 0.46808510638297873 and parameters: {'C': 39.04476171891309, 'gamma': 12.757605053415046, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:36:51,757] Trial 20 finished with value: 0.46808510638297873 and parameters: {'C': 30.0559756684657, 'gamma': 40.40843054998746, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:37:27,655] Trial 18 finished with value: 0.0 and parameters: {'C': 41.40786259408789, 'gamma': 26.997867691210686, 'kernel': 'rbf'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:37:45,407] Trial 22 finished with value: 0.46808510638297873 and parameters: {'C': 33.71979336624849, 'gamma': 18.402470379102063, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:38:01,740] Trial 23 finished with value: 0.45454545454545453 and parameters: {'C': 43.81588677438836, 'gamma': 24.139640721701124, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:38:18,149] Trial 24 finished with value: 0.46808510638297873 and parameters: {'C': 30.491555282821444, 'gamma': 16.887377112290533, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:38:31,719] Trial 21 finished with value: 0.0 and parameters: {'C': 13.400961918818975, 'gamma': 26.540575269352242, 'kernel': 'rbf'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:39:24,213] Trial 25 finished with value: 0.03278688524590164 and parameters: {'C': 35.4605395163757, 'gamma': 22.929086013893645, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:39:34,394] Trial 26 finished with value: 0.10526315789473684 and parameters: {'C': 29.62123769929358, 'gamma': 12.29880807188504, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:39:40,393] Trial 27 finished with value: 0.46808510638297873 and parameters: {'C': 27.947105004614336, 'gamma': 11.761471758185566, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:39:50,717] Trial 28 finished with value: 0.46808510638297873 and parameters: {'C': 37.40028995071597, 'gamma': 31.949192832224764, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:39:58,002] Trial 29 finished with value: 0.45454545454545453 and parameters: {'C': 44.56283691882455, 'gamma': 31.71650339356244, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:40:07,111] Trial 30 finished with value: 0.46153846153846156 and parameters: {'C': 17.614783838693477, 'gamma': 38.99887190398262, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:40:14,352] Trial 31 finished with value: 0.45454545454545453 and parameters: {'C': 43.22496106922585, 'gamma': 19.984674870351864, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:40:24,109] Trial 32 finished with value: 0.45454545454545453 and parameters: {'C': 42.231150014861235, 'gamma': 21.95514433846928, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:40:30,808] Trial 33 finished with value: 0.4583333333333333 and parameters: {'C': 41.30207385500013, 'gamma': 21.876299687646426, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:40:40,580] Trial 34 finished with value: 0.46808510638297873 and parameters: {'C': 37.86031388220744, 'gamma': 23.44849142711462, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:40:47,160] Trial 35 finished with value: 0.45454545454545453 and parameters: {'C': 46.90507974723231, 'gamma': 16.876609919541757, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:40:56,949] Trial 36 finished with value: 0.46808510638297873 and parameters: {'C': 49.91880561090933, 'gamma': 15.906301768550406, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:41:04,993] Trial 37 finished with value: 0.46808510638297873 and parameters: {'C': 31.58805780837275, 'gamma': 29.344880362067453, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:41:12,926] Trial 38 finished with value: 0.46808510638297873 and parameters: {'C': 31.243825515599774, 'gamma': 28.212663760073877, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:41:52,902] Trial 39 finished with value: 0.21739130434782608 and parameters: {'C': 36.30049360204058, 'gamma': 34.923986543415396, 'kernel': 'poly'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:42:02,104] Trial 40 finished with value: 0.21739130434782608 and parameters: {'C': 18.20173860788607, 'gamma': 49.0362718662782, 'kernel': 'poly'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:42:18,382] Trial 42 finished with value: 0.4583333333333333 and parameters: {'C': 39.503004991056926, 'gamma': 9.88906375477438, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:42:35,052] Trial 43 finished with value: 0.46808510638297873 and parameters: {'C': 38.912905019018055, 'gamma': 5.6173240631888675, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:42:46,369] Trial 41 finished with value: 0.23076923076923078 and parameters: {'C': 20.294597807392396, 'gamma': 6.863585690545651, 'kernel': 'sigmoid'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:42:51,810] Trial 44 finished with value: 0.45454545454545453 and parameters: {'C': 46.317934005957966, 'gamma': 14.896760861163848, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:43:04,138] Trial 45 finished with value: 0.45454545454545453 and parameters: {'C': 45.95943007509679, 'gamma': 14.712924216005488, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:44:32,153] Trial 46 finished with value: 0.0 and parameters: {'C': 39.545433629297186, 'gamma': 20.41446203008439, 'kernel': 'rbf'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:44:45,196] Trial 47 finished with value: 0.0 and parameters: {'C': 25.087091740078073, 'gamma': 18.92740013221707, 'kernel': 'rbf'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:44:49,397] Trial 48 finished with value: 0.46808510638297873 and parameters: {'C': 24.723827728798504, 'gamma': 18.743362286995918, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:45:02,513] Trial 49 finished with value: 0.4166666666666667 and parameters: {'C': 1.4090016622648704, 'gamma': 25.056502313409627, 'kernel': 'linear'}. Best is trial 8 with value: 0.46808510638297873.
[I 2026-05-20 21:45:02,515] A new study created in memory with name: no-name-f019c1d7-7b42-442a-999b-32b2c90e554e

Best trial for Service Complaint: F1 score= 0.4681
Best hyperparameters: {'C': 35.090090145618966, 'gamma': 27.94796889048917, 'kernel': 'linear'}

[I 2026-05-20 21:46:06,275] Trial 1 finished with value: 0.4444444444444444 and parameters: {'C': 31.563160687561954, 'gamma': 46.96740785954416, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.4444444444444444.
[I 2026-05-20 21:46:19,059] Trial 2 finished with value: 0.782608695652174 and parameters: {'C': 44.11992449424033, 'gamma': 47.99142365865519, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:46:21,015] Trial 0 finished with value: 0.782608695652174 and parameters: {'C': 4.36296652598019, 'gamma': 18.84650709782848, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:46:28,989] Trial 3 finished with value: 0.782608695652174 and parameters: {'C': 37.648567514396866, 'gamma': 0.8671845353451244, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:46:34,621] Trial 4 finished with value: 0.782608695652174 and parameters: {'C': 3.820048796823795, 'gamma': 21.459313789564543, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:46:42,073] Trial 5 finished with value: 0.782608695652174 and parameters: {'C': 13.702207783251694, 'gamma': 38.35217258716299, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:46:46,975] Trial 6 finished with value: 0.782608695652174 and parameters: {'C': 14.00329234724924, 'gamma': 22.99316224743723, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:46:55,558] Trial 7 finished with value: 0.75 and parameters: {'C': 1.8732367579476346, 'gamma': 11.296707137658261, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:47:00,486] Trial 8 finished with value: 0.75 and parameters: {'C': 2.420705916659736, 'gamma': 45.259910822362606, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:47:08,447] Trial 9 finished with value: 0.782608695652174 and parameters: {'C': 31.368056410725913, 'gamma': 43.41040663051521, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:48:20,747] Trial 10 finished with value: 0.782608695652174 and parameters: {'C': 9.83384569102097, 'gamma': 49.66981545936419, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:48:28,541] Trial 11 finished with value: 0.782608695652174 and parameters: {'C': 17.226961562812548, 'gamma': 31.613243055173633, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:49:39,364] Trial 12 finished with value: 0.782608695652174 and parameters: {'C': 49.64578649728305, 'gamma': 31.5767423553295, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:50:11,308] Trial 13 finished with value: 0.3333333333333333 and parameters: {'C': 49.8747630067075, 'gamma': 16.75634268984613, 'kernel': 'rbf'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:51:23,504] Trial 14 finished with value: 0.35294117647058826 and parameters: {'C': 42.845725616240244, 'gamma': 15.133755212266776, 'kernel': 'rbf'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:51:51,132] Trial 15 finished with value: 0.6086956521739131 and parameters: {'C': 22.276821892664422, 'gamma': 9.727489770050056, 'kernel': 'rbf'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:52:45,862] Trial 16 finished with value: 0.782608695652174 and parameters: {'C': 25.589544755558265, 'gamma': 7.414638943082913, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:53:10,588] Trial 17 finished with value: 0.782608695652174 and parameters: {'C': 26.403874985308256, 'gamma': 31.263413860880704, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:54:03,831] Trial 18 finished with value: 0.782608695652174 and parameters: {'C': 40.86392466327163, 'gamma': 29.794915925477028, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:54:14,180] Trial 19 finished with value: 0.46153846153846156 and parameters: {'C': 41.15910838649283, 'gamma': 37.95155455528706, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:54:27,164] Trial 21 finished with value: 0.782608695652174 and parameters: {'C': 8.11879560629632, 'gamma': 26.61478421540193, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:54:36,525] Trial 22 finished with value: 0.48484848484848486 and parameters: {'C': 35.95508188957285, 'gamma': 1.6951480643089774, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:54:49,732] Trial 23 finished with value: 0.782608695652174 and parameters: {'C': 45.806678035141076, 'gamma': 0.20573252286600396, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:55:07,311] Trial 20 finished with value: 0.46153846153846156 and parameters: {'C': 8.218967513721601, 'gamma': 38.13173187275774, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:55:21,706] Trial 24 finished with value: 0.23076923076923078 and parameters: {'C': 35.9679374280649, 'gamma': 5.940918121829969, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:55:36,553] Trial 25 finished with value: 0.2127659574468085 and parameters: {'C': 36.31933138165292, 'gamma': 5.060989229506683, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:56:17,140] Trial 26 finished with value: 0.6153846153846154 and parameters: {'C': 37.35061592522828, 'gamma': 18.48300720721287, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:56:57,238] Trial 27 finished with value: 0.782608695652174 and parameters: {'C': 31.294263979087, 'gamma': 17.641892918341828, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:57:37,464] Trial 28 finished with value: 0.782608695652174 and parameters: {'C': 31.405814881796594, 'gamma': 12.797955062187873, 'kernel': 'poly'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:58:41,278] Trial 29 finished with value: 0.5454545454545454 and parameters: {'C': 20.605717527060364, 'gamma': 11.66722439279065, 'kernel': 'rbf'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:58:54,477] Trial 31 finished with value: 0.782608695652174 and parameters: {'C': 46.11303163815387, 'gamma': 34.5920801809706, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:59:07,528] Trial 32 finished with value: 0.782608695652174 and parameters: {'C': 5.516180086675231, 'gamma': 22.021539996277934, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:59:20,187] Trial 33 finished with value: 0.782608695652174 and parameters: {'C': 11.98648002571309, 'gamma': 20.434779736740886, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:59:21,194] Trial 30 finished with value: 0.25 and parameters: {'C': 21.94929495323172, 'gamma': 42.080115909088114, 'kernel': 'rbf'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:59:43,290] Trial 34 finished with value: 0.75 and parameters: {'C': 0.2977399975678381, 'gamma': 41.58181564061105, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 21:59:56,891] Trial 36 finished with value: 0.782608695652174 and parameters: {'C': 3.3089737678718114, 'gamma': 25.01181748692338, 'kernel': 'linear'}. Best is trial 2 with value: 0.782608695652174.
[I 2026-05-20 22:00:03,531] Trial 35 finished with value: 0.8148148148148148 and parameters: {'C': 0.08594042122857681, 'gamma': 25.74758053593542, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:00:09,949] Trial 37 finished with value: 0.782608695652174 and parameters: {'C': 15.684236668127713, 'gamma': 27.55688415659686, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:00:16,301] Trial 38 finished with value: 0.782608695652174 and parameters: {'C': 5.380363476076854, 'gamma': 28.45067326470675, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:00:22,878] Trial 39 finished with value: 0.782608695652174 and parameters: {'C': 6.07198294246714, 'gamma': 48.19960903932557, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:00:29,135] Trial 40 finished with value: 0.782608695652174 and parameters: {'C': 29.352434799244982, 'gamma': 49.95997789718902, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:00:47,097] Trial 42 finished with value: 0.75 and parameters: {'C': 0.5902428443248104, 'gamma': 23.2628980669356, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:01:00,149] Trial 43 finished with value: 0.782608695652174 and parameters: {'C': 12.15229854804144, 'gamma': 15.1175877970211, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:01:13,291] Trial 44 finished with value: 0.782608695652174 and parameters: {'C': 3.416936838170166, 'gamma': 34.92579940105561, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:01:27,479] Trial 41 finished with value: 0.4444444444444444 and parameters: {'C': 0.2643682404315708, 'gamma': 45.45439445776822, 'kernel': 'sigmoid'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:02:32,748] Trial 45 finished with value: 0.782608695652174 and parameters: {'C': 46.61272721393529, 'gamma': 20.90338926918607, 'kernel': 'poly'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:02:43,581] Trial 46 finished with value: 0.782608695652174 and parameters: {'C': 45.90592968108742, 'gamma': 20.279383244619332, 'kernel': 'poly'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:02:45,119] Trial 47 finished with value: 0.782608695652174 and parameters: {'C': 9.346527676750625, 'gamma': 14.137295002499263, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:02:56,664] Trial 48 finished with value: 0.782608695652174 and parameters: {'C': 39.564365721065435, 'gamma': 8.662433630324912, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:02:57,407] Trial 49 finished with value: 0.782608695652174 and parameters: {'C': 40.22715798486273, 'gamma': 8.961278594427666, 'kernel': 'linear'}. Best is trial 35 with value: 0.8148148148148148.
[I 2026-05-20 22:02:57,409] A new study created in memory with name: no-name-2ca37945-81b5-418c-89af-f83ca609c8e1

Best trial for Social Services: F1 score= 0.8148
Best hyperparameters: {'C': 0.08594042122857681, 'gamma': 25.74758053593542, 'kernel': 'linear'}

[I 2026-05-20 22:04:24,499] Trial 1 finished with value: 0.5882352941176471 and parameters: {'C': 39.63176741911121, 'gamma': 20.77117145062501, 'kernel': 'poly'}. Best is trial 1 with value: 0.5882352941176471.
[I 2026-05-20 22:04:42,004] Trial 0 finished with value: 0.3333333333333333 and parameters: {'C': 14.719738534215915, 'gamma': 24.085549347074267, 'kernel': 'rbf'}. Best is trial 1 with value: 0.5882352941176471.
[I 2026-05-20 22:05:07,780] Trial 3 finished with value: 0.6388888888888888 and parameters: {'C': 41.02652275262337, 'gamma': 7.419887535533878, 'kernel': 'linear'}. Best is trial 3 with value: 0.6388888888888888.
[I 2026-05-20 22:05:42,186] Trial 2 finished with value: 0.11469534050179211 and parameters: {'C': 42.51948498619397, 'gamma': 25.670087744289994, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.6388888888888888.
[I 2026-05-20 22:06:23,555] Trial 4 finished with value: 0.10914927768860354 and parameters: {'C': 0.8799124659174625, 'gamma': 19.057288609885426, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.6388888888888888.
[I 2026-05-20 22:06:50,979] Trial 6 finished with value: 0.696969696969697 and parameters: {'C': 3.7865613604892, 'gamma': 44.3088841772399, 'kernel': 'linear'}. Best is trial 6 with value: 0.696969696969697.
[I 2026-05-20 22:07:23,894] Trial 5 finished with value: 0.25 and parameters: {'C': 11.919054632701267, 'gamma': 26.875483799989937, 'kernel': 'rbf'}. Best is trial 6 with value: 0.696969696969697.
[I 2026-05-20 22:08:20,485] Trial 7 finished with value: 0.5882352941176471 and parameters: {'C': 47.5772778241548, 'gamma': 7.857165856700025, 'kernel': 'poly'}. Best is trial 6 with value: 0.696969696969697.
[I 2026-05-20 22:08:57,849] Trial 8 finished with value: 0.5882352941176471 and parameters: {'C': 31.00895850534204, 'gamma': 32.40849403487746, 'kernel': 'poly'}. Best is trial 6 with value: 0.696969696969697.
[I 2026-05-20 22:10:03,972] Trial 9 finished with value: 0.6545454545454545 and parameters: {'C': 4.825832829807105, 'gamma': 5.038788457008469, 'kernel': 'rbf'}. Best is trial 6 with value: 0.696969696969697.
[I 2026-05-20 22:10:28,027] Trial 10 finished with value: 0.5882352941176471 and parameters: {'C': 24.782315791898526, 'gamma': 22.29897851126418, 'kernel': 'poly'}. Best is trial 6 with value: 0.696969696969697.
[I 2026-05-20 22:10:30,024] Trial 11 finished with value: 0.6428571428571429 and parameters: {'C': 23.053283254926704, 'gamma': 48.76755908873555, 'kernel': 'linear'}. Best is trial 6 with value: 0.696969696969697.
[I 2026-05-20 22:10:56,585] Trial 12 finished with value: 0.7076923076923077 and parameters: {'C': 2.647355701022743, 'gamma': 48.25319301657141, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:11:07,382] Trial 13 finished with value: 0.6774193548387096 and parameters: {'C': 1.0567576187139949, 'gamma': 48.71404321692205, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:11:22,439] Trial 14 finished with value: 0.6756756756756757 and parameters: {'C': 9.893796922810619, 'gamma': 49.240744195943805, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:11:33,257] Trial 15 finished with value: 0.6756756756756757 and parameters: {'C': 10.45563372056682, 'gamma': 40.26813397708921, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:11:47,913] Trial 16 finished with value: 0.647887323943662 and parameters: {'C': 17.97152409756665, 'gamma': 40.2573452195825, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:11:59,154] Trial 17 finished with value: 0.647887323943662 and parameters: {'C': 18.512142376983757, 'gamma': 40.0949672922204, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:12:14,112] Trial 18 finished with value: 0.6388888888888888 and parameters: {'C': 32.71181083755481, 'gamma': 40.61932266485266, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:12:25,224] Trial 19 finished with value: 0.6956521739130435 and parameters: {'C': 5.851461446509076, 'gamma': 35.17890367260466, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:13:31,119] Trial 20 finished with value: 0.11262135922330097 and parameters: {'C': 6.161371714799221, 'gamma': 33.404579314089084, 'kernel': 'sigmoid'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:13:43,189] Trial 21 finished with value: 0.1141732283464567 and parameters: {'C': 6.117002891522349, 'gamma': 34.838503815389316, 'kernel': 'sigmoid'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:13:57,015] Trial 22 finished with value: 0.6956521739130435 and parameters: {'C': 6.338131488892659, 'gamma': 43.31373359226838, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:14:38,744] Trial 23 finished with value: 0.6461538461538462 and parameters: {'C': 0.2812963661372758, 'gamma': 44.32340101324199, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:14:42,227] Trial 24 finished with value: 0.6666666666666666 and parameters: {'C': 0.5045571869931154, 'gamma': 44.657414750089465, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:15:03,861] Trial 25 finished with value: 0.647887323943662 and parameters: {'C': 16.533643566842358, 'gamma': 35.783434629526376, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:15:07,905] Trial 26 finished with value: 0.6575342465753424 and parameters: {'C': 13.631047822033914, 'gamma': 35.55175830687496, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:15:28,795] Trial 27 finished with value: 0.6666666666666666 and parameters: {'C': 10.852309872520802, 'gamma': 15.129704178257267, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:15:33,647] Trial 28 finished with value: 0.6666666666666666 and parameters: {'C': 8.922989089034811, 'gamma': 29.928422445576516, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:17:10,487] Trial 29 finished with value: 0.20512820512820512 and parameters: {'C': 4.240502480872674, 'gamma': 30.998977808579546, 'kernel': 'rbf'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:17:15,890] Trial 30 finished with value: 0.10967741935483871 and parameters: {'C': 3.636878587264681, 'gamma': 44.863586204520736, 'kernel': 'rbf'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:17:41,605] Trial 32 finished with value: 0.676056338028169 and parameters: {'C': 7.721564116413212, 'gamma': 43.286481170572976, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:18:06,727] Trial 33 finished with value: 0.6551724137931034 and parameters: {'C': 14.261382838913962, 'gamma': 38.367849388755495, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:18:31,161] Trial 34 finished with value: 0.6428571428571429 and parameters: {'C': 21.129324129646378, 'gamma': 46.13887725501875, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:18:53,958] Trial 31 finished with value: 0.10967741935483871 and parameters: {'C': 14.747558215119636, 'gamma': 45.151832169714496, 'kernel': 'rbf'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:18:59,359] Trial 35 finished with value: 0.7076923076923077 and parameters: {'C': 3.2648071578404245, 'gamma': 37.47158544077888, 'kernel': 'linear'}. Best is trial 12 with value: 0.7076923076923077.
[I 2026-05-20 22:19:20,921] Trial 36 finished with value: 0.7164179104477612 and parameters: {'C': 3.944601563392854, 'gamma': 41.551652033569944, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:20:17,556] Trial 37 finished with value: 0.11355311355311355 and parameters: {'C': 3.071416412699339, 'gamma': 27.92658949741566, 'kernel': 'sigmoid'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:20:38,688] Trial 38 finished with value: 0.11670020120724346 and parameters: {'C': 3.0840316990634977, 'gamma': 38.43115993343173, 'kernel': 'sigmoid'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:21:46,533] Trial 39 finished with value: 0.5882352941176471 and parameters: {'C': 3.247747515755373, 'gamma': 38.19724733057545, 'kernel': 'poly'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:22:08,390] Trial 40 finished with value: 0.5882352941176471 and parameters: {'C': 29.312634048105807, 'gamma': 47.26086901606803, 'kernel': 'poly'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:22:33,523] Trial 42 finished with value: 0.676923076923077 and parameters: {'C': 7.171323678668657, 'gamma': 41.594475497728325, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:22:59,540] Trial 43 finished with value: 0.6388888888888888 and parameters: {'C': 38.02431699666096, 'gamma': 36.87440846127508, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:23:19,123] Trial 41 finished with value: 0.5882352941176471 and parameters: {'C': 37.133237199439996, 'gamma': 16.432954153110337, 'kernel': 'poly'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:23:24,292] Trial 44 finished with value: 0.6666666666666666 and parameters: {'C': 12.025474753347554, 'gamma': 49.96100226732, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:23:44,719] Trial 45 finished with value: 0.6666666666666666 and parameters: {'C': 12.332867311850778, 'gamma': 23.895055336391884, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:23:50,276] Trial 46 finished with value: 0.6666666666666666 and parameters: {'C': 8.763702951485858, 'gamma': 47.26521307663023, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:24:14,723] Trial 47 finished with value: 0.696969696969697 and parameters: {'C': 1.9593831654486822, 'gamma': 47.01928453683081, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:24:22,457] Trial 48 finished with value: 0.6885245901639344 and parameters: {'C': 1.8006416505823721, 'gamma': 42.48273445604209, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:24:37,530] Trial 49 finished with value: 0.6885245901639344 and parameters: {'C': 1.8534500512714032, 'gamma': 42.13569335863436, 'kernel': 'linear'}. Best is trial 36 with value: 0.7164179104477612.
[I 2026-05-20 22:24:37,532] A new study created in memory with name: no-name-de660004-31c8-4892-b22d-057e4a45d9f8

Best trial for Technical/IT: F1 score= 0.7164
Best hyperparameters: {'C': 3.944601563392854, 'gamma': 41.551652033569944, 'kernel': 'linear'}

[I 2026-05-20 22:26:21,902] Trial 0 finished with value: 0.1360759493670886 and parameters: {'C': 16.6974875660596, 'gamma': 35.77221039288694, 'kernel': 'rbf'}. Best is trial 0 with value: 0.1360759493670886.
[I 2026-05-20 22:26:22,225] Trial 1 finished with value: 0.1360759493670886 and parameters: {'C': 22.440290837008472, 'gamma': 34.91513648885286, 'kernel': 'rbf'}. Best is trial 0 with value: 0.1360759493670886.
[I 2026-05-20 22:26:50,901] Trial 3 finished with value: 0.32857142857142857 and parameters: {'C': 28.50239586336966, 'gamma': 38.20214746435896, 'kernel': 'linear'}. Best is trial 3 with value: 0.32857142857142857.
[I 2026-05-20 22:27:06,056] Trial 2 finished with value: 0.22535211267605634 and parameters: {'C': 5.2112786213800595, 'gamma': 3.759022294939943, 'kernel': 'sigmoid'}. Best is trial 3 with value: 0.32857142857142857.
[I 2026-05-20 22:27:22,917] Trial 4 finished with value: 0.36619718309859156 and parameters: {'C': 3.6191266867221774, 'gamma': 30.812906413181643, 'kernel': 'linear'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:27:35,343] Trial 5 finished with value: 0.32857142857142857 and parameters: {'C': 30.031225544291818, 'gamma': 39.35705234268176, 'kernel': 'linear'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:28:03,565] Trial 7 finished with value: 0.3492063492063492 and parameters: {'C': 11.983033838497759, 'gamma': 41.56530965065816, 'kernel': 'linear'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:28:31,646] Trial 8 finished with value: 0.3240223463687151 and parameters: {'C': 17.381996814078, 'gamma': 16.720314608415766, 'kernel': 'linear'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:28:35,756] Trial 6 finished with value: 0.14956521739130435 and parameters: {'C': 3.8488425950155505, 'gamma': 41.65803845919391, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:29:40,700] Trial 9 finished with value: 0.1532976827094474 and parameters: {'C': 39.15267978773178, 'gamma': 32.07839907413479, 'kernel': 'sigmoid'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:30:18,310] Trial 10 finished with value: 0.1360759493670886 and parameters: {'C': 8.539846412133647, 'gamma': 31.279890829713526, 'kernel': 'rbf'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:31:10,879] Trial 11 finished with value: 0.25136612021857924 and parameters: {'C': 48.868861452668, 'gamma': 21.6437850416726, 'kernel': 'poly'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:31:49,077] Trial 12 finished with value: 0.25136612021857924 and parameters: {'C': 0.6678786222479705, 'gamma': 20.71868216066568, 'kernel': 'poly'}. Best is trial 4 with value: 0.36619718309859156.
[I 2026-05-20 22:32:15,733] Trial 13 finished with value: 0.391304347826087 and parameters: {'C': 0.22616365417535178, 'gamma': 48.104706633582026, 'kernel': 'linear'}. Best is trial 13 with value: 0.391304347826087.
[I 2026-05-20 22:32:17,630] Trial 14 finished with value: 0.3333333333333333 and parameters: {'C': 12.70598674733074, 'gamma': 49.172867842950446, 'kernel': 'linear'}. Best is trial 13 with value: 0.391304347826087.
[I 2026-05-20 22:32:50,441] Trial 16 finished with value: 0.36363636363636365 and parameters: {'C': 3.522462552407578, 'gamma': 49.64827384829361, 'kernel': 'linear'}. Best is trial 13 with value: 0.391304347826087.
[I 2026-05-20 22:33:14,509] Trial 15 finished with value: 0.41818181818181815 and parameters: {'C': 0.3567844706058591, 'gamma': 49.00329419478095, 'kernel': 'linear'}. Best is trial 15 with value: 0.41818181818181815.
[I 2026-05-20 22:33:37,820] Trial 17 finished with value: 0.39285714285714285 and parameters: {'C': 0.7480114469501942, 'gamma': 7.439374110589537, 'kernel': 'linear'}. Best is trial 15 with value: 0.41818181818181815.
[I 2026-05-20 22:34:28,118] Trial 18 finished with value: 0.42 and parameters: {'C': 0.11917930838260272, 'gamma': 45.68069745689419, 'kernel': 'linear'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:35:08,251] Trial 19 finished with value: 0.25136612021857924 and parameters: {'C': 36.773220494436856, 'gamma': 2.647278898467671, 'kernel': 'poly'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:35:37,144] Trial 21 finished with value: 0.35398230088495575 and parameters: {'C': 9.270864673801317, 'gamma': 44.27129289959257, 'kernel': 'linear'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:35:59,776] Trial 20 finished with value: 0.25136612021857924 and parameters: {'C': 9.839219070434885, 'gamma': 44.208653470002666, 'kernel': 'poly'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:36:07,888] Trial 22 finished with value: 0.35398230088495575 and parameters: {'C': 8.21399194667922, 'gamma': 10.649525625111897, 'kernel': 'linear'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:36:28,798] Trial 23 finished with value: 0.336 and parameters: {'C': 17.019245997874492, 'gamma': 10.26667855406156, 'kernel': 'linear'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:36:36,627] Trial 24 finished with value: 0.3333333333333333 and parameters: {'C': 16.201847604033176, 'gamma': 9.448513413787792, 'kernel': 'linear'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:37:14,873] Trial 25 finished with value: 0.39316239316239315 and parameters: {'C': 0.8147389624172936, 'gamma': 11.880482635554994, 'kernel': 'linear'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:37:45,281] Trial 27 finished with value: 0.359375 and parameters: {'C': 5.9400955971063585, 'gamma': 26.562624408522108, 'kernel': 'linear'}. Best is trial 18 with value: 0.42.
[I 2026-05-20 22:38:00,005] Trial 26 finished with value: 0.42105263157894735 and parameters: {'C': 0.06539329887378409, 'gamma': 23.445021409188733, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:39:29,863] Trial 28 finished with value: 0.13629160063391443 and parameters: {'C': 21.69901682357801, 'gamma': 15.5377381084082, 'kernel': 'rbf'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:39:46,854] Trial 29 finished with value: 0.1360759493670886 and parameters: {'C': 12.711067682740724, 'gamma': 26.04246094019871, 'kernel': 'rbf'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:40:32,660] Trial 30 finished with value: 0.16602316602316602 and parameters: {'C': 15.003935457210575, 'gamma': 22.733037905752354, 'kernel': 'sigmoid'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:41:01,233] Trial 31 finished with value: 0.15034965034965034 and parameters: {'C': 6.167206522960575, 'gamma': 44.641541670415734, 'kernel': 'sigmoid'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:41:44,826] Trial 32 finished with value: 0.41304347826086957 and parameters: {'C': 0.16596119570461607, 'gamma': 15.304642904575507, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:41:52,941] Trial 33 finished with value: 0.4067796610169492 and parameters: {'C': 0.5523297264164388, 'gamma': 15.702328312244935, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:42:18,231] Trial 34 finished with value: 0.368 and parameters: {'C': 2.921756900190631, 'gamma': 14.658358235866006, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:42:23,177] Trial 35 finished with value: 0.35398230088495575 and parameters: {'C': 6.434499201575309, 'gamma': 18.926927007538893, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:42:49,636] Trial 36 finished with value: 0.36507936507936506 and parameters: {'C': 5.516712781558899, 'gamma': 36.515435868217864, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:42:51,848] Trial 37 finished with value: 0.3240223463687151 and parameters: {'C': 20.09625403295252, 'gamma': 28.56054814541833, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:43:17,884] Trial 38 finished with value: 0.3333333333333333 and parameters: {'C': 20.344106805071902, 'gamma': 34.20946145664627, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:44:38,650] Trial 39 finished with value: 0.1360759493670886 and parameters: {'C': 27.749659825447832, 'gamma': 33.78657384265706, 'kernel': 'rbf'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:45:03,962] Trial 40 finished with value: 0.20098039215686275 and parameters: {'C': 25.052569924270564, 'gamma': 5.268451926015093, 'kernel': 'rbf'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:45:14,040] Trial 41 finished with value: 0.368 and parameters: {'C': 3.262329026505908, 'gamma': 5.881264992331584, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:45:36,663] Trial 42 finished with value: 0.368 and parameters: {'C': 3.1885449095957408, 'gamma': 0.09448205850729607, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:45:47,065] Trial 43 finished with value: 0.368 and parameters: {'C': 2.989273055382057, 'gamma': 18.140475541980113, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:46:42,018] Trial 45 finished with value: 0.40707964601769914 and parameters: {'C': 0.4683447792293599, 'gamma': 13.717531725528469, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:47:08,669] Trial 44 finished with value: 0.3404255319148936 and parameters: {'C': 0.034442728211444534, 'gamma': 18.238661400644013, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:47:43,082] Trial 46 finished with value: 0.15717092337917485 and parameters: {'C': 7.593433709270924, 'gamma': 13.508402126808893, 'kernel': 'sigmoid'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:48:14,362] Trial 48 finished with value: 0.36363636363636365 and parameters: {'C': 4.469425001489863, 'gamma': 46.27546900601923, 'kernel': 'linear'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:48:25,515] Trial 47 finished with value: 0.14502529510961215 and parameters: {'C': 7.630583242302662, 'gamma': 46.68462863971266, 'kernel': 'sigmoid'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:49:16,714] Trial 49 finished with value: 0.25136612021857924 and parameters: {'C': 10.649918545389674, 'gamma': 23.252878280154793, 'kernel': 'poly'}. Best is trial 26 with value: 0.42105263157894735.
[I 2026-05-20 22:49:16,716] A new study created in memory with name: no-name-e324d2eb-22dd-44a6-9f9c-30f67719cc57

Best trial for Urgent: F1 score= 0.4211
Best hyperparameters: {'C': 0.06539329887378409, 'gamma': 23.445021409188733, 'kernel': 'linear'}

[I 2026-05-20 22:49:30,999] Trial 1 finished with value: 0.7346938775510204 and parameters: {'C': 29.582984827850282, 'gamma': 0.49318600629915804, 'kernel': 'sigmoid'}. Best is trial 1 with value: 0.7346938775510204.
[I 2026-05-20 22:49:47,075] Trial 2 finished with value: 0.7567567567567568 and parameters: {'C': 27.325184116789, 'gamma': 3.893549582123168, 'kernel': 'linear'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:50:04,347] Trial 3 finished with value: 0.7567567567567568 and parameters: {'C': 45.76275667388636, 'gamma': 46.338010005144874, 'kernel': 'linear'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:50:20,649] Trial 4 finished with value: 0.7567567567567568 and parameters: {'C': 44.98214112944153, 'gamma': 24.467457621321458, 'kernel': 'linear'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:51:02,277] Trial 0 finished with value: 0.08695652173913043 and parameters: {'C': 22.251287913357466, 'gamma': 41.0819004484208, 'kernel': 'rbf'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:51:43,188] Trial 5 finished with value: 0.5142857142857142 and parameters: {'C': 45.08926169868139, 'gamma': 8.8675358353964, 'kernel': 'poly'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:51:53,402] Trial 6 finished with value: 0.41025641025641024 and parameters: {'C': 31.795287097919786, 'gamma': 16.643467722517684, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:52:40,937] Trial 7 finished with value: 0.4090909090909091 and parameters: {'C': 22.802246261693185, 'gamma': 29.093398528453722, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:52:49,162] Trial 8 finished with value: 0.42105263157894735 and parameters: {'C': 13.666990884387069, 'gamma': 22.23995524229786, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:53:41,153] Trial 9 finished with value: 0.28125 and parameters: {'C': 35.17381597284039, 'gamma': 39.980882560465965, 'kernel': 'sigmoid'}. Best is trial 2 with value: 0.7567567567567568.
[I 2026-05-20 22:54:07,178] Trial 11 finished with value: 0.8421052631578947 and parameters: {'C': 0.6864276039190074, 'gamma': 0.3245467035524947, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:54:13,007] Trial 10 finished with value: 0.5142857142857142 and parameters: {'C': 23.316786272468995, 'gamma': 28.554726254476375, 'kernel': 'poly'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:54:23,930] Trial 12 finished with value: 0.8292682926829268 and parameters: {'C': 3.442518132571859, 'gamma': 0.2518526976444111, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:54:44,359] Trial 14 finished with value: 0.8292682926829268 and parameters: {'C': 1.5867228510954305, 'gamma': 10.73567148609193, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:55:03,007] Trial 15 finished with value: 0.8292682926829268 and parameters: {'C': 1.9899579931322826, 'gamma': 8.426137576309191, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:55:29,290] Trial 13 finished with value: 0.6666666666666666 and parameters: {'C': 0.04066443011947041, 'gamma': 0.7346698495498876, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:56:47,189] Trial 16 finished with value: 0.24 and parameters: {'C': 9.865688185706425, 'gamma': 15.070756755419561, 'kernel': 'rbf'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:57:03,629] Trial 18 finished with value: 0.7906976744186046 and parameters: {'C': 9.308690656112496, 'gamma': 5.58264996702713, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:57:13,325] Trial 17 finished with value: 0.24 and parameters: {'C': 7.308907063859834, 'gamma': 15.888426016107344, 'kernel': 'rbf'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:57:20,265] Trial 19 finished with value: 0.7567567567567568 and parameters: {'C': 16.18872160441928, 'gamma': 15.425373518570053, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:57:29,970] Trial 20 finished with value: 0.7567567567567568 and parameters: {'C': 16.868147975278962, 'gamma': 12.638544924709269, 'kernel': 'linear'}. Best is trial 11 with value: 0.8421052631578947.
[I 2026-05-20 22:57:46,703] Trial 22 finished with value: 0.85 and parameters: {'C': 4.564465823137762, 'gamma': 0.07958371075691811, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:58:04,577] Trial 23 finished with value: 0.8292682926829268 and parameters: {'C': 5.567826916028777, 'gamma': 4.550748675024531, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:58:42,054] Trial 21 finished with value: 0.5142857142857142 and parameters: {'C': 17.143337428265664, 'gamma': 20.53213616441589, 'kernel': 'poly'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:58:59,233] Trial 25 finished with value: 0.85 and parameters: {'C': 4.2910694262424665, 'gamma': 0.066481712072609, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:59:15,888] Trial 26 finished with value: 0.7567567567567568 and parameters: {'C': 12.079961379144462, 'gamma': 5.688085956899915, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:59:27,678] Trial 24 finished with value: 0.42857142857142855 and parameters: {'C': 5.242874311985598, 'gamma': 0.441553564481449, 'kernel': 'poly'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:59:32,584] Trial 27 finished with value: 0.8292682926829268 and parameters: {'C': 5.633522949120616, 'gamma': 3.783787626741261, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:59:43,946] Trial 28 finished with value: 0.8292682926829268 and parameters: {'C': 7.905650038313504, 'gamma': 7.249499563665001, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 22:59:50,346] Trial 29 finished with value: 0.7567567567567568 and parameters: {'C': 10.721793270271382, 'gamma': 8.512094117833662, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:01:29,394] Trial 30 finished with value: 0.08695652173913043 and parameters: {'C': 18.787046822542816, 'gamma': 33.628555541307804, 'kernel': 'rbf'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:01:33,947] Trial 31 finished with value: 0.08695652173913043 and parameters: {'C': 19.92335228659708, 'gamma': 35.32357988353064, 'kernel': 'rbf'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:01:46,249] Trial 32 finished with value: 0.8292682926829268 and parameters: {'C': 3.4352158349096094, 'gamma': 2.7497919151814094, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:01:52,104] Trial 33 finished with value: 0.85 and parameters: {'C': 3.052186051527209, 'gamma': 1.21583835067817, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:02:04,471] Trial 34 finished with value: 0.8292682926829268 and parameters: {'C': 3.4632419322776276, 'gamma': 0.053973760220923095, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:02:41,183] Trial 36 finished with value: 0.7555555555555555 and parameters: {'C': 0.28489250669484784, 'gamma': 3.086944246033245, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:02:50,118] Trial 35 finished with value: 0.6956521739130435 and parameters: {'C': 0.09911174364517761, 'gamma': 2.7910886747224817, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:02:59,321] Trial 37 finished with value: 0.7567567567567568 and parameters: {'C': 13.828639264464982, 'gamma': 12.154127798532521, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:03:07,195] Trial 38 finished with value: 0.7567567567567568 and parameters: {'C': 13.107178547967406, 'gamma': 9.901872749105388, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:03:16,144] Trial 39 finished with value: 0.8292682926829268 and parameters: {'C': 6.783124687320081, 'gamma': 10.495878827928761, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:03:53,743] Trial 41 finished with value: 0.39080459770114945 and parameters: {'C': 28.57937650572298, 'gamma': 6.04572798434779, 'kernel': 'sigmoid'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:04:07,919] Trial 40 finished with value: 0.19672131147540983 and parameters: {'C': 48.11891331910292, 'gamma': 48.19539568201179, 'kernel': 'sigmoid'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:04:10,607] Trial 42 finished with value: 0.85 and parameters: {'C': 4.050005596972541, 'gamma': 48.07576358578443, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:04:24,426] Trial 43 finished with value: 0.85 and parameters: {'C': 3.947479912303275, 'gamma': 2.1968808661073607, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:04:27,839] Trial 44 finished with value: 0.7567567567567568 and parameters: {'C': 42.00542755203356, 'gamma': 43.865615922518785, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:05:47,982] Trial 45 finished with value: 0.5142857142857142 and parameters: {'C': 38.13355180195141, 'gamma': 42.455623296768174, 'kernel': 'poly'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:05:53,419] Trial 46 finished with value: 0.5142857142857142 and parameters: {'C': 4.283305895253709, 'gamma': 19.528500986030476, 'kernel': 'poly'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:06:05,252] Trial 47 finished with value: 0.85 and parameters: {'C': 4.470635512265108, 'gamma': 19.210211371957772, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:06:10,185] Trial 48 finished with value: 0.7906976744186046 and parameters: {'C': 8.912403780550463, 'gamma': 30.21874837362165, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.
[I 2026-05-20 23:06:17,584] Trial 49 finished with value: 0.8095238095238095 and parameters: {'C': 8.641408853113173, 'gamma': 24.79701003450562, 'kernel': 'linear'}. Best is trial 22 with value: 0.85.

Best trial for Work/School: F1 score= 0.8500
Best hyperparameters: {'C': 4.564465823137762, 'gamma': 0.07958371075691811, 'kernel': 'linear'}

In [ ]:
models = {}
for i,label_name in enumerate(label_keep_original):
  model = SVC(**list_params[label_name],class_weight='balanced',random_state=42, probability=True, cache_size=2000)
  model.fit(x_train,y_train[:,i])
  models[label_name] = model

In [ ]:
optimal_thresholds = {}
import numpy as np
for i, label_name in enumerate(label_keep_original):
    x_val_predic = models[label_name].predict_proba(x_val)[:, 1]
    best_f1 = 0
    best_thresh = 0.5 # Default
    for threshold_val in np.arange(0.05, 0.96, 0.05):
        preds = (x_val_predic > threshold_val).astype(int)
        current_f1 = f1_score(y_val[:, i], preds)
        if current_f1 > best_f1:
            best_f1 = current_f1
            best_thresh = threshold_val
    optimal_thresholds[label_name] = best_thresh
    print(f"Optimal threshold for {label_name}: {best_thresh:.2f} (F1: {best_f1:.4f})")

Optimal threshold for Cultural/Religion: 0.55 (F1: 0.9485)
Optimal threshold for Diet/Nutrition: 0.30 (F1: 0.8952)
Optimal threshold for Emergent: 0.25 (F1: 0.4211)
Optimal threshold for Exercise: 0.60 (F1: 0.6667)
Optimal threshold for Friends & Family: 0.25 (F1: 0.5882)
Optimal threshold for Grateful Patient: 0.40 (F1: 0.5205)
Optimal threshold for Health Education: 0.20 (F1: 0.7912)
Optimal threshold for Laboratory/Testing: 0.35 (F1: 0.9301)
Optimal threshold for Medications: 0.20 (F1: 0.9091)
Optimal threshold for No Symptoms: 0.70 (F1: 0.8797)
Optimal threshold for Non-urgent: 0.05 (F1: 0.9534)
Optimal threshold for Outpatient Logistics/Scheduling: 0.30 (F1: 0.6406)
Optimal threshold for Physical: 0.40 (F1: 0.7807)
Optimal threshold for Physical Environment/Climate: 0.35 (F1: 0.8780)
Optimal threshold for Service Complaint: 0.10 (F1: 0.4681)
Optimal threshold for Social Services: 0.20 (F1: 0.8148)
Optimal threshold for Technical/IT: 0.70 (F1: 0.7164)
Optimal threshold for Urgent: 0.30 (F1: 0.4211)
Optimal threshold for Work/School: 0.35 (F1: 0.8500)

In [ ]:
import numpy as np
from sklearn.metrics import f1_score, classification_report

Y_pred_all = np.zeros(y_test.shape)

print("--- Individual Class F1 Scores ---")

for i, label_name in enumerate(label_keep_original):

    x_test_predic = models[label_name].predict_proba(x_test)[:,1]
    y_test_final = (x_test_predic > optimal_thresholds[label_name]).astype(int)
    Y_pred_all[:, i] = y_test_final

    f1 = f1_score(y_test[:, i], y_test_final)
    count = dfCombined_filtered[label_name].sum()
    print(f"  {label_name:<40} F1: {f1:.4f}   Count: {count}")

print("\n" + "="*50 + "\n")

macro_f1    = f1_score(y_test, Y_pred_all, average='macro',    zero_division=0)
micro_f1    = f1_score(y_test, Y_pred_all, average='micro',    zero_division=0)
weighted_f1 = f1_score(y_test, Y_pred_all, average='weighted', zero_division=0)

print("--- Overall Test Set Metrics ---")
print(f"  Macro F1 Score:    {macro_f1:.4f}")
print(f"  Micro F1 Score:    {micro_f1:.4f}")
print(f"  Weighted F1 Score: {weighted_f1:.4f}")
print("--- Full Classification Report ---")
print(classification_report(
    y_test,
    Y_pred_all,
    target_names=label_keep_original,
    zero_division=0
))

--- Individual Class F1 Scores ---
  Cultural/Religion                        F1: 0.8824   Count: 343
  Diet/Nutrition                           F1: 0.8421   Count: 340
  Emergent                                 F1: 0.5161   Count: 140
  Exercise                                 F1: 0.5161   Count: 131
  Friends & Family                         F1: 0.5352   Count: 291
  Grateful Patient                         F1: 0.5517   Count: 291
  Health Education                         F1: 0.8222   Count: 322
  Laboratory/Testing                       F1: 0.9610   Count: 1078
  Medications                              F1: 0.7652   Count: 418
  No Symptoms                              F1: 0.8845   Count: 1658
  Non-urgent                               F1: 0.9508   Count: 3483
  Outpatient Logistics/Scheduling          F1: 0.7153   Count: 448
  Physical                                 F1: 0.7684   Count: 628
  Physical Environment/Climate             F1: 0.8718   Count: 203
  Service Complaint                        F1: 0.2692   Count: 116
  Social Services                          F1: 0.5882   Count: 100
  Technical/IT                             F1: 0.5424   Count: 238
  Urgent                                   F1: 0.3696   Count: 284
  Work/School                              F1: 0.6486   Count: 143

==================================================

--- Overall Test Set Metrics ---
  Macro F1 Score:    0.6843
  Micro F1 Score:    0.8322
  Weighted F1 Score: 0.8287
--- Full Classification Report ---
                                 precision    recall  f1-score   support

              Cultural/Religion       0.92      0.85      0.88        53
                 Diet/Nutrition       0.89      0.80      0.84        50
                       Emergent       0.73      0.40      0.52        20
                       Exercise       0.80      0.38      0.52        21
               Friends & Family       0.61      0.47      0.54        40
               Grateful Patient       0.60      0.51      0.55        47
               Health Education       0.84      0.80      0.82        46
             Laboratory/Testing       0.96      0.96      0.96       166
                    Medications       0.83      0.71      0.77        62
                    No Symptoms       0.88      0.89      0.88       255
                     Non-urgent       0.92      0.98      0.95       522
Outpatient Logistics/Scheduling       0.78      0.66      0.72        74
                       Physical       0.82      0.72      0.77        94
   Physical Environment/Climate       0.89      0.85      0.87        20
              Service Complaint       0.21      0.39      0.27        18
                Social Services       0.59      0.59      0.59        17
                   Technical/IT       0.76      0.42      0.54        38
                         Urgent       0.34      0.40      0.37        42
                    Work/School       0.86      0.52      0.65        23

                      micro avg       0.84      0.82      0.83      1608
                      macro avg       0.75      0.65      0.68      1608
                   weighted avg       0.85      0.82      0.83      1608
                    samples avg       0.86      0.85      0.84      1608

In [ ]:
# SAVE_PREDS_v1
import numpy as np, os
os.makedirs("predictions", exist_ok=True)
np.savez_compressed(
    "predictions/SVM_preds.npz",
    y_true = y_test,
    y_pred = Y_pred_all,
)
print("Saved predictions/SVM_preds.npz", Y_pred_all.shape)

In [ ]:

import numpy as np
from sklearn.metrics import f1_score

N_BOOTSTRAP = 1000
rng = np.random.default_rng(42)
n = len(y_test)

boot_scores = []
for _ in range(N_BOOTSTRAP):
    idx = rng.integers(0, n, size=n)
    score = f1_score(y_test[idx], Y_pred_all[idx], average='macro', zero_division=0)
    boot_scores.append(score)

boot_scores = np.array(boot_scores)
lo = np.percentile(boot_scores, 2.5)
hi = np.percentile(boot_scores, 97.5)
print(f"Macro F1: {macro_f1:.4f}  95% CI [{lo:.4f}, {hi:.4f}]")

Macro F1: 0.6843  95% CI [0.6493, 0.7121]

## Per-corpus + per-label evaluation (SVM)

Loads saved `SVM_preds.npz` and reports Macro F1 (+ 95% bootstrap CI) and per-label F1 separately for the pooled corpus and for the Rwanda and Canada halves. Source labels come from `Ensemble_test_predictions.json`, which carries the per-row `source_corpus` field for the same 584-doc test set.

In [ ]:
# PERCORPUSCELL_v1
# Per-corpus + per-label evaluation against the shared test split, with 1,000-resample bootstrap CIs.
import json, numpy as np
from sklearn.metrics import f1_score, classification_report

with open("predictions/Ensemble_test_predictions.json") as f:
    _ens = json.load(f)
_src    = np.array([r["source_corpus"] for r in _ens])
_labels = list(_ens[0]["true_labels"].keys())

_d = np.load("predictions/SVM_preds.npz")
_yt, _yp = _d["y_true"].astype(int), _d["y_pred"]
if _yp.dtype != int:
    _yp = (_yp > 0.5).astype(int) if _yp.max() <= 1 else _yp.astype(int)

for _corpus in ["Combined", "Rwanda", "Canada"]:
    _mask = np.ones(len(_src), bool) if _corpus == "Combined" else (_src == _corpus)
    _yti, _ypi = _yt[_mask], _yp[_mask]
    _macro = f1_score(_yti, _ypi, average="macro", zero_division=0)

    _rng = np.random.default_rng(42)
    _n = len(_yti)
    _boot = np.empty(1000)
    for _i in range(1000):
        _idx = _rng.integers(0, _n, _n)
        _boot[_i] = f1_score(_yti[_idx], _ypi[_idx], average="macro", zero_division=0)
    _lo, _hi = np.percentile(_boot, [2.5, 97.5])

    print(f"\n=== {{_corpus}} (n={{_n}})  Macro F1 {{_macro:.4f}}  95% CI [{{_lo:.4f}}, {{_hi:.4f}}] ===")
    print(classification_report(_yti, _ypi, target_names=_labels, zero_division=0))