In [1]:
import pandas as pd
import random
import numpy as np
import torch
def set_seed(seed):
    """Set seed for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)

In [2]:
dfCovid = pd.read_csv('data/dataRwaCovid.csv')

In [3]:
dfDiabetes = pd.read_csv('data/dataIHADiabetes.csv')

In [4]:
DiabetesTopics = [
    "Physical",
    "Psychological",
    "No Symptoms",
    "Prognosis",
    "Laboratory/Testing",
    "Imaging",
    "Clinical",
    "Testing/Monitoring Devices",
    "Health Data",
    "Diagnostic Methods - Other",
    "Medications",
    "Procedures",
    "Alternative",
    "Physical Therapy",
    "Counseling",
    "Adverse Events",
    "Therapeutic Devices",
    "Treatment(Rx) - Other",
    "Outpatient Logistics/Scheduling",
    "Hospitalizations",
    "Insurance/Billing",
    "Medical Records",
    "Referrals",
    "Transportation",
    "Primary (Pharmaceutical Prevention)",
    "Primary (Non-Pharmaceutical Prevention)",
    "Secondary (Pharmaceutical Prevention)",
    "Secondary (Non-Pharmaceutical Prevention)",
    "Diet/Nutrition",
    "Exercise",
    "Substance Use",
    "Entertainment",
    "Lifestyle - Other",
    "Housing",
    "Work/School",
    "Social Services",
    "Friends & Family",
    "Cultural/Religion",
    "Travel",
    "Physical Environment/Climate",
    "Financial",
    "Social - Other",
    "Technical/IT",
    "Safety Concerns",
    "Health Education",
    "Sexual & Reproductive Health",
    "Child & Family Health",
    "Problems Solved",
    "Grateful Patient",
    "Service Complaint",
    "Request to Stop",
    "Emergent",
    "Urgent",
    "Non-urgent",
    "Stigma Present",
    "Rapport",
    "Transition to Adult Clinic"
]

In [5]:
CovidTopics = [
    "Physical",
    "Mental/Emotional",
    "No Symptoms",
    "Laboratory/Testing",
    "Imaging",
    "Clinical",
    "Diagnostic Methods - Other",
    "Medications",
    "Procedures",
    "Alternative",
    "Physical Therapy",
    "Counseling",
    "Treatment(Rx) - Other",
    "Outpatient Logistics/Scheduling",
    "Hospitalizations",
    "Pharmaceutical Prevention",
    "Non-Pharmaceutical Prevention",
    "Diet/Nutrition",
    "Exercise",
    "Substance Use",
    "Lifestyle - Other",
    "Housing",
    "Work/School",
    "Social Services",
    "Friends & Family",
    "Cultural/Religion",
    "Travel",
    "Physical Environment/Climate",
    "Financial",
    "Social - Other",
    "Technical/IT",
    "Safety concern",
    "Health Education",
    "Maternal & Child Health",
    "Problems Solved",
    "Grateful Patient",
    "Service Complaint",
    "Request to Stop",
    "Emergent",
    "Urgent",
    "Non-urgent",
    "Stigma Present",
    "wave",
    "batch"
]

In [6]:
commonSubtopics = sorted(list(set(DiabetesTopics) & set(CovidTopics)))

In [7]:
dfCovid[commonSubtopics].sum()

Alternative                          35
Clinical                              5
Counseling                            0
Cultural/Religion                   154
Diagnostic Methods - Other            5
Diet/Nutrition                      102
Emergent                            138
Exercise                             25
Financial                            53
Friends & Family                    138
Grateful Patient                    244
Health Education                     45
Hospitalizations                     15
Housing                              32
Imaging                               7
Laboratory/Testing                 1018
Lifestyle - Other                    52
Medications                         152
No Symptoms                        1657
Non-urgent                         2383
Outpatient Logistics/Scheduling     268
Physical                            406
Physical Environment/Climate          6
Physical Therapy                      1
Problems Solved                      45
Procedures                            0
Request to Stop                      50
Service Complaint                   106
Social - Other                        7
Social Services                      30
Stigma Present                       15
Substance Use                         0
Technical/IT                        185
Travel                               12
Treatment(Rx) - Other                 0
Urgent                              270
Work/School                          46
dtype: int64

In [8]:
diabetesColumns = commonSubtopics[:]
diabetesColumns.insert(0,"conversation")
dfDiabetesNew = dfDiabetes[diabetesColumns]

In [9]:
covidColumns = commonSubtopics[:]
covidColumns.insert(0,"conversation(english_only)")
dfCovidNew = dfCovid[covidColumns]

In [10]:
dfCovidNew = dfCovidNew.rename(columns={"conversation(english_only)":"conversation"})

df

In [11]:
dfCombined = pd.concat([dfCovidNew, dfDiabetesNew])

In [12]:
dfCombined.sum()

conversation                       (S): Hello, how are you today? Do you have any...
Alternative                                                                       35
Clinical                                                                           6
Counseling                                                                         0
Cultural/Religion                                                                343
Diagnostic Methods - Other                                                         8
Diet/Nutrition                                                                   340
Emergent                                                                         140
Exercise                                                                         131
Financial                                                                         53
Friends & Family                                                                 291
Grateful Patient                                                                 291
Health Education                                                                 322
Hospitalizations                                                                  15
Housing                                                                           41
Imaging                                                                            8
Laboratory/Testing                                                              1078
Lifestyle - Other                                                                 73
Medications                                                                      418
No Symptoms                                                                     1658
Non-urgent                                                                      3483
Outpatient Logistics/Scheduling                                                  448
Physical                                                                         628
Physical Environment/Climate                                                     203
Physical Therapy                                                                   1
Problems Solved                                                                   57
Procedures                                                                         7
Request to Stop                                                                   56
Service Complaint                                                                116
Social - Other                                                                    10
Social Services                                                                  100
Stigma Present                                                                    15
Substance Use                                                                      0
Technical/IT                                                                     238
Travel                                                                            38
Treatment(Rx) - Other                                                              1
Urgent                                                                           284
Work/School                                                                      143
dtype: object

In [13]:
n = 100
label_sum = dfCombined[commonSubtopics].sum()
label_keep = label_sum[label_sum >= n].index.tolist()
label_keep_original = label_keep[:]
label_keep.insert(0,"conversation")

dfCombined_filtered = dfCombined[label_keep]
dfCombined_filtered.shape

(3907, 20)

In [14]:
dfCombined_filtered.sum()

conversation                       (S): Hello, how are you today? Do you have any...
Cultural/Religion                                                                343
Diet/Nutrition                                                                   340
Emergent                                                                         140
Exercise                                                                         131
Friends & Family                                                                 291
Grateful Patient                                                                 291
Health Education                                                                 322
Laboratory/Testing                                                              1078
Medications                                                                      418
No Symptoms                                                                     1658
Non-urgent                                                                      3483
Outpatient Logistics/Scheduling                                                  448
Physical                                                                         628
Physical Environment/Climate                                                     203
Service Complaint                                                                116
Social Services                                                                  100
Technical/IT                                                                     238
Urgent                                                                           284
Work/School                                                                      143
dtype: object

In [15]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].str.lower()

/tmp/ipykernel_394/1116881674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].str.lower()

In [16]:
import nltk
import re
import string

In [17]:
!pip install contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 11.6 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 13.6 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.1 textsearch-0.0.24

In [18]:
import contractions

In [19]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([contractions.fix(word) for word in x.split()]))

/tmp/ipykernel_394/2646981620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([contractions.fix(word) for word in x.split()]))

In [20]:
dfCombined_filtered.shape

(3907, 20)

In [21]:
dfCombined_filtered.head()

,conversation,Cultural/Religion,Diet/Nutrition,Emergent,Exercise,Friends & Family,Grateful Patient,Health Education,Laboratory/Testing,Medications,No Symptoms,Non-urgent,Outpatient Logistics/Scheduling,Physical,Physical Environment/Climate,Service Complaint,Social Services,Technical/IT,Urgent,Work/School
0,"(s): hello, how are you today? do you have any...",1,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0
1,(s): welcome to rwanda ministry of health plat...,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
2,(s): welcome to rwanda ministry of health plat...,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
3,"(s): hello, how are you today? do you have any...",0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0
4,(s): welcome to rwanda ministry of health plat...,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0

In [22]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'\d+','',x))

/tmp/ipykernel_394/3892837535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'\d+','',x))

In [23]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'[.]',' ',x))

/tmp/ipykernel_394/1879545715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: re.sub(r'[.]',' ',x))

In [24]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: "".join([char for char in x if char not in string.punctuation]))

/tmp/ipykernel_394/2885321218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: "".join([char for char in x if char not in string.punctuation]))

In [25]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [26]:
from nltk.corpus import stopwords

In [27]:
sw = stopwords.words('english')

In [28]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([word for word in x.split() if word not in sw]))

/tmp/ipykernel_394/280526503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lambda x: " ".join([word for word in x.split() if word not in sw]))

In [29]:
import nltk
nltk.download("punkt_tab")
nltk.download('punkt')
nltk.download("wordnet")
nltk.download("averaged_perceptron_tagger_eng")
nltk.download('averaged_perceptron_tagger')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

from nltk.corpus import wordnet

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def lemmatize_with_pos(text):
    tokens = nltk.word_tokenize(text)
    tagged_tokens = nltk.pos_tag(tokens)
    return " ".join([lemmatizer.lemmatize(token, get_wordnet_pos(pos)) for token, pos in tagged_tokens])

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

In [30]:
dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lemmatize_with_pos)

/tmp/ipykernel_394/306948834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered["conversation"] = dfCombined_filtered["conversation"].apply(lemmatize_with_pos)

In [31]:
dfCombined_filtered.head()
dfCombined_filtered.shape

(3907, 20)

In [32]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

dfCombined_filtered['conversation_tokens'] = dfCombined_filtered['conversation'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/tmp/ipykernel_394/4092647881.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombined_filtered['conversation_tokens'] = dfCombined_filtered['conversation'].apply(word_tokenize)

In [33]:
!pip install scikit-multilearn

Collecting scikit-multilearn
  Downloading scikit_multilearn-0.2.0-py3-none-any.whl.metadata (6.0 kB)
Downloading scikit_multilearn-0.2.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 5.5 MB/s eta 0:00:00
Installing collected packages: scikit-multilearn
Successfully installed scikit-multilearn-0.2.0

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import pandas as pd
from skmultilearn.model_selection import iterative_train_test_split
from sklearn.model_selection import train_test_split

In [35]:
tf = TfidfVectorizer(max_features=5000,ngram_range=(1,2),min_df=3,max_df=0.6 )
x =dfCombined_filtered["conversation"]

In [36]:
import torch
# from sklearn.multi
# torch.cuda.get_device_name()

In [37]:
y = dfCombined_filtered[label_keep_original].to_numpy()
print(y.shape)

(3907, 19)

In [38]:

import numpy as np

split = np.load("data/shared_split_indices.npz")
train_idx = split["train_idx"]
val_idx   = split["val_idx"]
test_idx  = split["test_idx"]

x_raw = dfCombined_filtered["conversation"].to_numpy()
y     = dfCombined_filtered[label_keep_original].to_numpy()

x_train_raw = x_raw[train_idx]
x_val_raw   = x_raw[val_idx]
x_test_raw  = x_raw[test_idx]

y_train = y[train_idx]
y_val   = y[val_idx]
y_test  = y[test_idx]

df_aug_train = pd.read_csv("data/backtranslated_train.csv")

import pandas as pd
import numpy as np
import re
import string
import contractions
import nltk
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

df_aug_train = pd.read_csv('data/backtranslated_train.csv')

y_train = df_aug_train[label_keep_original].to_numpy()

sw = stopwords.words('english')
lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'): return wordnet.ADJ
    elif treebank_tag.startswith('V'): return wordnet.VERB
    elif treebank_tag.startswith('N'): return wordnet.NOUN
    elif treebank_tag.startswith('R'): return wordnet.ADV
    else: return wordnet.NOUN

def lemmatize_with_pos(text):
    tokens = word_tokenize(text)
    tagged = nltk.pos_tag(tokens)
    return " ".join([lemmatizer.lemmatize(tok, get_wordnet_pos(pos)) for tok, pos in tagged])

def preprocess(text):
    text = text.lower()
    text = " ".join([contractions.fix(word) for word in text.split()])
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[.]', ' ', text)
    text = "".join([c for c in text if c not in string.punctuation])
    text = " ".join([w for w in text.split() if w not in sw])
    text = lemmatize_with_pos(text)
    return text

df_aug_train['conversation'] = df_aug_train['conversation'].apply(preprocess)
x_train = df_aug_train["conversation"].to_numpy()

y_train = df_aug_train[label_keep_original].to_numpy()

x_train = tf.fit_transform(pd.Series(x_train.flatten()))
x_val   = tf.transform(pd.Series(x_val_raw.flatten()))
x_test  = tf.transform(pd.Series(x_test_raw.flatten()))

In [39]:
x_train.shape

(5468, 5000)

In [40]:
x_train.shape
type(x_train)

scipy.sparse._csr.csr_matrix

In [41]:
y_train.shape
type(y_train)

numpy.ndarray

In [42]:
from xgboost import XGBClassifier
from sklearn.multiclass import OneVsRestClassifier

In [43]:
# x_val,  y_val,  x_test,y_test = iterative_train_test_split(x_, y_, test_size=0.5)

In [44]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)

In [45]:
!pip install --upgrade scikit-multilearn

Requirement already satisfied: scikit-multilearn in /usr/local/lib/python3.12/dist-packages (0.2.0)

In [46]:
y_val.shape

(589, 19)

In [47]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [48]:
from xgboost import XGBClassifier
import xgboost as xgb
from sklearn.multiclass import OneVsRestClassifier

In [49]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 12.4 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [50]:
import optuna

In [51]:
dmatrix_train = xgb.DMatrix(x_train)
dmatrix_val = xgb.DMatrix(x_val)
dmatrix_test = xgb.DMatrix(x_test)

In [52]:
from xgboost import XGBClassifier
from sklearn.multiclass import OneVsRestClassifier
import numpy as np
from sklearn.metrics import f1_score
print(y_train.shape)
print(type(y_train))
print(type(y_val))
print(type(y_test))

(5468, 19)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [53]:
models = {}
list_params = {}

tempDmatrix_val = xgb.DMatrix(x_val)
tempDmatrix_test = xgb.DMatrix(x_test)
for i,label_name in enumerate(label_keep_original):
    print(label_name)
    dmatrix_train.set_label(y_train[:,i])
    dmatrix_val.set_label(y_val[:,i])
    dmatrix_test.set_label(y_test[:,i])
    def objective(trial):
      params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'booster': 'gbtree',
        'subsample': trial.suggest_float('subsample', 0.3, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree',0.3,1.0),
        'scale_pos_weight':(len(y_train[:,i])-y_train[:,i].sum())/y_train[:,i].sum(),

        'eta': trial.suggest_float('eta', 0.01, 1.5),
        'max_depth': trial.suggest_int('max_depth', 1, 10),
        'seed': 42,
        'n_jobs': -1,
        'reg_lambda': trial.suggest_int('reg_lambda',0.5,4),
        'reg_alpha':trial.suggest_int('reg_alpha',0.5,4),
        'gamma': trial.suggest_float('gamma', 0.1, 1),
        'device': 'cuda',
        'use_label_encoder': False,
      }
      eval_list = [(dmatrix_val, 'validation')]
      model = xgb.train(params=params, dtrain=dmatrix_train,evals=eval_list,num_boost_round=1000,verbose_eval=False,early_stopping_rounds=30)


      x_val_predic = model.predict(tempDmatrix_val)


      best_f1 = 0
      best_thresh = 0.5
      for threshold_val in np.arange(0.05, 0.96, 0.05):
          preds = (x_val_predic > threshold_val).astype(int)
          # print(preds.shape)
          # print(y_val[:, i].shape)
          current_f1 = f1_score(y_val[:, i], preds)
          if current_f1 > best_f1:
              best_f1 = current_f1
              best_thresh = threshold_val
      return best_f1
    study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
    study.optimize(objective, n_trials=50)
    print(f"Best trial for {label_name}: F1 score= {study.best_value:.4f}")
    print(f"Best hyperparameters: {study.best_params}")
    list_params[label_name] = study.best_params

[I 2026-05-25 15:37:31,906] A new study created in memory with name: no-name-d88f246c-29df-4266-bab4-4ae28a6752d5

Cultural/Religion

/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:32,583] Trial 0 finished with value: 0.9504950495049505 and parameters: {'subsample': 0.945404102593965, 'colsample_bytree': 0.7397939550373951, 'eta': 1.1156456305775933, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.5102950721156049}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:33,809] Trial 1 finished with value: 0.9292929292929293 and parameters: {'subsample': 0.3821247181031435, 'colsample_bytree': 0.7080305563987621, 'eta': 0.23981479297932812, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.4492232450038026}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:34,443] Trial 2 finished with value: 0.9387755102040817 and parameters: {'subsample': 0.5026638022468173, 'colsample_bytree': 0.8977670394311967, 'eta': 0.40822829067564054, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.5517769312003151}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:34,963] Trial 3 finished with value: 0.94 and parameters: {'subsample': 0.3904449460931604, 'colsample_bytree': 0.584753927520328, 'eta': 0.8479279503376685, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.629552463391463}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:35,456] Trial 4 finished with value: 0.9292929292929293 and parameters: {'subsample': 0.8868866117234702, 'colsample_bytree': 0.4775590607337995, 'eta': 0.7635644467577246, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.4491905987004018}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:35,934] Trial 5 finished with value: 0.94 and parameters: {'subsample': 0.726904659367423, 'colsample_bytree': 0.31113843581395473, 'eta': 0.8704557986547858, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.2346102517815159}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:36,527] Trial 6 finished with value: 0.9504950495049505 and parameters: {'subsample': 0.9496800794654177, 'colsample_bytree': 0.8082723609387135, 'eta': 0.9729202223697171, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.19352896842921652}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:36,999] Trial 7 finished with value: 0.8761904761904762 and parameters: {'subsample': 0.46450627829593527, 'colsample_bytree': 0.36587689301854265, 'eta': 1.407896950814698, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.48699267308850036}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:37,562] Trial 8 finished with value: 0.8842105263157894 and parameters: {'subsample': 0.5503593729138236, 'colsample_bytree': 0.41416788488651707, 'eta': 1.3846355340931602, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.5343216243197784}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:38,522] Trial 9 finished with value: 0.9504950495049505 and parameters: {'subsample': 0.6324380996825656, 'colsample_bytree': 0.6830728505901826, 'eta': 0.3851508142335773, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.8606156078476083}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:39,084] Trial 10 finished with value: 0.3508771929824561 and parameters: {'subsample': 0.7919156600304181, 'colsample_bytree': 0.9659471770655319, 'eta': 1.1731383901240318, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.9146471034225268}. Best is trial 0 with value: 0.9504950495049505.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:39,807] Trial 11 finished with value: 0.9514563106796117 and parameters: {'subsample': 0.9977431996850876, 'colsample_bytree': 0.8087472949475869, 'eta': 1.0781674824297398, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.12965229621366742}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:40,800] Trial 12 finished with value: 0.9292929292929293 and parameters: {'subsample': 0.9908826338748034, 'colsample_bytree': 0.8006388003725425, 'eta': 1.1317885131190317, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.10867100893023177}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:41,670] Trial 13 finished with value: 0.9072164948453608 and parameters: {'subsample': 0.844722629739457, 'colsample_bytree': 0.8098237250037807, 'eta': 1.1376425236353633, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.31019804418950464}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:42,623] Trial 14 finished with value: 0.9306930693069307 and parameters: {'subsample': 0.9919033126580217, 'colsample_bytree': 0.568129729645025, 'eta': 0.571287114848811, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.7378052701093739}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:43,093] Trial 15 finished with value: 0.9514563106796117 and parameters: {'subsample': 0.7380985750042772, 'colsample_bytree': 0.7476624149246863, 'eta': 1.2632028187922018, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.3624885719875687}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:43,730] Trial 16 finished with value: 0.822429906542056 and parameters: {'subsample': 0.7319283784435223, 'colsample_bytree': 0.9148180164447169, 'eta': 1.3341133830794798, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.34852230246232907}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:48,906] Trial 17 finished with value: 0.9494949494949495 and parameters: {'subsample': 0.6628561251205097, 'colsample_bytree': 0.6016271935009325, 'eta': 0.024265501502089837, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.11041707777305831}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:49,391] Trial 18 finished with value: 0.65 and parameters: {'subsample': 0.85443762491954, 'colsample_bytree': 0.8785452116383757, 'eta': 1.4961495118402266, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.3330234031389417}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:50,335] Trial 19 finished with value: 0.8602150537634409 and parameters: {'subsample': 0.5895582324610249, 'colsample_bytree': 0.9894704444364635, 'eta': 0.9724264378475069, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.22236532028014963}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:50,800] Trial 20 finished with value: 0.912621359223301 and parameters: {'subsample': 0.7577069568507264, 'colsample_bytree': 0.7601163707373293, 'eta': 1.2738601991712442, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.3560805004200414}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:51,290] Trial 21 finished with value: 0.9494949494949495 and parameters: {'subsample': 0.8966857546922842, 'colsample_bytree': 0.7277912443605341, 'eta': 1.0240612546184213, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.6374294416675456}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:51,511] Trial 22 finished with value: 0.9320388349514563 and parameters: {'subsample': 0.9404759380025425, 'colsample_bytree': 0.6315360190802091, 'eta': 1.2327426485852397, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.7208854716611783}. Best is trial 11 with value: 0.9514563106796117.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:51,924] Trial 23 finished with value: 0.9607843137254902 and parameters: {'subsample': 0.8053909240762616, 'colsample_bytree': 0.7707822841814779, 'eta': 1.042346194360421, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.3904913654386146}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:52,877] Trial 24 finished with value: 0.9306930693069307 and parameters: {'subsample': 0.6768315421756963, 'colsample_bytree': 0.8573999356652457, 'eta': 0.6809445862949968, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.4038521877993054}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:53,827] Trial 25 finished with value: 0.9387755102040817 and parameters: {'subsample': 0.8076900427501222, 'colsample_bytree': 0.6608690752057566, 'eta': 1.0279043296829102, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.2753046589391464}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:54,673] Trial 26 finished with value: 0.9230769230769231 and parameters: {'subsample': 0.8036716840310254, 'colsample_bytree': 0.5176323075291653, 'eta': 0.8895421377947422, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.160293591652022}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:55,182] Trial 27 finished with value: 0.8958333333333334 and parameters: {'subsample': 0.7252246574585745, 'colsample_bytree': 0.8344486074441244, 'eta': 1.4949590093418164, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.39892245071593746}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:55,936] Trial 28 finished with value: 0.0 and parameters: {'subsample': 0.6049235096318477, 'colsample_bytree': 0.7722551099197807, 'eta': 1.2730922540140879, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.2606103189841748}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:56,240] Trial 29 finished with value: 0.96 and parameters: {'subsample': 0.9074039807826386, 'colsample_bytree': 0.7380231878690318, 'eta': 1.068873025156629, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.1828591188087857}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:56,485] Trial 30 finished with value: 0.9423076923076923 and parameters: {'subsample': 0.9362671524682182, 'colsample_bytree': 0.9383958558328072, 'eta': 1.0644234405598831, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.16359682486803012}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:56,687] Trial 31 finished with value: 0.7719298245614035 and parameters: {'subsample': 0.8580340116163431, 'colsample_bytree': 0.7047378327247272, 'eta': 1.2069683102834579, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.28810280620710205}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:57,061] Trial 32 finished with value: 0.9607843137254902 and parameters: {'subsample': 0.9059095560379674, 'colsample_bytree': 0.7464024385476431, 'eta': 0.7458289880154645, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.16255730915683075}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:57,469] Trial 33 finished with value: 0.9494949494949495 and parameters: {'subsample': 0.9111063576135985, 'colsample_bytree': 0.7046547681816384, 'eta': 0.6584858608661867, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.16614445246446}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:37:57,760] Trial 34 finished with value: 0.94 and parameters: {'subsample': 0.9990496600840867, 'colsample_bytree': 0.7778024001390744, 'eta': 0.7795873699934834, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.1020370716897053}. Best is trial 23 with value: 0.9607843137254902.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:37:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Cultural/Religion: F1 score= 0.9608
Best hyperparameters: {'subsample': 0.8053909240762616, 'colsample_bytree': 0.7707822841814779, 'eta': 1.042346194360421, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.3904913654386146}
Diet/Nutrition

[I 2026-05-25 15:38:05,548] Trial 0 finished with value: 0.8118811881188119 and parameters: {'subsample': 0.335545306083955, 'colsample_bytree': 0.6949397346881581, 'eta': 0.34055581597635126, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.6818189551675108}. Best is trial 0 with value: 0.8118811881188119.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:06,690] Trial 1 finished with value: 0.8932038834951457 and parameters: {'subsample': 0.6645000256152709, 'colsample_bytree': 0.6772864580754918, 'eta': 0.22589633113517452, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.825418455891992}. Best is trial 1 with value: 0.8932038834951457.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:07,925] Trial 2 finished with value: 0.831858407079646 and parameters: {'subsample': 0.6466665554700914, 'colsample_bytree': 0.8926026340420703, 'eta': 0.3633061535575543, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.28680145208309205}. Best is trial 1 with value: 0.8932038834951457.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:10,886] Trial 3 finished with value: 0.9 and parameters: {'subsample': 0.46075075891320394, 'colsample_bytree': 0.6988914141973439, 'eta': 0.09786669073603098, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.9401087327871399}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:11,891] Trial 4 finished with value: 0.8910891089108911 and parameters: {'subsample': 0.6534242136910481, 'colsample_bytree': 0.9101154849324495, 'eta': 0.20998180916127762, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.577105357941436}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:12,098] Trial 5 finished with value: 0.845360824742268 and parameters: {'subsample': 0.9371184260220842, 'colsample_bytree': 0.9627307963440856, 'eta': 1.1805342466490074, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.14715837725662914}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:15,088] Trial 6 finished with value: 0.8867924528301887 and parameters: {'subsample': 0.7406495929506421, 'colsample_bytree': 0.7615586343889367, 'eta': 0.08014339669053964, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.33384129848830124}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:15,550] Trial 7 finished with value: 0.8514851485148515 and parameters: {'subsample': 0.8455164328862921, 'colsample_bytree': 0.8721500596591141, 'eta': 0.5746983537977559, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.8103068692784497}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:15,879] Trial 8 finished with value: 0.8461538461538461 and parameters: {'subsample': 0.9537111709487325, 'colsample_bytree': 0.3282093137934677, 'eta': 1.2786935057978814, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.11150880710430655}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:16,294] Trial 9 finished with value: 0.8737864077669902 and parameters: {'subsample': 0.9064969567688974, 'colsample_bytree': 0.8743054035814584, 'eta': 0.799871179689456, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.9629604850999776}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:16,718] Trial 10 finished with value: 0.782608695652174 and parameters: {'subsample': 0.39879794769073357, 'colsample_bytree': 0.4896716355541131, 'eta': 0.8802153004873299, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.9953260005850084}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:21,515] Trial 11 finished with value: 0.88 and parameters: {'subsample': 0.5305289819992869, 'colsample_bytree': 0.5769625007191226, 'eta': 0.03772407695613556, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.8213537560729302}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:22,285] Trial 12 finished with value: 0.8043478260869565 and parameters: {'subsample': 0.49468881630268297, 'colsample_bytree': 0.5926392020820566, 'eta': 0.5611094838844919, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.8038783262635032}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:22,893] Trial 13 finished with value: 0.8823529411764706 and parameters: {'subsample': 0.5387778780220739, 'colsample_bytree': 0.770520648693972, 'eta': 0.44591233719030765, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.6537595231328159}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:24,044] Trial 14 finished with value: 0.8910891089108911 and parameters: {'subsample': 0.7346200112824961, 'colsample_bytree': 0.4837043574314979, 'eta': 0.19001934064259873, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.9052511355675901}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:24,484] Trial 15 finished with value: 0.7878787878787878 and parameters: {'subsample': 0.6199637868726224, 'colsample_bytree': 0.6787063350459254, 'eta': 0.9450046609211317, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.42383044575559287}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:25,632] Trial 16 finished with value: 0.8076923076923077 and parameters: {'subsample': 0.3017454535244856, 'colsample_bytree': 0.7838744017794799, 'eta': 0.564849400775079, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.7161656344123888}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:29,675] Trial 17 finished with value: 0.8867924528301887 and parameters: {'subsample': 0.4525966648784189, 'colsample_bytree': 0.5806304116116453, 'eta': 0.04279539457247028, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.8704711294802445}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:30,507] Trial 18 finished with value: 0.897196261682243 and parameters: {'subsample': 0.7973947588976793, 'colsample_bytree': 0.45814293166123515, 'eta': 0.25107387023548017, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.49831850259217153}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:30,763] Trial 19 finished with value: 0.8888888888888888 and parameters: {'subsample': 0.8502027094111793, 'colsample_bytree': 0.31131512880700896, 'eta': 0.6788644569323354, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.4843571363666189}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:31,108] Trial 20 finished with value: 0.8484848484848485 and parameters: {'subsample': 0.7767433314686473, 'colsample_bytree': 0.41775566047976903, 'eta': 1.047779868609456, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.5773561214305372}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:32,206] Trial 21 finished with value: 0.8686868686868687 and parameters: {'subsample': 0.5919959782653406, 'colsample_bytree': 0.6425337104166888, 'eta': 0.23169945695659197, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.7204427567435484}. Best is trial 3 with value: 0.9.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:32,943] Trial 22 finished with value: 0.9230769230769231 and parameters: {'subsample': 0.7041290874545167, 'colsample_bytree': 0.4883125685138074, 'eta': 0.3480210607655795, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.4533137035405515}. Best is trial 22 with value: 0.9230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:33,741] Trial 23 finished with value: 0.8910891089108911 and parameters: {'subsample': 0.7809345314381795, 'colsample_bytree': 0.4259244908552572, 'eta': 0.3821411600709651, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.4197767982676468}. Best is trial 22 with value: 0.9230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:35,300] Trial 24 finished with value: 0.9142857142857143 and parameters: {'subsample': 0.7003820546188237, 'colsample_bytree': 0.5131881838349976, 'eta': 0.12009685231447353, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.2924630513540139}. Best is trial 22 with value: 0.9230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:35,446] Trial 25 finished with value: 0.5031446540880503 and parameters: {'subsample': 0.7086303662403205, 'colsample_bytree': 0.521871260662228, 'eta': 1.4769143641917513, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.23666220885568395}. Best is trial 22 with value: 0.9230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:36,654] Trial 26 finished with value: 0.912621359223301 and parameters: {'subsample': 0.5764741816007706, 'colsample_bytree': 0.378136502288442, 'eta': 0.1267805488047642, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.3615820329674017}. Best is trial 22 with value: 0.9230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:37,010] Trial 27 finished with value: 0.9038461538461539 and parameters: {'subsample': 0.5739018587397369, 'colsample_bytree': 0.3626186070181931, 'eta': 0.46166215914024405, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.3800409549597401}. Best is trial 22 with value: 0.9230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:38,119] Trial 28 finished with value: 0.9320388349514563 and parameters: {'subsample': 0.6881177646213142, 'colsample_bytree': 0.3694148766560351, 'eta': 0.13560609375811203, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.2212903210912265}. Best is trial 28 with value: 0.9320388349514563.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:38,871] Trial 29 finished with value: 0.9230769230769231 and parameters: {'subsample': 0.7010228713608964, 'colsample_bytree': 0.5332414825286158, 'eta': 0.32121892804746355, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.20220907697071422}. Best is trial 28 with value: 0.9320388349514563.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:39,487] Trial 30 finished with value: 0.9333333333333333 and parameters: {'subsample': 0.8405428609616105, 'colsample_bytree': 0.39977599739157665, 'eta': 0.3043206354487006, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.19525231429779677}. Best is trial 30 with value: 0.9333333333333333.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:40,150] Trial 31 finished with value: 0.9333333333333333 and parameters: {'subsample': 0.8685151584380064, 'colsample_bytree': 0.3873230980753726, 'eta': 0.29926434695522863, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.19007050454227262}. Best is trial 30 with value: 0.9333333333333333.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:40,896] Trial 32 finished with value: 0.9333333333333333 and parameters: {'subsample': 0.8682505532144988, 'colsample_bytree': 0.3843105145349676, 'eta': 0.3078630800776591, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.22385846828875128}. Best is trial 30 with value: 0.9333333333333333.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:41,422] Trial 33 finished with value: 0.9306930693069307 and parameters: {'subsample': 0.8765579124499906, 'colsample_bytree': 0.3791965551364896, 'eta': 0.4750609915052685, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.2162774566073534}. Best is trial 30 with value: 0.9333333333333333.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:42,088] Trial 34 finished with value: 0.9108910891089109 and parameters: {'subsample': 0.9957279246040937, 'colsample_bytree': 0.3502004430029232, 'eta': 0.2909530225789597, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.1593856689579477}. Best is trial 30 with value: 0.9333333333333333.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:42,332] Trial 35 finished with value: 0.8727272727272727 and parameters: {'subsample': 0.816069169676498, 'colsample_bytree': 0.41899957560342316, 'eta': 0.6730221546286165, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.26614251936322536}. Best is trial 30 with value: 0.9333333333333333.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Diet/Nutrition: F1 score= 0.9333
Best hyperparameters: {'subsample': 0.8405428609616105, 'colsample_bytree': 0.39977599739157665, 'eta': 0.3043206354487006, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.19525231429779677}
Emergent

[I 2026-05-25 15:38:52,737] Trial 0 finished with value: 0.32786885245901637 and parameters: {'subsample': 0.7918530103441145, 'colsample_bytree': 0.7906709000662371, 'eta': 1.0845133367969781, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.6029058624652036}. Best is trial 0 with value: 0.32786885245901637.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:53,022] Trial 1 finished with value: 0.36065573770491804 and parameters: {'subsample': 0.9553000946904759, 'colsample_bytree': 0.7018645807652821, 'eta': 1.1421170793632558, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7673375946349532}. Best is trial 1 with value: 0.36065573770491804.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:53,784] Trial 2 finished with value: 0.3404255319148936 and parameters: {'subsample': 0.7915006348725782, 'colsample_bytree': 0.9853788835867259, 'eta': 0.3510743985220263, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.6205495350597562}. Best is trial 1 with value: 0.36065573770491804.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:54,009] Trial 3 finished with value: 0.07952286282306163 and parameters: {'subsample': 0.4910940422986127, 'colsample_bytree': 0.44466184638709877, 'eta': 0.9768889662342622, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.6898014801389122}. Best is trial 1 with value: 0.36065573770491804.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:54,228] Trial 4 finished with value: 0.15819209039548024 and parameters: {'subsample': 0.6531270105029003, 'colsample_bytree': 0.5235656676005473, 'eta': 1.0639189103143432, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.17382552479718955}. Best is trial 1 with value: 0.36065573770491804.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:54,695] Trial 5 finished with value: 0.3037974683544304 and parameters: {'subsample': 0.8860091632292566, 'colsample_bytree': 0.7944056464115284, 'eta': 0.6683809237833297, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.19878891724859837}. Best is trial 1 with value: 0.36065573770491804.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:55,022] Trial 6 finished with value: 0.37037037037037035 and parameters: {'subsample': 0.9753994489252704, 'colsample_bytree': 0.6087561912537935, 'eta': 1.1910979315055656, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.18992023114303486}. Best is trial 6 with value: 0.37037037037037035.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:55,726] Trial 7 finished with value: 0.4230769230769231 and parameters: {'subsample': 0.5049279575413919, 'colsample_bytree': 0.3628212574456816, 'eta': 0.2303735764600903, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.7834902854238298}. Best is trial 7 with value: 0.4230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:56,339] Trial 8 finished with value: 0.3018867924528302 and parameters: {'subsample': 0.4300140364030348, 'colsample_bytree': 0.8910572073861374, 'eta': 0.3335933798170431, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.6997301644096956}. Best is trial 7 with value: 0.4230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:56,845] Trial 9 finished with value: 0.41025641025641024 and parameters: {'subsample': 0.7084722248687344, 'colsample_bytree': 0.9743528385357423, 'eta': 0.6577312235994874, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.17304113307233635}. Best is trial 7 with value: 0.4230769230769231.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:57,847] Trial 10 finished with value: 0.4266666666666667 and parameters: {'subsample': 0.3507557244560851, 'colsample_bytree': 0.30994862016653485, 'eta': 0.012519539692258247, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.9926480512148883}. Best is trial 10 with value: 0.4266666666666667.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:58,387] Trial 11 finished with value: 0.44776119402985076 and parameters: {'subsample': 0.30481738606471537, 'colsample_bytree': 0.33371171475745837, 'eta': 0.03356282505103114, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.9919153668731959}. Best is trial 11 with value: 0.44776119402985076.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:58,862] Trial 12 finished with value: 0.3939393939393939 and parameters: {'subsample': 0.30202495734783547, 'colsample_bytree': 0.30008598920138996, 'eta': 0.013484724982909101, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.9916117147356984}. Best is trial 11 with value: 0.44776119402985076.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:38:58,952] Trial 13 finished with value: 0.20408163265306123 and parameters: {'subsample': 0.3010627136656708, 'colsample_bytree': 0.43633151482316923, 'eta': 1.4555788346269005, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.9935317347317393}. Best is trial 11 with value: 0.44776119402985076.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:38:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:00,606] Trial 14 finished with value: 0.4444444444444444 and parameters: {'subsample': 0.401102858565617, 'colsample_bytree': 0.3074067850686287, 'eta': 0.041963670805782956, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.40560385000975074}. Best is trial 11 with value: 0.44776119402985076.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:00,960] Trial 15 finished with value: 0.42105263157894735 and parameters: {'subsample': 0.4252068810340661, 'colsample_bytree': 0.5148644072354714, 'eta': 0.457506716654574, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.4012396991138648}. Best is trial 11 with value: 0.44776119402985076.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:01,606] Trial 16 finished with value: 0.4528301886792453 and parameters: {'subsample': 0.5629417574319862, 'colsample_bytree': 0.39674390694070305, 'eta': 0.17132218457915466, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.395194359916752}. Best is trial 16 with value: 0.4528301886792453.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:02,022] Trial 17 finished with value: 0.47058823529411764 and parameters: {'subsample': 0.5560806792574429, 'colsample_bytree': 0.4022516620545659, 'eta': 0.19361035739980204, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.4273109040882442}. Best is trial 17 with value: 0.47058823529411764.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:02,345] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.5697486707745832, 'colsample_bytree': 0.5956752216747606, 'eta': 0.5057787922041561, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.4069326352738853}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:02,706] Trial 19 finished with value: 0.4583333333333333 and parameters: {'subsample': 0.5866327475202089, 'colsample_bytree': 0.6126630091652119, 'eta': 0.5193466865919566, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.3077635768374307}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:02,944] Trial 20 finished with value: 0.32558139534883723 and parameters: {'subsample': 0.6918743971567588, 'colsample_bytree': 0.5220396883511061, 'eta': 0.8483452936525644, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.5106814155997428}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:03,324] Trial 21 finished with value: 0.4057971014492754 and parameters: {'subsample': 0.5302716846091016, 'colsample_bytree': 0.6125687510894212, 'eta': 0.53765039802004, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.2984856477999975}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:03,679] Trial 22 finished with value: 0.2857142857142857 and parameters: {'subsample': 0.592315357747541, 'colsample_bytree': 0.7034469625975803, 'eta': 0.5143974494355078, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.30995683311073213}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:03,962] Trial 23 finished with value: 0.43137254901960786 and parameters: {'subsample': 0.6156269294477086, 'colsample_bytree': 0.5672315398681311, 'eta': 0.7834963835097112, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.4929955544750314}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:04,450] Trial 24 finished with value: 0.43333333333333335 and parameters: {'subsample': 0.7356693645695098, 'colsample_bytree': 0.6983143707090469, 'eta': 0.35798387262778897, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.3037197001905806}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:05,051] Trial 25 finished with value: 0.4528301886792453 and parameters: {'subsample': 0.6369372427966272, 'colsample_bytree': 0.4793097037135499, 'eta': 0.20943221963406633, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.465590973261362}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:05,371] Trial 26 finished with value: 0.3673469387755102 and parameters: {'subsample': 0.5560721058294926, 'colsample_bytree': 0.6526989526091238, 'eta': 0.6082421643571388, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.10382286720184172}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:05,644] Trial 27 finished with value: 0.3888888888888889 and parameters: {'subsample': 0.4814847017902096, 'colsample_bytree': 0.771855219346263, 'eta': 0.44047907685354765, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.35594611200274184}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:05,921] Trial 28 finished with value: 0.37209302325581395 and parameters: {'subsample': 0.5821051720568448, 'colsample_bytree': 0.589845417564915, 'eta': 0.8795345705921831, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.5547663671994474}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:06,737] Trial 29 finished with value: 0.4666666666666667 and parameters: {'subsample': 0.7690753414343867, 'colsample_bytree': 0.7813600990452083, 'eta': 0.15680239261967582, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.26060970549170276}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:07,648] Trial 30 finished with value: 0.43902439024390244 and parameters: {'subsample': 0.8299417130602205, 'colsample_bytree': 0.8354099933048826, 'eta': 0.14750259713464936, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.2611649762866781}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:08,313] Trial 31 finished with value: 0.417910447761194 and parameters: {'subsample': 0.756914893117181, 'colsample_bytree': 0.7464740629298203, 'eta': 0.27659650757382126, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.4451429251887401}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:08,642] Trial 32 finished with value: 0.4444444444444444 and parameters: {'subsample': 0.6757151679273105, 'colsample_bytree': 0.6569514818136315, 'eta': 0.4347949817087081, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.24739760254329232}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:09,133] Trial 33 finished with value: 0.45454545454545453 and parameters: {'subsample': 0.8518921217735738, 'colsample_bytree': 0.8750159309241086, 'eta': 0.3285918776571616, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.3661150823524163}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:10,259] Trial 34 finished with value: 0.42857142857142855 and parameters: {'subsample': 0.7809676403369146, 'colsample_bytree': 0.727682392738086, 'eta': 0.1277778489194554, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.5559743780158104}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:10,708] Trial 35 finished with value: 0.32786885245901637 and parameters: {'subsample': 0.46887151490148493, 'colsample_bytree': 0.4364627700352256, 'eta': 0.6032899960413941, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.3399181759363484}. Best is trial 18 with value: 0.5.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.


Best trial for Emergent: F1 score= 0.5000
Best hyperparameters: {'subsample': 0.5697486707745832, 'colsample_bytree': 0.5956752216747606, 'eta': 0.5057787922041561, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.4069326352738853}
Exercise

[I 2026-05-25 15:39:23,663] Trial 0 finished with value: 0.6829268292682927 and parameters: {'subsample': 0.4423937357036146, 'colsample_bytree': 0.6195782721979257, 'eta': 0.8536439911850633, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.648183516127457}. Best is trial 0 with value: 0.6829268292682927.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:23,850] Trial 1 finished with value: 0.6857142857142857 and parameters: {'subsample': 0.5110363089438671, 'colsample_bytree': 0.3401115709091655, 'eta': 0.7403333172753433, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.8657508107365476}. Best is trial 1 with value: 0.6857142857142857.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:24,176] Trial 2 finished with value: 0.8108108108108109 and parameters: {'subsample': 0.6155312750115194, 'colsample_bytree': 0.9588280352365215, 'eta': 0.8840641064960731, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.2667622857730755}. Best is trial 2 with value: 0.8108108108108109.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:24,330] Trial 3 finished with value: 0.6451612903225806 and parameters: {'subsample': 0.8524510594691201, 'colsample_bytree': 0.411569117967368, 'eta': 1.0613131435389136, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.3761298608815905}. Best is trial 2 with value: 0.8108108108108109.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:24,610] Trial 4 finished with value: 0.7777777777777778 and parameters: {'subsample': 0.6008276435222648, 'colsample_bytree': 0.9997575609766933, 'eta': 0.7596755046727333, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.3646327857476269}. Best is trial 2 with value: 0.8108108108108109.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:25,843] Trial 5 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.648884190865117, 'colsample_bytree': 0.4340586935817352, 'eta': 0.1502198311291818, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.17126127426452512}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:26,171] Trial 6 finished with value: 0.7428571428571429 and parameters: {'subsample': 0.7485259570789883, 'colsample_bytree': 0.5828394286843095, 'eta': 0.6386560488839275, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.990943992149392}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:26,518] Trial 7 finished with value: 0.7647058823529411 and parameters: {'subsample': 0.6346239412556431, 'colsample_bytree': 0.6368273785793481, 'eta': 0.6847093247543868, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.9210540939869428}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:26,775] Trial 8 finished with value: 0.7428571428571429 and parameters: {'subsample': 0.8188538374212022, 'colsample_bytree': 0.37043850819014157, 'eta': 0.6055468968659464, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.36963051448540896}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:27,277] Trial 9 finished with value: 0.8292682926829268 and parameters: {'subsample': 0.3622143994455798, 'colsample_bytree': 0.42906668652095237, 'eta': 0.08175327451930574, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.6832416514997058}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:29,688] Trial 10 finished with value: 0.7272727272727273 and parameters: {'subsample': 0.9885659389248298, 'colsample_bytree': 0.8062034878814048, 'eta': 0.04333541328123769, 'max_depth': 10, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.12487148746370008}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:32,690] Trial 11 finished with value: 0.7567567567567568 and parameters: {'subsample': 0.30614130907680104, 'colsample_bytree': 0.4903881719943039, 'eta': 0.017244277577561515, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.64375103401051}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:32,925] Trial 12 finished with value: 0.75 and parameters: {'subsample': 0.36300278143974374, 'colsample_bytree': 0.4925886585481843, 'eta': 0.3286391385308261, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.7535570278826942}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:33,232] Trial 13 finished with value: 0.5333333333333333 and parameters: {'subsample': 0.4871074588586971, 'colsample_bytree': 0.75554900836028, 'eta': 1.395753254411458, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.5051115924986358}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:33,715] Trial 14 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.729705780212657, 'colsample_bytree': 0.30020368453499696, 'eta': 0.3110762402938967, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.13506427483566352}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:34,351] Trial 15 finished with value: 0.6857142857142857 and parameters: {'subsample': 0.41012272355022195, 'colsample_bytree': 0.48620739888676073, 'eta': 0.2826041569267254, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.5227767330276196}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:35,032] Trial 16 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.5402790989807347, 'colsample_bytree': 0.4272393949002987, 'eta': 0.16256598439806685, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.7656627958230631}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:35,480] Trial 17 finished with value: 0.75 and parameters: {'subsample': 0.9435073354697323, 'colsample_bytree': 0.7338412961946592, 'eta': 0.45183607109163376, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.6237920006896768}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:35,750] Trial 18 finished with value: 0.7567567567567568 and parameters: {'subsample': 0.7297009502526026, 'colsample_bytree': 0.5674042312902718, 'eta': 0.47333662226417395, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.23771315437555957}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:37,029] Trial 19 finished with value: 0.6470588235294118 and parameters: {'subsample': 0.330729529692069, 'colsample_bytree': 0.441485702466005, 'eta': 0.16681628497076945, 'max_depth': 10, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.7756127319772587}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:37,225] Trial 20 finished with value: 0.6451612903225806 and parameters: {'subsample': 0.3997864114295779, 'colsample_bytree': 0.5446837127113687, 'eta': 1.1015714593228492, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.48686961005449936}. Best is trial 5 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:37,662] Trial 21 finished with value: 0.8571428571428571 and parameters: {'subsample': 0.7074905758724126, 'colsample_bytree': 0.30784375494417643, 'eta': 0.23151065758689765, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.11768553901160028}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:38,252] Trial 22 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.690940545007352, 'colsample_bytree': 0.3169958444680673, 'eta': 0.14617010938602348, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.22084486299134298}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:38,503] Trial 23 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.5731004588621058, 'colsample_bytree': 0.38220342509473715, 'eta': 0.4457872706854717, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.1755869132755558}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:38,939] Trial 24 finished with value: 0.7647058823529411 and parameters: {'subsample': 0.8131954161992103, 'colsample_bytree': 0.451238593745796, 'eta': 0.21567477594450363, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.29960986050047717}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:40,431] Trial 25 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.8897593197269167, 'colsample_bytree': 0.3596103568165221, 'eta': 0.032271788617383675, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.44103914528467414}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:40,768] Trial 26 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.8999992148533804, 'colsample_bytree': 0.3680922213664114, 'eta': 0.38266605642193025, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.10358469861767074}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:41,129] Trial 27 finished with value: 0.6222222222222222 and parameters: {'subsample': 0.6707017910643065, 'colsample_bytree': 0.33350250431339123, 'eta': 0.5333628321757212, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.45451829087380957}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:41,613] Trial 28 finished with value: 0.7647058823529411 and parameters: {'subsample': 0.8059193481633596, 'colsample_bytree': 0.5213618955039911, 'eta': 0.23807322737276793, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.31304174227729575}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:47,884] Trial 29 finished with value: 0.7692307692307693 and parameters: {'subsample': 0.8905462210677277, 'colsample_bytree': 0.3781261681512462, 'eta': 0.01402355434791791, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.19902286546877512}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:48,780] Trial 30 finished with value: 0.7692307692307693 and parameters: {'subsample': 0.7760293472632536, 'colsample_bytree': 0.661553376368846, 'eta': 0.13714060251992735, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.42183680598574946}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:49,460] Trial 31 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.47363348571083347, 'colsample_bytree': 0.40483777028318596, 'eta': 0.10935327836256842, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.5691118183566671}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:50,109] Trial 32 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.5467508287663114, 'colsample_bytree': 0.3422719995098758, 'eta': 0.07427203528242905, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.5859771839494915}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:50,508] Trial 33 finished with value: 0.7647058823529411 and parameters: {'subsample': 0.9928998283458237, 'colsample_bytree': 0.30208129479118867, 'eta': 0.23803769415997544, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.6735648163900161}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:39:50,796] Trial 34 finished with value: 0.8108108108108109 and parameters: {'subsample': 0.8718205476049156, 'colsample_bytree': 0.4564570942875501, 'eta': 0.3977469836883062, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.8185394805755299}. Best is trial 21 with value: 0.8571428571428571.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:39:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Exercise: F1 score= 0.8571
Best hyperparameters: {'subsample': 0.7074905758724126, 'colsample_bytree': 0.30784375494417643, 'eta': 0.23151065758689765, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.11768553901160028}
Friends & Family

[I 2026-05-25 15:40:04,508] Trial 0 finished with value: 0.46 and parameters: {'subsample': 0.41451851985844074, 'colsample_bytree': 0.6432543543936109, 'eta': 1.0826036359561102, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.31382354451421374}. Best is trial 0 with value: 0.46.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:12,405] Trial 1 finished with value: 0.5871559633027523 and parameters: {'subsample': 0.9340546512985739, 'colsample_bytree': 0.9824357542378885, 'eta': 0.029235553541277902, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.23077217288652602}. Best is trial 1 with value: 0.5871559633027523.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:12,801] Trial 2 finished with value: 0.5360824742268041 and parameters: {'subsample': 0.9412471027798399, 'colsample_bytree': 0.9706541979220396, 'eta': 1.3241822239878847, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.6159714999244632}. Best is trial 1 with value: 0.5871559633027523.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:13,076] Trial 3 finished with value: 0.5116279069767442 and parameters: {'subsample': 0.9050050541519807, 'colsample_bytree': 0.43969877438331956, 'eta': 1.342524134967431, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.8791964956780766}. Best is trial 1 with value: 0.5871559633027523.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:13,339] Trial 4 finished with value: 0.5555555555555556 and parameters: {'subsample': 0.9319321241593304, 'colsample_bytree': 0.40101718101057326, 'eta': 0.9792413370105133, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.5578440594927956}. Best is trial 1 with value: 0.5871559633027523.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:13,659] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.914122983894907, 'colsample_bytree': 0.6332469954818976, 'eta': 1.48834126147866, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.35354572276688423}. Best is trial 1 with value: 0.5871559633027523.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:14,844] Trial 6 finished with value: 0.594059405940594 and parameters: {'subsample': 0.8074000127031289, 'colsample_bytree': 0.9351903480975583, 'eta': 0.2795506882451912, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.21571776644599117}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:15,837] Trial 7 finished with value: 0.5517241379310345 and parameters: {'subsample': 0.484935134538243, 'colsample_bytree': 0.825540910769063, 'eta': 0.14809415932870837, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.7487302467783943}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:16,267] Trial 8 finished with value: 0.5607476635514018 and parameters: {'subsample': 0.7457030582317608, 'colsample_bytree': 0.302075842904178, 'eta': 0.49448687247403833, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.3298488358047339}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:16,633] Trial 9 finished with value: 0.49523809523809526 and parameters: {'subsample': 0.8815387404809258, 'colsample_bytree': 0.32332927937499045, 'eta': 0.9578225411624125, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.4842347959960701}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:17,353] Trial 10 finished with value: 0.5849056603773585 and parameters: {'subsample': 0.6573513971107757, 'colsample_bytree': 0.7888516922075114, 'eta': 0.4619365179972712, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.10008142122888247}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:23,759] Trial 11 finished with value: 0.5742574257425742 and parameters: {'subsample': 0.7644254415945927, 'colsample_bytree': 0.9916910425632196, 'eta': 0.04455255745270485, 'max_depth': 10, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.1450432114898612}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:24,743] Trial 12 finished with value: 0.5714285714285714 and parameters: {'subsample': 0.7857992993147139, 'colsample_bytree': 0.8696782658893374, 'eta': 0.3926080011273457, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.23748488305154097}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:25,963] Trial 13 finished with value: 0.5277777777777778 and parameters: {'subsample': 0.5613068429933219, 'colsample_bytree': 0.7361501112766027, 'eta': 0.23378471891994854, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.46352304977827197}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:26,680] Trial 14 finished with value: 0.46938775510204084 and parameters: {'subsample': 0.31313851485203154, 'colsample_bytree': 0.9083348506491129, 'eta': 0.6007427387484334, 'max_depth': 9, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.21595953220322878}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:33,075] Trial 15 finished with value: 0.5825242718446602 and parameters: {'subsample': 0.9963610729832957, 'colsample_bytree': 0.5571905698116801, 'eta': 0.01295722451845224, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.3973700455913459}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:33,991] Trial 16 finished with value: 0.5373134328358209 and parameters: {'subsample': 0.8015093757575936, 'colsample_bytree': 0.9179368233692091, 'eta': 0.29099162926759875, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.2225168873383983}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:34,453] Trial 17 finished with value: 0.5227272727272727 and parameters: {'subsample': 0.6651753347226842, 'colsample_bytree': 0.7421706965454004, 'eta': 0.7111062247728002, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.6747721379336378}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:35,879] Trial 18 finished with value: 0.5742574257425742 and parameters: {'subsample': 0.8290790349731131, 'colsample_bytree': 0.9977071312500062, 'eta': 0.19752453916890053, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.9863046419367931}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:36,925] Trial 19 finished with value: 0.56 and parameters: {'subsample': 0.7083510843131208, 'colsample_bytree': 0.8477713088909775, 'eta': 0.3190179631355408, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.4508460032057626}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:37,637] Trial 20 finished with value: 0.5057471264367817 and parameters: {'subsample': 0.5890123823608749, 'colsample_bytree': 0.721548060987126, 'eta': 0.6434887835027719, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.27791118664235387}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:38,429] Trial 21 finished with value: 0.5542168674698795 and parameters: {'subsample': 0.6322521763367224, 'colsample_bytree': 0.7953861797357931, 'eta': 0.43471229886408874, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.10947644282433898}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:39,278] Trial 22 finished with value: 0.5853658536585366 and parameters: {'subsample': 0.858096881092819, 'colsample_bytree': 0.9196551176405806, 'eta': 0.5254083281974794, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.1000543134754896}. Best is trial 6 with value: 0.594059405940594.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:41,240] Trial 23 finished with value: 0.6019417475728155 and parameters: {'subsample': 0.8572225545448172, 'colsample_bytree': 0.9199019759417025, 'eta': 0.11412011744220346, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.20930937378108644}. Best is trial 23 with value: 0.6019417475728155.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:43,089] Trial 24 finished with value: 0.6067415730337079 and parameters: {'subsample': 0.9937267766664707, 'colsample_bytree': 0.9332304417630842, 'eta': 0.1418924553407683, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.19442907209399432}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:45,060] Trial 25 finished with value: 0.5934065934065934 and parameters: {'subsample': 0.9753968313771131, 'colsample_bytree': 0.8927461612776805, 'eta': 0.14110683121562215, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.17283865786069524}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:45,972] Trial 26 finished with value: 0.5137614678899083 and parameters: {'subsample': 0.8543371040762255, 'colsample_bytree': 0.9475734591828264, 'eta': 0.34508217131059304, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.3927692988608674}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:47,631] Trial 27 finished with value: 0.56 and parameters: {'subsample': 0.7241810686332646, 'colsample_bytree': 0.8125824945579764, 'eta': 0.15475326663010466, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.28695188638284974}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:48,175] Trial 28 finished with value: 0.5882352941176471 and parameters: {'subsample': 0.9765672389063136, 'colsample_bytree': 0.5234560692250935, 'eta': 0.8438582702526499, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.18961508686390818}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:49,182] Trial 29 finished with value: 0.5652173913043478 and parameters: {'subsample': 0.846995961393914, 'colsample_bytree': 0.6640682486859051, 'eta': 0.25079727886854086, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.2976131666465643}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:50,885] Trial 30 finished with value: 0.5631067961165048 and parameters: {'subsample': 0.8082611073368122, 'colsample_bytree': 0.8610943140841132, 'eta': 0.12154495711123536, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.37371884140816325}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:53,413] Trial 31 finished with value: 0.6041666666666666 and parameters: {'subsample': 0.9936725917279388, 'colsample_bytree': 0.8929322635295338, 'eta': 0.1101178715347049, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.1943566147643542}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:57,584] Trial 32 finished with value: 0.5714285714285714 and parameters: {'subsample': 0.9836669531095891, 'colsample_bytree': 0.9576730044995958, 'eta': 0.05962256223812145, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.25602912764985764}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:40:59,034] Trial 33 finished with value: 0.5945945945945946 and parameters: {'subsample': 0.9468838160122455, 'colsample_bytree': 0.9404406615419192, 'eta': 0.2515689085079984, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.16103349392182992}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:40:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:01,502] Trial 34 finished with value: 0.5647058823529412 and parameters: {'subsample': 0.9422429924696066, 'colsample_bytree': 0.8843297968863965, 'eta': 0.10677516704256163, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.16192330031716073}. Best is trial 24 with value: 0.6067415730337079.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:02,878] Trial 35 finished with value: 0.5641025641025641 and parameters: {'subsample': 0.8986664342593784, 'colsample_bytree': 0.77318274173039, 'eta': 0.20599147335446566, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.15653900300337165}. Best is trial 24 with value: 0.6067415730337079.

Best trial for Friends & Family: F1 score= 0.6067
Best hyperparameters: {'subsample': 0.9937267766664707, 'colsample_bytree': 0.9332304417630842, 'eta': 0.1418924553407683, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.19442907209399432}
Grateful Patient

[I 2026-05-25 15:41:26,728] Trial 0 finished with value: 0.5747126436781609 and parameters: {'subsample': 0.5520830616387284, 'colsample_bytree': 0.7252295096358188, 'eta': 0.8272136536229501, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.9627411572788249}. Best is trial 0 with value: 0.5747126436781609.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:27,435] Trial 1 finished with value: 0.525 and parameters: {'subsample': 0.48821333517120574, 'colsample_bytree': 0.8317206937379693, 'eta': 1.0238097367369041, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.17805537547814654}. Best is trial 0 with value: 0.5747126436781609.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:27,802] Trial 2 finished with value: 0.2682926829268293 and parameters: {'subsample': 0.9488774786609364, 'colsample_bytree': 0.7011000298459691, 'eta': 1.1782849967546336, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.2753734171945401}. Best is trial 0 with value: 0.5747126436781609.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:28,100] Trial 3 finished with value: 0.5633802816901409 and parameters: {'subsample': 0.935328993675119, 'colsample_bytree': 0.5328508265145903, 'eta': 0.948573571121883, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.7536945921223349}. Best is trial 0 with value: 0.5747126436781609.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:28,968] Trial 4 finished with value: 0.5882352941176471 and parameters: {'subsample': 0.9676922860655179, 'colsample_bytree': 0.9689142817221974, 'eta': 0.3283727138351856, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.7988752827356795}. Best is trial 4 with value: 0.5882352941176471.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:29,593] Trial 5 finished with value: 0.5684210526315789 and parameters: {'subsample': 0.38235699388806926, 'colsample_bytree': 0.727631403928032, 'eta': 0.43833088365030426, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.43105123385386634}. Best is trial 4 with value: 0.5882352941176471.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:30,125] Trial 6 finished with value: 0.5945945945945946 and parameters: {'subsample': 0.5851466143615164, 'colsample_bytree': 0.7715088958797471, 'eta': 0.6122729699541519, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.2471089475023318}. Best is trial 6 with value: 0.5945945945945946.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:30,930] Trial 7 finished with value: 0.575 and parameters: {'subsample': 0.5629842634154102, 'colsample_bytree': 0.6683972746473549, 'eta': 0.6249062973095494, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.13642550096831196}. Best is trial 6 with value: 0.5945945945945946.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:31,856] Trial 8 finished with value: 0.6136363636363636 and parameters: {'subsample': 0.551849796048947, 'colsample_bytree': 0.8347241408806565, 'eta': 0.41208720104513785, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.9790561844541426}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:32,968] Trial 9 finished with value: 0.5203252032520326 and parameters: {'subsample': 0.5296321116398108, 'colsample_bytree': 0.5152025991802446, 'eta': 0.24985062957606316, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.829445165852063}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:44,903] Trial 10 finished with value: 0.6136363636363636 and parameters: {'subsample': 0.6987203131269629, 'colsample_bytree': 0.3183230199529419, 'eta': 0.015074584627551069, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.5819940925039995}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:49,196] Trial 11 finished with value: 0.6 and parameters: {'subsample': 0.7428451155883258, 'colsample_bytree': 0.3057882088229818, 'eta': 0.0491791534061955, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.5729764426694564}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:56,273] Trial 12 finished with value: 0.611764705882353 and parameters: {'subsample': 0.7408699917914451, 'colsample_bytree': 0.31576537491176404, 'eta': 0.031928127727288536, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.5617554392573002}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:57,652] Trial 13 finished with value: 0.6052631578947368 and parameters: {'subsample': 0.7579590448436944, 'colsample_bytree': 0.9270364790446816, 'eta': 0.22903681361795886, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.9855621371688598}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:58,604] Trial 14 finished with value: 0.5581395348837209 and parameters: {'subsample': 0.31848579633930074, 'colsample_bytree': 0.5453489417455358, 'eta': 0.505745921335812, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.40669835465988324}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:41:59,012] Trial 15 finished with value: 0.449438202247191 and parameters: {'subsample': 0.6535974502167848, 'colsample_bytree': 0.43301390020861674, 'eta': 1.4691905268933398, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.6740775667340734}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:41:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:01,083] Trial 16 finished with value: 0.6086956521739131 and parameters: {'subsample': 0.8505761562601118, 'colsample_bytree': 0.8599975528207779, 'eta': 0.1550468600622514, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.40373667754561426}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:01,817] Trial 17 finished with value: 0.5405405405405406 and parameters: {'subsample': 0.42716869843949445, 'colsample_bytree': 0.5918285751363028, 'eta': 0.38555517006640944, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.8889822774816899}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:02,200] Trial 18 finished with value: 0.5384615384615384 and parameters: {'subsample': 0.6650755970853545, 'colsample_bytree': 0.42444278298259397, 'eta': 0.6699613571457601, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.6875101612211503}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:05,012] Trial 19 finished with value: 0.6075949367088608 and parameters: {'subsample': 0.7951340840436989, 'colsample_bytree': 0.858192175419035, 'eta': 0.1235642653786087, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.6503559640311396}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:05,948] Trial 20 finished with value: 0.5869565217391305 and parameters: {'subsample': 0.6624327030095168, 'colsample_bytree': 0.4320416602903269, 'eta': 0.5082609171186034, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.47706948158551515}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:16,111] Trial 21 finished with value: 0.5934065934065934 and parameters: {'subsample': 0.7142950441356564, 'colsample_bytree': 0.3073101823476958, 'eta': 0.020511234659737233, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.5390311352729769}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:17,143] Trial 22 finished with value: 0.6075949367088608 and parameters: {'subsample': 0.8496500622665037, 'colsample_bytree': 0.3746880713648041, 'eta': 0.2691357803230136, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.5951562080032166}. Best is trial 8 with value: 0.6136363636363636.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:22,852] Trial 23 finished with value: 0.6285714285714286 and parameters: {'subsample': 0.6218649351513597, 'colsample_bytree': 0.3547187444695581, 'eta': 0.03592863798722081, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.33705632395099727}. Best is trial 23 with value: 0.6285714285714286.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:25,260] Trial 24 finished with value: 0.6017699115044248 and parameters: {'subsample': 0.6129353947119844, 'colsample_bytree': 0.6066648845967679, 'eta': 0.17131552345451262, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.3262507261026835}. Best is trial 23 with value: 0.6285714285714286.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:26,055] Trial 25 finished with value: 0.547945205479452 and parameters: {'subsample': 0.5010804622585541, 'colsample_bytree': 0.37758492467891047, 'eta': 0.3867870800172876, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.33090193848577515}. Best is trial 23 with value: 0.6285714285714286.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:29,834] Trial 26 finished with value: 0.6105263157894737 and parameters: {'subsample': 0.454335374821055, 'colsample_bytree': 0.793067024653643, 'eta': 0.10730445194963001, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.897769787761524}. Best is trial 23 with value: 0.6285714285714286.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:30,384] Trial 27 finished with value: 0.5977011494252874 and parameters: {'subsample': 0.6269538531872005, 'colsample_bytree': 0.46806939545316273, 'eta': 0.7858891844103087, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.20683809003788428}. Best is trial 23 with value: 0.6285714285714286.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:31,534] Trial 28 finished with value: 0.5858585858585859 and parameters: {'subsample': 0.6927647372509299, 'colsample_bytree': 0.3576601040531136, 'eta': 0.2847251686885942, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.10588548625796912}. Best is trial 23 with value: 0.6285714285714286.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:34,141] Trial 29 finished with value: 0.6341463414634146 and parameters: {'subsample': 0.5821309927177943, 'colsample_bytree': 0.999000045849141, 'eta': 0.17261099660692245, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.5037142583364228}. Best is trial 29 with value: 0.6341463414634146.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:35,182] Trial 30 finished with value: 0.5454545454545454 and parameters: {'subsample': 0.5545463095533126, 'colsample_bytree': 0.9982769928732317, 'eta': 0.5065463504020545, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.5017802111170425}. Best is trial 29 with value: 0.6341463414634146.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:36,507] Trial 31 finished with value: 0.5915492957746479 and parameters: {'subsample': 0.6071695587528646, 'colsample_bytree': 0.7733219752608713, 'eta': 0.17876052050028296, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.30699665966952866}. Best is trial 29 with value: 0.6341463414634146.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:39,398] Trial 32 finished with value: 0.6122448979591837 and parameters: {'subsample': 0.5012106920433363, 'colsample_bytree': 0.9152431323479031, 'eta': 0.08958471405423152, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.3715819081409888}. Best is trial 29 with value: 0.6341463414634146.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:49,449] Trial 33 finished with value: 0.6236559139784946 and parameters: {'subsample': 0.5368223057572318, 'colsample_bytree': 0.9427129705736228, 'eta': 0.0185296179430686, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.4732394543984649}. Best is trial 29 with value: 0.6341463414634146.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:50,375] Trial 34 finished with value: 0.5945945945945946 and parameters: {'subsample': 0.4548971203373833, 'colsample_bytree': 0.9610009782094144, 'eta': 0.33786479191660856, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.48900492374331045}. Best is trial 29 with value: 0.6341463414634146.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:42:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:42:51,050] Trial 35 finished with value: 0.5274725274725275 and parameters: {'subsample': 0.5294911516783424, 'colsample_bytree': 0.9176004886913182, 'eta': 1.0397293043851383, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.4439115407116105}. Best is trial 29 with value: 0.6341463414634146.

Best trial for Grateful Patient: F1 score= 0.6667
Best hyperparameters: {'subsample': 0.35520758277319314, 'colsample_bytree': 0.7394678574740327, 'eta': 0.013844654697125015, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.9392483546983912}
Health Education

[I 2026-05-25 15:43:12,439] Trial 0 finished with value: 0.7469879518072289 and parameters: {'subsample': 0.5678414479218753, 'colsample_bytree': 0.7873505235670805, 'eta': 0.3077300811288566, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.9310816019621607}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:12,695] Trial 1 finished with value: 0.7228915662650602 and parameters: {'subsample': 0.9404217747231605, 'colsample_bytree': 0.5268297216154573, 'eta': 0.4287860795200592, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.962733447980073}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:12,937] Trial 2 finished with value: 0.6588235294117647 and parameters: {'subsample': 0.9181365878305043, 'colsample_bytree': 0.6934192229303446, 'eta': 1.0882921114285171, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.6618480736728416}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:13,451] Trial 3 finished with value: 0.6753246753246753 and parameters: {'subsample': 0.8824595071423837, 'colsample_bytree': 0.7747935715810977, 'eta': 0.7231485355161748, 'max_depth': 10, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.16125279446394683}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:13,715] Trial 4 finished with value: 0.6744186046511628 and parameters: {'subsample': 0.3796420094038001, 'colsample_bytree': 0.7701907345954816, 'eta': 0.9260495817017261, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.21233164414922717}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:13,863] Trial 5 finished with value: 0.717391304347826 and parameters: {'subsample': 0.7028584065508123, 'colsample_bytree': 0.5202585865577494, 'eta': 1.136046169846667, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.23348095087282875}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:14,212] Trial 6 finished with value: 0.4 and parameters: {'subsample': 0.36904051958967277, 'colsample_bytree': 0.9646538155540638, 'eta': 0.845100231623476, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.17274209383463068}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:15,405] Trial 7 finished with value: 0.7228915662650602 and parameters: {'subsample': 0.963047984459757, 'colsample_bytree': 0.4415267735614752, 'eta': 0.08540194982117592, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.9601097186071319}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:15,840] Trial 8 finished with value: 0.7 and parameters: {'subsample': 0.5775097716577193, 'colsample_bytree': 0.6425003491433843, 'eta': 0.3276619944077091, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.873873593204336}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:16,481] Trial 9 finished with value: 0.7407407407407407 and parameters: {'subsample': 0.7330526964228269, 'colsample_bytree': 0.5719143815090069, 'eta': 0.20359100353259896, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.375494734471447}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:16,835] Trial 10 finished with value: 0.6730769230769231 and parameters: {'subsample': 0.542657063012921, 'colsample_bytree': 0.3586448508324749, 'eta': 0.5647411426915588, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.7058650715541748}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:17,063] Trial 11 finished with value: 0.6363636363636364 and parameters: {'subsample': 0.7381588565991355, 'colsample_bytree': 0.8961779377200039, 'eta': 1.498246229199979, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.4354757759655074}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:18,402] Trial 12 finished with value: 0.7272727272727273 and parameters: {'subsample': 0.48747085241567134, 'colsample_bytree': 0.6093404403535011, 'eta': 0.027976186342295317, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.4267659269690101}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:19,120] Trial 13 finished with value: 0.7142857142857143 and parameters: {'subsample': 0.792882788755485, 'colsample_bytree': 0.8318868008013767, 'eta': 0.2394144332547037, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.42092930304052245}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:19,380] Trial 14 finished with value: 0.7294117647058823 and parameters: {'subsample': 0.6284619248125531, 'colsample_bytree': 0.7203589735415141, 'eta': 0.5044398706857793, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.5770271930658984}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:19,945] Trial 15 finished with value: 0.7 and parameters: {'subsample': 0.8008781731474188, 'colsample_bytree': 0.568369141547256, 'eta': 0.23195256450697987, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.798148911316347}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:20,281] Trial 16 finished with value: 0.6987951807228916 and parameters: {'subsample': 0.4386378279936526, 'colsample_bytree': 0.32835064146727666, 'eta': 0.6174056726850198, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.3255619384270078}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:20,855] Trial 17 finished with value: 0.7380952380952381 and parameters: {'subsample': 0.6552519035931761, 'colsample_bytree': 0.8680541734560194, 'eta': 0.17443787128647595, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.541559402106579}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:21,206] Trial 18 finished with value: 0.7469879518072289 and parameters: {'subsample': 0.8289605834918938, 'colsample_bytree': 0.978577039602907, 'eta': 0.38299273593565186, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.3227597294118103}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:21,400] Trial 19 finished with value: 0.7111111111111111 and parameters: {'subsample': 0.8123243106388249, 'colsample_bytree': 0.9953098114408752, 'eta': 0.7355769333861686, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.5282830286322436}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:21,708] Trial 20 finished with value: 0.7228915662650602 and parameters: {'subsample': 0.8524636336016236, 'colsample_bytree': 0.9167577277698776, 'eta': 0.37129476838597214, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.2923697992762084}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:22,109] Trial 21 finished with value: 0.7160493827160493 and parameters: {'subsample': 0.7205132436241583, 'colsample_bytree': 0.8215621283643364, 'eta': 0.3270168664594171, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.3315464393917031}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:22,830] Trial 22 finished with value: 0.7441860465116279 and parameters: {'subsample': 0.6170891825759277, 'colsample_bytree': 0.6918986281623357, 'eta': 0.13285415250182125, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.37635718366711246}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:24,557] Trial 23 finished with value: 0.735632183908046 and parameters: {'subsample': 0.5780750663315555, 'colsample_bytree': 0.6942059938927055, 'eta': 0.03954278251869402, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.1202416169944007}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:24,938] Trial 24 finished with value: 0.6746987951807228 and parameters: {'subsample': 0.5116325827084359, 'colsample_bytree': 0.7624187917013646, 'eta': 0.5184966223091638, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.48406146211237944}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:25,641] Trial 25 finished with value: 0.7441860465116279 and parameters: {'subsample': 0.6155173462238988, 'colsample_bytree': 0.9422075503723818, 'eta': 0.1570945665560021, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.6281759773011306}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:26,140] Trial 26 finished with value: 0.6966292134831461 and parameters: {'subsample': 0.4640660264799155, 'colsample_bytree': 0.8196544639598955, 'eta': 0.422334722505509, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7505522783613936}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:26,623] Trial 27 finished with value: 0.735632183908046 and parameters: {'subsample': 0.6771288214061812, 'colsample_bytree': 0.6525079824949614, 'eta': 0.29395739042988195, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.2806959550227016}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:26,865] Trial 28 finished with value: 0.7126436781609196 and parameters: {'subsample': 0.5802903994916233, 'colsample_bytree': 0.8678452094028832, 'eta': 0.6490159890159753, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.4759321692053604}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:27,134] Trial 29 finished with value: 0.7209302325581395 and parameters: {'subsample': 0.3179610659124738, 'colsample_bytree': 0.7297033470318206, 'eta': 0.439363948295186, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.9933359503015218}. Best is trial 0 with value: 0.7469879518072289.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:27,997] Trial 30 finished with value: 0.7529411764705882 and parameters: {'subsample': 0.9791097211927906, 'colsample_bytree': 0.47153793780414316, 'eta': 0.10523180957089531, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.9005257736070702}. Best is trial 30 with value: 0.7529411764705882.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:28,769] Trial 31 finished with value: 0.7380952380952381 and parameters: {'subsample': 0.922144203762188, 'colsample_bytree': 0.4677859666987991, 'eta': 0.11155097123205224, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.8574609061101868}. Best is trial 30 with value: 0.7529411764705882.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:35,586] Trial 32 finished with value: 0.7380952380952381 and parameters: {'subsample': 0.9922242283959201, 'colsample_bytree': 0.46536430404570084, 'eta': 0.011550515729229216, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.9313133050358963}. Best is trial 30 with value: 0.7529411764705882.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:36,450] Trial 33 finished with value: 0.7228915662650602 and parameters: {'subsample': 0.8910478065443593, 'colsample_bytree': 0.6603216505062534, 'eta': 0.13350292314475096, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.8764991026616299}. Best is trial 30 with value: 0.7529411764705882.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:36,951] Trial 34 finished with value: 0.7045454545454546 and parameters: {'subsample': 0.8498281309485782, 'colsample_bytree': 0.39204996794332664, 'eta': 0.28243229212962606, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.7902820764584308}. Best is trial 30 with value: 0.7529411764705882.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:37,295] Trial 35 finished with value: 0.7088607594936709 and parameters: {'subsample': 0.7660409190006292, 'colsample_bytree': 0.517845347620133, 'eta': 0.4088075031340335, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.6447212897995014}. Best is trial 30 with value: 0.7529411764705882.

Best trial for Health Education: F1 score= 0.7529
Best hyperparameters: {'subsample': 0.9791097211927906, 'colsample_bytree': 0.47153793780414316, 'eta': 0.10523180957089531, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.9005257736070702}
Laboratory/Testing

[I 2026-05-25 15:43:43,114] Trial 0 finished with value: 0.9415384615384615 and parameters: {'subsample': 0.8076544674027304, 'colsample_bytree': 0.6005511726835149, 'eta': 1.2180646235749542, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.4330728384580892}. Best is trial 0 with value: 0.9415384615384615.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:43,363] Trial 1 finished with value: 0.9053254437869822 and parameters: {'subsample': 0.37888941048772373, 'colsample_bytree': 0.3431137141656582, 'eta': 1.152236189538142, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.7031589155547279}. Best is trial 0 with value: 0.9415384615384615.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:43,672] Trial 2 finished with value: 0.9285714285714286 and parameters: {'subsample': 0.3421089828037978, 'colsample_bytree': 0.4126352573880102, 'eta': 0.8420099911975111, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.7741019103933161}. Best is trial 0 with value: 0.9415384615384615.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:43,814] Trial 3 finished with value: 0.9198813056379822 and parameters: {'subsample': 0.33271350419772966, 'colsample_bytree': 0.6996669894841789, 'eta': 1.2949996199531018, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.5221697279959092}. Best is trial 0 with value: 0.9415384615384615.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:44,135] Trial 4 finished with value: 0.9483282674772037 and parameters: {'subsample': 0.5682740823755382, 'colsample_bytree': 0.3919869897145149, 'eta': 0.2758433389129897, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.391972935296767}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:44,251] Trial 5 finished with value: 0.9404388714733543 and parameters: {'subsample': 0.5956369136303163, 'colsample_bytree': 0.7387156457988532, 'eta': 1.2082376967372956, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.5091122137563658}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:44,413] Trial 6 finished with value: 0.9382716049382716 and parameters: {'subsample': 0.9730037465601538, 'colsample_bytree': 0.6239809177145306, 'eta': 1.3109858412620876, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.8941313755397676}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:44,599] Trial 7 finished with value: 0.9480122324159022 and parameters: {'subsample': 0.7990641424346241, 'colsample_bytree': 0.35830346827865783, 'eta': 0.8310265089441116, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.8387768902417845}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:45,151] Trial 8 finished with value: 0.9309309309309309 and parameters: {'subsample': 0.46630635712569607, 'colsample_bytree': 0.9410736769901424, 'eta': 1.1385830255385785, 'max_depth': 9, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.991221312310532}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:45,583] Trial 9 finished with value: 0.9300911854103343 and parameters: {'subsample': 0.388234891536395, 'colsample_bytree': 0.5513289514024595, 'eta': 0.6076595778980673, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.4834830047559717}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:46,613] Trial 10 finished with value: 0.9423076923076923 and parameters: {'subsample': 0.591603036944935, 'colsample_bytree': 0.4900262527045396, 'eta': 0.039074095299991035, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.1821202145963282}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:46,984] Trial 11 finished with value: 0.9440993788819876 and parameters: {'subsample': 0.7528198699647501, 'colsample_bytree': 0.31973544398730736, 'eta': 0.32123989617161264, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.3045809291390278}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:47,210] Trial 12 finished with value: 0.9444444444444444 and parameters: {'subsample': 0.7423717026241587, 'colsample_bytree': 0.450712810963966, 'eta': 0.7332696996528031, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.7012566965985179}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:47,478] Trial 13 finished with value: 0.9451219512195121 and parameters: {'subsample': 0.8918468386011764, 'colsample_bytree': 0.30971452174897807, 'eta': 0.40166277227246583, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.31988535625648284}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:47,978] Trial 14 finished with value: 0.9283489096573209 and parameters: {'subsample': 0.5243453914751047, 'colsample_bytree': 0.8216942310363753, 'eta': 0.9515513577410434, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.12161885145122164}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:48,071] Trial 15 finished with value: 0.9043478260869565 and parameters: {'subsample': 0.6647967957135326, 'colsample_bytree': 0.41358577402043567, 'eta': 1.4978843668539898, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.6320105049342828}. Best is trial 4 with value: 0.9483282674772037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:54,489] Trial 16 finished with value: 0.9544072948328267 and parameters: {'subsample': 0.6831129205052076, 'colsample_bytree': 0.5221005725201978, 'eta': 0.017834369312552334, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.3512186582761765}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:43:58,776] Trial 17 finished with value: 0.9544072948328267 and parameters: {'subsample': 0.6740198096415647, 'colsample_bytree': 0.5257484276178134, 'eta': 0.020802222986145487, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.3504437750277386}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:43:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:00,449] Trial 18 finished with value: 0.9515151515151515 and parameters: {'subsample': 0.6849624489724183, 'colsample_bytree': 0.5333314938395395, 'eta': 0.10951983938744858, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.26214753758138476}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:01,144] Trial 19 finished with value: 0.9457831325301205 and parameters: {'subsample': 0.8793031601004353, 'colsample_bytree': 0.7756634046377081, 'eta': 0.4867733705720466, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.22035382800770298}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:02,723] Trial 20 finished with value: 0.9457831325301205 and parameters: {'subsample': 0.47141078511886847, 'colsample_bytree': 0.6768016996253902, 'eta': 0.17887495248526825, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.36911834438185653}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:06,941] Trial 21 finished with value: 0.9515151515151515 and parameters: {'subsample': 0.6539727998470164, 'colsample_bytree': 0.5316035144234253, 'eta': 0.026227907999480243, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.24924028793275177}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:08,391] Trial 22 finished with value: 0.9515151515151515 and parameters: {'subsample': 0.7071583976982905, 'colsample_bytree': 0.5567584715941538, 'eta': 0.16939483067763306, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.10650615762653948}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:10,200] Trial 23 finished with value: 0.9518072289156626 and parameters: {'subsample': 0.683785770789236, 'colsample_bytree': 0.506871983195743, 'eta': 0.11799260636237661, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.29144590769100537}. Best is trial 16 with value: 0.9544072948328267.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:11,169] Trial 24 finished with value: 0.9602446483180428 and parameters: {'subsample': 0.7992829271538655, 'colsample_bytree': 0.4643797581841315, 'eta': 0.25713883205026433, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.43475281894381773}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:11,871] Trial 25 finished with value: 0.9570552147239264 and parameters: {'subsample': 0.8383541948680415, 'colsample_bytree': 0.46283689097044434, 'eta': 0.27820860473119885, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.6093064317080924}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:12,264] Trial 26 finished with value: 0.9535603715170279 and parameters: {'subsample': 0.8707703101407662, 'colsample_bytree': 0.4592574901137037, 'eta': 0.5283225314844597, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.6077989657788623}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:12,840] Trial 27 finished with value: 0.948948948948949 and parameters: {'subsample': 0.9553378858797381, 'colsample_bytree': 0.5976979646334843, 'eta': 0.2733660122648241, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.5928005182178735}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:13,364] Trial 28 finished with value: 0.9486404833836858 and parameters: {'subsample': 0.8075726620887669, 'colsample_bytree': 0.46791007365285364, 'eta': 0.3890049979947332, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.41112253810410293}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:13,844] Trial 29 finished with value: 0.9373134328358209 and parameters: {'subsample': 0.757297129327708, 'colsample_bytree': 0.5833961654483855, 'eta': 0.66364671808196, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.46011689219041557}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:14,805] Trial 30 finished with value: 0.9538461538461539 and parameters: {'subsample': 0.8382354352538717, 'colsample_bytree': 0.6520188834162182, 'eta': 0.2314342542438993, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.5656436076838794}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:17,430] Trial 31 finished with value: 0.9538461538461539 and parameters: {'subsample': 0.7796962480570111, 'colsample_bytree': 0.4308105846763337, 'eta': 0.047904507903214565, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.44067581906945313}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:17,906] Trial 32 finished with value: 0.9503105590062112 and parameters: {'subsample': 0.6288134501690414, 'colsample_bytree': 0.38017323170874473, 'eta': 0.4073689735375182, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.3459789517679929}. Best is trial 24 with value: 0.9602446483180428.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:18,903] Trial 33 finished with value: 0.9604863221884499 and parameters: {'subsample': 0.9205562110901776, 'colsample_bytree': 0.5141810514940717, 'eta': 0.15853439208701395, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.7086075969782478}. Best is trial 33 with value: 0.9604863221884499.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:19,795] Trial 34 finished with value: 0.9546827794561934 and parameters: {'subsample': 0.9217398881441213, 'colsample_bytree': 0.4852672637628028, 'eta': 0.17864674601360334, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.6916955292921859}. Best is trial 33 with value: 0.9604863221884499.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Laboratory/Testing: F1 score= 0.9605
Best hyperparameters: {'subsample': 0.9205562110901776, 'colsample_bytree': 0.5141810514940717, 'eta': 0.15853439208701395, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.7086075969782478}
Medications

[I 2026-05-25 15:44:26,770] Trial 0 finished with value: 0.8769230769230769 and parameters: {'subsample': 0.8102160454162748, 'colsample_bytree': 0.5239764154368522, 'eta': 0.5064163125948951, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.9592390089524644}. Best is trial 0 with value: 0.8769230769230769.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:27,300] Trial 1 finished with value: 0.8837209302325582 and parameters: {'subsample': 0.7702295398917485, 'colsample_bytree': 0.6892844343332165, 'eta': 0.5858863585504243, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.5429647668823373}. Best is trial 1 with value: 0.8837209302325582.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:27,626] Trial 2 finished with value: 0.859375 and parameters: {'subsample': 0.8162642697333282, 'colsample_bytree': 0.31072144912759253, 'eta': 1.0086969733222408, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.3354048379731383}. Best is trial 1 with value: 0.8837209302325582.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:28,484] Trial 3 finished with value: 0.9037037037037037 and parameters: {'subsample': 0.7619328574826675, 'colsample_bytree': 0.5536448279873933, 'eta': 0.17478035425689026, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.8601941662576781}. Best is trial 3 with value: 0.9037037037037037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:28,780] Trial 4 finished with value: 0.8253968253968254 and parameters: {'subsample': 0.7332415599943759, 'colsample_bytree': 0.4195019998054198, 'eta': 1.3563951624988717, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.4341490869642729}. Best is trial 3 with value: 0.9037037037037037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:29,016] Trial 5 finished with value: 0.7862068965517242 and parameters: {'subsample': 0.48078067944345676, 'colsample_bytree': 0.47003989280598363, 'eta': 1.3940248584564638, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.5352270976185779}. Best is trial 3 with value: 0.9037037037037037.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:30,480] Trial 6 finished with value: 0.9185185185185185 and parameters: {'subsample': 0.9407652477977966, 'colsample_bytree': 0.6952023436375998, 'eta': 0.1166745296635892, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.32867235999843625}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:30,770] Trial 7 finished with value: 0.8235294117647058 and parameters: {'subsample': 0.703582332754735, 'colsample_bytree': 0.6335436826957658, 'eta': 1.2525486505672083, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.5974720118010506}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:31,194] Trial 8 finished with value: 0.8592592592592593 and parameters: {'subsample': 0.7243901103977028, 'colsample_bytree': 0.6932198747694635, 'eta': 1.2605082322636505, 'max_depth': 9, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.5136538093035355}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:31,506] Trial 9 finished with value: 0.7936507936507936 and parameters: {'subsample': 0.37834786689727506, 'colsample_bytree': 0.3935308784958579, 'eta': 1.3295028961786866, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.9027168903973438}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:32,982] Trial 10 finished with value: 0.8976377952755905 and parameters: {'subsample': 0.9835202086662359, 'colsample_bytree': 0.9194161544057163, 'eta': 0.033179825630369475, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.10403793939603012}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:35,651] Trial 11 finished with value: 0.9007633587786259 and parameters: {'subsample': 0.9797394110714682, 'colsample_bytree': 0.8411776584583988, 'eta': 0.08219877755854499, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.7834968195501222}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:36,108] Trial 12 finished with value: 0.890625 and parameters: {'subsample': 0.5758829912443282, 'colsample_bytree': 0.5837885383103754, 'eta': 0.3163014814016493, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.20606663438665448}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:36,980] Trial 13 finished with value: 0.8970588235294118 and parameters: {'subsample': 0.8501877027043233, 'colsample_bytree': 0.7424314122647809, 'eta': 0.3160079700930486, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.709693634671276}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:37,570] Trial 14 finished with value: 0.9172932330827067 and parameters: {'subsample': 0.8876769145750802, 'colsample_bytree': 0.8351615785798954, 'eta': 0.25197945486411943, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.29717497982083096}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:37,921] Trial 15 finished with value: 0.8823529411764706 and parameters: {'subsample': 0.9349334408533618, 'colsample_bytree': 0.9884410885919633, 'eta': 0.8149894236969698, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.3085804488527608}. Best is trial 6 with value: 0.9185185185185185.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:38,420] Trial 16 finished with value: 0.9312977099236641 and parameters: {'subsample': 0.8887711526599652, 'colsample_bytree': 0.8004240824104984, 'eta': 0.3760477445513547, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.33621012433982067}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:38,816] Trial 17 finished with value: 0.9242424242424242 and parameters: {'subsample': 0.9042441812057372, 'colsample_bytree': 0.7837008146668053, 'eta': 0.4714174961201115, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.4201539542448414}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:39,263] Trial 18 finished with value: 0.9047619047619048 and parameters: {'subsample': 0.5997297619874512, 'colsample_bytree': 0.7853609466626184, 'eta': 0.5996804456574402, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.4278236100006976}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:39,499] Trial 19 finished with value: 0.8873239436619719 and parameters: {'subsample': 0.6492171100753948, 'colsample_bytree': 0.9120303780363019, 'eta': 0.7797359286169757, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.6767652861022371}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:39,999] Trial 20 finished with value: 0.9022556390977443 and parameters: {'subsample': 0.8857347675815128, 'colsample_bytree': 0.7957488423490143, 'eta': 0.4596351440206183, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.1895083019694506}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:40,577] Trial 21 finished with value: 0.9022556390977443 and parameters: {'subsample': 0.9247617490698868, 'colsample_bytree': 0.7291830836164174, 'eta': 0.4057805942239035, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.3804982159710497}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:41,723] Trial 22 finished with value: 0.9312977099236641 and parameters: {'subsample': 0.9872963518777502, 'colsample_bytree': 0.6489781158618698, 'eta': 0.12520179435863038, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.2332114989163674}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:41,992] Trial 23 finished with value: 0.8992248062015504 and parameters: {'subsample': 0.8701789227861312, 'colsample_bytree': 0.6446213978998309, 'eta': 0.6350303077641181, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.21101301423753008}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:42,945] Trial 24 finished with value: 0.9185185185185185 and parameters: {'subsample': 0.9948627161499616, 'colsample_bytree': 0.8847278861758698, 'eta': 0.2165649881903574, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.1260882123749857}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:43,752] Trial 25 finished with value: 0.8888888888888888 and parameters: {'subsample': 0.8245063659856747, 'colsample_bytree': 0.7662039161609725, 'eta': 0.3787661489804404, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.4443635607377779}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:44,028] Trial 26 finished with value: 0.8243243243243243 and parameters: {'subsample': 0.32370822827848916, 'colsample_bytree': 0.6028072306696343, 'eta': 0.8799920440490142, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.26245177690329624}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:44,550] Trial 27 finished with value: 0.9312977099236641 and parameters: {'subsample': 0.9210880107254701, 'colsample_bytree': 0.9928211595226826, 'eta': 0.6620763987204977, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.37397109873813617}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:44,895] Trial 28 finished with value: 0.8837209302325582 and parameters: {'subsample': 0.9505443397755851, 'colsample_bytree': 0.9693062889277899, 'eta': 0.954393652167856, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.2359308154197889}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:45,279] Trial 29 finished with value: 0.8854961832061069 and parameters: {'subsample': 0.8051668305923082, 'colsample_bytree': 0.5248945293383903, 'eta': 0.7157405700429275, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.16256839360840805}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:45,617] Trial 30 finished with value: 0.9133858267716536 and parameters: {'subsample': 0.673531434893573, 'colsample_bytree': 0.851067997237247, 'eta': 0.5615012228600407, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.49567539706639274}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:46,060] Trial 31 finished with value: 0.916030534351145 and parameters: {'subsample': 0.8981065574916203, 'colsample_bytree': 0.8027015872462002, 'eta': 0.4633845938064782, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.3837336647865994}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:46,531] Trial 32 finished with value: 0.9022556390977443 and parameters: {'subsample': 0.8517162470797378, 'colsample_bytree': 0.9436462933279783, 'eta': 0.5228371171076184, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.37696320427585456}. Best is trial 16 with value: 0.9312977099236641.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:46,938] Trial 33 finished with value: 0.9393939393939394 and parameters: {'subsample': 0.9213436744853308, 'colsample_bytree': 0.7129776744936722, 'eta': 0.6619911422233133, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.28103358723011795}. Best is trial 33 with value: 0.9393939393939394.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:47,389] Trial 34 finished with value: 0.9104477611940298 and parameters: {'subsample': 0.9475987300105483, 'colsample_bytree': 0.685942363656508, 'eta': 0.6928571738838673, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.2635311305831606}. Best is trial 33 with value: 0.9393939393939394.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:44:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:44:48,496] Trial 35 finished with value: 0.8888888888888888 and parameters: {'subsample': 0.7815613927545855, 'colsample_bytree': 0.600853439736598, 'eta': 0.15473833231620227, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.35231852094228877}. Best is trial 33 with value: 0.9393939393939394.

Best trial for Medications: F1 score= 0.9394
Best hyperparameters: {'subsample': 0.9213436744853308, 'colsample_bytree': 0.7129776744936722, 'eta': 0.6619911422233133, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.28103358723011795}
No Symptoms

[I 2026-05-25 15:45:00,637] Trial 1 finished with value: 0.8346456692913385 and parameters: {'subsample': 0.49614072895215955, 'colsample_bytree': 0.3378782915858558, 'eta': 0.9560473328099891, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.504604341306618}. Best is trial 0 with value: 0.8514056224899599.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:00,922] Trial 2 finished with value: 0.8644400785854617 and parameters: {'subsample': 0.9624741946439812, 'colsample_bytree': 0.3904643704761442, 'eta': 1.134071120718018, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.8214765202455424}. Best is trial 2 with value: 0.8644400785854617.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:01,766] Trial 3 finished with value: 0.8651911468812877 and parameters: {'subsample': 0.6125914176677976, 'colsample_bytree': 0.6722423905965902, 'eta': 0.22606228447472282, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.4071497365959086}. Best is trial 3 with value: 0.8651911468812877.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:02,072] Trial 4 finished with value: 0.8469184890656064 and parameters: {'subsample': 0.9956870367773674, 'colsample_bytree': 0.5559193901555847, 'eta': 1.4310956437634097, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.7353853009788196}. Best is trial 3 with value: 0.8651911468812877.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:02,242] Trial 5 finished with value: 0.85 and parameters: {'subsample': 0.9936705593506783, 'colsample_bytree': 0.5913797431875839, 'eta': 1.188417245772605, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.7811161568502929}. Best is trial 3 with value: 0.8651911468812877.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:03,170] Trial 6 finished with value: 0.8651911468812877 and parameters: {'subsample': 0.4797926154920499, 'colsample_bytree': 0.6145443392099412, 'eta': 0.14509004440860923, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.30091310614005884}. Best is trial 3 with value: 0.8651911468812877.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:06,480] Trial 7 finished with value: 0.8879837067209776 and parameters: {'subsample': 0.3311289032180108, 'colsample_bytree': 0.6277452147584675, 'eta': 0.05082308102130302, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.7882939319112697}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:06,813] Trial 8 finished with value: 0.8617886178861789 and parameters: {'subsample': 0.5052828925399763, 'colsample_bytree': 0.3433868213257015, 'eta': 0.3222370000640879, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.8796939995921271}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:07,185] Trial 9 finished with value: 0.835820895522388 and parameters: {'subsample': 0.36503475551900166, 'colsample_bytree': 0.5562666148483686, 'eta': 0.9279128739827153, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.2351401527946193}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:07,854] Trial 10 finished with value: 0.8582995951417004 and parameters: {'subsample': 0.7814364195912171, 'colsample_bytree': 0.9370737379731449, 'eta': 0.6342651462847821, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.9901754389306532}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:09,691] Trial 11 finished with value: 0.8699186991869918 and parameters: {'subsample': 0.7124257244363926, 'colsample_bytree': 0.7689689927577287, 'eta': 0.10512959733697042, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.4498422274588337}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:16,020] Trial 12 finished with value: 0.8740157480314961 and parameters: {'subsample': 0.7571001643641334, 'colsample_bytree': 0.8103061481232192, 'eta': 0.027904010450900213, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.6444487931632067}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:29,314] Trial 13 finished with value: 0.8654970760233918 and parameters: {'subsample': 0.8323429673689874, 'colsample_bytree': 0.875515239016041, 'eta': 0.011180435713966458, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.6992085819484143}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:30,044] Trial 14 finished with value: 0.8634538152610441 and parameters: {'subsample': 0.6291606837402298, 'colsample_bytree': 0.8201566463044455, 'eta': 0.40199065555161906, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.6123674792494045}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:30,261] Trial 15 finished with value: 0.8624229979466119 and parameters: {'subsample': 0.8591264372239894, 'colsample_bytree': 0.9914757053108745, 'eta': 0.48623947799313527, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.11335436101380048}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:35,927] Trial 16 finished with value: 0.8709677419354839 and parameters: {'subsample': 0.7392871872561076, 'colsample_bytree': 0.43664937261951164, 'eta': 0.022641179327357167, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.9156492681003567}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:36,381] Trial 17 finished with value: 0.8256513026052105 and parameters: {'subsample': 0.30472408876391976, 'colsample_bytree': 0.6999234204050713, 'eta': 0.7043652680499702, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.6638201076231925}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:37,527] Trial 18 finished with value: 0.8649706457925636 and parameters: {'subsample': 0.5439366787061817, 'colsample_bytree': 0.8586431484236061, 'eta': 0.23008908391916977, 'max_depth': 9, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.5662905012663387}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:38,170] Trial 19 finished with value: 0.8717948717948718 and parameters: {'subsample': 0.8768765684974454, 'colsample_bytree': 0.46470458392795455, 'eta': 0.32313178446326307, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.8379506428890642}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:38,574] Trial 20 finished with value: 0.8673267326732673 and parameters: {'subsample': 0.6789143051258324, 'colsample_bytree': 0.7920073297907785, 'eta': 0.8620872878601349, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.9422056085429122}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:39,299] Trial 21 finished with value: 0.8712871287128713 and parameters: {'subsample': 0.9001004662352737, 'colsample_bytree': 0.46387497236274794, 'eta': 0.2901852561344249, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.8384780334738773}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:40,983] Trial 22 finished with value: 0.8747591522157996 and parameters: {'subsample': 0.7839499859402659, 'colsample_bytree': 0.5168820467952431, 'eta': 0.11987936674066443, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.7557303194828262}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:42,405] Trial 23 finished with value: 0.8685714285714285 and parameters: {'subsample': 0.7971984789429708, 'colsample_bytree': 0.5155966567470106, 'eta': 0.15780743323825022, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.7456488125720822}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:43,088] Trial 24 finished with value: 0.8628230616302187 and parameters: {'subsample': 0.5983867222543482, 'colsample_bytree': 0.6315951216811406, 'eta': 0.4682909916224105, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.6564422322924984}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:45,965] Trial 25 finished with value: 0.8713692946058091 and parameters: {'subsample': 0.7536310446832165, 'colsample_bytree': 0.707537458082499, 'eta': 0.0829118818252592, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.5022646145219539}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:46,655] Trial 26 finished with value: 0.8629032258064516 and parameters: {'subsample': 0.6818462174250766, 'colsample_bytree': 0.5364137611943728, 'eta': 0.2099995338832867, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.7763997739171427}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:49,654] Trial 27 finished with value: 0.8707753479125249 and parameters: {'subsample': 0.4389195215603474, 'colsample_bytree': 0.6542082100800442, 'eta': 0.040821013183845054, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.6925114344645452}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:50,797] Trial 28 finished with value: 0.8693957115009746 and parameters: {'subsample': 0.933071795219593, 'colsample_bytree': 0.9130266299192087, 'eta': 0.34334919249379364, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.6068786832736194}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:51,551] Trial 29 finished with value: 0.8624229979466119 and parameters: {'subsample': 0.5660703770811977, 'colsample_bytree': 0.7240496068875049, 'eta': 0.5694193588566925, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.3737819499288086}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:52,574] Trial 30 finished with value: 0.863905325443787 and parameters: {'subsample': 0.39880589031288893, 'colsample_bytree': 0.7774770773831795, 'eta': 0.39483239766282036, 'max_depth': 9, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.5627052302790965}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:54,373] Trial 31 finished with value: 0.8669354838709677 and parameters: {'subsample': 0.85906549057754, 'colsample_bytree': 0.48567201634679324, 'eta': 0.14976655444426157, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.8407600287993584}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:55,598] Trial 32 finished with value: 0.874251497005988 and parameters: {'subsample': 0.812327417781147, 'colsample_bytree': 0.4453380912945492, 'eta': 0.2709085680318404, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.8930705034234421}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:56,626] Trial 33 finished with value: 0.8629856850715747 and parameters: {'subsample': 0.7985113805738889, 'colsample_bytree': 0.3809364827892326, 'eta': 0.20774378176362496, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.9928378212532641}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:45:59,392] Trial 34 finished with value: 0.8598848368522073 and parameters: {'subsample': 0.7232914544001845, 'colsample_bytree': 0.41136662738591484, 'eta': 0.09867043429461425, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.8987820940194852}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:45:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:01,372] Trial 35 finished with value: 0.8744939271255061 and parameters: {'subsample': 0.8217036688939197, 'colsample_bytree': 0.30283642564927465, 'eta': 0.2519062744654033, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.7730148650448571}. Best is trial 7 with value: 0.8879837067209776.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:02,642] Trial 36 finished with value: 0.8594377510040161 and parameters: {'subsample': 0.9216710102519412, 'colsample_bytree': 0.5762623992432222, 'eta': 0.26740157911417545, 'max_depth': 10, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.7533900545012214}. Best is trial 7 with value: 0.8879837067209776.

Best trial for No Symptoms: F1 score= 0.8880
Best hyperparameters: {'subsample': 0.3311289032180108, 'colsample_bytree': 0.6277452147584675, 'eta': 0.05082308102130302, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.7882939319112697}
Non-urgent

[I 2026-05-25 15:46:13,900] Trial 0 finished with value: 0.9488117001828154 and parameters: {'subsample': 0.6810106468661925, 'colsample_bytree': 0.7763728444636937, 'eta': 0.6082632242249987, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.6006788922916536}. Best is trial 0 with value: 0.9488117001828154.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:15,765] Trial 1 finished with value: 0.9547553093259464 and parameters: {'subsample': 0.8761502307084645, 'colsample_bytree': 0.8247823557931944, 'eta': 0.0957621427565806, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.5296367909894996}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:16,520] Trial 2 finished with value: 0.9502762430939227 and parameters: {'subsample': 0.5182373361761988, 'colsample_bytree': 0.7709382526539461, 'eta': 0.4353506887678491, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.15804174050190375}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:16,814] Trial 3 finished with value: 0.9448529411764706 and parameters: {'subsample': 0.7173674592231707, 'colsample_bytree': 0.7676577618862717, 'eta': 0.8909942320520692, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.6826022355176457}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:17,143] Trial 4 finished with value: 0.9429097605893186 and parameters: {'subsample': 0.4909904264231972, 'colsample_bytree': 0.4807077464560805, 'eta': 0.6313551662626854, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.6863296675625102}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:17,381] Trial 5 finished with value: 0.9456521739130435 and parameters: {'subsample': 0.9695956578971445, 'colsample_bytree': 0.9006434878602376, 'eta': 0.7275827419477988, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.7831879131862799}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:17,662] Trial 6 finished with value: 0.9485294117647058 and parameters: {'subsample': 0.9581011166738496, 'colsample_bytree': 0.4737089967782295, 'eta': 0.439447433679338, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.4419753233481438}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:18,047] Trial 7 finished with value: 0.9482439926062847 and parameters: {'subsample': 0.41644137209126775, 'colsample_bytree': 0.6880811693126057, 'eta': 0.6137009599398141, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.49793960784379365}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:18,233] Trial 8 finished with value: 0.9507892293407614 and parameters: {'subsample': 0.7085230249935899, 'colsample_bytree': 0.5528050391668862, 'eta': 1.1033824923845708, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.30333022472227683}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:18,390] Trial 9 finished with value: 0.9248554913294798 and parameters: {'subsample': 0.709324014819162, 'colsample_bytree': 0.35458556951930836, 'eta': 1.4956425596579948, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.4703939559787592}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:19,329] Trial 10 finished with value: 0.9486461251167133 and parameters: {'subsample': 0.844708661148373, 'colsample_bytree': 0.98648929507399, 'eta': 0.09967430102150304, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.9758300818642196}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:19,578] Trial 11 finished with value: 0.9526462395543176 and parameters: {'subsample': 0.8198902203528613, 'colsample_bytree': 0.5463961225085199, 'eta': 1.1608823057029052, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.2583090327029322}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:19,813] Trial 12 finished with value: 0.9460966542750929 and parameters: {'subsample': 0.8506435330260739, 'colsample_bytree': 0.6131486746300251, 'eta': 1.236682450630931, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.11150596239686661}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:24,015] Trial 13 finished with value: 0.9538745387453874 and parameters: {'subsample': 0.8358140691527906, 'colsample_bytree': 0.906742950614111, 'eta': 0.031864126709402016, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.29281578411637277}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:30,985] Trial 14 finished with value: 0.9512419503219871 and parameters: {'subsample': 0.8777126723241365, 'colsample_bytree': 0.8779954112316416, 'eta': 0.01310291312687309, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.3394029720143421}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:32,294] Trial 15 finished with value: 0.9535095715587967 and parameters: {'subsample': 0.5807179273223049, 'colsample_bytree': 0.9861030031988285, 'eta': 0.21154054704357605, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.35390803934134635}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:32,674] Trial 16 finished with value: 0.9491211840888066 and parameters: {'subsample': 0.7792863553670517, 'colsample_bytree': 0.8678041625477435, 'eta': 0.2906039829671563, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.8670105871241985}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:33,395] Trial 17 finished with value: 0.9527340129749768 and parameters: {'subsample': 0.9134142169674266, 'colsample_bytree': 0.7147864672234469, 'eta': 0.2880928750020371, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.595031564055565}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:34,883] Trial 18 finished with value: 0.9473684210526315 and parameters: {'subsample': 0.33699750080432744, 'colsample_bytree': 0.8310478572847589, 'eta': 0.11819011798953066, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.21047941159123695}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:35,421] Trial 19 finished with value: 0.9463955637707948 and parameters: {'subsample': 0.7727940008452653, 'colsample_bytree': 0.9215618546230618, 'eta': 0.43062473958827563, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.3989314936848155}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:35,749] Trial 20 finished with value: 0.9518518518518518 and parameters: {'subsample': 0.6139341220447907, 'colsample_bytree': 0.8175482924525739, 'eta': 0.9547567531225934, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.5348008397491436}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:37,250] Trial 21 finished with value: 0.9497716894977168 and parameters: {'subsample': 0.5992567399261238, 'colsample_bytree': 0.9746765991323363, 'eta': 0.21967298052623951, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.3687205850635219}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:40,894] Trial 22 finished with value: 0.9520295202952029 and parameters: {'subsample': 0.5406190138495234, 'colsample_bytree': 0.9464902469863655, 'eta': 0.030728166229039733, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.22575608970181144}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:41,821] Trial 23 finished with value: 0.9545032497678737 and parameters: {'subsample': 0.997739319304032, 'colsample_bytree': 0.9824493944326133, 'eta': 0.25474400674416925, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.3040571462914854}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:42,284] Trial 24 finished with value: 0.9539594843462247 and parameters: {'subsample': 0.9912796158174203, 'colsample_bytree': 0.8377888759161704, 'eta': 0.3371702599386927, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.2837522274514682}. Best is trial 1 with value: 0.9547553093259464.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:42,933] Trial 25 finished with value: 0.9578754578754579 and parameters: {'subsample': 0.9986232341637362, 'colsample_bytree': 0.6770498003825837, 'eta': 0.4022844962136187, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.17909702582856496}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:43,391] Trial 26 finished with value: 0.9540768509840675 and parameters: {'subsample': 0.9231560296790968, 'colsample_bytree': 0.6356244680644574, 'eta': 0.49903232272297426, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.10904252493231821}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:44,733] Trial 27 finished with value: 0.9546716003700277 and parameters: {'subsample': 0.9217057760080837, 'colsample_bytree': 0.7042949024113432, 'eta': 0.20057399803779974, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.18043992155071417}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:45,189] Trial 28 finished with value: 0.95 and parameters: {'subsample': 0.9136945362359101, 'colsample_bytree': 0.713105642553439, 'eta': 0.18388750313982863, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.18320658338208112}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:45,659] Trial 29 finished with value: 0.9512419503219871 and parameters: {'subsample': 0.7772571140313781, 'colsample_bytree': 0.7456143564692993, 'eta': 0.5507292968239931, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.6984116772741874}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:46,140] Trial 30 finished with value: 0.9543336439888164 and parameters: {'subsample': 0.9340085076221085, 'colsample_bytree': 0.6695684126027561, 'eta': 0.3798397869583579, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.5957222378153211}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:47,855] Trial 31 finished with value: 0.9560439560439561 and parameters: {'subsample': 0.9769916347779077, 'colsample_bytree': 0.5893701744627442, 'eta': 0.1592309826415127, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.16127010478922976}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:49,595] Trial 32 finished with value: 0.9573283858998145 and parameters: {'subsample': 0.8966899293445778, 'colsample_bytree': 0.5881044875332739, 'eta': 0.12527908884035227, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.15998471276550075}. Best is trial 25 with value: 0.9578754578754579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:52,076] Trial 33 finished with value: 0.9589552238805971 and parameters: {'subsample': 0.8740609970250006, 'colsample_bytree': 0.5862961395615558, 'eta': 0.1239267766339551, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.10009799709888595}. Best is trial 33 with value: 0.9589552238805971.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:46:53,102] Trial 34 finished with value: 0.9545875810936052 and parameters: {'subsample': 0.8964261377503406, 'colsample_bytree': 0.5789792051682386, 'eta': 0.35751415114455987, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.14778282116123612}. Best is trial 33 with value: 0.9589552238805971.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:46:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Non-urgent: F1 score= 0.9590
Best hyperparameters: {'subsample': 0.8740609970250006, 'colsample_bytree': 0.5862961395615558, 'eta': 0.1239267766339551, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.10009799709888595}
Outpatient Logistics/Scheduling

[I 2026-05-25 15:47:16,030] Trial 0 finished with value: 0.3247863247863248 and parameters: {'subsample': 0.3331547376534924, 'colsample_bytree': 0.8911025153788072, 'eta': 1.2920538840988094, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.722475381905157}. Best is trial 0 with value: 0.3247863247863248.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:16,421] Trial 1 finished with value: 0.6271186440677966 and parameters: {'subsample': 0.802131324362519, 'colsample_bytree': 0.8808828772220867, 'eta': 0.734280209228263, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.912012898607247}. Best is trial 1 with value: 0.6271186440677966.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:17,113] Trial 2 finished with value: 0.6666666666666666 and parameters: {'subsample': 0.7768817751826035, 'colsample_bytree': 0.4529523579557913, 'eta': 0.32230577280990375, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.7593031025316657}. Best is trial 2 with value: 0.6666666666666666.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:17,751] Trial 3 finished with value: 0.6338028169014085 and parameters: {'subsample': 0.6695147971898211, 'colsample_bytree': 0.5167252510372478, 'eta': 0.6102289359437238, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.40432621759498377}. Best is trial 2 with value: 0.6666666666666666.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:18,003] Trial 4 finished with value: 0.6721311475409836 and parameters: {'subsample': 0.8767412900549247, 'colsample_bytree': 0.7848258350637296, 'eta': 0.7972839939202362, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.3959503749665024}. Best is trial 4 with value: 0.6721311475409836.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:18,402] Trial 5 finished with value: 0.5899280575539568 and parameters: {'subsample': 0.32719976122575983, 'colsample_bytree': 0.4263143956332247, 'eta': 0.7024166888521886, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.6010771818212672}. Best is trial 4 with value: 0.6721311475409836.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:19,171] Trial 6 finished with value: 0.6 and parameters: {'subsample': 0.5112595077323685, 'colsample_bytree': 0.9706816051997815, 'eta': 0.7014379668966059, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.8042263971345773}. Best is trial 4 with value: 0.6721311475409836.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:19,854] Trial 7 finished with value: 0.5895953757225434 and parameters: {'subsample': 0.41215745561596195, 'colsample_bytree': 0.8695134173386163, 'eta': 0.40200807723487725, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.30391867775397713}. Best is trial 4 with value: 0.6721311475409836.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:20,169] Trial 8 finished with value: 0.5511811023622047 and parameters: {'subsample': 0.7612946771349367, 'colsample_bytree': 0.6445373946065744, 'eta': 1.2429499055455757, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.6817419083791086}. Best is trial 4 with value: 0.6721311475409836.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:21,491] Trial 9 finished with value: 0.6615384615384615 and parameters: {'subsample': 0.6170439306799413, 'colsample_bytree': 0.5598464223546111, 'eta': 0.09629134033783394, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.8949255601009274}. Best is trial 4 with value: 0.6721311475409836.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:21,635] Trial 10 finished with value: 0.6766917293233082 and parameters: {'subsample': 0.9765319099650974, 'colsample_bytree': 0.30202713071001724, 'eta': 1.0266915339418878, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.10138738813461567}. Best is trial 10 with value: 0.6766917293233082.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:21,758] Trial 11 finished with value: 0.696969696969697 and parameters: {'subsample': 0.9941614660797583, 'colsample_bytree': 0.7398095045462205, 'eta': 0.9576424304205193, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.14995459272091075}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:21,895] Trial 12 finished with value: 0.6511627906976745 and parameters: {'subsample': 0.996628521409869, 'colsample_bytree': 0.7282901640025097, 'eta': 1.0951204613219399, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.10273655111745189}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:22,018] Trial 13 finished with value: 0.676056338028169 and parameters: {'subsample': 0.989834222403938, 'colsample_bytree': 0.30953267602388046, 'eta': 1.0078964541362487, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.116122360483936}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:22,166] Trial 14 finished with value: 0.6074074074074074 and parameters: {'subsample': 0.8976442089544379, 'colsample_bytree': 0.3109168819687211, 'eta': 1.4938934840046278, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.23469061267638958}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:22,292] Trial 15 finished with value: 0.624 and parameters: {'subsample': 0.9081791184489528, 'colsample_bytree': 0.6513899139779832, 'eta': 0.9816251616206856, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.22742547685649994}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:22,522] Trial 16 finished with value: 0.5873015873015873 and parameters: {'subsample': 0.6416798717337895, 'colsample_bytree': 0.7350067873037227, 'eta': 0.8984065813854164, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.48468854325555116}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:22,922] Trial 17 finished with value: 0.5846153846153846 and parameters: {'subsample': 0.9535348452214626, 'colsample_bytree': 0.6264868019933598, 'eta': 1.206143016696085, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.20567719595079575}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:23,059] Trial 18 finished with value: 0.6285714285714286 and parameters: {'subsample': 0.8461514177946434, 'colsample_bytree': 0.4354657580763987, 'eta': 1.4524133276467655, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.32988591278896556}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:23,669] Trial 19 finished with value: 0.6323529411764706 and parameters: {'subsample': 0.7305169846182058, 'colsample_bytree': 0.814287268734512, 'eta': 0.52998296185027, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.5297580439720221}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:23,797] Trial 20 finished with value: 0.5798816568047337 and parameters: {'subsample': 0.5080421944574849, 'colsample_bytree': 0.548926547159091, 'eta': 0.8587393765619461, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.16721414406940677}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:23,980] Trial 21 finished with value: 0.6764705882352942 and parameters: {'subsample': 0.9944712832696505, 'colsample_bytree': 0.32928037598227305, 'eta': 1.0569172171122623, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.10512452148030146}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:24,157] Trial 22 finished with value: 0.65625 and parameters: {'subsample': 0.9381582367846525, 'colsample_bytree': 0.37163487157233016, 'eta': 1.1334519471190432, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.2875525817324479}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:24,350] Trial 23 finished with value: 0.6153846153846154 and parameters: {'subsample': 0.8307546363208783, 'colsample_bytree': 0.3806249381281883, 'eta': 0.9235433080723797, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.12526709024211985}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:24,605] Trial 24 finished with value: 0.6142857142857143 and parameters: {'subsample': 0.9937795432504521, 'colsample_bytree': 0.35576616864180366, 'eta': 1.029072016411088, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.3971438977096969}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:24,770] Trial 25 finished with value: 0.6271186440677966 and parameters: {'subsample': 0.9421448390991612, 'colsample_bytree': 0.48702897960856695, 'eta': 1.3647619888914504, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.17412678006814092}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:25,017] Trial 26 finished with value: 0.5873015873015873 and parameters: {'subsample': 0.8927071630935685, 'colsample_bytree': 0.6951785012667671, 'eta': 1.132825749553434, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.2502763497312819}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:25,251] Trial 27 finished with value: 0.5945945945945946 and parameters: {'subsample': 0.7239152180245059, 'colsample_bytree': 0.40064045799094117, 'eta': 0.831428845247066, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.9875249728688}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:25,398] Trial 28 finished with value: 0.6323529411764706 and parameters: {'subsample': 0.8496929784616876, 'colsample_bytree': 0.5940632051117671, 'eta': 1.3459943173481648, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.16233819933238292}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:25,554] Trial 29 finished with value: 0.5909090909090909 and parameters: {'subsample': 0.9470023884564766, 'colsample_bytree': 0.3387912868864405, 'eta': 1.2140213721414053, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.1015869437429221}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:25,722] Trial 30 finished with value: 0.5972222222222222 and parameters: {'subsample': 0.5318769240026435, 'colsample_bytree': 0.9714048573280983, 'eta': 1.0754523996162917, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.3252165876376253}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:25,918] Trial 31 finished with value: 0.6724137931034483 and parameters: {'subsample': 0.9925511286422338, 'colsample_bytree': 0.3322098237404877, 'eta': 0.9789130824463965, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.1530646662436831}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:26,131] Trial 32 finished with value: 0.6504065040650406 and parameters: {'subsample': 0.9602846938639513, 'colsample_bytree': 0.3012534616469436, 'eta': 0.9562772446163325, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.10050955081646676}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:26,323] Trial 33 finished with value: 0.6666666666666666 and parameters: {'subsample': 0.9153083540974638, 'colsample_bytree': 0.46428703027821006, 'eta': 1.0536911614798388, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.19580590443656004}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:26,630] Trial 34 finished with value: 0.6466165413533834 and parameters: {'subsample': 0.8104824868876394, 'colsample_bytree': 0.3884056812792509, 'eta': 0.6026542408213391, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.267816897723391}. Best is trial 11 with value: 0.696969696969697.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:26,976] Trial 35 finished with value: 0.6771653543307087 and parameters: {'subsample': 0.9972414275035869, 'colsample_bytree': 0.4987687388553922, 'eta': 0.7569812933949134, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.20047911456106549}. Best is trial 11 with value: 0.696969696969697.

Best trial for Outpatient Logistics/Scheduling: F1 score= 0.6992
Best hyperparameters: {'subsample': 0.8687902317652172, 'colsample_bytree': 0.9386582679686446, 'eta': 0.24233602425415662, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.6372323866218496}
Physical

[I 2026-05-25 15:47:45,564] Trial 0 finished with value: 0.7586206896551724 and parameters: {'subsample': 0.9670389172035783, 'colsample_bytree': 0.3741063790724344, 'eta': 0.03931493796795881, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.3771977462925593}. Best is trial 0 with value: 0.7586206896551724.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:45,809] Trial 1 finished with value: 0.7263157894736842 and parameters: {'subsample': 0.9005211292896422, 'colsample_bytree': 0.6103350231081973, 'eta': 1.072756097115174, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.4810324336527134}. Best is trial 0 with value: 0.7586206896551724.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:45,987] Trial 2 finished with value: 0.6601941747572816 and parameters: {'subsample': 0.5262865149678143, 'colsample_bytree': 0.6491052479148769, 'eta': 0.8305412660547351, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.5940154704280313}. Best is trial 0 with value: 0.7586206896551724.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:46,163] Trial 3 finished with value: 0.7064676616915423 and parameters: {'subsample': 0.36738456959118404, 'colsample_bytree': 0.7978721392234067, 'eta': 0.6756792620336155, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.8877960831036039}. Best is trial 0 with value: 0.7586206896551724.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:46,438] Trial 4 finished with value: 0.7374301675977654 and parameters: {'subsample': 0.5793214019208147, 'colsample_bytree': 0.6047054586274377, 'eta': 0.644958386188888, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.23510969159485143}. Best is trial 0 with value: 0.7586206896551724.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:50,914] Trial 5 finished with value: 0.7624309392265194 and parameters: {'subsample': 0.913487213469464, 'colsample_bytree': 0.4224651146744763, 'eta': 0.01908792901901458, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.5997067005810398}. Best is trial 5 with value: 0.7624309392265194.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:52,068] Trial 6 finished with value: 0.7191011235955056 and parameters: {'subsample': 0.5819128717512894, 'colsample_bytree': 0.5290787542325541, 'eta': 0.3074271097319788, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.10177035282200322}. Best is trial 5 with value: 0.7624309392265194.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:52,373] Trial 7 finished with value: 0.7243243243243244 and parameters: {'subsample': 0.9007962346054099, 'colsample_bytree': 0.7094458680592448, 'eta': 0.5551199981844338, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.9321926562396387}. Best is trial 5 with value: 0.7624309392265194.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:52,964] Trial 8 finished with value: 0.5964912280701754 and parameters: {'subsample': 0.5751545911866596, 'colsample_bytree': 0.7823559135772593, 'eta': 1.3984905089542827, 'max_depth': 10, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.6509975947571536}. Best is trial 5 with value: 0.7624309392265194.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:53,694] Trial 9 finished with value: 0.7165775401069518 and parameters: {'subsample': 0.6729430751224075, 'colsample_bytree': 0.49578962465645726, 'eta': 0.4330762961517404, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.7770506083229822}. Best is trial 5 with value: 0.7624309392265194.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:47:54,775] Trial 10 finished with value: 0.7570621468926554 and parameters: {'subsample': 0.7704516921140705, 'colsample_bytree': 0.30578751305955676, 'eta': 0.1122594362467349, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.725479774028577}. Best is trial 5 with value: 0.7624309392265194.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:47:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:00,484] Trial 11 finished with value: 0.774869109947644 and parameters: {'subsample': 0.9974816824409369, 'colsample_bytree': 0.3170366620087172, 'eta': 0.0186197423527326, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.405287062893273}. Best is trial 11 with value: 0.774869109947644.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:01,157] Trial 12 finished with value: 0.7872340425531915 and parameters: {'subsample': 0.9971852334276758, 'colsample_bytree': 0.4148461922469522, 'eta': 0.23156816579017503, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.42684316078759665}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:02,237] Trial 13 finished with value: 0.7745664739884393 and parameters: {'subsample': 0.7924067689887845, 'colsample_bytree': 0.9982337763183269, 'eta': 0.2799940249199124, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.3981637267784711}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:02,809] Trial 14 finished with value: 0.7675675675675676 and parameters: {'subsample': 0.9923709314485393, 'colsample_bytree': 0.3175917721716548, 'eta': 0.254656990521971, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.28755606350826257}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:03,244] Trial 15 finished with value: 0.7142857142857143 and parameters: {'subsample': 0.7601266049817123, 'colsample_bytree': 0.4442960108428947, 'eta': 0.8553306131173842, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.4859233719020574}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:04,046] Trial 16 finished with value: 0.7604166666666666 and parameters: {'subsample': 0.8438352900707281, 'colsample_bytree': 0.3770247022207347, 'eta': 0.19550165346152618, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.23270106277512637}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:04,728] Trial 17 finished with value: 0.7529411764705882 and parameters: {'subsample': 0.9975299636642205, 'colsample_bytree': 0.521590825257216, 'eta': 0.4541335603430467, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.3363320193537901}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:05,104] Trial 18 finished with value: 0.5674418604651162 and parameters: {'subsample': 0.3585238976489886, 'colsample_bytree': 0.3006101159569609, 'eta': 1.2076663068211495, 'max_depth': 9, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.47937688133306666}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:05,723] Trial 19 finished with value: 0.7724867724867724 and parameters: {'subsample': 0.4489611507621848, 'colsample_bytree': 0.9448216231237125, 'eta': 0.42264235608737555, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.42506481971312815}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:06,231] Trial 20 finished with value: 0.7272727272727273 and parameters: {'subsample': 0.8440060105388352, 'colsample_bytree': 0.4533491798175592, 'eta': 0.9715368699251238, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.14084710649274673}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:07,498] Trial 21 finished with value: 0.751269035532995 and parameters: {'subsample': 0.7221867610364876, 'colsample_bytree': 0.9788995260293496, 'eta': 0.21126854148728452, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.37685111961901363}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:08,232] Trial 22 finished with value: 0.7653061224489796 and parameters: {'subsample': 0.8285986558441667, 'colsample_bytree': 0.8403196264560152, 'eta': 0.3484823655232185, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.5233555175452527}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:10,564] Trial 23 finished with value: 0.7608695652173914 and parameters: {'subsample': 0.9210798032475329, 'colsample_bytree': 0.8976075701593259, 'eta': 0.12952426720934734, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.2912724453212848}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:20,646] Trial 24 finished with value: 0.7613636363636364 and parameters: {'subsample': 0.8214396168028533, 'colsample_bytree': 0.7207247073532138, 'eta': 0.011314926953201687, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.41197950095899905}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:21,037] Trial 25 finished with value: 0.7528089887640449 and parameters: {'subsample': 0.9532715637270938, 'colsample_bytree': 0.3683821382947896, 'eta': 0.5521050859270737, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.19109551349623005}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:23,009] Trial 26 finished with value: 0.7567567567567568 and parameters: {'subsample': 0.6791439462148311, 'colsample_bytree': 0.8771088990614115, 'eta': 0.16700626251691703, 'max_depth': 9, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.3123222422099074}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:23,611] Trial 27 finished with value: 0.7638190954773869 and parameters: {'subsample': 0.8708909977598275, 'colsample_bytree': 0.5658685876184925, 'eta': 0.3146972242021175, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.5466670070824373}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:24,212] Trial 28 finished with value: 0.7578947368421053 and parameters: {'subsample': 0.7713869727031464, 'colsample_bytree': 0.4185599470892081, 'eta': 0.5281869495649306, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.42126463432658623}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:25,757] Trial 29 finished with value: 0.7604166666666666 and parameters: {'subsample': 0.9509769699919048, 'colsample_bytree': 0.3717851630341802, 'eta': 0.10082280643458047, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.3770917660383012}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:26,483] Trial 30 finished with value: 0.7657142857142857 and parameters: {'subsample': 0.9993958460599133, 'colsample_bytree': 0.6960426919471401, 'eta': 0.3648766113195836, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.702385578491449}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:27,008] Trial 31 finished with value: 0.7218934911242604 and parameters: {'subsample': 0.4377411738243492, 'colsample_bytree': 0.9690065730953079, 'eta': 0.4180446161346354, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.441443753781688}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:27,568] Trial 32 finished with value: 0.7391304347826086 and parameters: {'subsample': 0.47144263938429354, 'colsample_bytree': 0.9349072503751783, 'eta': 0.2509930180544262, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.37537504682163675}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:28,778] Trial 33 finished with value: 0.7513812154696132 and parameters: {'subsample': 0.42771383110891936, 'colsample_bytree': 0.9971492551701778, 'eta': 0.07197466380670425, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.4610138198994649}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:29,104] Trial 34 finished with value: 0.6532663316582915 and parameters: {'subsample': 0.3056561897012776, 'colsample_bytree': 0.9380208237450098, 'eta': 0.7119457779280582, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.5938573107657131}. Best is trial 12 with value: 0.7872340425531915.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Physical: F1 score= 0.7872
Best hyperparameters: {'subsample': 0.9971852334276758, 'colsample_bytree': 0.4148461922469522, 'eta': 0.23156816579017503, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.42684316078759665}
Physical Environment/Climate

[I 2026-05-25 15:48:40,655] Trial 1 finished with value: 0.7894736842105263 and parameters: {'subsample': 0.9580311324681743, 'colsample_bytree': 0.5179795029414838, 'eta': 0.5453744666936587, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.7016519942833096}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:41,078] Trial 2 finished with value: 0.7368421052631579 and parameters: {'subsample': 0.663810265238141, 'colsample_bytree': 0.5919807303477755, 'eta': 0.5182821555598378, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.35081629077550847}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:41,538] Trial 3 finished with value: 0.75 and parameters: {'subsample': 0.8716234445205551, 'colsample_bytree': 0.6291893437295107, 'eta': 0.5133166522816828, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.6521059181043857}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:41,887] Trial 4 finished with value: 0.7 and parameters: {'subsample': 0.5125405442548179, 'colsample_bytree': 0.7121771768358683, 'eta': 1.4416330640637374, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.1492804592545422}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:42,789] Trial 5 finished with value: 0.8108108108108109 and parameters: {'subsample': 0.8916436167309416, 'colsample_bytree': 0.9295805559589865, 'eta': 0.17851519824931644, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.17864234925731498}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:43,049] Trial 6 finished with value: 0.7804878048780488 and parameters: {'subsample': 0.5048230278121364, 'colsample_bytree': 0.7336985123810014, 'eta': 1.0796022423309715, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.9390882169270985}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:43,434] Trial 7 finished with value: 0.8 and parameters: {'subsample': 0.9213580475021979, 'colsample_bytree': 0.6784848536885144, 'eta': 0.9566358919626627, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.715984033463564}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:43,899] Trial 8 finished with value: 0.7368421052631579 and parameters: {'subsample': 0.7864872611311854, 'colsample_bytree': 0.5544833051907454, 'eta': 0.7169819251722463, 'max_depth': 10, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.36936865743311464}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:44,152] Trial 9 finished with value: 0.6976744186046512 and parameters: {'subsample': 0.40749864820052056, 'colsample_bytree': 0.7901551209874205, 'eta': 1.3629043793889368, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.8881292938169618}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:44,312] Trial 10 finished with value: 0.6666666666666666 and parameters: {'subsample': 0.6950435591316625, 'colsample_bytree': 0.3040555112603911, 'eta': 1.1373969817382503, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.45830479465026086}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:46,317] Trial 11 finished with value: 0.7692307692307693 and parameters: {'subsample': 0.8240637157828132, 'colsample_bytree': 0.9772318924981822, 'eta': 0.0982163862471226, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.17491855208585844}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:48,246] Trial 12 finished with value: 0.7804878048780488 and parameters: {'subsample': 0.7524326140890788, 'colsample_bytree': 0.3123821250422815, 'eta': 0.03344052413420129, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.2978542402037403}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:48,869] Trial 13 finished with value: 0.7777777777777778 and parameters: {'subsample': 0.9984496306798492, 'colsample_bytree': 0.9702041442781048, 'eta': 0.2729573632882323, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.5448762365489574}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:49,028] Trial 14 finished with value: 0.7441860465116279 and parameters: {'subsample': 0.5974010491035681, 'colsample_bytree': 0.4614867452390181, 'eta': 0.8617654478875181, 'max_depth': 1, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.22189535970276486}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:49,289] Trial 15 finished with value: 0.7222222222222222 and parameters: {'subsample': 0.863944749699072, 'colsample_bytree': 0.8329160956933855, 'eta': 1.2222899305863637, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.48214431405764696}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:50,143] Trial 16 finished with value: 0.75 and parameters: {'subsample': 0.3000004346924125, 'colsample_bytree': 0.8985222744482793, 'eta': 0.31800027588810076, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.8212609433420623}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:50,343] Trial 17 finished with value: 0.7567567567567568 and parameters: {'subsample': 0.7411730520863297, 'colsample_bytree': 0.41648864088577214, 'eta': 0.8996241867869779, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.27017061121679015}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:50,644] Trial 18 finished with value: 0.75 and parameters: {'subsample': 0.6043412997867067, 'colsample_bytree': 0.40304312968937644, 'eta': 0.730799708923764, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.41438003905083187}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:50,882] Trial 19 finished with value: 0.7441860465116279 and parameters: {'subsample': 0.907675706775973, 'colsample_bytree': 0.8353506523479485, 'eta': 1.2622559738472021, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.6285442358041856}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:51,481] Trial 20 finished with value: 0.7804878048780488 and parameters: {'subsample': 0.7977766230734531, 'colsample_bytree': 0.9095581663737642, 'eta': 0.23654175719796397, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.110153822275816}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:51,795] Trial 21 finished with value: 0.7692307692307693 and parameters: {'subsample': 0.9341100458558926, 'colsample_bytree': 0.6810637773199448, 'eta': 1.0205632376858156, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.7435270723822369}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:52,034] Trial 22 finished with value: 0.7906976744186046 and parameters: {'subsample': 0.8615803523827897, 'colsample_bytree': 0.49471517311854285, 'eta': 0.9466771147031963, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7876180467053379}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:52,330] Trial 23 finished with value: 0.7804878048780488 and parameters: {'subsample': 0.9782759199324023, 'colsample_bytree': 0.7732374803283673, 'eta': 0.6352758053344737, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.5625884346164933}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:52,565] Trial 24 finished with value: 0.7317073170731707 and parameters: {'subsample': 0.9139765280999996, 'colsample_bytree': 0.6424565396265309, 'eta': 0.8586044312650352, 'max_depth': 2, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.9983371757592416}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:52,740] Trial 25 finished with value: 0.7692307692307693 and parameters: {'subsample': 0.7322202788316214, 'colsample_bytree': 0.8989676075892352, 'eta': 1.1840381708705217, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.5679102525915704}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:53,123] Trial 26 finished with value: 0.7804878048780488 and parameters: {'subsample': 0.8288085872579811, 'colsample_bytree': 0.3695620306824521, 'eta': 0.37758323129462534, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.8538593712082787}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:53,332] Trial 27 finished with value: 0.7567567567567568 and parameters: {'subsample': 0.9015637540024486, 'colsample_bytree': 0.5483279661190006, 'eta': 1.0114329084155274, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.7063013036985412}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:53,532] Trial 28 finished with value: 0.7647058823529411 and parameters: {'subsample': 0.8004849573107579, 'colsample_bytree': 0.4572253659520338, 'eta': 1.317831259501443, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.4989038044005221}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:53,788] Trial 29 finished with value: 0.7906976744186046 and parameters: {'subsample': 0.9609786693759871, 'colsample_bytree': 0.5820469683633007, 'eta': 0.6138826376480351, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.6398350415587302}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:54,108] Trial 30 finished with value: 0.7567567567567568 and parameters: {'subsample': 0.9425506645370082, 'colsample_bytree': 0.6907567118578527, 'eta': 0.8136573064653876, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.7306938275714743}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:54,421] Trial 31 finished with value: 0.7804878048780488 and parameters: {'subsample': 0.8609611660084792, 'colsample_bytree': 0.49339862110356447, 'eta': 0.9623721635156295, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.8119735174108832}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:54,684] Trial 32 finished with value: 0.8 and parameters: {'subsample': 0.8754663084905556, 'colsample_bytree': 0.36867053464247, 'eta': 1.0973838487516012, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7592754651913711}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:54,982] Trial 33 finished with value: 0.7567567567567568 and parameters: {'subsample': 0.8877250246768887, 'colsample_bytree': 0.3339119973220346, 'eta': 1.1238166096411262, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.6418700194687653}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:55,246] Trial 34 finished with value: 0.7368421052631579 and parameters: {'subsample': 0.6926386413228167, 'colsample_bytree': 0.37222504952126667, 'eta': 1.0547788292310516, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7709475570888595}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:55,487] Trial 35 finished with value: 0.8 and parameters: {'subsample': 0.8377478090312704, 'colsample_bytree': 0.4299799533353059, 'eta': 1.488615712103954, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.6864657505910678}. Best is trial 0 with value: 0.8205128205128205.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:48:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:48:55,990] Trial 36 finished with value: 0.75 and parameters: {'subsample': 0.7607710445419698, 'colsample_bytree': 0.606991843714082, 'eta': 0.5301966836836438, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.34024793969579437}. Best is trial 0 with value: 0.8205128205128205.

Best trial for Physical Environment/Climate: F1 score= 0.8205
Best hyperparameters: {'subsample': 0.7843416272324752, 'colsample_bytree': 0.3579445527510975, 'eta': 1.0965229505345728, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.4934030051789644}
Service Complaint

[I 2026-05-25 15:49:00,177] Trial 0 finished with value: 0.2978723404255319 and parameters: {'subsample': 0.8125130083347094, 'colsample_bytree': 0.8339732735175243, 'eta': 0.8550767569513732, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.827246947148059}. Best is trial 0 with value: 0.2978723404255319.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:00,918] Trial 1 finished with value: 0.21739130434782608 and parameters: {'subsample': 0.8746114061626531, 'colsample_bytree': 0.43744344374353195, 'eta': 0.1786442838613706, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.7998472829129908}. Best is trial 0 with value: 0.2978723404255319.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:01,246] Trial 2 finished with value: 0.047619047619047616 and parameters: {'subsample': 0.4694897789121404, 'colsample_bytree': 0.9656509059445064, 'eta': 1.4877444361857155, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.26015593181143976}. Best is trial 0 with value: 0.2978723404255319.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:01,629] Trial 3 finished with value: 0.24561403508771928 and parameters: {'subsample': 0.7771445818479137, 'colsample_bytree': 0.34093034763096786, 'eta': 0.9858401031008739, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.9117391847188233}. Best is trial 0 with value: 0.2978723404255319.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:02,710] Trial 4 finished with value: 0.2 and parameters: {'subsample': 0.5428391175084616, 'colsample_bytree': 0.7976787291347553, 'eta': 0.17603351396850825, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.19919615193708}. Best is trial 0 with value: 0.2978723404255319.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:02,947] Trial 5 finished with value: 0.30303030303030304 and parameters: {'subsample': 0.44328469618595834, 'colsample_bytree': 0.4557500338120466, 'eta': 0.26107415909067544, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.1727457850825734}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:03,032] Trial 6 finished with value: 0.1651376146788991 and parameters: {'subsample': 0.9679259666747115, 'colsample_bytree': 0.38422892304196, 'eta': 1.4149291128532258, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.396411808474849}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:03,319] Trial 7 finished with value: 0.23255813953488372 and parameters: {'subsample': 0.8312153209102895, 'colsample_bytree': 0.4197496169642185, 'eta': 1.125844099558981, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.7098747159999478}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:03,664] Trial 8 finished with value: 0.17142857142857143 and parameters: {'subsample': 0.8755032511605083, 'colsample_bytree': 0.7302940059492002, 'eta': 0.6703538394795565, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.897849197533445}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:04,086] Trial 9 finished with value: 0.0548885077186964 and parameters: {'subsample': 0.5490907141331283, 'colsample_bytree': 0.8374214070452362, 'eta': 0.8750668719507451, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.402258456856773}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:04,652] Trial 10 finished with value: 0.22727272727272727 and parameters: {'subsample': 0.38448241344663014, 'colsample_bytree': 0.53751449333053, 'eta': 0.4840936729298656, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.1117933221901394}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:05,103] Trial 11 finished with value: 0.14814814814814814 and parameters: {'subsample': 0.699169398867499, 'colsample_bytree': 0.6015939768004563, 'eta': 0.5132014056081979, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.585746997454121}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:05,655] Trial 12 finished with value: 0.10526315789473684 and parameters: {'subsample': 0.3134928033708396, 'colsample_bytree': 0.9746748482195124, 'eta': 0.40901514798600225, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.6095681254287424}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:08,464] Trial 13 finished with value: 0.21428571428571427 and parameters: {'subsample': 0.64341250896928, 'colsample_bytree': 0.675124556315558, 'eta': 0.023169943316792896, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.9870981334399256}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:08,884] Trial 14 finished with value: 0.18461538461538463 and parameters: {'subsample': 0.6748826054991994, 'colsample_bytree': 0.5325851237958074, 'eta': 1.195013862917562, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 2, 'gamma': 0.4043226180900994}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:09,250] Trial 15 finished with value: 0.24 and parameters: {'subsample': 0.997005035859402, 'colsample_bytree': 0.8742283249907903, 'eta': 0.7417068876392496, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7565483950974339}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:09,931] Trial 16 finished with value: 0.2608695652173913 and parameters: {'subsample': 0.44759127147648836, 'colsample_bytree': 0.5015610092622598, 'eta': 0.2923162707225181, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.4888753408147203}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:10,331] Trial 17 finished with value: 0.2857142857142857 and parameters: {'subsample': 0.5803237881463337, 'colsample_bytree': 0.3051768821080652, 'eta': 0.6402293386414467, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.2811195178757348}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:10,731] Trial 18 finished with value: 0.17543859649122806 and parameters: {'subsample': 0.7827892539792668, 'colsample_bytree': 0.7302170597425124, 'eta': 0.8966136458981583, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.6470902330534558}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:10,986] Trial 19 finished with value: 0.06818181818181818 and parameters: {'subsample': 0.3151425556079739, 'colsample_bytree': 0.6160902652893788, 'eta': 1.252652324207284, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.5001404589740305}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:11,285] Trial 20 finished with value: 0.13513513513513514 and parameters: {'subsample': 0.7310839205526642, 'colsample_bytree': 0.9122202405376347, 'eta': 1.0662087736313888, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.8461460903371735}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:11,578] Trial 21 finished with value: 0.2553191489361702 and parameters: {'subsample': 0.5789233295407801, 'colsample_bytree': 0.3234602891665348, 'eta': 0.5961277821792716, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.26489915233688843}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:11,843] Trial 22 finished with value: 0.2222222222222222 and parameters: {'subsample': 0.6174446017691535, 'colsample_bytree': 0.30848016471257755, 'eta': 0.8216873313815787, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.12685320115124527}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:12,367] Trial 23 finished with value: 0.15384615384615385 and parameters: {'subsample': 0.4886506159007523, 'colsample_bytree': 0.4645498019774011, 'eta': 0.3006799703707333, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.2892848677506877}. Best is trial 5 with value: 0.30303030303030304.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:12,616] Trial 24 finished with value: 0.3225806451612903 and parameters: {'subsample': 0.37144486525253406, 'colsample_bytree': 0.3715553254063028, 'eta': 0.6604765149730241, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.18312275869255307}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:14,668] Trial 25 finished with value: 0.24489795918367346 and parameters: {'subsample': 0.3941859256570768, 'colsample_bytree': 0.5673742706879507, 'eta': 0.020807086385838947, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.20509386978842564}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:14,966] Trial 26 finished with value: 0.25 and parameters: {'subsample': 0.39213231553888744, 'colsample_bytree': 0.3863313388066249, 'eta': 0.7197958479117148, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.15774093235682707}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:15,202] Trial 27 finished with value: 0.05454545454545454 and parameters: {'subsample': 0.3592495667590811, 'colsample_bytree': 0.6980927571849952, 'eta': 0.9591246458448699, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.3602385146726612}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:15,574] Trial 28 finished with value: 0.25 and parameters: {'subsample': 0.490560994169876, 'colsample_bytree': 0.7805558946329609, 'eta': 0.43719564966186847, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.704317060243366}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:16,604] Trial 29 finished with value: 0.2962962962962963 and parameters: {'subsample': 0.8660305704197572, 'colsample_bytree': 0.4991069227287277, 'eta': 0.19561432320365568, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.4957529560145559}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:16,917] Trial 30 finished with value: 0.27586206896551724 and parameters: {'subsample': 0.43810707319189973, 'colsample_bytree': 0.41992725555139276, 'eta': 0.562857735538153, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.33367390335262676}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:17,951] Trial 31 finished with value: 0.2962962962962963 and parameters: {'subsample': 0.912063095838559, 'colsample_bytree': 0.4797439173362444, 'eta': 0.1593559612621191, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.485681712713344}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:18,467] Trial 32 finished with value: 0.25806451612903225 and parameters: {'subsample': 0.8413638332577809, 'colsample_bytree': 0.36617061009175855, 'eta': 0.36856015102726497, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.18826370407689214}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:20,153] Trial 33 finished with value: 0.2692307692307692 and parameters: {'subsample': 0.9116733534467332, 'colsample_bytree': 0.4406681752280621, 'eta': 0.08469275512385217, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.7981392237023675}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:20,923] Trial 34 finished with value: 0.30303030303030304 and parameters: {'subsample': 0.7753009891937934, 'colsample_bytree': 0.613438475764485, 'eta': 0.25247985062362105, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.2244905138009105}. Best is trial 24 with value: 0.3225806451612903.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:21,587] Trial 35 finished with value: 0.15 and parameters: {'subsample': 0.765063651306594, 'colsample_bytree': 0.6366055372164393, 'eta': 0.28727149650776174, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.22644768378154798}. Best is trial 24 with value: 0.3225806451612903.

Best trial for Service Complaint: F1 score= 0.3704
Best hyperparameters: {'subsample': 0.8085198163105257, 'colsample_bytree': 0.8079606864985156, 'eta': 1.0191022875882974, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.3250032413049373}
Social Services

[I 2026-05-25 15:49:28,340] Trial 0 finished with value: 0.8 and parameters: {'subsample': 0.828979199623467, 'colsample_bytree': 0.6066100763598103, 'eta': 0.6670043148716138, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.6192367582856897}. Best is trial 0 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:28,520] Trial 1 finished with value: 0.0 and parameters: {'subsample': 0.5565994303485844, 'colsample_bytree': 0.7400462520086384, 'eta': 1.443068343792818, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7742348334325058}. Best is trial 0 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:28,696] Trial 2 finished with value: 0.782608695652174 and parameters: {'subsample': 0.8173121633971432, 'colsample_bytree': 0.5229251474732535, 'eta': 1.226801275912547, 'max_depth': 1, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.24349718985238017}. Best is trial 0 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:28,908] Trial 3 finished with value: 0.6666666666666666 and parameters: {'subsample': 0.47722920911025835, 'colsample_bytree': 0.8352214648824574, 'eta': 1.3943581726937555, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.8382553247194875}. Best is trial 0 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:29,149] Trial 4 finished with value: 0.6285714285714286 and parameters: {'subsample': 0.4989984885970684, 'colsample_bytree': 0.39523315724848074, 'eta': 1.4981852619044336, 'max_depth': 3, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.13101008221705387}. Best is trial 0 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:29,438] Trial 5 finished with value: 0.782608695652174 and parameters: {'subsample': 0.7325912608766447, 'colsample_bytree': 0.40033764753747414, 'eta': 0.7983994011622815, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.796016704281572}. Best is trial 0 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:29,813] Trial 6 finished with value: 0.75 and parameters: {'subsample': 0.3031148558661449, 'colsample_bytree': 0.9462035164882641, 'eta': 0.7508072272731406, 'max_depth': 10, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.1290712046586929}. Best is trial 0 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:30,094] Trial 7 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.442694972839177, 'colsample_bytree': 0.42699969976373153, 'eta': 0.8745967451717239, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.878813803155788}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:30,380] Trial 8 finished with value: 0.75 and parameters: {'subsample': 0.5461767211525956, 'colsample_bytree': 0.6479028952079919, 'eta': 0.7838013847383357, 'max_depth': 6, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.9418966174781135}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:30,573] Trial 9 finished with value: 0.7407407407407407 and parameters: {'subsample': 0.583902051577488, 'colsample_bytree': 0.31539599341241537, 'eta': 1.1702955265323218, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.36297138466792545}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:34,038] Trial 10 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.9952882133375083, 'colsample_bytree': 0.5067933996232211, 'eta': 0.01057518559216497, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.5484409147711033}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:34,714] Trial 11 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.9379988074630702, 'colsample_bytree': 0.4816223552466563, 'eta': 0.1572471545897992, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.5475154296423381}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:36,488] Trial 12 finished with value: 0.8 and parameters: {'subsample': 0.38172385101169615, 'colsample_bytree': 0.5387494343674323, 'eta': 0.05467834428335191, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.5824350491485771}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:36,853] Trial 13 finished with value: 0.782608695652174 and parameters: {'subsample': 0.6892455825766155, 'colsample_bytree': 0.41943454909643796, 'eta': 0.39249848363718576, 'max_depth': 7, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.4594582846619887}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:37,122] Trial 14 finished with value: 0.782608695652174 and parameters: {'subsample': 0.9985478835888649, 'colsample_bytree': 0.31816022459313253, 'eta': 0.5278488888246393, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.6682633110177055}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:37,410] Trial 15 finished with value: 0.72 and parameters: {'subsample': 0.4312007575570728, 'colsample_bytree': 0.7439200683204514, 'eta': 1.0309281260799974, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.9933751939380051}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:37,884] Trial 16 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.6262827510282176, 'colsample_bytree': 0.5553727173477145, 'eta': 0.276851745319943, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.4161272185644076}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:38,178] Trial 17 finished with value: 0.782608695652174 and parameters: {'subsample': 0.8079649779319982, 'colsample_bytree': 0.46679490869112544, 'eta': 1.0039238016567238, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7165585027930577}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:38,498] Trial 18 finished with value: 0.782608695652174 and parameters: {'subsample': 0.32551020536880554, 'colsample_bytree': 0.7063362944737044, 'eta': 0.5463671566421867, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.5045027214223872}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:38,673] Trial 19 finished with value: 0.75 and parameters: {'subsample': 0.8872273087169884, 'colsample_bytree': 0.5866170883097384, 'eta': 1.0380185243665998, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.34722180789236035}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:39,118] Trial 20 finished with value: 0.8 and parameters: {'subsample': 0.7373429801726565, 'colsample_bytree': 0.4573043688441631, 'eta': 0.36056560897733303, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.8858161808830024}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:42,354] Trial 21 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.9522274293475543, 'colsample_bytree': 0.49589071083767294, 'eta': 0.01563992256829617, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.5459728257996387}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:42,969] Trial 22 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.9151524828219721, 'colsample_bytree': 0.37068323982539786, 'eta': 0.16476006222703274, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.680068121875658}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:43,483] Trial 23 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.9962992368740973, 'colsample_bytree': 0.4655695407390875, 'eta': 0.19291999851404254, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.5182449515211249}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:43,702] Trial 24 finished with value: 0.8 and parameters: {'subsample': 0.8868030766748625, 'colsample_bytree': 0.6378124456972687, 'eta': 0.9116392092565353, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.6378685800428836}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:44,401] Trial 25 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.9521757232178663, 'colsample_bytree': 0.3647041272937258, 'eta': 0.13266188994325007, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.7319026377375997}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:44,843] Trial 26 finished with value: 0.782608695652174 and parameters: {'subsample': 0.7610491288950261, 'colsample_bytree': 0.4391479045663871, 'eta': 0.5013647139297357, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.2824534565137075}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:45,417] Trial 27 finished with value: 0.8148148148148148 and parameters: {'subsample': 0.6367078160210513, 'colsample_bytree': 0.5143328684001899, 'eta': 0.2897303225574264, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.44670077928457175}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:47,366] Trial 28 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.8625048558265229, 'colsample_bytree': 0.5759893825198121, 'eta': 0.012414546892902861, 'max_depth': 2, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.583482468972454}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:47,592] Trial 29 finished with value: 0.782608695652174 and parameters: {'subsample': 0.9316872316376323, 'colsample_bytree': 0.6114970945272423, 'eta': 0.6788315819329586, 'max_depth': 2, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.6291067834000236}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:47,940] Trial 30 finished with value: 0.782608695652174 and parameters: {'subsample': 0.7791072875507745, 'colsample_bytree': 0.6834701322143916, 'eta': 0.6225329388205776, 'max_depth': 9, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.4861086544680697}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:48,454] Trial 31 finished with value: 0.8 and parameters: {'subsample': 0.6170176394140645, 'colsample_bytree': 0.5538336999777478, 'eta': 0.27174538758513894, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.3861697164501235}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:49,109] Trial 32 finished with value: 0.8 and parameters: {'subsample': 0.6688317007861481, 'colsample_bytree': 0.48474836071664, 'eta': 0.13703221492338075, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.4036643739461848}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:49,463] Trial 33 finished with value: 0.8333333333333334 and parameters: {'subsample': 0.3855580023290519, 'colsample_bytree': 0.5145571652070235, 'eta': 0.42318891503706213, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.2590855631065808}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:49,864] Trial 34 finished with value: 0.782608695652174 and parameters: {'subsample': 0.5052412120324012, 'colsample_bytree': 0.5470951778655584, 'eta': 0.28067999146535544, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.4267278629478029}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:49:51,104] Trial 35 finished with value: 0.8 and parameters: {'subsample': 0.8419392417783326, 'colsample_bytree': 0.6125593234322502, 'eta': 0.10302880312400753, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.33112185083919304}. Best is trial 7 with value: 0.8333333333333334.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:49:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Social Services: F1 score= 0.8333
Best hyperparameters: {'subsample': 0.442694972839177, 'colsample_bytree': 0.42699969976373153, 'eta': 0.8745967451717239, 'max_depth': 10, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.878813803155788}
Technical/IT

[I 2026-05-25 15:50:03,289] Trial 1 finished with value: 0.6451612903225806 and parameters: {'subsample': 0.6909061808344437, 'colsample_bytree': 0.3597282568903864, 'eta': 0.14413593086972237, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.23236362165085273}. Best is trial 1 with value: 0.6451612903225806.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:03,695] Trial 2 finished with value: 0.2011173184357542 and parameters: {'subsample': 0.49699781515827546, 'colsample_bytree': 0.50638415904169, 'eta': 1.398165113050521, 'max_depth': 10, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.7403753948630352}. Best is trial 1 with value: 0.6451612903225806.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:04,278] Trial 3 finished with value: 0.5862068965517241 and parameters: {'subsample': 0.5980171743552487, 'colsample_bytree': 0.7393190655217982, 'eta': 1.002118051794729, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.6081600757698415}. Best is trial 1 with value: 0.6451612903225806.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:04,907] Trial 4 finished with value: 0.6129032258064516 and parameters: {'subsample': 0.4058734071386123, 'colsample_bytree': 0.8945565953574706, 'eta': 0.80401622924904, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.34189283218456}. Best is trial 1 with value: 0.6451612903225806.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:06,498] Trial 5 finished with value: 0.6774193548387096 and parameters: {'subsample': 0.77911942642707, 'colsample_bytree': 0.44920018536285145, 'eta': 0.12017264837352513, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.5309737560244897}. Best is trial 5 with value: 0.6774193548387096.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:07,029] Trial 6 finished with value: 0.6779661016949152 and parameters: {'subsample': 0.9113956026044463, 'colsample_bytree': 0.9120049467000251, 'eta': 0.7649286663638389, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.4382157637257812}. Best is trial 6 with value: 0.6779661016949152.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:07,427] Trial 7 finished with value: 0.6774193548387096 and parameters: {'subsample': 0.9693279440219003, 'colsample_bytree': 0.676553017158251, 'eta': 1.129898492558367, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.19330490811251133}. Best is trial 6 with value: 0.6779661016949152.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:07,832] Trial 8 finished with value: 0.5757575757575758 and parameters: {'subsample': 0.43944350079986816, 'colsample_bytree': 0.5285044034964648, 'eta': 1.12498737569115, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 0, 'gamma': 0.5119771525893895}. Best is trial 6 with value: 0.6779661016949152.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:08,281] Trial 9 finished with value: 0.6376811594202898 and parameters: {'subsample': 0.6089443260019358, 'colsample_bytree': 0.8776572715640196, 'eta': 1.1278784739372236, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.9414291812134294}. Best is trial 6 with value: 0.6779661016949152.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:08,864] Trial 10 finished with value: 0.676923076923077 and parameters: {'subsample': 0.9806328752030583, 'colsample_bytree': 0.9895081673417652, 'eta': 0.5392738455877275, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.10303340635440966}. Best is trial 6 with value: 0.6779661016949152.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:09,974] Trial 11 finished with value: 0.6875 and parameters: {'subsample': 0.8239956538601323, 'colsample_bytree': 0.3586484161921088, 'eta': 0.010860641029714069, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.6556348923005572}. Best is trial 11 with value: 0.6875.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:10,447] Trial 12 finished with value: 0.6363636363636364 and parameters: {'subsample': 0.841466693262607, 'colsample_bytree': 0.7409002386739098, 'eta': 0.44569138475431674, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.7491058484476838}. Best is trial 11 with value: 0.6875.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:11,005] Trial 13 finished with value: 0.6779661016949152 and parameters: {'subsample': 0.862789786873617, 'colsample_bytree': 0.31871646284480654, 'eta': 0.45517382686244073, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7247931992984529}. Best is trial 11 with value: 0.6875.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:11,374] Trial 14 finished with value: 0.6461538461538462 and parameters: {'subsample': 0.8776781952378823, 'colsample_bytree': 0.5930799312059192, 'eta': 0.6778357409691145, 'max_depth': 1, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.9507419362860179}. Best is trial 11 with value: 0.6875.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:12,388] Trial 15 finished with value: 0.6885245901639344 and parameters: {'subsample': 0.8100710726725349, 'colsample_bytree': 0.7929335239334737, 'eta': 0.2805082336976294, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 3, 'gamma': 0.43366273081426654}. Best is trial 15 with value: 0.6885245901639344.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:13,329] Trial 16 finished with value: 0.711864406779661 and parameters: {'subsample': 0.7612307415444531, 'colsample_bytree': 0.7831846463219977, 'eta': 0.2561171268311249, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.6460710579292349}. Best is trial 16 with value: 0.711864406779661.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:14,301] Trial 17 finished with value: 0.7142857142857143 and parameters: {'subsample': 0.7535617079220132, 'colsample_bytree': 0.7871862358358558, 'eta': 0.28440505817580247, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.8375894373049865}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:15,139] Trial 18 finished with value: 0.7142857142857143 and parameters: {'subsample': 0.7360682517093139, 'colsample_bytree': 0.8077498358460296, 'eta': 0.33186792798642184, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.8591605767820485}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:16,279] Trial 19 finished with value: 0.6885245901639344 and parameters: {'subsample': 0.5386652262327363, 'colsample_bytree': 0.6629794524079341, 'eta': 0.3403863790621151, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.8542653093559635}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:17,000] Trial 20 finished with value: 0.6666666666666666 and parameters: {'subsample': 0.30711456539679827, 'colsample_bytree': 0.8314978675711382, 'eta': 0.6102845763435433, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.839356329481475}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:18,057] Trial 21 finished with value: 0.711864406779661 and parameters: {'subsample': 0.7260204908146823, 'colsample_bytree': 0.769098760544234, 'eta': 0.27541197364856873, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.8389369215726287}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:20,025] Trial 22 finished with value: 0.711864406779661 and parameters: {'subsample': 0.7482843467525975, 'colsample_bytree': 0.9933711266937266, 'eta': 0.1792056217425391, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.6496826944554436}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:20,853] Trial 23 finished with value: 0.6764705882352942 and parameters: {'subsample': 0.6288449412932177, 'colsample_bytree': 0.8231968702783187, 'eta': 0.38605586181705065, 'max_depth': 4, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.9974979209516457}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:24,088] Trial 24 finished with value: 0.7017543859649122 and parameters: {'subsample': 0.6708595883839523, 'colsample_bytree': 0.7082915188529675, 'eta': 0.06656486522626587, 'max_depth': 5, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.7970320251411757}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:25,119] Trial 25 finished with value: 0.6779661016949152 and parameters: {'subsample': 0.7634628561204622, 'colsample_bytree': 0.5909729321778834, 'eta': 0.2582430940919855, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.9030022791906125}. Best is trial 17 with value: 0.7142857142857143.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:25,849] Trial 26 finished with value: 0.7241379310344828 and parameters: {'subsample': 0.9166547945231098, 'colsample_bytree': 0.83529611913363, 'eta': 0.5183171057523418, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 4, 'gamma': 0.6079717591483141}. Best is trial 26 with value: 0.7241379310344828.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:26,444] Trial 27 finished with value: 0.7241379310344828 and parameters: {'subsample': 0.9176980648061835, 'colsample_bytree': 0.8418131828335423, 'eta': 0.5514753649189279, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.7606679415825746}. Best is trial 26 with value: 0.7241379310344828.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:26,978] Trial 28 finished with value: 0.6551724137931034 and parameters: {'subsample': 0.9302583063642257, 'colsample_bytree': 0.849964838291391, 'eta': 0.9221553464503431, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.5740273084738037}. Best is trial 26 with value: 0.7241379310344828.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:27,562] Trial 29 finished with value: 0.7368421052631579 and parameters: {'subsample': 0.9956986071698033, 'colsample_bytree': 0.9452188375939842, 'eta': 0.5474821965991338, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.7171872204130991}. Best is trial 29 with value: 0.7368421052631579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:28,093] Trial 30 finished with value: 0.6909090909090909 and parameters: {'subsample': 0.9981718660257636, 'colsample_bytree': 0.939997941109453, 'eta': 0.5537450968300518, 'max_depth': 10, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.6957881933811958}. Best is trial 29 with value: 0.7368421052631579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:28,647] Trial 31 finished with value: 0.6440677966101694 and parameters: {'subsample': 0.9200361098822661, 'colsample_bytree': 0.9280108385239517, 'eta': 0.6568850044851868, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.7589374587112452}. Best is trial 29 with value: 0.7368421052631579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:29,393] Trial 32 finished with value: 0.6896551724137931 and parameters: {'subsample': 0.9455660726283733, 'colsample_bytree': 0.956297663179062, 'eta': 0.49108623933419526, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 1, 'gamma': 0.784045076300747}. Best is trial 29 with value: 0.7368421052631579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:29,848] Trial 33 finished with value: 0.6857142857142857 and parameters: {'subsample': 0.8913479274148747, 'colsample_bytree': 0.8605551652829719, 'eta': 0.8273796886418423, 'max_depth': 6, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.689928518263218}. Best is trial 29 with value: 0.7368421052631579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:30,397] Trial 34 finished with value: 0.7241379310344828 and parameters: {'subsample': 0.9545235790105887, 'colsample_bytree': 0.8889106186112292, 'eta': 0.7022383542936212, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.5779479382509838}. Best is trial 29 with value: 0.7368421052631579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:30,967] Trial 35 finished with value: 0.6896551724137931 and parameters: {'subsample': 0.9545765094525741, 'colsample_bytree': 0.8776473996139778, 'eta': 0.7001043166869567, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.48587821583174223}. Best is trial 29 with value: 0.7368421052631579.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:31,453] Trial 36 finished with value: 0.65625 and parameters: {'subsample': 0.8845223958898147, 'colsample_bytree': 0.9539825411502181, 'eta': 0.8920675021086337, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.6098898386168794}. Best is trial 29 with value: 0.7368421052631579.

Best trial for Technical/IT: F1 score= 0.7368
Best hyperparameters: {'subsample': 0.9956986071698033, 'colsample_bytree': 0.9452188375939842, 'eta': 0.5474821965991338, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.7171872204130991}
Urgent

[I 2026-05-25 15:50:40,281] Trial 0 finished with value: 0.38961038961038963 and parameters: {'subsample': 0.6251034009023412, 'colsample_bytree': 0.6162119154005151, 'eta': 0.1219460323478835, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.8874728876248497}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:41,248] Trial 1 finished with value: 0.35294117647058826 and parameters: {'subsample': 0.8275677978842939, 'colsample_bytree': 0.4926997945505179, 'eta': 0.2144222345954035, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.8743795193042657}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:41,395] Trial 2 finished with value: 0.2857142857142857 and parameters: {'subsample': 0.6656482392850356, 'colsample_bytree': 0.38065025350332293, 'eta': 1.1941384004876896, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.9600292575787702}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:41,765] Trial 3 finished with value: 0.38461538461538464 and parameters: {'subsample': 0.8134466952401216, 'colsample_bytree': 0.8189798909874353, 'eta': 0.5503167940040691, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.3091812609566054}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:42,777] Trial 4 finished with value: 0.3333333333333333 and parameters: {'subsample': 0.4514198575777758, 'colsample_bytree': 0.8328227785326012, 'eta': 0.4378968378626391, 'max_depth': 8, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.2516710880511077}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:43,482] Trial 5 finished with value: 0.37037037037037035 and parameters: {'subsample': 0.4145222571298976, 'colsample_bytree': 0.5815507421247046, 'eta': 0.3071430100839807, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.6264979671133}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:45,813] Trial 6 finished with value: 0.3829787234042553 and parameters: {'subsample': 0.7425100366385089, 'colsample_bytree': 0.5930122480651445, 'eta': 0.09136368915298014, 'max_depth': 10, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.8484755238012672}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:47,524] Trial 7 finished with value: 0.3697478991596639 and parameters: {'subsample': 0.929357695409148, 'colsample_bytree': 0.7742093470217819, 'eta': 0.14929200598168096, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.5083003942806836}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:48,141] Trial 8 finished with value: 0.3114754098360656 and parameters: {'subsample': 0.6039142994865669, 'colsample_bytree': 0.733987294583121, 'eta': 1.078907425117108, 'max_depth': 8, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.11506934906888999}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:48,270] Trial 9 finished with value: 0.3120567375886525 and parameters: {'subsample': 0.6840270323285351, 'colsample_bytree': 0.8406312965438694, 'eta': 1.307106485045015, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.5993277398202626}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:48,505] Trial 10 finished with value: 0.3310344827586207 and parameters: {'subsample': 0.5004653204036338, 'colsample_bytree': 0.9690120185293329, 'eta': 0.8118359771930934, 'max_depth': 1, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.7693353686742448}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:48,937] Trial 11 finished with value: 0.3511450381679389 and parameters: {'subsample': 0.9402600454210188, 'colsample_bytree': 0.9632136803617499, 'eta': 0.5993603808609619, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.3891919929118108}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:49,437] Trial 12 finished with value: 0.3333333333333333 and parameters: {'subsample': 0.7665642690272787, 'colsample_bytree': 0.6715800313728529, 'eta': 0.831823995708612, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.3614665453460537}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:49,768] Trial 13 finished with value: 0.3157894736842105 and parameters: {'subsample': 0.3239121440632187, 'colsample_bytree': 0.4594027359746384, 'eta': 0.5931673295627558, 'max_depth': 3, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.712720946286723}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:50,171] Trial 14 finished with value: 0.3548387096774194 and parameters: {'subsample': 0.582015032772498, 'colsample_bytree': 0.8607674593660015, 'eta': 0.43363253400581375, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.4718212252595204}. Best is trial 0 with value: 0.38961038961038963.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:54,549] Trial 15 finished with value: 0.4126984126984127 and parameters: {'subsample': 0.8248839864518034, 'colsample_bytree': 0.6865507646280251, 'eta': 0.02896537910080657, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.2075813412024204}. Best is trial 15 with value: 0.4126984126984127.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:50:58,891] Trial 16 finished with value: 0.38961038961038963 and parameters: {'subsample': 0.8689413455051509, 'colsample_bytree': 0.6699827284985185, 'eta': 0.03748232110910901, 'max_depth': 4, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.10479500925710336}. Best is trial 15 with value: 0.4126984126984127.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:50:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:00,200] Trial 17 finished with value: 0.36363636363636365 and parameters: {'subsample': 0.550481824821531, 'colsample_bytree': 0.5231186343902063, 'eta': 0.3010598939009843, 'max_depth': 7, 'reg_lambda': 4, 'reg_alpha': 4, 'gamma': 0.2186098310437979}. Best is trial 15 with value: 0.4126984126984127.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:03,342] Trial 18 finished with value: 0.42990654205607476 and parameters: {'subsample': 0.9897243851797022, 'colsample_bytree': 0.3672481574890575, 'eta': 0.015688729028376175, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.9975442229103662}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:03,544] Trial 19 finished with value: 0.25806451612903225 and parameters: {'subsample': 0.998461206685077, 'colsample_bytree': 0.3202096997986378, 'eta': 1.4517728752362717, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.9913147973172314}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:03,797] Trial 20 finished with value: 0.34285714285714286 and parameters: {'subsample': 0.988511631338059, 'colsample_bytree': 0.4168495787514306, 'eta': 1.0195233230159133, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.4330365502751352}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:05,531] Trial 21 finished with value: 0.3974358974358974 and parameters: {'subsample': 0.7249118872494943, 'colsample_bytree': 0.5854546802136904, 'eta': 0.014997038106486862, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.8934534165685986}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:06,987] Trial 22 finished with value: 0.3968253968253968 and parameters: {'subsample': 0.8801932877596819, 'colsample_bytree': 0.31401370363233616, 'eta': 0.016975416221724993, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.7376194955557385}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:07,239] Trial 23 finished with value: 0.375 and parameters: {'subsample': 0.7423722354989105, 'colsample_bytree': 0.5451988800195816, 'eta': 0.2792603377425521, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.9366443721201183}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:13,358] Trial 24 finished with value: 0.4 and parameters: {'subsample': 0.9128146901900596, 'colsample_bytree': 0.7096310352104482, 'eta': 0.012832501170157324, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.8033945100572799}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:14,189] Trial 25 finished with value: 0.4032258064516129 and parameters: {'subsample': 0.9253361202560605, 'colsample_bytree': 0.7061034418475348, 'eta': 0.4255299602287963, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.7984479245781461}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:15,114] Trial 26 finished with value: 0.3225806451612903 and parameters: {'subsample': 0.8329733614193989, 'colsample_bytree': 0.8985116612978417, 'eta': 0.39939027716857695, 'max_depth': 7, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.6516605255226782}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:16,211] Trial 27 finished with value: 0.37681159420289856 and parameters: {'subsample': 0.938932888962303, 'colsample_bytree': 0.7608640311611732, 'eta': 0.19751772649960123, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.5410746725706126}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:16,656] Trial 28 finished with value: 0.35443037974683544 and parameters: {'subsample': 0.9750925862243743, 'colsample_bytree': 0.6331421363520651, 'eta': 0.6965141215240804, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.6700745067594778}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:18,378] Trial 29 finished with value: 0.3564356435643564 and parameters: {'subsample': 0.8091866126050683, 'colsample_bytree': 0.6901431475043666, 'eta': 0.14020128179584954, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.8022304734290953}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:19,304] Trial 30 finished with value: 0.3883495145631068 and parameters: {'subsample': 0.8964632794814708, 'colsample_bytree': 0.7839596542708575, 'eta': 0.3678730320382584, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.9115070774167644}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:21,186] Trial 31 finished with value: 0.35 and parameters: {'subsample': 0.9011588143792804, 'colsample_bytree': 0.7113888481236903, 'eta': 0.10992728205460056, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.827139497814811}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:22,115] Trial 32 finished with value: 0.34408602150537637 and parameters: {'subsample': 0.8503487724658391, 'colsample_bytree': 0.6317009754934685, 'eta': 0.20383696316101468, 'max_depth': 4, 'reg_lambda': 0, 'reg_alpha': 4, 'gamma': 0.9972180618641672}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:23,077] Trial 33 finished with value: 0.3883495145631068 and parameters: {'subsample': 0.9501686172671214, 'colsample_bytree': 0.7273938520359701, 'eta': 0.23781087473915036, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.713771639683606}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:24,911] Trial 34 finished with value: 0.38961038961038963 and parameters: {'subsample': 0.9069532117800267, 'colsample_bytree': 0.47207635387900587, 'eta': 0.10592129410886021, 'max_depth': 5, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.8020605743278723}. Best is trial 18 with value: 0.42990654205607476.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Urgent: F1 score= 0.4299
Best hyperparameters: {'subsample': 0.9897243851797022, 'colsample_bytree': 0.3672481574890575, 'eta': 0.015688729028376175, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.9975442229103662}
Work/School

[I 2026-05-25 15:51:47,294] Trial 0 finished with value: 0.7755102040816326 and parameters: {'subsample': 0.47295499185484635, 'colsample_bytree': 0.6785295275232998, 'eta': 0.10852283980275362, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.32275494071042266}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:47,441] Trial 1 finished with value: 0.3191489361702128 and parameters: {'subsample': 0.7142240613170943, 'colsample_bytree': 0.7073497461520213, 'eta': 1.2487744693426017, 'max_depth': 3, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.6659471179584987}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:47,718] Trial 2 finished with value: 0.7222222222222222 and parameters: {'subsample': 0.4200580451368236, 'colsample_bytree': 0.5107451755073943, 'eta': 0.4206900041891354, 'max_depth': 3, 'reg_lambda': 2, 'reg_alpha': 3, 'gamma': 0.5247796596764721}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:49,278] Trial 3 finished with value: 0.723404255319149 and parameters: {'subsample': 0.8847422465958852, 'colsample_bytree': 0.40865473238044336, 'eta': 0.055021230590220245, 'max_depth': 3, 'reg_lambda': 1, 'reg_alpha': 4, 'gamma': 0.2043193870860179}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:49,478] Trial 4 finished with value: 0.7222222222222222 and parameters: {'subsample': 0.5859571978937903, 'colsample_bytree': 0.4871958450554325, 'eta': 0.8065227471668217, 'max_depth': 2, 'reg_lambda': 2, 'reg_alpha': 4, 'gamma': 0.9645827384007863}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:49,745] Trial 5 finished with value: 0.7317073170731707 and parameters: {'subsample': 0.8565214137519974, 'colsample_bytree': 0.40928675873574494, 'eta': 0.9400541855929344, 'max_depth': 7, 'reg_lambda': 3, 'reg_alpha': 2, 'gamma': 0.7708519594515659}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:50,256] Trial 6 finished with value: 0.7368421052631579 and parameters: {'subsample': 0.7895407558897879, 'colsample_bytree': 0.9148249802860431, 'eta': 0.6323344585259466, 'max_depth': 8, 'reg_lambda': 4, 'reg_alpha': 3, 'gamma': 0.24842242706441306}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:50,431] Trial 7 finished with value: 0.75 and parameters: {'subsample': 0.7651149666563533, 'colsample_bytree': 0.5136903233441357, 'eta': 1.3618638774510534, 'max_depth': 2, 'reg_lambda': 1, 'reg_alpha': 2, 'gamma': 0.877989408837282}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:50,769] Trial 8 finished with value: 0.7222222222222222 and parameters: {'subsample': 0.920624210013689, 'colsample_bytree': 0.8669522058124157, 'eta': 1.2397951698818208, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 3, 'gamma': 0.22474802546519845}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:51,319] Trial 9 finished with value: 0.7441860465116279 and parameters: {'subsample': 0.9228993526055937, 'colsample_bytree': 0.4339384232836745, 'eta': 0.5899765798709175, 'max_depth': 1, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.8004358233219041}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:57,364] Trial 10 finished with value: 0.7659574468085106 and parameters: {'subsample': 0.3037127945574478, 'colsample_bytree': 0.7015937849503284, 'eta': 0.01396719479844577, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.44695777566930606}. Best is trial 0 with value: 0.7755102040816326.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:59,220] Trial 11 finished with value: 0.7906976744186046 and parameters: {'subsample': 0.3029415262218909, 'colsample_bytree': 0.705301560198726, 'eta': 0.06124564967874224, 'max_depth': 10, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.42502282719079315}. Best is trial 11 with value: 0.7906976744186046.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:51:59,953] Trial 12 finished with value: 0.7272727272727273 and parameters: {'subsample': 0.48316744393387845, 'colsample_bytree': 0.7892312735979075, 'eta': 0.253668510602258, 'max_depth': 10, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.37816054431476076}. Best is trial 11 with value: 0.7906976744186046.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:51:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:00,492] Trial 13 finished with value: 0.717948717948718 and parameters: {'subsample': 0.30633743657717855, 'colsample_bytree': 0.6150401277930777, 'eta': 0.26631246543881026, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.35061500944792945}. Best is trial 11 with value: 0.7906976744186046.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:01,080] Trial 14 finished with value: 0.7692307692307693 and parameters: {'subsample': 0.4428494249734069, 'colsample_bytree': 0.6113476407625837, 'eta': 0.24009303703313287, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.5810541908673184}. Best is trial 11 with value: 0.7906976744186046.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:01,397] Trial 15 finished with value: 0.7894736842105263 and parameters: {'subsample': 0.5658754326111941, 'colsample_bytree': 0.30659458231025505, 'eta': 0.4588820493020693, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.12523915808444613}. Best is trial 11 with value: 0.7906976744186046.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:01,694] Trial 16 finished with value: 0.7368421052631579 and parameters: {'subsample': 0.6173098237300159, 'colsample_bytree': 0.3343846583679711, 'eta': 0.46649971298361853, 'max_depth': 5, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.1310028154089415}. Best is trial 11 with value: 0.7906976744186046.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:02,066] Trial 17 finished with value: 0.6363636363636364 and parameters: {'subsample': 0.552694223057526, 'colsample_bytree': 0.8133618746923135, 'eta': 0.9855034091830688, 'max_depth': 5, 'reg_lambda': 1, 'reg_alpha': 0, 'gamma': 0.11457190640943515}. Best is trial 11 with value: 0.7906976744186046.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:02,556] Trial 18 finished with value: 0.8 and parameters: {'subsample': 0.37736569733056236, 'colsample_bytree': 0.3079285998098096, 'eta': 0.4260084553694353, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.47716430323527936}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:03,271] Trial 19 finished with value: 0.7027027027027027 and parameters: {'subsample': 0.34977500957801666, 'colsample_bytree': 0.9642956404875186, 'eta': 0.3276807642842577, 'max_depth': 6, 'reg_lambda': 3, 'reg_alpha': 1, 'gamma': 0.4801981541359913}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:04,210] Trial 20 finished with value: 0.7555555555555555 and parameters: {'subsample': 0.3949896819839994, 'colsample_bytree': 0.5755278081233248, 'eta': 0.16499608903809498, 'max_depth': 9, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.6128788178169718}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:04,519] Trial 21 finished with value: 0.6829268292682927 and parameters: {'subsample': 0.5179968006110506, 'colsample_bytree': 0.32664425410353926, 'eta': 0.5240343481096508, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.4205740183190928}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:04,787] Trial 22 finished with value: 0.7368421052631579 and parameters: {'subsample': 0.36761260357329795, 'colsample_bytree': 0.3236360145748532, 'eta': 0.7369862963475469, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.30584277184790687}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:05,245] Trial 23 finished with value: 0.7441860465116279 and parameters: {'subsample': 0.6689379912962546, 'colsample_bytree': 0.7541214928521647, 'eta': 0.3807764434086961, 'max_depth': 4, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.6727655664302409}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:05,552] Trial 24 finished with value: 0.7391304347826086 and parameters: {'subsample': 0.36806102396051216, 'colsample_bytree': 0.37491819036977925, 'eta': 0.7170191537288424, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.4872008406551256}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:06,324] Trial 25 finished with value: 0.7 and parameters: {'subsample': 0.5184028098537642, 'colsample_bytree': 0.46368786943086093, 'eta': 0.1812222573584148, 'max_depth': 5, 'reg_lambda': 4, 'reg_alpha': 1, 'gamma': 0.2597435189463151}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:06,612] Trial 26 finished with value: 0.6470588235294118 and parameters: {'subsample': 0.43649865146897393, 'colsample_bytree': 0.5773642671952947, 'eta': 0.543926222586069, 'max_depth': 4, 'reg_lambda': 3, 'reg_alpha': 0, 'gamma': 0.4030276095729746}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:06,832] Trial 27 finished with value: 0.24817518248175183 and parameters: {'subsample': 0.3236843538827488, 'colsample_bytree': 0.3713095158236814, 'eta': 0.8801306557513755, 'max_depth': 6, 'reg_lambda': 1, 'reg_alpha': 1, 'gamma': 0.16636709509179876}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:07,308] Trial 28 finished with value: 0.7058823529411765 and parameters: {'subsample': 0.6586339461138624, 'colsample_bytree': 0.3039535365619566, 'eta': 0.35440848763854815, 'max_depth': 9, 'reg_lambda': 2, 'reg_alpha': 0, 'gamma': 0.6431463425830223}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:07,634] Trial 29 finished with value: 0.7317073170731707 and parameters: {'subsample': 0.98425794621393, 'colsample_bytree': 0.6662495751393545, 'eta': 0.6469338985246967, 'max_depth': 8, 'reg_lambda': 0, 'reg_alpha': 1, 'gamma': 0.301280248949271}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:08,713] Trial 30 finished with value: 0.7058823529411765 and parameters: {'subsample': 0.4757157756099809, 'colsample_bytree': 0.5556701387367936, 'eta': 0.11682907298858569, 'max_depth': 7, 'reg_lambda': 2, 'reg_alpha': 2, 'gamma': 0.544259688295772}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:10,169] Trial 31 finished with value: 0.7317073170731707 and parameters: {'subsample': 0.3902144480113999, 'colsample_bytree': 0.7299190867465912, 'eta': 0.09192321564234757, 'max_depth': 10, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.33378365947116895}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:10,604] Trial 32 finished with value: 0.7058823529411765 and parameters: {'subsample': 0.4798589873395436, 'colsample_bytree': 0.6739175230466765, 'eta': 0.4535385162454437, 'max_depth': 9, 'reg_lambda': 0, 'reg_alpha': 2, 'gamma': 0.49434979358317777}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:15,781] Trial 33 finished with value: 0.7346938775510204 and parameters: {'subsample': 0.414475504644053, 'colsample_bytree': 0.6377129715958756, 'eta': 0.025434916969329063, 'max_depth': 8, 'reg_lambda': 1, 'reg_alpha': 3, 'gamma': 0.15938287245252503}. Best is trial 18 with value: 0.8.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:16,595] Trial 34 finished with value: 0.8372093023255814 and parameters: {'subsample': 0.5685888706475029, 'colsample_bytree': 0.808749336565037, 'eta': 0.20720242066677816, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.2845551201361284}. Best is trial 34 with value: 0.8372093023255814.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[I 2026-05-25 15:52:17,208] Trial 35 finished with value: 0.7111111111111111 and parameters: {'subsample': 0.6084289773198219, 'colsample_bytree': 0.8192718988088052, 'eta': 0.29927100963428616, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.2817530296049233}. Best is trial 34 with value: 0.8372093023255814.
/usr/local/lib/python3.12/dist-packages/xgboost/callback.py:385: UserWarning: [15:52:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()

Best trial for Work/School: F1 score= 0.8372
Best hyperparameters: {'subsample': 0.5685888706475029, 'colsample_bytree': 0.808749336565037, 'eta': 0.20720242066677816, 'max_depth': 6, 'reg_lambda': 0, 'reg_alpha': 0, 'gamma': 0.2845551201361284}

In [54]:
models = {}
for i,label_name in enumerate(label_keep_original):

  dmatrix_train.set_label(y_train[:,i])
  dmatrix_val.set_label(y_val[:,i])
  dmatrix_test.set_label(y_test[:,i])



  eval_list = [(dmatrix_val, 'validation')]
  model = xgb.train(params=list_params[label_name], dtrain=dmatrix_train,evals=eval_list,num_boost_round=1500,verbose_eval=False,early_stopping_rounds=30)
  models[label_name] = model

In [55]:
models

{'Cultural/Religion': <xgboost.core.Booster at 0x780a134af260>,
 'Diet/Nutrition': <xgboost.core.Booster at 0x780a13482300>,
 'Emergent': <xgboost.core.Booster at 0x780a13482120>,
 'Exercise': <xgboost.core.Booster at 0x780a11a772f0>,
 'Friends & Family': <xgboost.core.Booster at 0x780a0ff91f70>,
 'Grateful Patient': <xgboost.core.Booster at 0x780a0ff92480>,
 'Health Education': <xgboost.core.Booster at 0x780a0ff93890>,
 'Laboratory/Testing': <xgboost.core.Booster at 0x780a0ff907a0>,
 'Medications': <xgboost.core.Booster at 0x780a0ff920c0>,
 'No Symptoms': <xgboost.core.Booster at 0x780a191d81a0>,
 'Non-urgent': <xgboost.core.Booster at 0x780a191da2a0>,
 'Outpatient Logistics/Scheduling': <xgboost.core.Booster at 0x780a191da840>,
 'Physical': <xgboost.core.Booster at 0x780a191db380>,
 'Physical Environment/Climate': <xgboost.core.Booster at 0x780a191da540>,
 'Service Complaint': <xgboost.core.Booster at 0x780a191d9c40>,
 'Social Services': <xgboost.core.Booster at 0x780a191da390>,
 'Technical/IT': <xgboost.core.Booster at 0x780a191d9580>,
 'Urgent': <xgboost.core.Booster at 0x780a12b79ac0>,
 'Work/School': <xgboost.core.Booster at 0x780a12b79c10>}

In [56]:
import numpy as np

In [57]:
from sklearn.metrics import f1_score

In [58]:
optimal_thresholds = {}
import numpy as np
dmatrix_val = xgb.DMatrix(x_val)

for i, label_name in enumerate(label_keep_original):

    x_val_predic = models[label_name].predict(dmatrix_val)
    best_f1 = 0
    best_thresh = 0.5
    for threshold_val in np.arange(0.05, 0.96, 0.05):
        preds = (x_val_predic > threshold_val).astype(int)
        current_f1 = f1_score(y_val[:, i], preds)
        if current_f1 > best_f1:
            best_f1 = current_f1
            best_thresh = threshold_val
    optimal_thresholds[label_name] = best_thresh
    print(f"Optimal threshold for {label_name}: {best_thresh:.2f} (F1: {best_f1:.4f})")

Optimal threshold for Cultural/Religion: 0.40 (F1: 0.9485)
Optimal threshold for Diet/Nutrition: 0.45 (F1: 0.9333)
Optimal threshold for Emergent: 0.40 (F1: 0.3721)
Optimal threshold for Exercise: 0.50 (F1: 0.8571)
Optimal threshold for Friends & Family: 0.50 (F1: 0.6389)
Optimal threshold for Grateful Patient: 0.20 (F1: 0.6512)
Optimal threshold for Health Education: 0.10 (F1: 0.7333)
Optimal threshold for Laboratory/Testing: 0.30 (F1: 0.9433)
Optimal threshold for Medications: 0.45 (F1: 0.9302)
Optimal threshold for No Symptoms: 0.60 (F1: 0.8583)
Optimal threshold for Non-urgent: 0.40 (F1: 0.9512)
Optimal threshold for Outpatient Logistics/Scheduling: 0.45 (F1: 0.6970)
Optimal threshold for Physical: 0.45 (F1: 0.7485)
Optimal threshold for Physical Environment/Climate: 0.50 (F1: 0.8000)
Optimal threshold for Service Complaint: 0.20 (F1: 0.2667)
Optimal threshold for Social Services: 0.35 (F1: 0.7826)
Optimal threshold for Technical/IT: 0.55 (F1: 0.7143)
Optimal threshold for Urgent: 0.20 (F1: 0.3958)
Optimal threshold for Work/School: 0.75 (F1: 0.7059)

In [59]:

from sklearn.metrics import f1_score
dmatrix_test = xgb.DMatrix(x_test)


for i,_ in enumerate(label_keep_original):

  x_test_predic = models[label_keep_original[i]].predict(dmatrix_test)
  y_test_final = (x_test_predic > optimal_thresholds[_]).astype(int)
  f1 = f1_score(y_test[:,i], y_test_final)
  print(f"F1 Score for {_}:", f1)

F1 Score for Cultural/Religion: 0.9345794392523364
F1 Score for Diet/Nutrition: 0.875
F1 Score for Emergent: 0.45
F1 Score for Exercise: 0.7368421052631579
F1 Score for Friends & Family: 0.6363636363636364
F1 Score for Grateful Patient: 0.5871559633027523
F1 Score for Health Education: 0.7291666666666666
F1 Score for Laboratory/Testing: 0.967741935483871
F1 Score for Medications: 0.896551724137931
F1 Score for No Symptoms: 0.8439306358381503
F1 Score for Non-urgent: 0.9514925373134329
F1 Score for Outpatient Logistics/Scheduling: 0.7611940298507462
F1 Score for Physical: 0.8095238095238095
F1 Score for Physical Environment/Climate: 0.85
F1 Score for Service Complaint: 0.06349206349206349
F1 Score for Social Services: 0.6206896551724138
F1 Score for Technical/IT: 0.5555555555555556
F1 Score for Urgent: 0.2826086956521739
F1 Score for Work/School: 0.6111111111111112

In [60]:
import numpy as np
from sklearn.metrics import f1_score, classification_report

Y_pred_all = np.zeros(y_test.shape)

dmatrix_test = xgb.DMatrix(x_test)

print("--- Individual Class F1 Scores ---")
for i, label_name in enumerate(label_keep_original):

    x_test_predic = models[label_name].predict(dmatrix_test)

    y_test_final = (x_test_predic > optimal_thresholds[label_name]).astype(int)

    Y_pred_all[:, i] = y_test_final

    f1 = f1_score(y_test[:, i], y_test_final)
    print(f"F1 Score for {label_name}: {f1:.4f}")


macro_f1 = f1_score(y_test, Y_pred_all, average='macro', zero_division=0)
micro_f1 = f1_score(y_test, Y_pred_all, average='micro', zero_division=0)
weighted_f1 = f1_score(y_test, Y_pred_all, average='weighted', zero_division=0)

print("--- Overall Test Set Metrics ---")
print(f"Macro F1 Score:    {macro_f1:.4f}")
print(f"Micro F1 Score:    {micro_f1:.4f}")
print(f"Weighted F1 Score: {weighted_f1:.4f}")


print("--- Full Classification Report ---")
print(classification_report(y_test, Y_pred_all, target_names=label_keep_original, zero_division=0))

--- Individual Class F1 Scores ---
F1 Score for Cultural/Religion: 0.9346
F1 Score for Diet/Nutrition: 0.8750
F1 Score for Emergent: 0.4500
F1 Score for Exercise: 0.7368
F1 Score for Friends & Family: 0.6364
F1 Score for Grateful Patient: 0.5872
F1 Score for Health Education: 0.7292
F1 Score for Laboratory/Testing: 0.9677
F1 Score for Medications: 0.8966
F1 Score for No Symptoms: 0.8439
F1 Score for Non-urgent: 0.9515
F1 Score for Outpatient Logistics/Scheduling: 0.7612
F1 Score for Physical: 0.8095
F1 Score for Physical Environment/Climate: 0.8500
F1 Score for Service Complaint: 0.0635
F1 Score for Social Services: 0.6207
F1 Score for Technical/IT: 0.5556
F1 Score for Urgent: 0.2826
F1 Score for Work/School: 0.6111
--- Overall Test Set Metrics ---
Macro F1 Score:    0.6928
Micro F1 Score:    0.8302
Weighted F1 Score: 0.8337
--- Full Classification Report ---
                                 precision    recall  f1-score   support

              Cultural/Religion       0.93      0.94      0.93        53
                 Diet/Nutrition       0.91      0.84      0.88        50
                       Emergent       0.45      0.45      0.45        20
                       Exercise       0.82      0.67      0.74        21
               Friends & Family       0.81      0.53      0.64        40
               Grateful Patient       0.52      0.68      0.59        47
               Health Education       0.70      0.76      0.73        46
             Laboratory/Testing       0.94      0.99      0.97       166
                    Medications       0.96      0.84      0.90        62
                    No Symptoms       0.83      0.86      0.84       255
                     Non-urgent       0.93      0.98      0.95       522
Outpatient Logistics/Scheduling       0.85      0.69      0.76        74
                       Physical       0.92      0.72      0.81        94
   Physical Environment/Climate       0.85      0.85      0.85        20
              Service Complaint       0.04      0.11      0.06        18
                Social Services       0.75      0.53      0.62        17
                   Technical/IT       0.94      0.39      0.56        38
                         Urgent       0.26      0.31      0.28        42
                    Work/School       0.85      0.48      0.61        23

                      micro avg       0.83      0.83      0.83      1608
                      macro avg       0.75      0.66      0.69      1608
                   weighted avg       0.85      0.83      0.83      1608
                    samples avg       0.86      0.86      0.84      1608

In [61]:

import numpy as np
from sklearn.metrics import f1_score

N_BOOTSTRAP = 1000
rng = np.random.default_rng(42)
n = len(y_test)

boot_scores = []
for _ in range(N_BOOTSTRAP):
    idx = rng.integers(0, n, size=n)
    score = f1_score(y_test[idx], Y_pred_all[idx], average='macro', zero_division=0)
    boot_scores.append(score)

boot_scores = np.array(boot_scores)
lo = np.percentile(boot_scores, 2.5)
hi = np.percentile(boot_scores, 97.5)
print(f"Macro F1: {macro_f1:.4f}  95% CI [{lo:.4f}, {hi:.4f}]")

Macro F1: 0.6928  95% CI [0.6609, 0.7175]

In [62]:

import numpy as np, os
os.makedirs("predictions", exist_ok=True)



np.savez_compressed(
    "predictions/XGBoost_preds.npz",
    y_true = y_test,
    y_pred = Y_pred_all,
)
print("Saved predictions/XGBoost_preds.npz")

Saved predictions/XGBoost_preds.npz

## Per-corpus + per-label evaluation (XGBoost)

Loads saved `XGBoost_preds.npz` and reports Macro F1 (+ 95% bootstrap CI) and per-label F1 separately for the pooled corpus and for the Rwanda and Canada halves. Source labels come from `Ensemble_test_predictions.json`, which carries the per-row `source_corpus` field for the same 584-doc test set.

In [ ]:
# PERCORPUSCELL_v1
# Per-corpus + per-label evaluation against the shared test split, with 1,000-resample bootstrap CIs.
import json, numpy as np
from sklearn.metrics import f1_score, classification_report

with open("predictions/Ensemble_test_predictions.json") as f:
    _ens = json.load(f)
_src    = np.array([r["source_corpus"] for r in _ens])
_labels = list(_ens[0]["true_labels"].keys())

_d = np.load("predictions/XGBoost_preds.npz")
_yt, _yp = _d["y_true"].astype(int), _d["y_pred"]
if _yp.dtype != int:
    _yp = (_yp > 0.5).astype(int) if _yp.max() <= 1 else _yp.astype(int)

for _corpus in ["Combined", "Rwanda", "Canada"]:
    _mask = np.ones(len(_src), bool) if _corpus == "Combined" else (_src == _corpus)
    _yti, _ypi = _yt[_mask], _yp[_mask]
    _macro = f1_score(_yti, _ypi, average="macro", zero_division=0)

    _rng = np.random.default_rng(42)
    _n = len(_yti)
    _boot = np.empty(1000)
    for _i in range(1000):
        _idx = _rng.integers(0, _n, _n)
        _boot[_i] = f1_score(_yti[_idx], _ypi[_idx], average="macro", zero_division=0)
    _lo, _hi = np.percentile(_boot, [2.5, 97.5])

    print(f"\n=== {{_corpus}} (n={{_n}})  Macro F1 {{_macro:.4f}}  95% CI [{{_lo:.4f}}, {{_hi:.4f}}] ===")
    print(classification_report(_yti, _ypi, target_names=_labels, zero_division=0))